define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'تكوين Smart Permissions',
    PropertyPane_GroupName: 'عام',
    PropertyPane_DefaultViewLabel: 'العرض الافتراضي عند الفتح',
    PropertyPane_View_Home: 'الصفحة الرئيسية',
    PropertyPane_View_Report: 'تقرير الأذونات',
    PropertyPane_View_Explorer: 'مستكشف الأذونات',
    PropertyPane_View_UserAccess: 'وصول المستخدم',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: 'اتصال',
    CancelButton: 'إلغاء',
    ChangeUrlButton: 'تغيير عنوان URL',
    SettingsLabel: 'الإعدادات',
    RenderErrorTitle: 'Smart Permissions — خطأ في العرض',
    RenderErrorMessageLabel: 'الرسالة:',
    RenderErrorStackLabel: 'المكدس:',
    RenderErrorNoStack: '(المكدس غير متوفر)',
    BackButton: 'رجوع',
    BackToHomeLabel: 'العودة إلى الصفحة الرئيسية',
    ExplorerCardTitle: 'مستكشف الأذونات',
    ExplorerCardAlt: 'مستكشف الأذونات مع شجرة المجلدات ولوحة الأذونات',
    ExplorerCardDesc: 'تصفح أي مجلد أو ملف وشاهد على الفور من لديه حق الوصول — مع عمليات بحث فورية عن الأذونات.',
    ExplorerCardButton: 'فتح مستكشف الأذونات',
    ReportCardTitle: 'تقرير الأذونات',
    ReportCardAlt: 'شاشة تكوين تقرير الأذونات',
    ReportCardDesc: 'أنشئ تقرير Excel مرمزًا بالألوان لكل تعيين إذن فريد في موقعك.',
    ReportCardButton: 'تشغيل تقرير الأذونات',
    UserAccessCardTitle: 'وصول المستخدم',
    UserAccessCardAlt: 'شاشة وصول المستخدم تعرض المواقع التي يمكن الوصول إليها لمستخدم محدد',
    UserAccessCardDesc: 'ابحث عن أي مستخدم لمعرفة كل موقع يمكنه الوصول إليه على موقع، مع مستوى الإذن الدقيق.',
    UserAccessCardButton: 'التحقق من وصول المستخدم',
    SiteOwnerRequiredTitle: 'مطلوب وصول مالك الموقع —',
    SiteOwnerRequiredDesc: 'تتطلب هذه الأدوات وصول مالك الموقع. اتصل بمالك الموقع إذا كانت لديك أسئلة حول الأذونات.',
    HomeSubtitle: 'تدقيق وفهم أذونات SharePoint — بدون PowerShell.',
    RequiresSiteOwnerTooltip: 'يتطلب وصول مالك الموقع',
    HomeNoteLabel: 'ملاحظة:',
    HomeNoteText: 'يعمل جزء الويب هذا بصفته المستخدم المسجل الدخول حاليًا. يمكنه فقط رؤية المواقع والعناصر التي يملك هذا المستخدم إذن الوصول إليها. لإجراء فحص كامل للمستأجر، استخدم حسابًا يتمتع بإذن قراءة مناسب عبر جميع المواقع.',
    SettingsTitle: 'الإعدادات',
    LibrariesSectionTitle: 'المكتبات',
    IncludeHiddenLabel: 'تضمين المكتبات النظامية والمخفية',
    IncludeHiddenTooltip: 'إذا تم التحديد، يتضمن مكتبة الأنماط وقوالب النماذج وأصول الموقع والمكتبات الأخرى المخفية من طرق العرض الافتراضية. ينطبق على جميع الأدوات.',
    MoreInfoHiddenLibrariesLabel: 'مزيد من المعلومات حول المكتبات المخفية',
    ExcludeLimitedAccessLabel: 'استبعاد إدخالات الوصول المحدود',
    ExcludeLimitedAccessTooltip: 'يخفي المستخدمين والمجموعات الذين يكون إذن SharePoint الوحيد لديهم هو الوصول المحدود — يتم تعيينه تلقائيًا عند مشاركة الملفات عبر الروابط. ينطبق على تقرير الأذونات والمستكشف ووصول المستخدم.',
    MoreInfoLimitedAccessLabel: 'مزيد من المعلومات حول الوصول المحدود',
    ExcludeSharingLinksLabel: 'استبعاد إدخالات روابط المشاركة',
    ExcludeSharingLinksTooltip: 'يخفي مجموعات "SharingLinks.*" الداخلية التي ينشئها SharePoint تلقائيًا لروابط المشاركة "أي شخص لديه الرابط" و"أشخاص محددون". ينطبق على تقرير الأذونات والمستكشف ووصول المستخدم.',
    MoreInfoSharingLinksLabel: 'مزيد من المعلومات حول روابط المشاركة',
    PerformanceSectionTitle: 'الأداء',
    ConcurrentRequestsLabel: 'طلبات API المتزامنة:',
    ConcurrencyTooltip: 'عدد طلبات API الخاصة بـ SharePoint التي تعمل بالتوازي أثناء عمليات فحص تقرير الأذونات وعمليات فحص وصول المستخدم والفحوصات الخلفية للمستكشف. القيم الأعلى أسرع ولكنها أكثر عرضة لتفعيل التقييد (HTTP 429). يوصى بـ 3–5.',
    MoreInfoConcurrencyLabel: 'مزيد من المعلومات حول التزامن',
    ConcurrencyHint: 'تفحص القيم الأعلى بشكل أسرع ولكنها قد تفعّل تقييد SharePoint. الموصى به: 3–5.',
    GroupMemberCapLabel: 'حد عرض أعضاء المجموعة:',
    GroupMemberCapTooltip: 'الحد الأقصى لعدد الأعضاء المعروضين لكل مجموعة عند تمكين "توسيع أعضاء المجموعة". يتم تحديد المجموعات الأكبر ويتم عرض إشعار. زيادة هذا يستخدم ذاكرة أكثر.',
    MoreInfoGroupMemberCapLabel: 'مزيد من المعلومات حول حد أعضاء المجموعة',
    GroupMemberCapHint: 'تعرض المجموعات الأكبر من هذا الحد إشعار اقتطاع. الافتراضي: 500.',
    DefaultViewSectionTitle: 'العرض الافتراضي عند التحميل',
    DefaultViewInstructionsIntro: 'لتغيير الشاشة التي تفتح عند تحميل جزء الويب لأول مرة، قم بتحرير خصائص جزء الويب:',
    DefaultViewStep1Pre: 'ضع صفحة SharePoint في وضع',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'انقر فوق أيقونة',
    DefaultViewStep2Post: 'على جزء ويب Smart Permissions.',
    DefaultViewStep3Pre: 'في لوحة الخصائص، اختر طريقة عرض من القائمة المنسدلة',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'الصفحة لحفظ التغيير.',
    EditModeWord: 'التحرير',
    PencilEditWord: 'القلم (تحرير)',
    DefaultViewOnOpenWord: 'العرض الافتراضي عند الفتح',
    RepublishWord: 'أعد النشر',
    SiteOwnersLabel: 'مالكو الموقع:',
    EveryoneClaimLabel: 'الجميع',
    EveryoneExceptExternalClaimLabel: 'الجميع باستثناء المستخدمين الخارجيين',
    PermissionAssignmentsLabel: 'تعيينات الأذونات',
    UserGroupColumnHeader: 'المستخدم / المجموعة',
    TypeColumnHeader: 'النوع',
    PermissionLevelColumnHeader: 'مستوى الإذن',
    TenantWideAccessSuffix: '— وصول على مستوى المستأجر بالكامل',
    SecurityGroupType: 'مجموعة أمان',
    SpGroupType: 'مجموعة SP',
    UserType: 'مستخدم',
    CheckAccessForLabel: 'التحقق من الوصول لـ {0}',
    ContainsUniqueAndExternalTooltip: 'يحتوي على عناصر ذات أذونات فريدة ووصول مستخدمين خارجيين',
    ContainsUniqueTooltip: 'يحتوي على عناصر ذات أذونات فريدة',
    ContainsExternalTooltip: 'يحتوي على عناصر ذات وصول مستخدمين خارجيين',
    UniqueBadge: 'فريد',
    ExternalAccessDetectedTooltip: 'تم اكتشاف وصول مستخدم خارجي',
    ConnectingStatus: 'جارٍ الاتصال…',
    ConnectedLibrarySingular: 'متصل — تم العثور على {0} مكتبة',
    ConnectedLibraryPlural: 'متصل — تم العثور على {0} مكتبات',
    ConnectionFailedError: 'فشل الاتصال: {0}',
    LibraryEmptyStatus: 'هذه المكتبة فارغة.',
    ErrorLoadingLibrary: 'خطأ في تحميل المكتبة: {0}',
    ErrorLoadingContents: 'خطأ في تحميل المحتوى',
    LibraryFieldLabel: 'المكتبة',
    HiddenFromSearchSuffix: '{0} (مخفي من البحث)',
    UniquePermissionsOnlyToggle: 'الأذونات الفريدة فقط',
    ExternalUsersOnlyToggle: 'المستخدمون الخارجيون فقط',
    LegendLabel: 'وسيلة الإيضاح:',
    LegendItemHasUnique: 'العنصر لديه أذونات فريدة',
    LegendContainsUniqueBelow: 'يحتوي على أذونات فريدة أدناه',
    LegendContainsExternalBelow: 'يحتوي على وصول مستخدم خارجي أدناه',
    LegendExternalOnItem: 'وصول مستخدم خارجي على هذا العنصر',
    ViewingWithMemberAccessTitle: 'العرض بوصول عضو',
    ViewingWithMemberAccessDesc1: '— تعيينات الأذونات غير مرئية. تتطلب معرفة من لديه حق الوصول الحق',
    ManagePermissionsWord: 'إدارة الأذونات',
    ViewingWithMemberAccessDesc2: '(مالك الموقع أو أعلى). لا يزال بإمكانك رؤية العناصر التي انقطع فيها الوراثة باستخدام المؤشرات ↓. لرؤية المواقع التي يمكنك الوصول إليها، استخدم أداة',
    UserAccessWord: 'وصول المستخدم',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'المجلدات والملفات',
    SelectFolderOrFilePrompt: 'حدد مجلدًا أو ملفًا لعرض أذوناته.',
    UniquePermissionsBadge: 'أذونات فريدة',
    InheritedBadge: 'موروث',
    ExpandGroupMembersLabel: 'توسيع أعضاء المجموعة',
    ShowParentPermissionsLabel: 'إظهار أذونات العنصر الأصل',
    InheritsFromParentText: 'يرث هذا العنصر الأذونات من عنصره الأصل.',
    YourAccessLabel: 'وصولك:',
    PermissionsNotVisibleNodeText: 'تعيينات الأذونات غير مرئية — يلزم حق إدارة الأذونات (مالك الموقع أو أعلى) لمعرفة من لديه حق الوصول إلى هذا العنصر.',
    NoExternalUsersDirectAccessText: 'لا يوجد مستخدمون خارجيون لديهم وصول مباشر إلى هذا العنصر.',
    InheritedFromLabel: 'موروث من:',
    ParentPermissionsNotVisibleText: 'تعيينات أذونات العنصر الأصل غير مرئية — تتطلب حق إدارة الأذونات (مالك الموقع أو أعلى).',
    NoPermissionsFoundOnParentText: 'لم يتم العثور على أذونات في العنصر الأصل.',
    StartingScanStatus: 'بدء الفحص…',
    ScanCancelledStatus: 'تم إلغاء الفحص — تم جمع {0} كائن(كائنات) قبل الإلغاء.',
    ScanCompleteStatus: 'اكتمل الفحص — تم العثور على {0} كائن(كائنات)، منها {1} بأذونات فريدة.',
    ScanCompleteNotificationTitle: 'Smart Permissions — اكتمل الفحص',
    ScanCompleteNotificationBody: '{0} كائن، {1} بأذونات فريدة.',
    CancelledStatus: 'تم الإلغاء.',
    GenericErrorPrefix: 'خطأ: {0}',
    ExportErrorPrefix: 'خطأ في التصدير: {0}',
    ScopeSiteOnly: 'الموقع فقط',
    ScopeLibraries: 'المكتبات',
    ScopeFolders: 'المجلدات',
    ScopeFilesAndFolders: 'الملفات والمجلدات',
    ScanInProgressConfirm: 'الفحص قيد التقدم. هل تريد المغادرة والإلغاء؟',
    HistoryButton: 'السجل',
    BackToHistoryButton: 'العودة إلى السجل',
    ComparingLabel: 'المقارنة',
    CompareMismatchWarning: 'تم أخذ هذه التقارير بمواقع أو خيارات فحص مختلفة — قد تعكس الاختلافات أدناه إعدادات الفحص المتغيرة بدلاً من تغييرات الأذونات الفعلية.',
    NoPermissionDifferencesFound: 'لم يتم العثور على اختلافات في الأذونات بين هذين التقريرين.',
    PermissionChangesHeaderSingular: 'تغييرات الأذونات ({0} كائن)',
    PermissionChangesHeaderPlural: 'تغييرات الأذونات ({0} كائنات)',
    ChangeColumnHeader: 'التغيير',
    BeforeColumnHeader: 'قبل',
    AfterColumnHeader: 'بعد',
    AddedBadge: 'تمت الإضافة',
    RemovedBadge: 'تمت الإزالة',
    ChangedBadge: 'تم التغيير',
    InheritanceChangedHeader: 'تغيرت الوراثة ({0})',
    NameColumnHeader: 'الاسم',
    PathColumnHeader: 'المسار',
    NowColumnHeader: 'الآن',
    UniqueInheritanceBrokenBadge: 'فريد (انقطعت الوراثة)',
    InheritedRestoredBadge: 'موروث (تمت الاستعادة)',
    NewObjectsHeader: 'كائنات جديدة',
    RemovedObjectsHeader: 'كائنات تمت إزالتها',
    BackToScanButton: 'العودة إلى الفحص',
    CompareSelectedButton: 'مقارنة المحدد',
    NoReportsSavedYet: 'لم يتم حفظ أي تقارير بعد.',
    SelectForCompareLabel: 'حدد للمقارنة',
    DateTimeColumnHeader: 'التاريخ / الوقت',
    SiteColumnHeader: 'الموقع',
    ScopeColumnHeader: 'النطاق',
    ObjectsColumnHeader: 'الكائنات',
    UniqueColumnHeader: 'فريد',
    SelectReportForCompareLabel: 'حدد التقرير من {0} للمقارنة',
    AllSitesPrefix: 'جميع المواقع · ',
    PlusSubsitesSuffix: ' + مواقع فرعية',
    ExportingStatus: 'جارٍ التصدير…',
    ExportButton: 'تصدير',
    DeleteThisReportTitle: 'حذف هذا التقرير',
    ScanAllSiteCollectionsLabel: 'فحص جميع مجموعات المواقع في هذا المستأجر (متوفر فقط في الموقع الجذر)',
    AllSitesSearchCaveat: 'تأتي قائمة المواقع من البحث وقد لا تتضمن كل مجموعة مواقع — قد تكون المواقع التي تم إنشاؤها مؤخرًا جدًا، أو المستبعدة من فهرس البحث، مفقودة.',
    IncludeSubsitesLabel: 'تضمين المواقع الفرعية (يفحص كل موقع فرعي أسفل هذا الموقع)',
    ScanDepthFieldLabel: 'عمق الفحص',
    FolderDepthLimitLabel: 'حد عمق المجلد:',
    ExpandGroupMembersInReportLabel: 'توسيع أعضاء المجموعة في التقرير (مجموعات SharePoint، مجموعات الأمان، ومجموعات M365)',
    LibrariesToScanLabel: 'المكتبات المراد فحصها',
    OfSelectedCount: 'تم تحديد {0} من {1}',
    AllButton: 'الكل',
    NoneButton: 'لا شيء',
    LoadingLibrariesStatus: 'جارٍ تحميل المكتبات…',
    RunReportButton: 'تشغيل التقرير',
    ItemsFoundSoFar: 'تم العثور على {0} عنصر حتى الآن',
    LibraryOfProgress: 'المكتبة {0} من {1}',
    ScanCancelledPartialResults: 'تم إلغاء الفحص — نتائج جزئية',
    ScanCompleteLabel: 'اكتمل الفحص',
    ObjectsCountBadge: '{0} كائن',
    UniqueCountBadge: '{0} فريد',
    InheritedCountBadge: '{0} موروث',
    GeneratingExcelStatus: 'جارٍ إنشاء Excel…',
    ExportFilteredRowsButton: 'تصدير {0} صفوف مصفاة',
    ExportToExcelButton: 'تصدير إلى Excel',
    ExportToCsvButton: 'تصدير إلى CSV',
    ScanStoppedEarlyTitle: 'توقف الفحص مبكرًا — يقوم SharePoint بتقييد هذا المستأجر.',
    SiteCollectionsScannedBeforeStopping: 'تم فحص {0} من {1} مجموعة مواقع قبل التوقف. ',
    ResultsBelowCoverOnlyPre: 'تغطي النتائج أدناه فقط ما تم فحصه وهي',
    NotWord: 'ليست',
    ResultsBelowCoverOnlyPost: 'تدقيقًا كاملاً. يتوقف الفحص من تلقاء نفسه في هذه الحالة لأن الاستمرار في إرسال الطلبات هو ما يبقي التقييد ساريًا. انتظر عدة دقائق، ثم أعد التشغيل مع تعيين',
    ConcurrentRequestsWord: 'الطلبات المتزامنة',
    SetTo1Or2InSettings: 'على 1 أو 2 في الإعدادات.',
    ThrottledScanMessage: 'قام SharePoint بتقييد هذا الفحص (تم تقييد معدل {0} طلب(ات) وإعادة المحاولة).',
    OfEverythingScannedPre: 'من كل ما تم فحصه،',
    ItemCountSingular: '{0} عنصر',
    ItemCountPlural: '{0} عناصر',
    CouldNotBeConfirmedText: 'لم يتمكن من التأكيد بعد إعادة المحاولة (انظر الإشعار "تعذرت قراءته بالكامل" أدناه لمعرفة أيها بالضبط) — كان هذا الفشل مرتبطًا بالسعة، وليس انعكاسًا لأذوناتهم الفعلية. تمت قراءة جميع العناصر الأخرى في هذا التقرير بنجاح ويمكن الوثوق بها.',
    DespiteThrottlingText: 'على الرغم من التقييد، تم تأكيد كل عنصر بنجاح بعد إعادة المحاولة، لذا فإن هذا التقرير مكتمل.',
    ForCleanRunPre: 'لتشغيل نظيف، انتظر بضع دقائق وأعد الفحص بقيمة أقل لـ',
    ValueInSettingsPost: 'في الإعدادات.',
    OneItemWord: 'عنصر واحد',
    NItemsWord: '{0} عنصر(عناصر)',
    OutOfScannedCouldNotBeRead: 'من {0} تم فحصها لم يتمكن من قراءتها بوصولك الحالي —',
    PermissionAssignmentsForItAreNotShown: ' لا يتم عرض تعيينات الأذونات، ',
    PermissionAssignmentsForThoseAreNotShown: ' لا يتم عرض تعيينات الأذونات، ',
    RestOfReportReadSuccessfully: 'لكن تمت قراءة بقية هذا التقرير بنجاح.',
    RunScanAsSiteOwnerPre: 'قم بتشغيل الفحص بصفتك',
    SiteOwnerWord: 'مالك الموقع',
    RunScanAsSiteOwnerPost: 'لرؤية التفاصيل الكاملة للعناصر المرفوضة أدناه.',
    AndNMoreText: '…و{0} أخرى',
    GroupExpansionSkippedPre: 'تم تخطي توسيع أعضاء المجموعة — لم تتم الموافقة على إذن Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'في هذا المستأجر. يمكن لمسؤول SharePoint أو المسؤول العام الموافقة عليه في',
    SharePointAdminCenterPath: 'مركز إدارة SharePoint ← متقدم ← الوصول إلى API',
    ScanIncompleteItemsMessage: 'تعذرت قراءة {0} عنصر(عناصر) بالكامل بسبب خطأ مؤقت (وليس مشكلة أذونات) ويتم عرضها بأذونات عنصرها الأصل كحل بديل — قد لا يعكس هذا وصولها الفعلي. أعد تشغيل الفحص لإعادة محاولة هذه العناصر.',
    FilterByNamePathUserPlaceholder: 'تصفية حسب الاسم أو المسار أو المستخدم/المجموعة…',
    FilterResultsLabel: 'تصفية النتائج',
    ExternalUsersOnlyExtLabel: 'المستخدمون الخارجيون فقط (#ext#)',
    ShowingOfCount: 'عرض {0} من {1}',
    ScanResultsLabel: 'نتائج الفحص',
    PermissionsColumnHeader: 'الأذونات',
    CollapsePermissionsLabel: 'طي الأذونات',
    ExpandPermissionsLabel: 'توسيع الأذونات',
    HiddenFromSearchBadge: 'مخفي من البحث',
    AssignmentCountSingular: '{0} تعيين',
    AssignmentCountPlural: '{0} تعيينات',
    LoadMoreRemainingButton: 'تحميل المزيد ({0} متبقٍ)',
    LoadingUsersStatus: 'جارٍ تحميل المستخدمين…',
    ConnectedUserSingular: 'متصل — تم العثور على {0} مستخدم',
    ConnectedUserPlural: 'متصل — تم العثور على {0} مستخدمين',
    CheckingAccessForStatus: 'جارٍ التحقق من الوصول لـ {0}…',
    FullSiteAccessDetectedStatus: 'تم اكتشاف وصول كامل للموقع.',
    AccessibleLocationsFoundSingular: 'تم العثور على {0} موقع يمكن الوصول إليه.',
    AccessibleLocationsFoundPlural: 'تم العثور على {0} مواقع يمكن الوصول إليها.',
    NoAccessibleLocationsFoundStatus: 'لم يتم العثور على مواقع يمكن الوصول إليها.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — اكتمل فحص وصول المستخدم',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'فحص جديد',
    NoUserAccessScansSavedYet: 'لم يتم حفظ أي فحوصات وصول المستخدم بعد.',
    UserColumnHeader: 'المستخدم',
    LocationsColumnHeader: 'المواقع',
    FullControlBadge: 'تحكم كامل',
    DeleteThisRecordTitle: 'حذف هذا السجل',
    SelectAUserFieldLabel: 'حدد مستخدمًا',
    SearchUsersPlaceholder: 'البحث عن المستخدمين…',
    SelectAUserToCheckAccessLabel: 'حدد مستخدمًا للتحقق من الوصول',
    NotInThisSiteLabel: 'ليس في هذا الموقع',
    ScanInProgressLabel: 'الفحص قيد التقدم',
    ScanningUserAccessLabel: 'جارٍ فحص وصول المستخدم',
    ScanningStatus: 'جارٍ الفحص…',
    FullControlAccessPre: 'لدى هذا المستخدم',
    FullControlWord: 'تحكم كامل',
    FullControlAccessPost: 'أو وصول على مستوى المالك للموقع بأكمله — يمكن الوصول إلى جميع المكتبات والمجلدات.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'تعذر تحديد الإذن على مستوى الموقع — من المحتمل أن يستخدم هذا الموقع وصول مجموعة Microsoft 365. لعرضه، يجب على مسؤول SharePoint الموافقة على إذن',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph في',
    ShowingSiteLevelAccessOnlyPre: 'يتم عرض',
    SiteLevelAccessOnlyWord: 'الوصول على مستوى الموقع فقط',
    ShowingSiteLevelAccessOnlyMid: '، بناءً على عضوية مجموعة SharePoint الافتراضية. تعذرت قراءة الأذونات الفريدة للمكتبات والمجلدات والملفات ولا يتم عرضها. للحصول على نتائج كاملة، قم بتشغيل هذا الفحص بصفتك',
    UserAccessCouldNotBeDeterminedPre: 'تعذر تحديد وصول هذا المستخدم. تتطلب قراءة تعيينات الأذونات الحق',
    UserAccessCouldNotBeDeterminedPost: '(مالك الموقع أو أعلى)، ولا يبدو أن هذا المستخدم عضو في مجموعات المالكين أو الأعضاء أو الزوار الافتراضية للموقع.',
    SiteLevelAccessBannerPre: 'لدى هذا المستخدم وصول على مستوى الموقع. تظهر أدناه فقط المواقع ذات',
    UniquePermissionAssignmentsWord: 'تعيينات أذونات فريدة',
    SiteLevelAccessBannerPost: '— يمكن الوصول إلى كل المحتوى الآخر من خلال الإذن على مستوى الموقع الموضح في أعلى القائمة.',
    UserAccessResultsLabel: 'نتائج وصول المستخدم',
  };
});
