define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Konfigurace Smart Permissions',
    PropertyPane_GroupName: 'Obecné',
    PropertyPane_DefaultViewLabel: 'Výchozí zobrazení při otevření',
    PropertyPane_View_Home: 'Domů',
    PropertyPane_View_Report: 'Sestava oprávnění',
    PropertyPane_View_Explorer: 'Průzkumník oprávnění',
    PropertyPane_View_UserAccess: 'Přístup uživatele',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mojewitryna',
    ConnectButton: 'Připojit',
    CancelButton: 'Zrušit',
    ChangeUrlButton: 'Změnit adresu URL',
    SettingsLabel: 'Nastavení',
    RenderErrorTitle: 'Smart Permissions — Chyba vykreslování',
    RenderErrorMessageLabel: 'Zpráva:',
    RenderErrorStackLabel: 'Zásobník:',
    RenderErrorNoStack: '(zásobník není k dispozici)',
    BackButton: 'Zpět',
    BackToHomeLabel: 'Zpět na domovskou stránku',
    ExplorerCardTitle: 'Průzkumník oprávnění',
    ExplorerCardAlt: 'Průzkumník oprávnění se stromem složek a panelem oprávnění',
    ExplorerCardDesc: 'Procházejte libovolnou složku nebo soubor a okamžitě zjistěte, kdo má přístup — s vyhledáváním oprávnění v reálném čase.',
    ExplorerCardButton: 'Otevřít Průzkumníka oprávnění',
    ReportCardTitle: 'Sestava oprávnění',
    ReportCardAlt: 'Obrazovka konfigurace sestavy oprávnění',
    ReportCardDesc: 'Vygenerujte barevně kódovanou sestavu Excel pro každé jedinečné přiřazení oprávnění na vašem webu.',
    ReportCardButton: 'Spustit sestavu oprávnění',
    UserAccessCardTitle: 'Přístup uživatele',
    UserAccessCardAlt: 'Obrazovka přístupu uživatele zobrazující přístupná umístění pro vybraného uživatele',
    UserAccessCardDesc: 'Vyhledejte libovolného uživatele a zjistěte, ke kterým místům má na webu přístup, s přesnou úrovní oprávnění.',
    UserAccessCardButton: 'Zkontrolovat přístup uživatele',
    SiteOwnerRequiredTitle: 'Vyžadován přístup vlastníka webu —',
    SiteOwnerRequiredDesc: 'Tyto nástroje vyžadují přístup vlastníka webu. V případě dotazů ohledně oprávnění kontaktujte vlastníka webu.',
    HomeSubtitle: 'Auditujte a rozumějte oprávněním SharePoint — bez PowerShellu.',
    RequiresSiteOwnerTooltip: 'Vyžaduje přístup vlastníka webu',
    HomeNoteLabel: 'Poznámka:',
    HomeNoteText: 'Tato webová část se spouští jako aktuálně přihlášený uživatel. Vidí pouze weby a položky, ke kterým má tento uživatel oprávnění. Pro úplné skenování tenanta použijte účet s odpovídajícím oprávněním ke čtení na všech webech.',
    SettingsTitle: 'Nastavení',
    LibrariesSectionTitle: 'Knihovny',
    IncludeHiddenLabel: 'Zahrnout systémové a skryté knihovny',
    IncludeHiddenTooltip: 'Pokud je zaškrtnuto, zahrnuje knihovnu stylů, šablony formulářů, prostředky webu a další knihovny skryté ve výchozích zobrazeních. Platí pro všechny nástroje.',
    MoreInfoHiddenLibrariesLabel: 'Další informace o skrytých knihovnách',
    ExcludeLimitedAccessLabel: 'Vyloučit položky s omezeným přístupem',
    ExcludeLimitedAccessTooltip: 'Skryje uživatele a skupiny, jejichž jediné oprávnění SharePoint je Omezený přístup — přiřazené automaticky při sdílení souborů prostřednictvím odkazů. Platí pro sestavu oprávnění, Průzkumníka a přístup uživatele.',
    MoreInfoLimitedAccessLabel: 'Další informace o omezeném přístupu',
    ExcludeSharingLinksLabel: 'Vyloučit položky odkazů pro sdílení',
    ExcludeSharingLinksTooltip: 'Skryje interní skupiny "SharingLinks.*", které SharePoint automaticky vytváří pro odkazy pro sdílení "Kdokoli s odkazem" a "Konkrétní osoby". Platí pro sestavu oprávnění, Průzkumníka a přístup uživatele.',
    MoreInfoSharingLinksLabel: 'Další informace o odkazech pro sdílení',
    PerformanceSectionTitle: 'Výkon',
    ConcurrentRequestsLabel: 'Souběžné požadavky API:',
    ConcurrencyTooltip: 'Kolik požadavků API SharePoint běží paralelně během skenování sestavy oprávnění, skenování přístupu uživatele a kontrol na pozadí Průzkumníka. Vyšší hodnoty jsou rychlejší, ale náchylnější ke spuštění omezování (HTTP 429). Doporučuje se 3–5.',
    MoreInfoConcurrencyLabel: 'Další informace o souběžnosti',
    ConcurrencyHint: 'Vyšší hodnoty skenují rychleji, ale mohou spustit omezování SharePoint. Doporučeno: 3–5.',
    GroupMemberCapLabel: 'Limit zobrazení členů skupiny:',
    GroupMemberCapTooltip: 'Maximální počet zobrazených členů na skupinu, když je povolena možnost „Rozbalit členy skupiny". Větší skupiny jsou omezeny a zobrazí se upozornění. Zvýšení této hodnoty spotřebuje více paměti.',
    MoreInfoGroupMemberCapLabel: 'Další informace o limitu členů skupiny',
    GroupMemberCapHint: 'Skupiny větší než tento limit zobrazují upozornění na zkrácení. Výchozí: 500.',
    DefaultViewSectionTitle: 'Výchozí zobrazení při načtení',
    DefaultViewInstructionsIntro: 'Chcete-li změnit, která obrazovka se otevře při prvním načtení webové části, upravte vlastnosti webové části:',
    DefaultViewStep1Pre: 'Přepněte stránku SharePoint do režimu',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Klikněte na ikonu',
    DefaultViewStep2Post: 've webové části Smart Permissions.',
    DefaultViewStep3Pre: 'V panelu vlastností vyberte zobrazení z rozevíracího seznamu',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'stránku a uložte změnu.',
    EditModeWord: 'Úprav',
    PencilEditWord: 'tužky (upravit)',
    DefaultViewOnOpenWord: 'Výchozí zobrazení při otevření',
    RepublishWord: 'Znovu publikujte',
    SiteOwnersLabel: 'Vlastníci webu:',
    EveryoneClaimLabel: 'Všichni',
    EveryoneExceptExternalClaimLabel: 'Všichni kromě externích uživatelů',
    PermissionAssignmentsLabel: 'Přiřazení oprávnění',
    UserGroupColumnHeader: 'Uživatel / Skupina',
    TypeColumnHeader: 'Typ',
    PermissionLevelColumnHeader: 'Úroveň oprávnění',
    TenantWideAccessSuffix: '— přístup v celém tenantovi',
    SecurityGroupType: 'Skupina zabezpečení',
    SpGroupType: 'Skupina SP',
    UserType: 'Uživatel',
    CheckAccessForLabel: 'Zkontrolovat přístup pro {0}',
    ContainsUniqueAndExternalTooltip: 'Obsahuje položky s jedinečnými oprávněními a přístupem externích uživatelů',
    ContainsUniqueTooltip: 'Obsahuje položky s jedinečnými oprávněními',
    ContainsExternalTooltip: 'Obsahuje položky s přístupem externích uživatelů',
    UniqueBadge: 'Jedinečné',
    ExternalAccessDetectedTooltip: 'Zjištěn přístup externího uživatele',
    ConnectingStatus: 'Připojování…',
    ConnectedLibrarySingular: 'Připojeno — nalezena {0} knihovna',
    ConnectedLibraryPlural: 'Připojeno — nalezeno {0} knihoven',
    ConnectionFailedError: 'Připojení se nezdařilo: {0}',
    LibraryEmptyStatus: 'Tato knihovna je prázdná.',
    ErrorLoadingLibrary: 'Chyba při načítání knihovny: {0}',
    ErrorLoadingContents: 'Chyba při načítání obsahu',
    LibraryFieldLabel: 'Knihovna',
    HiddenFromSearchSuffix: '{0} (skryto z vyhledávání)',
    UniquePermissionsOnlyToggle: 'Pouze jedinečná oprávnění',
    ExternalUsersOnlyToggle: 'Pouze externí uživatelé',
    LegendLabel: 'Legenda:',
    LegendItemHasUnique: 'Položka má jedinečná oprávnění',
    LegendContainsUniqueBelow: 'Obsahuje jedinečná oprávnění níže',
    LegendContainsExternalBelow: 'Obsahuje přístup externího uživatele níže',
    LegendExternalOnItem: 'Přístup externího uživatele k této položce',
    ViewingWithMemberAccessTitle: 'Zobrazení s přístupem člena',
    ViewingWithMemberAccessDesc1: '— přiřazení oprávnění nejsou viditelná. Zjištění, kdo má přístup, vyžaduje oprávnění',
    ManagePermissionsWord: 'Spravovat oprávnění',
    ViewingWithMemberAccessDesc2: '(vlastník webu nebo vyšší). Stále můžete vidět, které položky mají přerušenou dědičnost, pomocí indikátorů ↓. Chcete-li zobrazit umístění, ke kterým máte přístup, použijte nástroj',
    UserAccessWord: 'Přístup uživatele',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Složky a soubory',
    SelectFolderOrFilePrompt: 'Vyberte složku nebo soubor a zobrazte jeho oprávnění.',
    UniquePermissionsBadge: 'Jedinečná oprávnění',
    InheritedBadge: 'Zděděné',
    ExpandGroupMembersLabel: 'Rozbalit členy skupiny',
    ShowParentPermissionsLabel: 'Zobrazit nadřazená oprávnění',
    InheritsFromParentText: 'Tato položka dědí oprávnění od nadřazené položky.',
    YourAccessLabel: 'Váš přístup:',
    PermissionsNotVisibleNodeText: 'Přiřazení oprávnění nejsou viditelná — ke zjištění, kdo má přístup k této položce, je vyžadováno oprávnění Spravovat oprávnění (vlastník webu nebo vyšší).',
    NoExternalUsersDirectAccessText: 'Žádný externí uživatel nemá přímý přístup k této položce.',
    InheritedFromLabel: 'Zděděno od:',
    ParentPermissionsNotVisibleText: 'Přiřazení oprávnění nadřazené položky nejsou viditelná — vyžaduje oprávnění Spravovat oprávnění (vlastník webu nebo vyšší).',
    NoPermissionsFoundOnParentText: 'U nadřazené položky nebyla nalezena žádná oprávnění.',
    StartingScanStatus: 'Spouštění kontroly…',
    ScanCancelledStatus: 'Kontrola zrušena — před zrušením shromážděno {0} objekt(ů).',
    ScanCompleteStatus: 'Kontrola dokončena — nalezeno {0} objekt(ů), {1} s jedinečnými oprávněními.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Kontrola dokončena',
    ScanCompleteNotificationBody: '{0} objektů, {1} s jedinečnými oprávněními.',
    CancelledStatus: 'Zrušeno.',
    GenericErrorPrefix: 'Chyba: {0}',
    ExportErrorPrefix: 'Chyba exportu: {0}',
    ScopeSiteOnly: 'Pouze web',
    ScopeLibraries: 'Knihovny',
    ScopeFolders: 'Složky',
    ScopeFilesAndFolders: 'Soubory a složky',
    ScanInProgressConfirm: 'Probíhá kontrola. Opustit a zrušit?',
    HistoryButton: 'Historie',
    BackToHistoryButton: 'Zpět na historii',
    ComparingLabel: 'Porovnávání',
    CompareMismatchWarning: 'Tyto sestavy byly pořízeny s různými weby nebo možnostmi kontroly — rozdíly níže mohou odrážet změněná nastavení kontroly, nikoli skutečné změny oprávnění.',
    NoPermissionDifferencesFound: 'Mezi těmito dvěma sestavami nebyly nalezeny žádné rozdíly v oprávněních.',
    PermissionChangesHeaderSingular: 'Změny oprávnění ({0} objekt)',
    PermissionChangesHeaderPlural: 'Změny oprávnění ({0} objektů)',
    ChangeColumnHeader: 'Změna',
    BeforeColumnHeader: 'Před',
    AfterColumnHeader: 'Po',
    AddedBadge: 'Přidáno',
    RemovedBadge: 'Odebráno',
    ChangedBadge: 'Změněno',
    InheritanceChangedHeader: 'Dědičnost změněna ({0})',
    NameColumnHeader: 'Název',
    PathColumnHeader: 'Cesta',
    NowColumnHeader: 'Nyní',
    UniqueInheritanceBrokenBadge: 'Jedinečné (dědičnost přerušena)',
    InheritedRestoredBadge: 'Zděděné (obnoveno)',
    NewObjectsHeader: 'Nové objekty',
    RemovedObjectsHeader: 'Odebrané objekty',
    BackToScanButton: 'Zpět na kontrolu',
    CompareSelectedButton: 'Porovnat vybrané',
    NoReportsSavedYet: 'Zatím nebyly uloženy žádné sestavy.',
    SelectForCompareLabel: 'Vybrat k porovnání',
    DateTimeColumnHeader: 'Datum / Čas',
    SiteColumnHeader: 'Web',
    ScopeColumnHeader: 'Rozsah',
    ObjectsColumnHeader: 'Objekty',
    UniqueColumnHeader: 'Jedinečné',
    SelectReportForCompareLabel: 'Vybrat sestavu z {0} k porovnání',
    AllSitesPrefix: 'Všechny weby · ',
    PlusSubsitesSuffix: ' + podřízené weby',
    ExportingStatus: 'Exportování…',
    ExportButton: 'Exportovat',
    DeleteThisReportTitle: 'Odstranit tuto sestavu',
    ScanAllSiteCollectionsLabel: 'Zkontrolovat všechny kolekce webů v tomto tenantovi (dostupné pouze na kořenovém webu)',
    AllSitesSearchCaveat: 'Seznam webů pochází z vyhledávání a nemusí obsahovat všechny kolekce webů — velmi nedávno vytvořené weby nebo weby vyloučené z vyhledávacího indexu mohou chybět.',
    IncludeSubsitesLabel: 'Zahrnout podřízené weby (zkontroluje každý podřízený web pod tímto webem)',
    ScanDepthFieldLabel: 'Hloubka kontroly',
    FolderDepthLimitLabel: 'Limit hloubky složek:',
    ExpandGroupMembersInReportLabel: 'Rozbalit členy skupiny v sestavě (skupiny SharePoint, skupiny zabezpečení a skupiny M365)',
    LibrariesToScanLabel: 'Knihovny ke kontrole',
    OfSelectedCount: 'Vybráno {0} z {1}',
    AllButton: 'Vše',
    NoneButton: 'Žádné',
    LoadingLibrariesStatus: 'Načítání knihoven…',
    RunReportButton: 'Spustit sestavu',
    ItemsFoundSoFar: 'Zatím nalezeno {0} položek',
    LibraryOfProgress: 'Knihovna {0} z {1}',
    ScanCancelledPartialResults: 'Kontrola zrušena — částečné výsledky',
    ScanCompleteLabel: 'Kontrola dokončena',
    ObjectsCountBadge: '{0} objektů',
    UniqueCountBadge: '{0} jedinečných',
    InheritedCountBadge: '{0} zděděných',
    GeneratingExcelStatus: 'Generování Excelu…',
    ExportFilteredRowsButton: 'Exportovat {0} filtrovaných řádků',
    ExportToExcelButton: 'Exportovat do Excelu',
    ExportToCsvButton: 'Exportovat do CSV',
    ScanStoppedEarlyTitle: 'Kontrola byla předčasně zastavena — SharePoint omezuje tohoto tenanta.',
    SiteCollectionsScannedBeforeStopping: 'Před zastavením bylo zkontrolováno {0} z {1} kolekcí webů. ',
    ResultsBelowCoverOnlyPre: 'Výsledky níže pokrývají pouze to, co bylo zkontrolováno, a nejsou',
    NotWord: 'nejsou',
    ResultsBelowCoverOnlyPost: 'úplným auditem. Kontrola se v této situaci sama zastavuje, protože pokračování v odesílání požadavků udržuje omezování aktivní. Počkejte několik minut a poté spusťte znovu s',
    ConcurrentRequestsWord: 'Souběžné požadavky',
    SetTo1Or2InSettings: 'nastaveno na 1 nebo 2 v Nastavení.',
    ThrottledScanMessage: 'SharePoint omezil tuto kontrolu ({0} požadavek(ů) bylo omezeno a zopakováno).',
    OfEverythingScannedPre: 'Ze všeho, co bylo zkontrolováno,',
    ItemCountSingular: '{0} položku',
    ItemCountPlural: '{0} položek',
    CouldNotBeConfirmedText: 'se nepodařilo potvrdit po opakování (podrobnosti viz upozornění „nepodařilo se plně přečíst" níže) — tato chyba souvisela s kapacitou, nikoli s jejich skutečnými oprávněními. Všechny ostatní položky v této sestavě byly úspěšně přečteny a lze jim důvěřovat.',
    DespiteThrottlingText: 'Navzdory omezování byla každá položka po opakování úspěšně potvrzena, takže tato sestava je úplná.',
    ForCleanRunPre: 'Pro čistý průběh počkejte několik minut a zkontrolujte znovu s nižší hodnotou pro',
    ValueInSettingsPost: 'v Nastavení.',
    OneItemWord: '1 položku',
    NItemsWord: '{0} položek',
    OutOfScannedCouldNotBeRead: 'z {0} zkontrolovaných se nepodařilo přečíst s vaším aktuálním přístupem —',
    PermissionAssignmentsForItAreNotShown: ' přiřazení oprávnění nejsou zobrazena, ',
    PermissionAssignmentsForThoseAreNotShown: ' přiřazení oprávnění nejsou zobrazena, ',
    RestOfReportReadSuccessfully: 'ale zbytek této sestavy byl úspěšně přečten.',
    RunScanAsSiteOwnerPre: 'Spusťte kontrolu jako',
    SiteOwnerWord: 'vlastník webu',
    RunScanAsSiteOwnerPost: 'a zobrazte úplné podrobnosti odepřených položek níže.',
    AndNMoreText: '…a dalších {0}',
    GroupExpansionSkippedPre: 'Rozbalení členů skupiny bylo přeskočeno — oprávnění Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'nebylo v tomto tenantovi schváleno. Správce SharePoint nebo globální správce jej může schválit v',
    SharePointAdminCenterPath: 'Centrum pro správu SharePoint → Pokročilé → Přístup API',
    ScanIncompleteItemsMessage: '{0} položek se nepodařilo plně přečíst kvůli dočasné chybě (nikoli problému s oprávněními) a jsou zobrazeny s oprávněními nadřazené položky jako záložní řešení — to nemusí odrážet jejich skutečný přístup. Spusťte kontrolu znovu a zopakujte pokus u těchto položek.',
    FilterByNamePathUserPlaceholder: 'Filtrovat podle názvu, cesty nebo uživatele/skupiny…',
    FilterResultsLabel: 'Filtrovat výsledky',
    ExternalUsersOnlyExtLabel: 'Pouze externí uživatelé (#ext#)',
    ShowingOfCount: 'Zobrazeno {0} z {1}',
    ScanResultsLabel: 'Výsledky kontroly',
    PermissionsColumnHeader: 'Oprávnění',
    CollapsePermissionsLabel: 'Sbalit oprávnění',
    ExpandPermissionsLabel: 'Rozbalit oprávnění',
    HiddenFromSearchBadge: 'Skryto z vyhledávání',
    AssignmentCountSingular: '{0} přiřazení',
    AssignmentCountPlural: '{0} přiřazení',
    LoadMoreRemainingButton: 'Načíst více (zbývá {0})',
    LoadingUsersStatus: 'Načítání uživatelů…',
    ConnectedUserSingular: 'Připojeno — nalezen {0} uživatel',
    ConnectedUserPlural: 'Připojeno — nalezeno {0} uživatelů',
    CheckingAccessForStatus: 'Kontrola přístupu pro {0}…',
    FullSiteAccessDetectedStatus: 'Zjištěn úplný přístup k webu.',
    AccessibleLocationsFoundSingular: 'Nalezeno {0} přístupné umístění.',
    AccessibleLocationsFoundPlural: 'Nalezeno {0} přístupných umístění.',
    NoAccessibleLocationsFoundStatus: 'Nebyla nalezena žádná přístupná umístění.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Kontrola přístupu uživatele dokončena',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Nová kontrola',
    NoUserAccessScansSavedYet: 'Zatím nebyly uloženy žádné kontroly přístupu uživatele.',
    UserColumnHeader: 'Uživatel',
    LocationsColumnHeader: 'Umístění',
    FullControlBadge: 'Úplné řízení',
    DeleteThisRecordTitle: 'Odstranit tento záznam',
    SelectAUserFieldLabel: 'Vyberte uživatele',
    SearchUsersPlaceholder: 'Hledat uživatele…',
    SelectAUserToCheckAccessLabel: 'Vyberte uživatele pro kontrolu přístupu',
    NotInThisSiteLabel: 'Není v tomto webu',
    ScanInProgressLabel: 'Probíhá kontrola',
    ScanningUserAccessLabel: 'Kontrola přístupu uživatele',
    ScanningStatus: 'Kontrola…',
    FullControlAccessPre: 'Tento uživatel má',
    FullControlWord: 'Úplné řízení',
    FullControlAccessPost: 'nebo přístup na úrovni vlastníka k celému webu — všechny knihovny a složky jsou přístupné.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Oprávnění na úrovni webu se nepodařilo určit — tento web pravděpodobně používá přístup skupiny Microsoft 365. Chcete-li jej zobrazit, musí správce SharePoint schválit oprávnění',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph v',
    ShowingSiteLevelAccessOnlyPre: 'Zobrazuje se pouze',
    SiteLevelAccessOnlyWord: 'přístup na úrovni webu',
    ShowingSiteLevelAccessOnlyMid: ', na základě výchozího členství ve skupině SharePoint. Jedinečná oprávnění ke knihovnám, složkám a souborům se nepodařilo přečíst a nejsou zobrazena. Pro úplné výsledky spusťte tuto kontrolu jako',
    UserAccessCouldNotBeDeterminedPre: 'Přístup tohoto uživatele se nepodařilo určit. Čtení přiřazení oprávnění vyžaduje oprávnění',
    UserAccessCouldNotBeDeterminedPost: '(vlastník webu nebo vyšší) a tento uživatel se nezdá být členem výchozích skupin Vlastníci, Členové nebo Návštěvníci webu.',
    SiteLevelAccessBannerPre: 'Tento uživatel má přístup na úrovni webu. Níže se zobrazují pouze umístění s',
    UniquePermissionAssignmentsWord: 'jedinečnými přiřazeními oprávnění',
    SiteLevelAccessBannerPost: '— veškerý ostatní obsah je přístupný prostřednictvím oprávnění na úrovni webu zobrazeného v horní části seznamu.',
    UserAccessResultsLabel: 'Výsledky přístupu uživatele',
  };
});
