define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions-konfiguration',
    PropertyPane_GroupName: 'Generelt',
    PropertyPane_DefaultViewLabel: 'Standardvisning ved åbning',
    PropertyPane_View_Home: 'Startside',
    PropertyPane_View_Report: 'Tilladelsesrapport',
    PropertyPane_View_Explorer: 'Tilladelsesudforsker',
    PropertyPane_View_UserAccess: 'Brugeradgang',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/minwebsted',
    ConnectButton: 'Opret forbindelse',
    CancelButton: 'Annuller',
    ChangeUrlButton: 'Skift URL',
    SettingsLabel: 'Indstillinger',
    RenderErrorTitle: 'Smart Permissions — Gengivelsesfejl',
    RenderErrorMessageLabel: 'Meddelelse:',
    RenderErrorStackLabel: 'Stak:',
    RenderErrorNoStack: '(ingen stak tilgængelig)',
    BackButton: 'Tilbage',
    BackToHomeLabel: 'Tilbage til startside',
    ExplorerCardTitle: 'Tilladelsesudforsker',
    ExplorerCardAlt: 'Tilladelsesudforsker med mappetræ og tilladelsespanel',
    ExplorerCardDesc: 'Gennemse enhver mappe eller fil og se øjeblikkeligt, hvem der har adgang — med opslag i realtid.',
    ExplorerCardButton: 'Åbn tilladelsesudforsker',
    ReportCardTitle: 'Tilladelsesrapport',
    ReportCardAlt: 'Konfigurationsskærm til tilladelsesrapport',
    ReportCardDesc: 'Generér en farvekodet Excel-rapport over hver unik tilladelsestildeling på dit websted.',
    ReportCardButton: 'Kør tilladelsesrapport',
    UserAccessCardTitle: 'Brugeradgang',
    UserAccessCardAlt: 'Skærmbillede for brugeradgang med tilgængelige placeringer for en valgt bruger',
    UserAccessCardDesc: 'Slå en bruger op for at se alle steder, de kan tilgå på et websted, med deres nøjagtige tilladelsesniveau.',
    UserAccessCardButton: 'Kontrollér brugeradgang',
    SiteOwnerRequiredTitle: 'Adgang som webstedsejer er påkrævet —',
    SiteOwnerRequiredDesc: 'Disse værktøjer kræver adgang som webstedsejer. Kontakt en webstedsejer, hvis du har spørgsmål om tilladelser.',
    HomeSubtitle: 'Undersøg og forstå SharePoint-tilladelser — uden PowerShell.',
    RequiresSiteOwnerTooltip: 'Kræver adgang som webstedsejer',
    HomeNoteLabel: 'Bemærk:',
    HomeNoteText: 'Denne webdel kører som den aktuelt loggede bruger. Den kan kun se websteder og elementer, som denne bruger har adgang til. Brug en konto med passende læseadgang til alle websteder for et fuldt lejerscan.',
    SettingsTitle: 'Indstillinger',
    LibrariesSectionTitle: 'Biblioteker',
    IncludeHiddenLabel: 'Inkluder system- og skjulte biblioteker',
    IncludeHiddenTooltip: 'Hvis markeret, inkluderes stilbibliotek, formularskabeloner, webstedsaktiver og andre biblioteker, der er skjult fra standardvisninger. Gælder for alle værktøjer.',
    MoreInfoHiddenLibrariesLabel: 'Mere information om skjulte biblioteker',
    ExcludeLimitedAccessLabel: 'Udelad poster med begrænset adgang',
    ExcludeLimitedAccessTooltip: 'Skjuler brugere og grupper, hvis eneste SharePoint-tilladelse er Begrænset adgang — tildeles automatisk, når filer deles via links. Gælder for tilladelsesrapport, Udforsker og brugeradgang.',
    MoreInfoLimitedAccessLabel: 'Mere information om begrænset adgang',
    ExcludeSharingLinksLabel: 'Udelad poster for delingslinks',
    ExcludeSharingLinksTooltip: 'Skjuler de interne "SharingLinks.*"-grupper, som SharePoint automatisk opretter til "Alle med linket" og "Bestemte personer"-delingslinks. Gælder for tilladelsesrapport, Udforsker og brugeradgang.',
    MoreInfoSharingLinksLabel: 'Mere information om delingslinks',
    PerformanceSectionTitle: 'Ydeevne',
    ConcurrentRequestsLabel: 'Samtidige API-anmodninger:',
    ConcurrencyTooltip: 'Hvor mange SharePoint API-anmodninger der køres parallelt under scanninger af tilladelsesrapport, brugeradgang og baggrundskontroller i Udforsker. Højere værdier er hurtigere, men udløser oftere begrænsning (HTTP 429). 3–5 anbefales.',
    MoreInfoConcurrencyLabel: 'Mere information om samtidighed',
    ConcurrencyHint: 'Højere værdier scanner hurtigere, men kan udløse SharePoint-begrænsning. Anbefalet: 3–5.',
    GroupMemberCapLabel: 'Grænse for visning af gruppemedlemmer:',
    GroupMemberCapTooltip: 'Maksimalt antal medlemmer vist pr. gruppe, når "Udvid gruppemedlemmer" er aktiveret. Større grupper begrænses, og der vises en meddelelse. Forøgelse bruger mere hukommelse.',
    MoreInfoGroupMemberCapLabel: 'Mere information om grænsen for gruppemedlemmer',
    GroupMemberCapHint: 'Grupper større end denne grænse viser en afkortningsmeddelelse. Standard: 500.',
    DefaultViewSectionTitle: 'Standardvisning ved indlæsning',
    DefaultViewInstructionsIntro: 'For at ændre, hvilken skærm der åbnes, når webdelen indlæses første gang, skal du redigere webdelens egenskaber:',
    DefaultViewStep1Pre: 'Sæt SharePoint-siden i',
    DefaultViewStep1Post: '-tilstand.',
    DefaultViewStep2Pre: 'Klik på',
    DefaultViewStep2Post: '-ikonet på Smart Permissions-webdelen.',
    DefaultViewStep3Pre: 'I egenskabspanelet skal du vælge en visning fra rullelisten',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'siden for at gemme ændringen.',
    EditModeWord: 'Redigerings',
    PencilEditWord: 'blyant (rediger)',
    DefaultViewOnOpenWord: 'Standardvisning ved åbning',
    RepublishWord: 'Genudgiv',
    SiteOwnersLabel: 'Webstedsejere:',
    EveryoneClaimLabel: 'Alle',
    EveryoneExceptExternalClaimLabel: 'Alle undtagen eksterne brugere',
    PermissionAssignmentsLabel: 'Tilladelsestildelinger',
    UserGroupColumnHeader: 'Bruger / Gruppe',
    TypeColumnHeader: 'Type',
    PermissionLevelColumnHeader: 'Tilladelsesniveau',
    TenantWideAccessSuffix: '— lejerdækkende adgang',
    SecurityGroupType: 'Sikkerhedsgruppe',
    SpGroupType: 'SP-gruppe',
    UserType: 'Bruger',
    CheckAccessForLabel: 'Kontrollér adgang for {0}',
    ContainsUniqueAndExternalTooltip: 'Indeholder elementer med unikke tilladelser og ekstern brugeradgang',
    ContainsUniqueTooltip: 'Indeholder elementer med unikke tilladelser',
    ContainsExternalTooltip: 'Indeholder elementer med ekstern brugeradgang',
    UniqueBadge: 'Unik',
    ExternalAccessDetectedTooltip: 'Ekstern brugeradgang registreret',
    ConnectingStatus: 'Opretter forbindelse…',
    ConnectedLibrarySingular: 'Forbundet — {0} bibliotek fundet',
    ConnectedLibraryPlural: 'Forbundet — {0} biblioteker fundet',
    ConnectionFailedError: 'Forbindelsen mislykkedes: {0}',
    LibraryEmptyStatus: 'Dette bibliotek er tomt.',
    ErrorLoadingLibrary: 'Fejl ved indlæsning af bibliotek: {0}',
    ErrorLoadingContents: 'Fejl ved indlæsning af indhold',
    LibraryFieldLabel: 'Bibliotek',
    HiddenFromSearchSuffix: '{0} (skjult fra søgning)',
    UniquePermissionsOnlyToggle: 'Kun unikke tilladelser',
    ExternalUsersOnlyToggle: 'Kun eksterne brugere',
    LegendLabel: 'Forklaring:',
    LegendItemHasUnique: 'Element har unikke tilladelser',
    LegendContainsUniqueBelow: 'Indeholder unikke tilladelser nedenfor',
    LegendContainsExternalBelow: 'Indeholder ekstern brugeradgang nedenfor',
    LegendExternalOnItem: 'Ekstern brugeradgang på dette element',
    ViewingWithMemberAccessTitle: 'Ser med medlemsadgang',
    ViewingWithMemberAccessDesc1: '— tilladelsestildelinger er ikke synlige. At se, hvem der har adgang, kræver rettigheden',
    ManagePermissionsWord: 'Administrer tilladelser',
    ViewingWithMemberAccessDesc2: '(webstedsejer eller højere). Du kan stadig se, hvilke elementer der har brudt nedarvning, ved hjælp af ↓-indikatorerne. Brug værktøjet',
    UserAccessWord: 'Brugeradgang',
    ViewingWithMemberAccessDesc3: 'for at se steder, du kan tilgå.',
    FoldersAndFilesLabel: 'Mapper og filer',
    SelectFolderOrFilePrompt: 'Vælg en mappe eller fil for at se dens tilladelser.',
    UniquePermissionsBadge: 'Unikke tilladelser',
    InheritedBadge: 'Nedarvet',
    ExpandGroupMembersLabel: 'Udvid gruppemedlemmer',
    ShowParentPermissionsLabel: 'Vis overordnede tilladelser',
    InheritsFromParentText: 'Dette element nedarver tilladelser fra sit overordnede element.',
    YourAccessLabel: 'Din adgang:',
    PermissionsNotVisibleNodeText: 'Tilladelsestildelinger er ikke synlige — rettigheden Administrer tilladelser (webstedsejer eller højere) kræves for at se, hvem der har adgang til dette element.',
    NoExternalUsersDirectAccessText: 'Ingen eksterne brugere har direkte adgang til dette element.',
    InheritedFromLabel: 'Nedarvet fra:',
    ParentPermissionsNotVisibleText: 'Det overordnede elements tilladelsestildelinger er ikke synlige — kræver rettigheden Administrer tilladelser (webstedsejer eller højere).',
    NoPermissionsFoundOnParentText: 'Ingen tilladelser fundet på det overordnede element.',
    StartingScanStatus: 'Starter scanning…',
    ScanCancelledStatus: 'Scanning annulleret — {0} objekt(er) indsamlet før annullering.',
    ScanCompleteStatus: 'Scanning fuldført — {0} objekt(er) fundet, {1} med unikke tilladelser.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Scanning fuldført',
    ScanCompleteNotificationBody: '{0} objekter, {1} med unikke tilladelser.',
    CancelledStatus: 'Annulleret.',
    GenericErrorPrefix: 'Fejl: {0}',
    ExportErrorPrefix: 'Eksportfejl: {0}',
    ScopeSiteOnly: 'Kun websted',
    ScopeLibraries: 'Biblioteker',
    ScopeFolders: 'Mapper',
    ScopeFilesAndFolders: 'Filer og mapper',
    ScanInProgressConfirm: 'En scanning er i gang. Forlad og annuller?',
    HistoryButton: 'Historik',
    BackToHistoryButton: 'Tilbage til historik',
    ComparingLabel: 'Sammenligner',
    CompareMismatchWarning: 'Disse rapporter blev taget med forskellige websteder eller scanningsindstillinger — forskellene nedenfor kan afspejle de ændrede scanningsindstillinger snarere end faktiske tilladelsesændringer.',
    NoPermissionDifferencesFound: 'Ingen tilladelsesforskelle fundet mellem disse to rapporter.',
    PermissionChangesHeaderSingular: 'Tilladelsesændringer ({0} objekt)',
    PermissionChangesHeaderPlural: 'Tilladelsesændringer ({0} objekter)',
    ChangeColumnHeader: 'Ændring',
    BeforeColumnHeader: 'Før',
    AfterColumnHeader: 'Efter',
    AddedBadge: 'Tilføjet',
    RemovedBadge: 'Fjernet',
    ChangedBadge: 'Ændret',
    InheritanceChangedHeader: 'Nedarvning ændret ({0})',
    NameColumnHeader: 'Navn',
    PathColumnHeader: 'Sti',
    NowColumnHeader: 'Nu',
    UniqueInheritanceBrokenBadge: 'Unik (nedarvning brudt)',
    InheritedRestoredBadge: 'Nedarvet (gendannet)',
    NewObjectsHeader: 'Nye objekter',
    RemovedObjectsHeader: 'Fjernede objekter',
    BackToScanButton: 'Tilbage til scanning',
    CompareSelectedButton: 'Sammenlign valgte',
    NoReportsSavedYet: 'Ingen rapporter gemt endnu.',
    SelectForCompareLabel: 'Vælg til sammenligning',
    DateTimeColumnHeader: 'Dato / Tid',
    SiteColumnHeader: 'Websted',
    ScopeColumnHeader: 'Omfang',
    ObjectsColumnHeader: 'Objekter',
    UniqueColumnHeader: 'Unikke',
    SelectReportForCompareLabel: 'Vælg rapport fra {0} til sammenligning',
    AllSitesPrefix: 'Alle websteder · ',
    PlusSubsitesSuffix: ' + underwebsteder',
    ExportingStatus: 'Eksporterer…',
    ExportButton: 'Eksporter',
    DeleteThisReportTitle: 'Slet denne rapport',
    ScanAllSiteCollectionsLabel: 'Scan alle webstedssamlinger i denne lejer (kun tilgængelig på rodwebstedet)',
    AllSitesSearchCaveat: 'Webstedslisten kommer fra søgning og medtager muligvis ikke alle webstedssamlinger — meget nyoprettede websteder, eller websteder udelukket fra søgeindekset, kan mangle.',
    IncludeSubsitesLabel: 'Inkluder underwebsteder (scanner hvert underwebsted under dette websted)',
    ScanDepthFieldLabel: 'Scanningsdybde',
    FolderDepthLimitLabel: 'Grænse for mappedybde:',
    ExpandGroupMembersInReportLabel: 'Udvid gruppemedlemmer i rapporten (SharePoint-grupper, sikkerhedsgrupper og M365-grupper)',
    LibrariesToScanLabel: 'Biblioteker der skal scannes',
    OfSelectedCount: '{0} af {1} valgt',
    AllButton: 'Alle',
    NoneButton: 'Ingen',
    LoadingLibrariesStatus: 'Indlæser biblioteker…',
    RunReportButton: 'Kør rapport',
    ItemsFoundSoFar: '{0} elementer fundet indtil videre',
    LibraryOfProgress: 'Bibliotek {0} af {1}',
    ScanCancelledPartialResults: 'Scanning annulleret — delvise resultater',
    ScanCompleteLabel: 'Scanning fuldført',
    ObjectsCountBadge: '{0} objekter',
    UniqueCountBadge: '{0} unikke',
    InheritedCountBadge: '{0} nedarvet',
    GeneratingExcelStatus: 'Genererer Excel…',
    ExportFilteredRowsButton: 'Eksporter {0} filtrerede rækker',
    ExportToExcelButton: 'Eksporter til Excel',
    ExportToCsvButton: 'Eksporter til CSV',
    ScanStoppedEarlyTitle: 'Scanning stoppet tidligt — SharePoint begrænser denne lejer.',
    SiteCollectionsScannedBeforeStopping: '{0} af {1} webstedssamlinger blev scannet, før den stoppede. ',
    ResultsBelowCoverOnlyPre: 'Resultaterne nedenfor dækker kun det, der blev scannet, og er',
    NotWord: 'ikke',
    ResultsBelowCoverOnlyPost: 'en fuldstændig revision. Scanningen stopper sig selv i denne situation, fordi det er fortsat afsendelse af anmodninger, der opretholder begrænsningen. Vent flere minutter, og kør derefter igen med',
    ConcurrentRequestsWord: 'Samtidige anmodninger',
    SetTo1Or2InSettings: 'sat til 1 eller 2 i Indstillinger.',
    ThrottledScanMessage: 'SharePoint begrænsede denne scanning ({0} anmodning(er) blev hastighedsbegrænset og gentaget).',
    OfEverythingScannedPre: 'Af alt det scannede,',
    ItemCountSingular: '{0} element',
    ItemCountPlural: '{0} elementer',
    CouldNotBeConfirmedText: 'kunne ikke bekræftes efter gentagelse (se meddelelsen "kunne ikke læses fuldt ud" nedenfor for at se præcis hvilke) — den fejl var kapacitetsrelateret, ikke en afspejling af deres faktiske tilladelser. Alle andre elementer i denne rapport blev læst med succes og kan stoles på.',
    DespiteThrottlingText: 'På trods af begrænsningen blev hvert element stadig bekræftet med succes efter gentagelse, så denne rapport er komplet.',
    ForCleanRunPre: 'For en ren kørsel, vent et par minutter, og scan igen med en lavere værdi for',
    ValueInSettingsPost: 'i Indstillinger.',
    OneItemWord: '1 element',
    NItemsWord: '{0} element(er)',
    OutOfScannedCouldNotBeRead: 'ud af {0} scannede kunne ikke læses med din nuværende adgang —',
    PermissionAssignmentsForItAreNotShown: ' tilladelsestildelinger vises ikke, ',
    PermissionAssignmentsForThoseAreNotShown: ' tilladelsestildelinger vises ikke, ',
    RestOfReportReadSuccessfully: 'men resten af denne rapport blev læst med succes.',
    RunScanAsSiteOwnerPre: 'Kør scanningen som',
    SiteOwnerWord: 'webstedsejer',
    RunScanAsSiteOwnerPost: 'for at se fulde detaljer for de nægtede elementer nedenfor.',
    AndNMoreText: '…og {0} mere',
    GroupExpansionSkippedPre: 'Udvidelse af gruppemedlemmer blev sprunget over — Graph-tilladelsen',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'er ikke blevet godkendt i denne lejer. En SharePoint- eller global administrator kan godkende den i',
    SharePointAdminCenterPath: 'SharePoint-administrationscenter → Avanceret → API-adgang',
    ScanIncompleteItemsMessage: '{0} element(er) kunne ikke læses fuldt ud på grund af en midlertidig fejl (ikke et tilladelsesproblem) og vises med det overordnede elements tilladelser som en nødløsning — dette afspejler muligvis ikke deres faktiske adgang. Kør scanningen igen for at prøve disse elementer igen.',
    FilterByNamePathUserPlaceholder: 'Filtrer efter navn, sti eller bruger/gruppe…',
    FilterResultsLabel: 'Filtrer resultater',
    ExternalUsersOnlyExtLabel: 'Kun eksterne brugere (#ext#)',
    ShowingOfCount: 'Viser {0} af {1}',
    ScanResultsLabel: 'Scanningsresultater',
    PermissionsColumnHeader: 'Tilladelser',
    CollapsePermissionsLabel: 'Skjul tilladelser',
    ExpandPermissionsLabel: 'Udvid tilladelser',
    HiddenFromSearchBadge: 'Skjult fra søgning',
    AssignmentCountSingular: '{0} tildeling',
    AssignmentCountPlural: '{0} tildelinger',
    LoadMoreRemainingButton: 'Indlæs flere ({0} tilbage)',
    LoadingUsersStatus: 'Indlæser brugere…',
    ConnectedUserSingular: 'Forbundet — {0} bruger fundet',
    ConnectedUserPlural: 'Forbundet — {0} brugere fundet',
    CheckingAccessForStatus: 'Kontrollerer adgang for {0}…',
    FullSiteAccessDetectedStatus: 'Fuld webstedsadgang registreret.',
    AccessibleLocationsFoundSingular: '{0} tilgængelig placering fundet.',
    AccessibleLocationsFoundPlural: '{0} tilgængelige placeringer fundet.',
    NoAccessibleLocationsFoundStatus: 'Ingen tilgængelige placeringer fundet.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Brugeradgangsscanning fuldført',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Ny scanning',
    NoUserAccessScansSavedYet: 'Ingen brugeradgangsscanninger gemt endnu.',
    UserColumnHeader: 'Bruger',
    LocationsColumnHeader: 'Placeringer',
    FullControlBadge: 'Fuld kontrol',
    DeleteThisRecordTitle: 'Slet denne post',
    SelectAUserFieldLabel: 'Vælg en bruger',
    SearchUsersPlaceholder: 'Søg brugere…',
    SelectAUserToCheckAccessLabel: 'Vælg en bruger for at kontrollere adgang',
    NotInThisSiteLabel: 'Ikke på dette websted',
    ScanInProgressLabel: 'Scanning i gang',
    ScanningUserAccessLabel: 'Scanner brugeradgang',
    ScanningStatus: 'Scanner…',
    FullControlAccessPre: 'Denne bruger har',
    FullControlWord: 'Fuld kontrol',
    FullControlAccessPost: 'eller ejerniveau-adgang til hele webstedet — alle biblioteker og mapper er tilgængelige.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Tilladelse på webstedsniveau kunne ikke bestemmes — dette websted bruger sandsynligvis Microsoft 365-gruppeadgang. For at vise det skal en SharePoint-administrator godkende tilladelsen',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'i',
    ShowingSiteLevelAccessOnlyPre: 'Viser kun',
    SiteLevelAccessOnlyWord: 'adgang på webstedsniveau',
    ShowingSiteLevelAccessOnlyMid: ', baseret på standard SharePoint-gruppemedlemskab. Unikke tilladelser på biblioteker, mapper og filer kunne ikke læses og vises ikke. For fuldstændige resultater, kør denne scanning som',
    UserAccessCouldNotBeDeterminedPre: 'Denne brugers adgang kunne ikke bestemmes. At læse tilladelsestildelinger kræver rettigheden',
    UserAccessCouldNotBeDeterminedPost: '(webstedsejer eller højere), og denne bruger synes ikke at være medlem af webstedets standardgrupper for ejere, medlemmer eller besøgende.',
    SiteLevelAccessBannerPre: 'Denne bruger har adgang på webstedsniveau. Kun placeringer med',
    UniquePermissionAssignmentsWord: 'unikke tilladelsestildelinger',
    SiteLevelAccessBannerPost: 'vises nedenfor — alt andet indhold er tilgængeligt via tilladelsen på webstedsniveau vist øverst på listen.',
    UserAccessResultsLabel: 'Resultater for brugeradgang',
  };
});
