define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Διαμόρφωση Smart Permissions',
    PropertyPane_GroupName: 'Γενικά',
    PropertyPane_DefaultViewLabel: 'Προεπιλεγμένη προβολή κατά το άνοιγμα',
    PropertyPane_View_Home: 'Αρχική',
    PropertyPane_View_Report: 'Αναφορά δικαιωμάτων',
    PropertyPane_View_Explorer: 'Εξερευνητής δικαιωμάτων',
    PropertyPane_View_UserAccess: 'Πρόσβαση χρήστη',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/toposmou',
    ConnectButton: 'Σύνδεση',
    CancelButton: 'Ακύρωση',
    ChangeUrlButton: 'Αλλαγή URL',
    SettingsLabel: 'Ρυθμίσεις',
    RenderErrorTitle: 'Smart Permissions — Σφάλμα απόδοσης',
    RenderErrorMessageLabel: 'Μήνυμα:',
    RenderErrorStackLabel: 'Στοίβα:',
    RenderErrorNoStack: '(η στοίβα δεν είναι διαθέσιμη)',
    BackButton: 'Πίσω',
    BackToHomeLabel: 'Επιστροφή στην αρχική',
    ExplorerCardTitle: 'Εξερευνητής δικαιωμάτων',
    ExplorerCardAlt: 'Εξερευνητής δικαιωμάτων με δέντρο φακέλων και πίνακα δικαιωμάτων',
    ExplorerCardDesc: 'Περιηγηθείτε σε οποιονδήποτε φάκελο ή αρχείο και δείτε αμέσως ποιος έχει πρόσβαση — με έλεγχο δικαιωμάτων σε πραγματικό χρόνο.',
    ExplorerCardButton: 'Άνοιγμα Εξερευνητή δικαιωμάτων',
    ReportCardTitle: 'Αναφορά δικαιωμάτων',
    ReportCardAlt: 'Οθόνη διαμόρφωσης αναφοράς δικαιωμάτων',
    ReportCardDesc: 'Δημιουργήστε μια έγχρωμη αναφορά Excel για κάθε μοναδική ανάθεση δικαιώματος στον ιστότοπό σας.',
    ReportCardButton: 'Εκτέλεση αναφοράς δικαιωμάτων',
    UserAccessCardTitle: 'Πρόσβαση χρήστη',
    UserAccessCardAlt: 'Οθόνη πρόσβασης χρήστη που εμφανίζει τις προσβάσιμες τοποθεσίες για έναν επιλεγμένο χρήστη',
    UserAccessCardDesc: 'Αναζητήστε οποιονδήποτε χρήστη για να δείτε κάθε τοποθεσία στην οποία έχει πρόσβαση σε έναν ιστότοπο, με το ακριβές επίπεδο δικαιώματος.',
    UserAccessCardButton: 'Έλεγχος πρόσβασης χρήστη',
    SiteOwnerRequiredTitle: 'Απαιτείται πρόσβαση Κατόχου ιστότοπου —',
    SiteOwnerRequiredDesc: 'Αυτά τα εργαλεία απαιτούν πρόσβαση Κατόχου ιστότοπου. Επικοινωνήστε με έναν κάτοχο ιστότοπου εάν έχετε ερωτήσεις σχετικά με τα δικαιώματα.',
    HomeSubtitle: 'Ελέγξτε και κατανοήστε τα δικαιώματα SharePoint — χωρίς PowerShell.',
    RequiresSiteOwnerTooltip: 'Απαιτεί πρόσβαση Κατόχου ιστότοπου',
    HomeNoteLabel: 'Σημείωση:',
    HomeNoteText: 'Αυτό το τμήμα web εκτελείται ως ο τρέχων συνδεδεμένος χρήστης. Μπορεί να δει μόνο ιστότοπους και στοιχεία στα οποία αυτός ο χρήστης έχει δικαίωμα πρόσβασης. Για πλήρη σάρωση μισθωτή, χρησιμοποιήστε έναν λογαριασμό με κατάλληλη πρόσβαση ανάγνωσης σε όλους τους ιστότοπους.',
    SettingsTitle: 'Ρυθμίσεις',
    LibrariesSectionTitle: 'Βιβλιοθήκες',
    IncludeHiddenLabel: 'Συμπερίληψη βιβλιοθηκών συστήματος και κρυφών',
    IncludeHiddenTooltip: 'Εάν είναι επιλεγμένο, περιλαμβάνει τη Βιβλιοθήκη στυλ, τα Πρότυπα φόρμας, τα Στοιχεία ιστότοπου και άλλες βιβλιοθήκες που είναι κρυμμένες από τις προεπιλεγμένες προβολές. Ισχύει για όλα τα εργαλεία.',
    MoreInfoHiddenLibrariesLabel: 'Περισσότερες πληροφορίες για τις κρυφές βιβλιοθήκες',
    ExcludeLimitedAccessLabel: 'Εξαίρεση καταχωρήσεων περιορισμένης πρόσβασης',
    ExcludeLimitedAccessTooltip: 'Αποκρύπτει χρήστες και ομάδες των οποίων το μοναδικό δικαίωμα SharePoint είναι Περιορισμένη πρόσβαση — εκχωρείται αυτόματα όταν τα αρχεία κοινοποιούνται μέσω συνδέσμων. Ισχύει για την Αναφορά δικαιωμάτων, τον Εξερευνητή και την Πρόσβαση χρήστη.',
    MoreInfoLimitedAccessLabel: 'Περισσότερες πληροφορίες για την περιορισμένη πρόσβαση',
    ExcludeSharingLinksLabel: 'Εξαίρεση καταχωρήσεων συνδέσμων κοινής χρήσης',
    ExcludeSharingLinksTooltip: 'Αποκρύπτει τις εσωτερικές ομάδες "SharingLinks.*" που δημιουργεί αυτόματα το SharePoint για συνδέσμους κοινής χρήσης "Οποιοσδήποτε έχει τον σύνδεσμο" και "Συγκεκριμένα άτομα". Ισχύει για την Αναφορά δικαιωμάτων, τον Εξερευνητή και την Πρόσβαση χρήστη.',
    MoreInfoSharingLinksLabel: 'Περισσότερες πληροφορίες για συνδέσμους κοινής χρήσης',
    PerformanceSectionTitle: 'Απόδοση',
    ConcurrentRequestsLabel: 'Ταυτόχρονα αιτήματα API:',
    ConcurrencyTooltip: 'Πόσα αιτήματα API SharePoint εκτελούνται παράλληλα κατά τις σαρώσεις της Αναφοράς δικαιωμάτων, τις σαρώσεις Πρόσβασης χρήστη και τους ελέγχους παρασκηνίου του Εξερευνητή. Οι υψηλότερες τιμές είναι ταχύτερες αλλά πιο πιθανό να ενεργοποιήσουν τον περιορισμό (HTTP 429). Συνιστάται 3–5.',
    MoreInfoConcurrencyLabel: 'Περισσότερες πληροφορίες για την ταυτοχρονία',
    ConcurrencyHint: 'Οι υψηλότερες τιμές σαρώνουν ταχύτερα αλλά μπορεί να ενεργοποιήσουν τον περιορισμό SharePoint. Συνιστώμενο: 3–5.',
    GroupMemberCapLabel: 'Όριο εμφάνισης μελών ομάδας:',
    GroupMemberCapTooltip: 'Μέγιστος αριθμός μελών που εμφανίζονται ανά ομάδα όταν είναι ενεργοποιημένη η επιλογή "Επέκταση μελών ομάδας". Οι μεγαλύτερες ομάδες περιορίζονται και εμφανίζεται μια ειδοποίηση. Η αύξηση αυτού χρησιμοποιεί περισσότερη μνήμη.',
    MoreInfoGroupMemberCapLabel: 'Περισσότερες πληροφορίες για το όριο μελών ομάδας',
    GroupMemberCapHint: 'Ομάδες μεγαλύτερες από αυτό το όριο εμφανίζουν ειδοποίηση περικοπής. Προεπιλογή: 500.',
    DefaultViewSectionTitle: 'Προεπιλεγμένη προβολή κατά τη φόρτωση',
    DefaultViewInstructionsIntro: 'Για να αλλάξετε ποια οθόνη ανοίγει όταν το τμήμα web φορτώνεται για πρώτη φορά, επεξεργαστείτε τις ιδιότητες του τμήματος web:',
    DefaultViewStep1Pre: 'Θέστε τη σελίδα SharePoint σε λειτουργία',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Κάντε κλικ στο εικονίδιο',
    DefaultViewStep2Post: 'στο τμήμα web Smart Permissions.',
    DefaultViewStep3Pre: 'Στον πίνακα ιδιοτήτων, επιλέξτε μια προβολή από την αναπτυσσόμενη λίστα',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'τη σελίδα για να αποθηκεύσετε την αλλαγή.',
    EditModeWord: 'Επεξεργασίας',
    PencilEditWord: 'μολύβι (επεξεργασία)',
    DefaultViewOnOpenWord: 'Προεπιλεγμένη προβολή κατά το άνοιγμα',
    RepublishWord: 'Αναδημοσιεύστε',
    SiteOwnersLabel: 'Κάτοχοι ιστότοπου:',
    EveryoneClaimLabel: 'Όλοι',
    EveryoneExceptExternalClaimLabel: 'Όλοι εκτός από εξωτερικούς χρήστες',
    PermissionAssignmentsLabel: 'Αναθέσεις δικαιωμάτων',
    UserGroupColumnHeader: 'Χρήστης / Ομάδα',
    TypeColumnHeader: 'Τύπος',
    PermissionLevelColumnHeader: 'Επίπεδο δικαιώματος',
    TenantWideAccessSuffix: '— πρόσβαση σε όλο τον μισθωτή',
    SecurityGroupType: 'Ομάδα ασφαλείας',
    SpGroupType: 'Ομάδα SP',
    UserType: 'Χρήστης',
    CheckAccessForLabel: 'Έλεγχος πρόσβασης για {0}',
    ContainsUniqueAndExternalTooltip: 'Περιέχει στοιχεία με μοναδικά δικαιώματα και πρόσβαση εξωτερικών χρηστών',
    ContainsUniqueTooltip: 'Περιέχει στοιχεία με μοναδικά δικαιώματα',
    ContainsExternalTooltip: 'Περιέχει στοιχεία με πρόσβαση εξωτερικών χρηστών',
    UniqueBadge: 'Μοναδικό',
    ExternalAccessDetectedTooltip: 'Εντοπίστηκε πρόσβαση εξωτερικού χρήστη',
    ConnectingStatus: 'Σύνδεση…',
    ConnectedLibrarySingular: 'Συνδέθηκε — βρέθηκε {0} βιβλιοθήκη',
    ConnectedLibraryPlural: 'Συνδέθηκε — βρέθηκαν {0} βιβλιοθήκες',
    ConnectionFailedError: 'Η σύνδεση απέτυχε: {0}',
    LibraryEmptyStatus: 'Αυτή η βιβλιοθήκη είναι άδεια.',
    ErrorLoadingLibrary: 'Σφάλμα κατά τη φόρτωση της βιβλιοθήκης: {0}',
    ErrorLoadingContents: 'Σφάλμα κατά τη φόρτωση περιεχομένου',
    LibraryFieldLabel: 'Βιβλιοθήκη',
    HiddenFromSearchSuffix: '{0} (κρυμμένο από την αναζήτηση)',
    UniquePermissionsOnlyToggle: 'Μόνο μοναδικά δικαιώματα',
    ExternalUsersOnlyToggle: 'Μόνο εξωτερικοί χρήστες',
    LegendLabel: 'Υπόμνημα:',
    LegendItemHasUnique: 'Το στοιχείο έχει μοναδικά δικαιώματα',
    LegendContainsUniqueBelow: 'Περιέχει μοναδικά δικαιώματα παρακάτω',
    LegendContainsExternalBelow: 'Περιέχει πρόσβαση εξωτερικού χρήστη παρακάτω',
    LegendExternalOnItem: 'Πρόσβαση εξωτερικού χρήστη σε αυτό το στοιχείο',
    ViewingWithMemberAccessTitle: 'Προβολή με πρόσβαση μέλους',
    ViewingWithMemberAccessDesc1: '— οι αναθέσεις δικαιωμάτων δεν είναι ορατές. Η ανάγνωση του ποιος έχει πρόσβαση απαιτεί το δικαίωμα',
    ManagePermissionsWord: 'Διαχείριση δικαιωμάτων',
    ViewingWithMemberAccessDesc2: '(κάτοχος ιστότοπου ή υψηλότερο). Μπορείτε ακόμα να δείτε ποια στοιχεία έχουν διακοπεί την κληρονομικότητα χρησιμοποιώντας τους δείκτες ↓. Για να δείτε τοποθεσίες στις οποίες έχετε πρόσβαση, χρησιμοποιήστε το εργαλείο',
    UserAccessWord: 'Πρόσβαση χρήστη',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Φάκελοι και αρχεία',
    SelectFolderOrFilePrompt: 'Επιλέξτε έναν φάκελο ή αρχείο για να δείτε τα δικαιώματά του.',
    UniquePermissionsBadge: 'Μοναδικά δικαιώματα',
    InheritedBadge: 'Κληρονομημένο',
    ExpandGroupMembersLabel: 'Επέκταση μελών ομάδας',
    ShowParentPermissionsLabel: 'Εμφάνιση γονικών δικαιωμάτων',
    InheritsFromParentText: 'Αυτό το στοιχείο κληρονομεί δικαιώματα από το γονικό του στοιχείο.',
    YourAccessLabel: 'Η πρόσβασή σας:',
    PermissionsNotVisibleNodeText: 'Οι αναθέσεις δικαιωμάτων δεν είναι ορατές — απαιτείται το δικαίωμα Διαχείριση δικαιωμάτων (κάτοχος ιστότοπου ή υψηλότερο) για να δείτε ποιος έχει πρόσβαση σε αυτό το στοιχείο.',
    NoExternalUsersDirectAccessText: 'Κανένας εξωτερικός χρήστης δεν έχει άμεση πρόσβαση σε αυτό το στοιχείο.',
    InheritedFromLabel: 'Κληρονομημένο από:',
    ParentPermissionsNotVisibleText: 'Οι αναθέσεις δικαιωμάτων του γονικού στοιχείου δεν είναι ορατές — απαιτεί το δικαίωμα Διαχείριση δικαιωμάτων (κάτοχος ιστότοπου ή υψηλότερο).',
    NoPermissionsFoundOnParentText: 'Δεν βρέθηκαν δικαιώματα στο γονικό στοιχείο.',
    StartingScanStatus: 'Έναρξη σάρωσης…',
    ScanCancelledStatus: 'Η σάρωση ακυρώθηκε — συλλέχθηκαν {0} αντικείμενο(α) πριν την ακύρωση.',
    ScanCompleteStatus: 'Η σάρωση ολοκληρώθηκε — βρέθηκαν {0} αντικείμενο(α), {1} με μοναδικά δικαιώματα.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Η σάρωση ολοκληρώθηκε',
    ScanCompleteNotificationBody: '{0} αντικείμενα, {1} με μοναδικά δικαιώματα.',
    CancelledStatus: 'Ακυρώθηκε.',
    GenericErrorPrefix: 'Σφάλμα: {0}',
    ExportErrorPrefix: 'Σφάλμα εξαγωγής: {0}',
    ScopeSiteOnly: 'Μόνο ιστότοπος',
    ScopeLibraries: 'Βιβλιοθήκες',
    ScopeFolders: 'Φάκελοι',
    ScopeFilesAndFolders: 'Αρχεία και φάκελοι',
    ScanInProgressConfirm: 'Μια σάρωση βρίσκεται σε εξέλιξη. Έξοδος και ακύρωση;',
    HistoryButton: 'Ιστορικό',
    BackToHistoryButton: 'Επιστροφή στο ιστορικό',
    ComparingLabel: 'Σύγκριση',
    CompareMismatchWarning: 'Αυτές οι αναφορές δημιουργήθηκαν με διαφορετικούς ιστότοπους ή επιλογές σάρωσης — οι παρακάτω διαφορές μπορεί να αντικατοπτρίζουν τις αλλαγμένες ρυθμίσεις σάρωσης και όχι πραγματικές αλλαγές δικαιωμάτων.',
    NoPermissionDifferencesFound: 'Δεν βρέθηκαν διαφορές δικαιωμάτων μεταξύ αυτών των δύο αναφορών.',
    PermissionChangesHeaderSingular: 'Αλλαγές δικαιωμάτων ({0} αντικείμενο)',
    PermissionChangesHeaderPlural: 'Αλλαγές δικαιωμάτων ({0} αντικείμενα)',
    ChangeColumnHeader: 'Αλλαγή',
    BeforeColumnHeader: 'Πριν',
    AfterColumnHeader: 'Μετά',
    AddedBadge: 'Προστέθηκε',
    RemovedBadge: 'Αφαιρέθηκε',
    ChangedBadge: 'Άλλαξε',
    InheritanceChangedHeader: 'Η κληρονομικότητα άλλαξε ({0})',
    NameColumnHeader: 'Όνομα',
    PathColumnHeader: 'Διαδρομή',
    NowColumnHeader: 'Τώρα',
    UniqueInheritanceBrokenBadge: 'Μοναδικό (η κληρονομικότητα διακόπηκε)',
    InheritedRestoredBadge: 'Κληρονομημένο (αποκαταστάθηκε)',
    NewObjectsHeader: 'Νέα αντικείμενα',
    RemovedObjectsHeader: 'Αφαιρεθέντα αντικείμενα',
    BackToScanButton: 'Επιστροφή στη σάρωση',
    CompareSelectedButton: 'Σύγκριση επιλεγμένων',
    NoReportsSavedYet: 'Δεν έχουν αποθηκευτεί ακόμα αναφορές.',
    SelectForCompareLabel: 'Επιλογή για σύγκριση',
    DateTimeColumnHeader: 'Ημερομηνία / Ώρα',
    SiteColumnHeader: 'Ιστότοπος',
    ScopeColumnHeader: 'Εύρος',
    ObjectsColumnHeader: 'Αντικείμενα',
    UniqueColumnHeader: 'Μοναδικά',
    SelectReportForCompareLabel: 'Επιλέξτε αναφορά από {0} για σύγκριση',
    AllSitesPrefix: 'Όλοι οι ιστότοποι · ',
    PlusSubsitesSuffix: ' + υποϊστότοποι',
    ExportingStatus: 'Εξαγωγή…',
    ExportButton: 'Εξαγωγή',
    DeleteThisReportTitle: 'Διαγραφή αυτής της αναφοράς',
    ScanAllSiteCollectionsLabel: 'Σάρωση όλων των συλλογών ιστότοπων σε αυτόν τον μισθωτή (διαθέσιμο μόνο στον ριζικό ιστότοπο)',
    AllSitesSearchCaveat: 'Η λίστα ιστότοπων προέρχεται από την αναζήτηση και ενδέχεται να μην περιλαμβάνει κάθε συλλογή ιστότοπων — πολύ πρόσφατα δημιουργημένοι ιστότοποι, ή ιστότοποι που αποκλείονται από το ευρετήριο αναζήτησης, μπορεί να λείπουν.',
    IncludeSubsitesLabel: 'Συμπερίληψη υποϊστότοπων (σαρώνει κάθε υποϊστότοπο κάτω από αυτόν τον ιστότοπο)',
    ScanDepthFieldLabel: 'Βάθος σάρωσης',
    FolderDepthLimitLabel: 'Όριο βάθους φακέλων:',
    ExpandGroupMembersInReportLabel: 'Επέκταση μελών ομάδας στην αναφορά (ομάδες SharePoint, ομάδες ασφαλείας και ομάδες M365)',
    LibrariesToScanLabel: 'Βιβλιοθήκες προς σάρωση',
    OfSelectedCount: '{0} από {1} επιλεγμένα',
    AllButton: 'Όλα',
    NoneButton: 'Κανένα',
    LoadingLibrariesStatus: 'Φόρτωση βιβλιοθηκών…',
    RunReportButton: 'Εκτέλεση αναφοράς',
    ItemsFoundSoFar: 'Βρέθηκαν {0} στοιχεία μέχρι στιγμής',
    LibraryOfProgress: 'Βιβλιοθήκη {0} από {1}',
    ScanCancelledPartialResults: 'Η σάρωση ακυρώθηκε — μερικά αποτελέσματα',
    ScanCompleteLabel: 'Η σάρωση ολοκληρώθηκε',
    ObjectsCountBadge: '{0} αντικείμενα',
    UniqueCountBadge: '{0} μοναδικά',
    InheritedCountBadge: '{0} κληρονομημένα',
    GeneratingExcelStatus: 'Δημιουργία Excel…',
    ExportFilteredRowsButton: 'Εξαγωγή {0} φιλτραρισμένων γραμμών',
    ExportToExcelButton: 'Εξαγωγή σε Excel',
    ExportToCsvButton: 'Εξαγωγή σε CSV',
    ScanStoppedEarlyTitle: 'Η σάρωση σταμάτησε νωρίτερα — το SharePoint περιορίζει αυτόν τον μισθωτή.',
    SiteCollectionsScannedBeforeStopping: '{0} από {1} συλλογές ιστότοπων σαρώθηκαν πριν από τη διακοπή. ',
    ResultsBelowCoverOnlyPre: 'Τα παρακάτω αποτελέσματα καλύπτουν μόνο ό,τι σαρώθηκε και δεν είναι',
    NotWord: 'δεν είναι',
    ResultsBelowCoverOnlyPost: 'πλήρης έλεγχος. Η σάρωση σταματά μόνη της σε αυτή την κατάσταση επειδή η συνέχιση της αποστολής αιτημάτων διατηρεί τον περιορισμό ενεργό. Περιμένετε αρκετά λεπτά και μετά εκτελέστε ξανά με',
    ConcurrentRequestsWord: 'Ταυτόχρονα αιτήματα',
    SetTo1Or2InSettings: 'ρυθμισμένο σε 1 ή 2 στις Ρυθμίσεις.',
    ThrottledScanMessage: 'Το SharePoint περιόρισε αυτήν τη σάρωση ({0} αίτημα(τα) περιορίστηκαν και επαναλήφθηκαν).',
    OfEverythingScannedPre: 'Από όλα όσα σαρώθηκαν,',
    ItemCountSingular: '{0} στοιχείο',
    ItemCountPlural: '{0} στοιχεία',
    CouldNotBeConfirmedText: 'δεν μπόρεσαν να επιβεβαιωθούν μετά από επανάληψη (δείτε την ειδοποίηση "δεν μπόρεσε να διαβαστεί πλήρως" παρακάτω για να δείτε ακριβώς ποια) — αυτή η αποτυχία σχετιζόταν με τη χωρητικότητα, όχι με τα πραγματικά τους δικαιώματα. Όλα τα άλλα στοιχεία σε αυτήν την αναφορά διαβάστηκαν με επιτυχία και είναι αξιόπιστα.',
    DespiteThrottlingText: 'Παρά τον περιορισμό, κάθε στοιχείο επιβεβαιώθηκε με επιτυχία μετά από επανάληψη, οπότε αυτή η αναφορά είναι πλήρης.',
    ForCleanRunPre: 'Για μια καθαρή εκτέλεση, περιμένετε λίγα λεπτά και σαρώστε ξανά με μια χαμηλότερη τιμή για',
    ValueInSettingsPost: 'στις Ρυθμίσεις.',
    OneItemWord: '1 στοιχείο',
    NItemsWord: '{0} στοιχείο(α)',
    OutOfScannedCouldNotBeRead: 'από {0} που σαρώθηκαν δεν μπόρεσαν να διαβαστούν με την τρέχουσα πρόσβασή σας —',
    PermissionAssignmentsForItAreNotShown: ' οι αναθέσεις δικαιωμάτων δεν εμφανίζονται, ',
    PermissionAssignmentsForThoseAreNotShown: ' οι αναθέσεις δικαιωμάτων δεν εμφανίζονται, ',
    RestOfReportReadSuccessfully: 'αλλά το υπόλοιπο αυτής της αναφοράς διαβάστηκε με επιτυχία.',
    RunScanAsSiteOwnerPre: 'Εκτελέστε τη σάρωση ως',
    SiteOwnerWord: 'κάτοχος ιστότοπου',
    RunScanAsSiteOwnerPost: 'για να δείτε πλήρεις λεπτομέρειες για τα απορριφθέντα στοιχεία παρακάτω.',
    AndNMoreText: '…και {0} ακόμα',
    GroupExpansionSkippedPre: 'Η επέκταση των μελών της ομάδας παραλείφθηκε — το δικαίωμα Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'δεν έχει εγκριθεί σε αυτόν τον μισθωτή. Ένας διαχειριστής SharePoint ή γενικός διαχειριστής μπορεί να το εγκρίνει στο',
    SharePointAdminCenterPath: 'Κέντρο διαχείρισης SharePoint → Σύνθετα → Πρόσβαση API',
    ScanIncompleteItemsMessage: '{0} στοιχείο(α) δεν μπόρεσαν να διαβαστούν πλήρως λόγω προσωρινού σφάλματος (όχι πρόβλημα δικαιωμάτων) και εμφανίζονται με τα δικαιώματα του γονικού τους στοιχείου ως εναλλακτική λύση — αυτό μπορεί να μην αντικατοπτρίζει την πραγματική τους πρόσβαση. Εκτελέστε ξανά τη σάρωση για να επαναλάβετε αυτά τα στοιχεία.',
    FilterByNamePathUserPlaceholder: 'Φιλτράρισμα κατά όνομα, διαδρομή ή χρήστη/ομάδα…',
    FilterResultsLabel: 'Φιλτράρισμα αποτελεσμάτων',
    ExternalUsersOnlyExtLabel: 'Μόνο εξωτερικοί χρήστες (#ext#)',
    ShowingOfCount: 'Εμφάνιση {0} από {1}',
    ScanResultsLabel: 'Αποτελέσματα σάρωσης',
    PermissionsColumnHeader: 'Δικαιώματα',
    CollapsePermissionsLabel: 'Σύμπτυξη δικαιωμάτων',
    ExpandPermissionsLabel: 'Επέκταση δικαιωμάτων',
    HiddenFromSearchBadge: 'Κρυμμένο από την αναζήτηση',
    AssignmentCountSingular: '{0} ανάθεση',
    AssignmentCountPlural: '{0} αναθέσεις',
    LoadMoreRemainingButton: 'Φόρτωση περισσότερων (απομένουν {0})',
    LoadingUsersStatus: 'Φόρτωση χρηστών…',
    ConnectedUserSingular: 'Συνδέθηκε — βρέθηκε {0} χρήστης',
    ConnectedUserPlural: 'Συνδέθηκε — βρέθηκαν {0} χρήστες',
    CheckingAccessForStatus: 'Έλεγχος πρόσβασης για {0}…',
    FullSiteAccessDetectedStatus: 'Εντοπίστηκε πλήρης πρόσβαση στον ιστότοπο.',
    AccessibleLocationsFoundSingular: 'Βρέθηκε {0} προσβάσιμη τοποθεσία.',
    AccessibleLocationsFoundPlural: 'Βρέθηκαν {0} προσβάσιμες τοποθεσίες.',
    NoAccessibleLocationsFoundStatus: 'Δεν βρέθηκαν προσβάσιμες τοποθεσίες.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Η σάρωση πρόσβασης χρήστη ολοκληρώθηκε',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Νέα σάρωση',
    NoUserAccessScansSavedYet: 'Δεν έχουν αποθηκευτεί ακόμα σαρώσεις πρόσβασης χρήστη.',
    UserColumnHeader: 'Χρήστης',
    LocationsColumnHeader: 'Τοποθεσίες',
    FullControlBadge: 'Πλήρης έλεγχος',
    DeleteThisRecordTitle: 'Διαγραφή αυτής της εγγραφής',
    SelectAUserFieldLabel: 'Επιλέξτε έναν χρήστη',
    SearchUsersPlaceholder: 'Αναζήτηση χρηστών…',
    SelectAUserToCheckAccessLabel: 'Επιλέξτε έναν χρήστη για να ελέγξετε την πρόσβαση',
    NotInThisSiteLabel: 'Δεν είναι σε αυτόν τον ιστότοπο',
    ScanInProgressLabel: 'Η σάρωση βρίσκεται σε εξέλιξη',
    ScanningUserAccessLabel: 'Σάρωση πρόσβασης χρήστη',
    ScanningStatus: 'Σάρωση…',
    FullControlAccessPre: 'Αυτός ο χρήστης έχει',
    FullControlWord: 'Πλήρη έλεγχο',
    FullControlAccessPost: 'ή πρόσβαση επιπέδου Κατόχου σε ολόκληρο τον ιστότοπο — όλες οι βιβλιοθήκες και οι φάκελοι είναι προσβάσιμοι.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Το δικαίωμα σε επίπεδο ιστότοπου δεν μπόρεσε να προσδιοριστεί — αυτός ο ιστότοπος πιθανώς χρησιμοποιεί πρόσβαση ομάδας Microsoft 365. Για να το εμφανίσετε, ένας διαχειριστής SharePoint πρέπει να εγκρίνει το δικαίωμα',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph στο',
    ShowingSiteLevelAccessOnlyPre: 'Εμφανίζεται μόνο',
    SiteLevelAccessOnlyWord: 'πρόσβαση σε επίπεδο ιστότοπου',
    ShowingSiteLevelAccessOnlyMid: ', με βάση την προεπιλεγμένη συμμετοχή στην ομάδα SharePoint. Τα μοναδικά δικαιώματα σε βιβλιοθήκες, φακέλους και αρχεία δεν μπόρεσαν να διαβαστούν και δεν εμφανίζονται. Για πλήρη αποτελέσματα, εκτελέστε αυτήν τη σάρωση ως',
    UserAccessCouldNotBeDeterminedPre: 'Η πρόσβαση αυτού του χρήστη δεν μπόρεσε να προσδιοριστεί. Η ανάγνωση των αναθέσεων δικαιωμάτων απαιτεί το δικαίωμα',
    UserAccessCouldNotBeDeterminedPost: '(κάτοχος ιστότοπου ή υψηλότερο), και αυτός ο χρήστης δεν φαίνεται να είναι μέλος των προεπιλεγμένων ομάδων Κάτοχοι, Μέλη ή Επισκέπτες του ιστότοπου.',
    SiteLevelAccessBannerPre: 'Αυτός ο χρήστης έχει πρόσβαση σε επίπεδο ιστότοπου. Μόνο τοποθεσίες με',
    UniquePermissionAssignmentsWord: 'μοναδικές αναθέσεις δικαιωμάτων',
    SiteLevelAccessBannerPost: 'εμφανίζονται παρακάτω — όλο το υπόλοιπο περιεχόμενο είναι προσβάσιμο μέσω του δικαιώματος σε επίπεδο ιστότοπου που εμφανίζεται στην κορυφή της λίστας.',
    UserAccessResultsLabel: 'Αποτελέσματα πρόσβασης χρήστη',
  };
});
