define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions configuration',
    PropertyPane_GroupName: 'General',
    PropertyPane_DefaultViewLabel: 'Default view on open',
    PropertyPane_View_Home: 'Home',
    PropertyPane_View_Report: 'Permissions Report',
    PropertyPane_View_Explorer: 'Permissions Explorer',
    PropertyPane_View_UserAccess: 'User Access',

    // App shell
    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: 'Connect',
    CancelButton: 'Cancel',
    ChangeUrlButton: 'Change URL',
    SettingsLabel: 'Settings',
    RenderErrorTitle: 'Smart Permissions — Render Error',
    RenderErrorMessageLabel: 'Message:',
    RenderErrorStackLabel: 'Stack:',
    RenderErrorNoStack: '(no stack available)',
    BackButton: 'Back',
    BackToHomeLabel: 'Back to home',

    // Home view
    ExplorerCardTitle: 'Permissions Explorer',
    ExplorerCardAlt: 'Permissions Explorer with folder tree and permissions panel',
    ExplorerCardDesc: 'Browse any folder or file and instantly see who has access — with live, real-time permission lookups.',
    ExplorerCardButton: 'Open Permissions Explorer',
    ReportCardTitle: 'Permissions Report',
    ReportCardAlt: 'Permissions Report configuration screen',
    ReportCardDesc: 'Generate a color-coded Excel report of every unique permission assignment across your site.',
    ReportCardButton: 'Run Permissions Report',
    UserAccessCardTitle: 'User Access',
    UserAccessCardAlt: 'User Access screen showing accessible locations for a selected user',
    UserAccessCardDesc: 'Look up any user to see every location they can access on a site, with their exact permission level.',
    UserAccessCardButton: 'Check User Access',
    SiteOwnerRequiredTitle: 'Site Owner access required —',
    SiteOwnerRequiredDesc: 'These tools require Site Owner access. Contact a site owner if you have questions about permissions.',
    HomeSubtitle: 'Audit and understand SharePoint permissions — no PowerShell required.',
    RequiresSiteOwnerTooltip: 'Requires Site Owner access',
    HomeNoteLabel: 'Note:',
    HomeNoteText: 'This web part runs as the currently signed-in user. It can only see sites and items that user has permission to view. For a full tenant scan, use an account with appropriate read access across all sites.',

    // Settings view
    SettingsTitle: 'Settings',
    LibrariesSectionTitle: 'Libraries',
    IncludeHiddenLabel: 'Include system and hidden libraries',
    IncludeHiddenTooltip: 'When checked, includes Style Library, Form Templates, Site Assets, and other libraries hidden from default views. Applies to all tools.',
    MoreInfoHiddenLibrariesLabel: 'More info about hidden libraries',
    ExcludeLimitedAccessLabel: 'Exclude Limited Access entries',
    ExcludeLimitedAccessTooltip: 'Hides users and groups whose only SharePoint permission is Limited Access — automatically assigned when files are shared via links. Applies to Permissions Report, Explorer, and User Access.',
    MoreInfoLimitedAccessLabel: 'More info about Limited Access',
    ExcludeSharingLinksLabel: 'Exclude Sharing Links entries',
    ExcludeSharingLinksTooltip: 'Hides the internal "SharingLinks.*" groups SharePoint auto-creates for "Anyone with the link" and "Specific people" sharing links. Applies to Permissions Report, Explorer, and User Access.',
    MoreInfoSharingLinksLabel: 'More info about Sharing Links',
    PerformanceSectionTitle: 'Performance',
    ConcurrentRequestsLabel: 'Concurrent API requests:',
    ConcurrencyTooltip: 'How many SharePoint API requests run in parallel during Permissions Report scans, User Access scans, and Explorer background checks. Higher values are faster but more likely to trigger throttling (HTTP 429). 3–5 is recommended.',
    MoreInfoConcurrencyLabel: 'More info about concurrency',
    ConcurrencyHint: 'Higher values scan faster but may trigger SharePoint throttling. Recommended: 3–5.',
    GroupMemberCapLabel: 'Group member display cap:',
    GroupMemberCapTooltip: "Maximum members shown per group when 'Expand group members' is enabled. Larger groups are capped and a notice is shown. Increasing this uses more memory.",
    MoreInfoGroupMemberCapLabel: 'More info about group member cap',
    GroupMemberCapHint: 'Groups larger than this limit show a truncation notice. Default: 500.',
    DefaultViewSectionTitle: 'Default view on load',
    DefaultViewInstructionsIntro: 'To change which screen opens when the web part first loads, edit the web part properties:',
    DefaultViewStep1Pre: 'Put the SharePoint page into',
    DefaultViewStep1Post: 'mode.',
    DefaultViewStep2Pre: 'Click the',
    DefaultViewStep2Post: 'icon on the Smart Permissions web part.',
    DefaultViewStep3Pre: 'In the property panel, choose a view from the',
    DefaultViewStep3Post: 'dropdown.',
    DefaultViewStep4Post: 'the page to save the change.',
    EditModeWord: 'Edit',
    PencilEditWord: 'pencil (edit)',
    DefaultViewOnOpenWord: 'Default view on open',
    RepublishWord: 'Republish',

    // Shared
    SiteOwnersLabel: 'Site Owners:',
    EveryoneClaimLabel: 'Everyone',
    EveryoneExceptExternalClaimLabel: 'Everyone except external users',
    PermissionAssignmentsLabel: 'Permission assignments',
    UserGroupColumnHeader: 'User / Group',
    TypeColumnHeader: 'Type',
    PermissionLevelColumnHeader: 'Permission Level',
    TenantWideAccessSuffix: '— tenant-wide access',
    SecurityGroupType: 'Security Group',
    SpGroupType: 'SP Group',
    UserType: 'User',
    CheckAccessForLabel: 'Check access for {0}',

    // Explorer view
    ContainsUniqueAndExternalTooltip: 'Contains items with unique permissions and external user access',
    ContainsUniqueTooltip: 'Contains items with unique permissions',
    ContainsExternalTooltip: 'Contains items with external user access',
    UniqueBadge: 'Unique',
    ExternalAccessDetectedTooltip: 'External user access detected',
    ConnectingStatus: 'Connecting…',
    ConnectedLibrarySingular: 'Connected — {0} library found',
    ConnectedLibraryPlural: 'Connected — {0} libraries found',
    ConnectionFailedError: 'Connection failed: {0}',
    LibraryEmptyStatus: 'This library is empty.',
    ErrorLoadingLibrary: 'Error loading library: {0}',
    ErrorLoadingContents: 'Error loading contents',
    LibraryFieldLabel: 'Library',
    HiddenFromSearchSuffix: '{0} (hidden from search)',
    UniquePermissionsOnlyToggle: 'Unique permissions only',
    ExternalUsersOnlyToggle: 'External users only',
    LegendLabel: 'Legend:',
    LegendItemHasUnique: 'Item has unique permissions',
    LegendContainsUniqueBelow: 'Contains unique permissions below',
    LegendContainsExternalBelow: 'Contains external user access below',
    LegendExternalOnItem: 'External user access on this item',
    ViewingWithMemberAccessTitle: 'Viewing with Member access',
    ViewingWithMemberAccessDesc1: '— permission assignments are not visible. Reading who has access requires the',
    ManagePermissionsWord: 'Manage Permissions',
    ViewingWithMemberAccessDesc2: 'right (Site Owner or higher). You can still see which items have broken inheritance using the ↓ indicators. To see locations you can access, use the',
    UserAccessWord: 'User Access',
    ViewingWithMemberAccessDesc3: 'tool.',
    FoldersAndFilesLabel: 'Folders and files',
    SelectFolderOrFilePrompt: 'Select a folder or file to view its permissions.',
    UniquePermissionsBadge: 'Unique permissions',
    InheritedBadge: 'Inherited',
    ExpandGroupMembersLabel: 'Expand group members',
    ShowParentPermissionsLabel: 'Show parent permissions',
    InheritsFromParentText: 'This item inherits permissions from its parent.',
    YourAccessLabel: 'Your access:',
    PermissionsNotVisibleNodeText: 'Permission assignments are not visible — the Manage Permissions right (Site Owner or higher) is required to read who has access to this item.',
    NoExternalUsersDirectAccessText: 'No external users have direct access to this item.',
    InheritedFromLabel: 'Inherited from:',
    ParentPermissionsNotVisibleText: 'Parent permission assignments are not visible — requires the Manage Permissions right (Site Owner or higher).',
    NoPermissionsFoundOnParentText: 'No permissions found on parent.',

    // Report view
    StartingScanStatus: 'Starting scan…',
    ScanCancelledStatus: 'Scan cancelled — {0} object(s) collected before cancelling.',
    ScanCompleteStatus: 'Scan complete — {0} object(s) found, {1} with unique permissions.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Scan complete',
    ScanCompleteNotificationBody: '{0} objects, {1} with unique permissions.',
    CancelledStatus: 'Cancelled.',
    GenericErrorPrefix: 'Error: {0}',
    ExportErrorPrefix: 'Export error: {0}',
    ScopeSiteOnly: 'Site only',
    ScopeLibraries: 'Libraries',
    ScopeFolders: 'Folders',
    ScopeFilesAndFolders: 'Files & Folders',
    ScanInProgressConfirm: 'A scan is in progress. Leave and cancel?',
    HistoryButton: 'History',
    BackToHistoryButton: 'Back to history',
    ComparingLabel: 'Comparing',
    CompareMismatchWarning: 'These reports were taken with different sites or scan options — differences below may reflect the changed scan settings rather than actual permission changes.',
    NoPermissionDifferencesFound: 'No permission differences found between these two reports.',
    PermissionChangesHeaderSingular: 'Permission changes ({0} object)',
    PermissionChangesHeaderPlural: 'Permission changes ({0} objects)',
    ChangeColumnHeader: 'Change',
    BeforeColumnHeader: 'Before',
    AfterColumnHeader: 'After',
    AddedBadge: 'Added',
    RemovedBadge: 'Removed',
    ChangedBadge: 'Changed',
    InheritanceChangedHeader: 'Inheritance changed ({0})',
    NameColumnHeader: 'Name',
    PathColumnHeader: 'Path',
    NowColumnHeader: 'Now',
    UniqueInheritanceBrokenBadge: 'Unique (inheritance broken)',
    InheritedRestoredBadge: 'Inherited (restored)',
    NewObjectsHeader: 'New objects',
    RemovedObjectsHeader: 'Removed objects',
    BackToScanButton: 'Back to scan',
    CompareSelectedButton: 'Compare selected',
    NoReportsSavedYet: 'No reports saved yet.',
    SelectForCompareLabel: 'Select for compare',
    DateTimeColumnHeader: 'Date / Time',
    SiteColumnHeader: 'Site',
    ScopeColumnHeader: 'Scope',
    ObjectsColumnHeader: 'Objects',
    UniqueColumnHeader: 'Unique',
    SelectReportForCompareLabel: 'Select report from {0} for compare',
    AllSitesPrefix: 'All sites · ',
    PlusSubsitesSuffix: ' + subsites',
    ExportingStatus: 'Exporting…',
    ExportButton: 'Export',
    DeleteThisReportTitle: 'Delete this report',
    ScanAllSiteCollectionsLabel: 'Scan all site collections in this tenant (only available in root site)',
    AllSitesSearchCaveat: 'Site list comes from search and may not include every site collection — very recently created sites, or sites excluded from the search index, can be missed.',
    IncludeSubsitesLabel: 'Include subsites (scans every subsite below this site)',
    ScanDepthFieldLabel: 'Scan depth',
    FolderDepthLimitLabel: 'Folder depth limit:',
    ExpandGroupMembersInReportLabel: 'Expand group members in report (SharePoint groups, Security groups, and M365 groups)',
    LibrariesToScanLabel: 'Libraries to scan',
    OfSelectedCount: '{0} of {1} selected',
    AllButton: 'All',
    NoneButton: 'None',
    LoadingLibrariesStatus: 'Loading libraries…',
    RunReportButton: 'Run Report',
    ItemsFoundSoFar: '{0} items found so far',
    LibraryOfProgress: 'Library {0} of {1}',
    ScanCancelledPartialResults: 'Scan cancelled — partial results',
    ScanCompleteLabel: 'Scan complete',
    ObjectsCountBadge: '{0} objects',
    UniqueCountBadge: '{0} unique',
    InheritedCountBadge: '{0} inherited',
    GeneratingExcelStatus: 'Generating Excel…',
    ExportFilteredRowsButton: 'Export {0} filtered rows',
    ExportToExcelButton: 'Export to Excel',
    ExportToCsvButton: 'Export to CSV',
    ScanStoppedEarlyTitle: 'Scan stopped early — SharePoint is throttling this tenant.',
    SiteCollectionsScannedBeforeStopping: '{0} of {1} site collections were scanned before stopping. ',
    ResultsBelowCoverOnlyPre: 'The results below cover only what was scanned and are',
    NotWord: 'not',
    ResultsBelowCoverOnlyPost: 'a complete audit. The scan stops itself in this situation because continuing to send requests is what keeps the throttle applied. Wait several minutes, then re-run with',
    ConcurrentRequestsWord: 'Concurrent requests',
    SetTo1Or2InSettings: 'set to 1 or 2 in Settings.',
    ThrottledScanMessage: 'SharePoint throttled this scan ({0} request(s) were rate-limited and retried).',
    OfEverythingScannedPre: 'Of everything scanned,',
    ItemCountSingular: '{0} item',
    ItemCountPlural: '{0} items',
    CouldNotBeConfirmedText: "couldn't be confirmed after retrying (see the \"could not be fully read\" notice below for exactly which) — that failure was capacity-related, not a reflection of their actual permissions. Every other item in this report was read successfully and can be trusted.",
    DespiteThrottlingText: 'Despite the throttling, every item was still confirmed successfully after retrying, so this report is complete.',
    ForCleanRunPre: 'For a clean run, wait a few minutes and re-scan with a lower',
    ValueInSettingsPost: 'value in Settings.',
    OneItemWord: '1 item',
    NItemsWord: '{0} item(s)',
    OutOfScannedCouldNotBeRead: 'out of {0} scanned could not be read with your current access —',
    PermissionAssignmentsForItAreNotShown: ' permission assignments for it are not shown, ',
    PermissionAssignmentsForThoseAreNotShown: ' permission assignments for those are not shown, ',
    RestOfReportReadSuccessfully: 'but the rest of this report was read successfully. Run the scan as a',
    RunScanAsSiteOwnerPre: 'Run the scan as a',
    SiteOwnerWord: 'Site Owner',
    RunScanAsSiteOwnerPost: 'to see full details for the denied item(s) below.',
    AndNMoreText: '…and {0} more',
    GroupExpansionSkippedPre: 'Group member expansion was skipped — the',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'Graph permission has not been approved in this tenant. A SharePoint or Global Administrator can approve it in',
    SharePointAdminCenterPath: 'SharePoint Admin Center → Advanced → API access',
    ScanIncompleteItemsMessage: "{0} item(s) could not be fully read due to a temporary error (not a permission issue) and are shown with their parent's permissions as a best-effort fallback — this may not reflect their actual access. Re-run the scan to retry these items.",
    FilterByNamePathUserPlaceholder: 'Filter by name, path, or user/group…',
    FilterResultsLabel: 'Filter results',
    ExternalUsersOnlyExtLabel: 'External users only (#ext#)',
    ShowingOfCount: 'Showing {0} of {1}',
    ScanResultsLabel: 'Scan results',
    PermissionsColumnHeader: 'Permissions',
    CollapsePermissionsLabel: 'Collapse permissions',
    ExpandPermissionsLabel: 'Expand permissions',
    HiddenFromSearchBadge: 'Hidden from search',
    AssignmentCountSingular: '{0} assignment',
    AssignmentCountPlural: '{0} assignments',
    LoadMoreRemainingButton: 'Load more ({0} remaining)',

    // User Access view
    LoadingUsersStatus: 'Loading users…',
    ConnectedUserSingular: 'Connected — {0} user found',
    ConnectedUserPlural: 'Connected — {0} users found',
    CheckingAccessForStatus: 'Checking access for {0}…',
    FullSiteAccessDetectedStatus: 'Full site access detected.',
    AccessibleLocationsFoundSingular: '{0} accessible location found.',
    AccessibleLocationsFoundPlural: '{0} accessible locations found.',
    NoAccessibleLocationsFoundStatus: 'No accessible locations found.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — User Access scan complete',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'New scan',
    NoUserAccessScansSavedYet: 'No user access scans saved yet.',
    UserColumnHeader: 'User',
    LocationsColumnHeader: 'Locations',
    FullControlBadge: 'Full Control',
    DeleteThisRecordTitle: 'Delete this record',
    SelectAUserFieldLabel: 'Select a user',
    SearchUsersPlaceholder: 'Search users…',
    SelectAUserToCheckAccessLabel: 'Select a user to check access',
    NotInThisSiteLabel: 'Not in this site',
    ScanInProgressLabel: 'Scan in progress',
    ScanningUserAccessLabel: 'Scanning user access',
    ScanningStatus: 'Scanning…',
    FullControlAccessPre: 'This user has',
    FullControlWord: 'Full Control',
    FullControlAccessPost: 'or Owner-level access to the entire site — all libraries and folders are accessible.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Site-level permission could not be determined — this site likely uses Microsoft 365 Group access. To show it, a SharePoint Administrator must approve the',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'permission in',
    ShowingSiteLevelAccessOnlyPre: 'Showing',
    SiteLevelAccessOnlyWord: 'site-level access only',
    ShowingSiteLevelAccessOnlyMid: ', based on default SharePoint group membership. Unique permissions on libraries, folders, and files could not be read and are not shown. For complete results, run this scan as a',
    UserAccessCouldNotBeDeterminedPre: "This user's access could not be determined. Reading permission assignments requires the",
    UserAccessCouldNotBeDeterminedPost: "right (Site Owner or higher), and this user does not appear to be a member of the site's default Owner, Member, or Visitor groups.",
    SiteLevelAccessBannerPre: 'This user has site-level access. Only locations with',
    UniquePermissionAssignmentsWord: 'unique permission assignments',
    SiteLevelAccessBannerPost: 'appear below — all other content is accessible through the site-level permission shown at the top of the list.',
    UserAccessResultsLabel: 'User access results',
  };
});
