define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Configuración de Smart Permissions',
    PropertyPane_GroupName: 'General',
    PropertyPane_DefaultViewLabel: 'Vista predeterminada al abrir',
    PropertyPane_View_Home: 'Inicio',
    PropertyPane_View_Report: 'Informe de permisos',
    PropertyPane_View_Explorer: 'Explorador de permisos',
    PropertyPane_View_UserAccess: 'Acceso de usuario',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/misitio',
    ConnectButton: 'Conectar',
    CancelButton: 'Cancelar',
    ChangeUrlButton: 'Cambiar URL',
    SettingsLabel: 'Configuración',
    RenderErrorTitle: 'Smart Permissions — Error de renderizado',
    RenderErrorMessageLabel: 'Mensaje:',
    RenderErrorStackLabel: 'Pila:',
    RenderErrorNoStack: '(pila no disponible)',
    BackButton: 'Atrás',
    BackToHomeLabel: 'Volver al inicio',
    ExplorerCardTitle: 'Explorador de permisos',
    ExplorerCardAlt: 'Explorador de permisos con árbol de carpetas y panel de permisos',
    ExplorerCardDesc: 'Explore cualquier carpeta o archivo y vea al instante quién tiene acceso, con búsquedas de permisos en tiempo real.',
    ExplorerCardButton: 'Abrir explorador de permisos',
    ReportCardTitle: 'Informe de permisos',
    ReportCardAlt: 'Pantalla de configuración del informe de permisos',
    ReportCardDesc: 'Genere un informe de Excel codificado por colores de cada asignación de permiso único en su sitio.',
    ReportCardButton: 'Ejecutar informe de permisos',
    UserAccessCardTitle: 'Acceso de usuario',
    UserAccessCardAlt: 'Pantalla de acceso de usuario que muestra las ubicaciones accesibles para un usuario seleccionado',
    UserAccessCardDesc: 'Busque cualquier usuario para ver todos los lugares a los que puede acceder en un sitio, con su nivel de permiso exacto.',
    UserAccessCardButton: 'Comprobar acceso de usuario',
    SiteOwnerRequiredTitle: 'Se requiere acceso de propietario del sitio —',
    SiteOwnerRequiredDesc: 'Estas herramientas requieren acceso de propietario del sitio. Contacte con un propietario del sitio si tiene preguntas sobre permisos.',
    HomeSubtitle: 'Audite y comprenda los permisos de SharePoint, sin PowerShell.',
    RequiresSiteOwnerTooltip: 'Requiere acceso de propietario del sitio',
    HomeNoteLabel: 'Nota:',
    HomeNoteText: 'Este WebPart se ejecuta como el usuario actualmente conectado. Solo puede ver sitios y elementos a los que ese usuario tiene permiso de acceso. Para un análisis completo del inquilino, use una cuenta con acceso de lectura adecuado en todos los sitios.',
    SettingsTitle: 'Configuración',
    LibrariesSectionTitle: 'Bibliotecas',
    IncludeHiddenLabel: 'Incluir bibliotecas del sistema y ocultas',
    IncludeHiddenTooltip: 'Cuando está marcado, incluye Style Library, Form Templates, Site Assets y otras bibliotecas ocultas de las vistas predeterminadas. Se aplica a todas las herramientas.',
    MoreInfoHiddenLibrariesLabel: 'Más información sobre bibliotecas ocultas',
    ExcludeLimitedAccessLabel: 'Excluir entradas de acceso limitado',
    ExcludeLimitedAccessTooltip: 'Oculta usuarios y grupos cuyo único permiso de SharePoint es Acceso limitado, asignado automáticamente cuando se comparten archivos mediante enlaces. Se aplica al informe de permisos, explorador y acceso de usuario.',
    MoreInfoLimitedAccessLabel: 'Más información sobre acceso limitado',
    ExcludeSharingLinksLabel: 'Excluir entradas de enlaces para compartir',
    ExcludeSharingLinksTooltip: 'Oculta los grupos internos "SharingLinks.*" que SharePoint crea automáticamente para los enlaces de compartición "Cualquiera con el enlace" y "Personas específicas". Se aplica al informe de permisos, explorador y acceso de usuario.',
    MoreInfoSharingLinksLabel: 'Más información sobre enlaces para compartir',
    PerformanceSectionTitle: 'Rendimiento',
    ConcurrentRequestsLabel: 'Solicitudes API concurrentes:',
    ConcurrencyTooltip: 'Cuántas solicitudes API de SharePoint se ejecutan en paralelo durante los análisis del informe de permisos, análisis de acceso de usuario y comprobaciones en segundo plano del explorador. Valores más altos son más rápidos pero más propensos a activar la limitación (HTTP 429). Se recomienda 3–5.',
    MoreInfoConcurrencyLabel: 'Más información sobre la concurrencia',
    ConcurrencyHint: 'Valores más altos escanean más rápido pero pueden activar la limitación de SharePoint. Recomendado: 3–5.',
    GroupMemberCapLabel: 'Límite de visualización de miembros de grupo:',
    GroupMemberCapTooltip: 'Máximo de miembros mostrados por grupo cuando "Expandir miembros del grupo" está habilitado. Los grupos más grandes se limitan y se muestra un aviso. Aumentar esto usa más memoria.',
    MoreInfoGroupMemberCapLabel: 'Más información sobre el límite de miembros de grupo',
    GroupMemberCapHint: 'Los grupos más grandes que este límite muestran un aviso de truncamiento. Predeterminado: 500.',
    DefaultViewSectionTitle: 'Vista predeterminada al cargar',
    DefaultViewInstructionsIntro: 'Para cambiar qué pantalla se abre cuando el WebPart se carga por primera vez, edite las propiedades del WebPart:',
    DefaultViewStep1Pre: 'Ponga la página de SharePoint en modo',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Haga clic en el icono de',
    DefaultViewStep2Post: 'en el WebPart Smart Permissions.',
    DefaultViewStep3Pre: 'En el panel de propiedades, elija una vista en la lista desplegable',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'la página para guardar el cambio.',
    EditModeWord: 'Edición',
    PencilEditWord: 'lápiz (editar)',
    DefaultViewOnOpenWord: 'Vista predeterminada al abrir',
    RepublishWord: 'Vuelva a publicar',
    SiteOwnersLabel: 'Propietarios del sitio:',
    EveryoneClaimLabel: 'Todos',
    EveryoneExceptExternalClaimLabel: 'Todos excepto los usuarios externos',
    PermissionAssignmentsLabel: 'Asignaciones de permisos',
    UserGroupColumnHeader: 'Usuario / Grupo',
    TypeColumnHeader: 'Tipo',
    PermissionLevelColumnHeader: 'Nivel de permiso',
    TenantWideAccessSuffix: '— acceso en todo el inquilino',
    SecurityGroupType: 'Grupo de seguridad',
    SpGroupType: 'Grupo de SP',
    UserType: 'Usuario',
    CheckAccessForLabel: 'Comprobar acceso de {0}',
    ContainsUniqueAndExternalTooltip: 'Contiene elementos con permisos únicos y acceso de usuarios externos',
    ContainsUniqueTooltip: 'Contiene elementos con permisos únicos',
    ContainsExternalTooltip: 'Contiene elementos con acceso de usuarios externos',
    UniqueBadge: 'Único',
    ExternalAccessDetectedTooltip: 'Acceso de usuario externo detectado',
    ConnectingStatus: 'Conectando…',
    ConnectedLibrarySingular: 'Conectado — {0} biblioteca encontrada',
    ConnectedLibraryPlural: 'Conectado — {0} bibliotecas encontradas',
    ConnectionFailedError: 'Error de conexión: {0}',
    LibraryEmptyStatus: 'Esta biblioteca está vacía.',
    ErrorLoadingLibrary: 'Error al cargar la biblioteca: {0}',
    ErrorLoadingContents: 'Error al cargar el contenido',
    LibraryFieldLabel: 'Biblioteca',
    HiddenFromSearchSuffix: '{0} (oculto de la búsqueda)',
    UniquePermissionsOnlyToggle: 'Solo permisos únicos',
    ExternalUsersOnlyToggle: 'Solo usuarios externos',
    LegendLabel: 'Leyenda:',
    LegendItemHasUnique: 'El elemento tiene permisos únicos',
    LegendContainsUniqueBelow: 'Contiene permisos únicos debajo',
    LegendContainsExternalBelow: 'Contiene acceso de usuarios externos debajo',
    LegendExternalOnItem: 'Acceso de usuario externo en este elemento',
    ViewingWithMemberAccessTitle: 'Viendo con acceso de Miembro',
    ViewingWithMemberAccessDesc1: '— las asignaciones de permisos no son visibles. Leer quién tiene acceso requiere el derecho',
    ManagePermissionsWord: 'Administrar permisos',
    ViewingWithMemberAccessDesc2: '(Propietario del sitio o superior). Aún puede ver qué elementos tienen herencia interrumpida usando los indicadores ↓. Para ver ubicaciones a las que puede acceder, use la herramienta',
    UserAccessWord: 'Acceso de usuario',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Carpetas y archivos',
    SelectFolderOrFilePrompt: 'Seleccione una carpeta o archivo para ver sus permisos.',
    UniquePermissionsBadge: 'Permisos únicos',
    InheritedBadge: 'Heredado',
    ExpandGroupMembersLabel: 'Expandir miembros del grupo',
    ShowParentPermissionsLabel: 'Mostrar permisos del elemento superior',
    InheritsFromParentText: 'Este elemento hereda permisos de su elemento superior.',
    YourAccessLabel: 'Su acceso:',
    PermissionsNotVisibleNodeText: 'Las asignaciones de permisos no son visibles — se requiere el derecho Administrar permisos (Propietario del sitio o superior) para ver quién tiene acceso a este elemento.',
    NoExternalUsersDirectAccessText: 'Ningún usuario externo tiene acceso directo a este elemento.',
    InheritedFromLabel: 'Heredado de:',
    ParentPermissionsNotVisibleText: 'Las asignaciones de permisos del elemento superior no son visibles — requiere el derecho Administrar permisos (Propietario del sitio o superior).',
    NoPermissionsFoundOnParentText: 'No se encontraron permisos en el elemento superior.',
    StartingScanStatus: 'Iniciando análisis…',
    ScanCancelledStatus: 'Análisis cancelado — {0} objeto(s) recopilado(s) antes de cancelar.',
    ScanCompleteStatus: 'Análisis completo — {0} objeto(s) encontrado(s), {1} con permisos únicos.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Análisis completo',
    ScanCompleteNotificationBody: '{0} objetos, {1} con permisos únicos.',
    CancelledStatus: 'Cancelado.',
    GenericErrorPrefix: 'Error: {0}',
    ExportErrorPrefix: 'Error de exportación: {0}',
    ScopeSiteOnly: 'Solo sitio',
    ScopeLibraries: 'Bibliotecas',
    ScopeFolders: 'Carpetas',
    ScopeFilesAndFolders: 'Archivos y carpetas',
    ScanInProgressConfirm: '¿Hay un análisis en curso. Salir y cancelar?',
    HistoryButton: 'Historial',
    BackToHistoryButton: 'Volver al historial',
    ComparingLabel: 'Comparando',
    CompareMismatchWarning: 'Estos informes se tomaron con sitios u opciones de análisis diferentes — las diferencias siguientes pueden reflejar la configuración de análisis modificada en lugar de cambios reales de permisos.',
    NoPermissionDifferencesFound: 'No se encontraron diferencias de permisos entre estos dos informes.',
    PermissionChangesHeaderSingular: 'Cambios de permisos ({0} objeto)',
    PermissionChangesHeaderPlural: 'Cambios de permisos ({0} objetos)',
    ChangeColumnHeader: 'Cambio',
    BeforeColumnHeader: 'Antes',
    AfterColumnHeader: 'Después',
    AddedBadge: 'Añadido',
    RemovedBadge: 'Eliminado',
    ChangedBadge: 'Cambiado',
    InheritanceChangedHeader: 'Herencia cambiada ({0})',
    NameColumnHeader: 'Nombre',
    PathColumnHeader: 'Ruta',
    NowColumnHeader: 'Ahora',
    UniqueInheritanceBrokenBadge: 'Único (herencia interrumpida)',
    InheritedRestoredBadge: 'Heredado (restaurado)',
    NewObjectsHeader: 'Objetos nuevos',
    RemovedObjectsHeader: 'Objetos eliminados',
    BackToScanButton: 'Volver al análisis',
    CompareSelectedButton: 'Comparar seleccionados',
    NoReportsSavedYet: 'Aún no hay informes guardados.',
    SelectForCompareLabel: 'Seleccionar para comparar',
    DateTimeColumnHeader: 'Fecha / Hora',
    SiteColumnHeader: 'Sitio',
    ScopeColumnHeader: 'Alcance',
    ObjectsColumnHeader: 'Objetos',
    UniqueColumnHeader: 'Único',
    SelectReportForCompareLabel: 'Seleccionar informe del {0} para comparar',
    AllSitesPrefix: 'Todos los sitios · ',
    PlusSubsitesSuffix: ' + subsitios',
    ExportingStatus: 'Exportando…',
    ExportButton: 'Exportar',
    DeleteThisReportTitle: 'Eliminar este informe',
    ScanAllSiteCollectionsLabel: 'Analizar todas las colecciones de sitios en este inquilino (solo disponible en el sitio raíz)',
    AllSitesSearchCaveat: 'La lista de sitios proviene de la búsqueda y puede no incluir todas las colecciones de sitios — sitios creados muy recientemente, o excluidos del índice de búsqueda, pueden faltar.',
    IncludeSubsitesLabel: 'Incluir subsitios (analiza cada subsitio debajo de este sitio)',
    ScanDepthFieldLabel: 'Profundidad de análisis',
    FolderDepthLimitLabel: 'Límite de profundidad de carpetas:',
    ExpandGroupMembersInReportLabel: 'Expandir miembros del grupo en el informe (grupos de SharePoint, grupos de seguridad y grupos M365)',
    LibrariesToScanLabel: 'Bibliotecas a analizar',
    OfSelectedCount: '{0} de {1} seleccionadas',
    AllButton: 'Todas',
    NoneButton: 'Ninguna',
    LoadingLibrariesStatus: 'Cargando bibliotecas…',
    RunReportButton: 'Ejecutar informe',
    ItemsFoundSoFar: '{0} elementos encontrados hasta ahora',
    LibraryOfProgress: 'Biblioteca {0} de {1}',
    ScanCancelledPartialResults: 'Análisis cancelado — resultados parciales',
    ScanCompleteLabel: 'Análisis completo',
    ObjectsCountBadge: '{0} objetos',
    UniqueCountBadge: '{0} únicos',
    InheritedCountBadge: '{0} heredados',
    GeneratingExcelStatus: 'Generando Excel…',
    ExportFilteredRowsButton: 'Exportar {0} filas filtradas',
    ExportToExcelButton: 'Exportar a Excel',
    ExportToCsvButton: 'Exportar a CSV',
    ScanStoppedEarlyTitle: 'Análisis detenido antes de tiempo — SharePoint está limitando este inquilino.',
    SiteCollectionsScannedBeforeStopping: 'Se analizaron {0} de {1} colecciones de sitios antes de detenerse. ',
    ResultsBelowCoverOnlyPre: 'Los resultados a continuación cubren solo lo que se analizó y no son',
    NotWord: 'no',
    ResultsBelowCoverOnlyPost: 'una auditoría completa. El análisis se detiene solo en esta situación porque seguir enviando solicitudes es lo que mantiene la limitación activa. Espere varios minutos y vuelva a ejecutar con',
    ConcurrentRequestsWord: 'Solicitudes concurrentes',
    SetTo1Or2InSettings: 'configurado en 1 o 2 en Configuración.',
    ThrottledScanMessage: 'SharePoint limitó este análisis ({0} solicitud(es) fueron limitadas y reintentadas).',
    OfEverythingScannedPre: 'De todo lo analizado,',
    ItemCountSingular: '{0} elemento',
    ItemCountPlural: '{0} elementos',
    CouldNotBeConfirmedText: 'no pudieron confirmarse después de reintentar (vea el aviso "no se pudo leer completamente" a continuación para saber exactamente cuáles) — ese fallo estaba relacionado con la capacidad, no con sus permisos reales. Todos los demás elementos de este informe se leyeron correctamente y son de confianza.',
    DespiteThrottlingText: 'A pesar de la limitación, todos los elementos se confirmaron con éxito después de reintentar, por lo que este informe está completo.',
    ForCleanRunPre: 'Para una ejecución limpia, espere unos minutos y vuelva a analizar con un valor más bajo de',
    ValueInSettingsPost: 'en Configuración.',
    OneItemWord: '1 elemento',
    NItemsWord: '{0} elemento(s)',
    OutOfScannedCouldNotBeRead: 'de {0} analizados no se pudieron leer con su acceso actual —',
    PermissionAssignmentsForItAreNotShown: ' las asignaciones de permisos no se muestran, ',
    PermissionAssignmentsForThoseAreNotShown: ' las asignaciones de permisos no se muestran, ',
    RestOfReportReadSuccessfully: 'pero el resto de este informe se leyó correctamente.',
    RunScanAsSiteOwnerPre: 'Ejecute el análisis como',
    SiteOwnerWord: 'Propietario del sitio',
    RunScanAsSiteOwnerPost: 'para ver los detalles completos de los elementos denegados a continuación.',
    AndNMoreText: '…y {0} más',
    GroupExpansionSkippedPre: 'Se omitió la expansión de miembros del grupo — el permiso de Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'no ha sido aprobado en este inquilino. Un administrador de SharePoint o global puede aprobarlo en',
    SharePointAdminCenterPath: 'Centro de administración de SharePoint → Avanzado → Acceso API',
    ScanIncompleteItemsMessage: '{0} elemento(s) no se pudieron leer completamente debido a un error temporal (no un problema de permisos) y se muestran con los permisos de su elemento superior como solución alternativa — esto puede no reflejar su acceso real. Vuelva a ejecutar el análisis para reintentar estos elementos.',
    FilterByNamePathUserPlaceholder: 'Filtrar por nombre, ruta o usuario/grupo…',
    FilterResultsLabel: 'Filtrar resultados',
    ExternalUsersOnlyExtLabel: 'Solo usuarios externos (#ext#)',
    ShowingOfCount: 'Mostrando {0} de {1}',
    ScanResultsLabel: 'Resultados del análisis',
    PermissionsColumnHeader: 'Permisos',
    CollapsePermissionsLabel: 'Contraer permisos',
    ExpandPermissionsLabel: 'Expandir permisos',
    HiddenFromSearchBadge: 'Oculto de la búsqueda',
    AssignmentCountSingular: '{0} asignación',
    AssignmentCountPlural: '{0} asignaciones',
    LoadMoreRemainingButton: 'Cargar más ({0} restante(s))',
    LoadingUsersStatus: 'Cargando usuarios…',
    ConnectedUserSingular: 'Conectado — {0} usuario encontrado',
    ConnectedUserPlural: 'Conectado — {0} usuarios encontrados',
    CheckingAccessForStatus: 'Comprobando el acceso de {0}…',
    FullSiteAccessDetectedStatus: 'Acceso completo al sitio detectado.',
    AccessibleLocationsFoundSingular: '{0} ubicación accesible encontrada.',
    AccessibleLocationsFoundPlural: '{0} ubicaciones accesibles encontradas.',
    NoAccessibleLocationsFoundStatus: 'No se encontraron ubicaciones accesibles.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Análisis de acceso de usuario completo',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Nuevo análisis',
    NoUserAccessScansSavedYet: 'Aún no hay análisis de acceso de usuario guardados.',
    UserColumnHeader: 'Usuario',
    LocationsColumnHeader: 'Ubicaciones',
    FullControlBadge: 'Control total',
    DeleteThisRecordTitle: 'Eliminar este registro',
    SelectAUserFieldLabel: 'Seleccionar un usuario',
    SearchUsersPlaceholder: 'Buscar usuarios…',
    SelectAUserToCheckAccessLabel: 'Seleccionar un usuario para comprobar el acceso',
    NotInThisSiteLabel: 'No está en este sitio',
    ScanInProgressLabel: 'Análisis en curso',
    ScanningUserAccessLabel: 'Analizando acceso de usuario',
    ScanningStatus: 'Analizando…',
    FullControlAccessPre: 'Este usuario tiene',
    FullControlWord: 'Control total',
    FullControlAccessPost: 'o acceso de nivel Propietario a todo el sitio — todas las bibliotecas y carpetas son accesibles.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'No se pudo determinar el permiso a nivel de sitio — este sitio probablemente usa acceso de grupo de Microsoft 365. Para mostrarlo, un administrador de SharePoint debe aprobar el permiso',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'de Graph en',
    ShowingSiteLevelAccessOnlyPre: 'Mostrando solo',
    SiteLevelAccessOnlyWord: 'acceso a nivel de sitio',
    ShowingSiteLevelAccessOnlyMid: ', basado en la pertenencia predeterminada al grupo de SharePoint. Los permisos únicos en bibliotecas, carpetas y archivos no se pudieron leer y no se muestran. Para resultados completos, ejecute este análisis como',
    UserAccessCouldNotBeDeterminedPre: 'No se pudo determinar el acceso de este usuario. Leer las asignaciones de permisos requiere el derecho',
    UserAccessCouldNotBeDeterminedPost: '(Propietario del sitio o superior), y este usuario no parece ser miembro de los grupos predeterminados de Propietarios, Miembros o Visitantes del sitio.',
    SiteLevelAccessBannerPre: 'Este usuario tiene acceso a nivel de sitio. Solo las ubicaciones con',
    UniquePermissionAssignmentsWord: 'asignaciones de permisos únicas',
    SiteLevelAccessBannerPost: 'aparecen a continuación — todo el demás contenido es accesible a través del permiso a nivel de sitio mostrado en la parte superior de la lista.',
    UserAccessResultsLabel: 'Resultados de acceso de usuario',
  };
});
