define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions -asetukset',
    PropertyPane_GroupName: 'Yleiset',
    PropertyPane_DefaultViewLabel: 'Oletusnäkymä avattaessa',
    PropertyPane_View_Home: 'Etusivu',
    PropertyPane_View_Report: 'Käyttöoikeusraportti',
    PropertyPane_View_Explorer: 'Käyttöoikeuksien tutkija',
    PropertyPane_View_UserAccess: 'Käyttäjän käyttöoikeudet',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/omasivustoni',
    ConnectButton: 'Yhdistä',
    CancelButton: 'Peruuta',
    ChangeUrlButton: 'Vaihda URL-osoite',
    SettingsLabel: 'Asetukset',
    RenderErrorTitle: 'Smart Permissions — Renderöintivirhe',
    RenderErrorMessageLabel: 'Viesti:',
    RenderErrorStackLabel: 'Pino:',
    RenderErrorNoStack: '(pinoa ei saatavilla)',
    BackButton: 'Takaisin',
    BackToHomeLabel: 'Takaisin etusivulle',
    ExplorerCardTitle: 'Käyttöoikeuksien tutkija',
    ExplorerCardAlt: 'Käyttöoikeuksien tutkija kansiopuulla ja käyttöoikeuspaneelilla',
    ExplorerCardDesc: 'Selaa mitä tahansa kansiota tai tiedostoa ja näe heti, kenellä on käyttöoikeus — reaaliaikaisilla käyttöoikeushauilla.',
    ExplorerCardButton: 'Avaa käyttöoikeuksien tutkija',
    ReportCardTitle: 'Käyttöoikeusraportti',
    ReportCardAlt: 'Käyttöoikeusraportin määritysnäyttö',
    ReportCardDesc: 'Luo värikoodattu Excel-raportti jokaisesta yksilöllisestä käyttöoikeusmäärityksestä sivustollasi.',
    ReportCardButton: 'Suorita käyttöoikeusraportti',
    UserAccessCardTitle: 'Käyttäjän käyttöoikeudet',
    UserAccessCardAlt: 'Käyttäjän käyttöoikeusnäyttö, joka näyttää valitun käyttäjän käytettävissä olevat sijainnit',
    UserAccessCardDesc: 'Etsi mikä tahansa käyttäjä nähdäksesi jokaisen sijainnin, johon hänellä on pääsy sivustolla, tarkalla käyttöoikeustasolla.',
    UserAccessCardButton: 'Tarkista käyttäjän käyttöoikeudet',
    SiteOwnerRequiredTitle: 'Sivuston omistajan käyttöoikeudet vaaditaan —',
    SiteOwnerRequiredDesc: 'Nämä työkalut vaativat sivuston omistajan käyttöoikeudet. Ota yhteyttä sivuston omistajaan, jos sinulla on kysyttävää käyttöoikeuksista.',
    HomeSubtitle: 'Tarkasta ja ymmärrä SharePointin käyttöoikeudet — ilman PowerShelliä.',
    RequiresSiteOwnerTooltip: 'Vaatii sivuston omistajan käyttöoikeudet',
    HomeNoteLabel: 'Huomaa:',
    HomeNoteText: 'Tämä verkko-osa toimii kirjautuneena käyttäjänä. Se näkee vain sivustot ja kohteet, joihin kyseisellä käyttäjällä on käyttöoikeus. Käytä koko vuokraajan tarkistukseen tiliä, jolla on asianmukainen lukuoikeus kaikkiin sivustoihin.',
    SettingsTitle: 'Asetukset',
    LibrariesSectionTitle: 'Kirjastot',
    IncludeHiddenLabel: 'Sisällytä järjestelmä- ja piilotetut kirjastot',
    IncludeHiddenTooltip: 'Jos valittu, sisältää tyylikirjaston, lomakemallit, sivustoresurssit ja muut oletusnäkymistä piilotetut kirjastot. Koskee kaikkia työkaluja.',
    MoreInfoHiddenLibrariesLabel: 'Lisätietoja piilotetuista kirjastoista',
    ExcludeLimitedAccessLabel: 'Sulje pois rajoitetun käyttöoikeuden merkinnät',
    ExcludeLimitedAccessTooltip: 'Piilottaa käyttäjät ja ryhmät, joiden ainoa SharePoint-käyttöoikeus on Rajoitettu käyttöoikeus — myönnetään automaattisesti, kun tiedostoja jaetaan linkkien kautta. Koskee käyttöoikeusraporttia, Tutkijaa ja käyttäjän käyttöoikeuksia.',
    MoreInfoLimitedAccessLabel: 'Lisätietoja rajoitetusta käyttöoikeudesta',
    ExcludeSharingLinksLabel: 'Sulje pois jakolinkkien merkinnät',
    ExcludeSharingLinksTooltip: 'Piilottaa sisäiset "SharingLinks.*"-ryhmät, jotka SharePoint luo automaattisesti "Kaikki, joilla on linkki" ja "Tietyt henkilöt" -jakolinkeille. Koskee käyttöoikeusraporttia, Tutkijaa ja käyttäjän käyttöoikeuksia.',
    MoreInfoSharingLinksLabel: 'Lisätietoja jakolinkeistä',
    PerformanceSectionTitle: 'Suorituskyky',
    ConcurrentRequestsLabel: 'Samanaikaiset API-pyynnöt:',
    ConcurrencyTooltip: 'Kuinka monta SharePoint API -pyyntöä suoritetaan rinnakkain käyttöoikeusraportin tarkistusten, käyttäjän käyttöoikeustarkistusten ja Tutkijan taustatarkistusten aikana. Suuremmat arvot ovat nopeampia, mutta todennäköisemmin laukaisevat kuristuksen (HTTP 429). Suositus: 3–5.',
    MoreInfoConcurrencyLabel: 'Lisätietoja samanaikaisuudesta',
    ConcurrencyHint: 'Suuremmat arvot skannaavat nopeammin, mutta voivat laukaista SharePointin kuristuksen. Suositus: 3–5.',
    GroupMemberCapLabel: 'Ryhmän jäsenten näytön yläraja:',
    GroupMemberCapTooltip: 'Ryhmää kohti näytettävien jäsenten enimmäismäärä, kun "Laajenna ryhmän jäsenet" on käytössä. Suuremmat ryhmät rajoitetaan, ja ilmoitus näytetään. Tämän kasvattaminen käyttää enemmän muistia.',
    MoreInfoGroupMemberCapLabel: 'Lisätietoja ryhmän jäsenten ylärajasta',
    GroupMemberCapHint: 'Tätä rajaa suuremmat ryhmät näyttävät katkaisuilmoituksen. Oletus: 500.',
    DefaultViewSectionTitle: 'Oletusnäkymä latauksessa',
    DefaultViewInstructionsIntro: 'Jos haluat muuttaa, mikä näyttö avautuu, kun verkko-osa ladataan ensimmäisen kerran, muokkaa verkko-osan ominaisuuksia:',
    DefaultViewStep1Pre: 'Aseta SharePoint-sivu',
    DefaultViewStep1Post: '-tilaan.',
    DefaultViewStep2Pre: 'Napsauta Smart Permissions -verkko-osan',
    DefaultViewStep2Post: '-kuvaketta.',
    DefaultViewStep3Pre: 'Valitse ominaisuuspaneelissa näkymä avattavasta luettelosta',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'sivu tallentaaksesi muutoksen.',
    EditModeWord: 'Muokkaus',
    PencilEditWord: 'kynä (muokkaa)',
    DefaultViewOnOpenWord: 'Oletusnäkymä avattaessa',
    RepublishWord: 'Julkaise uudelleen',
    SiteOwnersLabel: 'Sivuston omistajat:',
    EveryoneClaimLabel: 'Kaikki',
    EveryoneExceptExternalClaimLabel: 'Kaikki paitsi ulkoiset käyttäjät',
    PermissionAssignmentsLabel: 'Käyttöoikeusmääritykset',
    UserGroupColumnHeader: 'Käyttäjä / Ryhmä',
    TypeColumnHeader: 'Tyyppi',
    PermissionLevelColumnHeader: 'Käyttöoikeustaso',
    TenantWideAccessSuffix: '— koko vuokraajan laajuinen käyttöoikeus',
    SecurityGroupType: 'Suojausryhmä',
    SpGroupType: 'SP-ryhmä',
    UserType: 'Käyttäjä',
    CheckAccessForLabel: 'Tarkista käyttöoikeus käyttäjälle {0}',
    ContainsUniqueAndExternalTooltip: 'Sisältää kohteita, joilla on yksilöllisiä käyttöoikeuksia ja ulkoisten käyttäjien käyttöoikeus',
    ContainsUniqueTooltip: 'Sisältää kohteita, joilla on yksilöllisiä käyttöoikeuksia',
    ContainsExternalTooltip: 'Sisältää kohteita, joilla on ulkoisten käyttäjien käyttöoikeus',
    UniqueBadge: 'Yksilöllinen',
    ExternalAccessDetectedTooltip: 'Ulkoisen käyttäjän käyttöoikeus havaittu',
    ConnectingStatus: 'Muodostetaan yhteyttä…',
    ConnectedLibrarySingular: 'Yhdistetty — {0} kirjasto löytyi',
    ConnectedLibraryPlural: 'Yhdistetty — {0} kirjastoa löytyi',
    ConnectionFailedError: 'Yhteys epäonnistui: {0}',
    LibraryEmptyStatus: 'Tämä kirjasto on tyhjä.',
    ErrorLoadingLibrary: 'Virhe ladattaessa kirjastoa: {0}',
    ErrorLoadingContents: 'Virhe ladattaessa sisältöä',
    LibraryFieldLabel: 'Kirjasto',
    HiddenFromSearchSuffix: '{0} (piilotettu hausta)',
    UniquePermissionsOnlyToggle: 'Vain yksilölliset käyttöoikeudet',
    ExternalUsersOnlyToggle: 'Vain ulkoiset käyttäjät',
    LegendLabel: 'Selite:',
    LegendItemHasUnique: 'Kohteella on yksilölliset käyttöoikeudet',
    LegendContainsUniqueBelow: 'Sisältää yksilöllisiä käyttöoikeuksia alla',
    LegendContainsExternalBelow: 'Sisältää ulkoisen käyttäjän käyttöoikeuden alla',
    LegendExternalOnItem: 'Ulkoisen käyttäjän käyttöoikeus tässä kohteessa',
    ViewingWithMemberAccessTitle: 'Tarkastellaan jäsenoikeuksilla',
    ViewingWithMemberAccessDesc1: '— käyttöoikeusmääritykset eivät ole näkyvissä. Käyttöoikeuksien lukeminen vaatii oikeuden',
    ManagePermissionsWord: 'Hallitse käyttöoikeuksia',
    ViewingWithMemberAccessDesc2: '(sivuston omistaja tai korkeampi). Voit silti nähdä, millä kohteilla on rikkoutunut periytyminen ↓-ilmaisimien avulla. Käytä työkalua',
    UserAccessWord: 'Käyttäjän käyttöoikeudet',
    ViewingWithMemberAccessDesc3: 'nähdäksesi sijainnit, joihin sinulla on pääsy.',
    FoldersAndFilesLabel: 'Kansiot ja tiedostot',
    SelectFolderOrFilePrompt: 'Valitse kansio tai tiedosto nähdäksesi sen käyttöoikeudet.',
    UniquePermissionsBadge: 'Yksilölliset käyttöoikeudet',
    InheritedBadge: 'Peritty',
    ExpandGroupMembersLabel: 'Laajenna ryhmän jäsenet',
    ShowParentPermissionsLabel: 'Näytä ylätason käyttöoikeudet',
    InheritsFromParentText: 'Tämä kohde perii käyttöoikeudet ylätason kohteeltaan.',
    YourAccessLabel: 'Käyttöoikeutesi:',
    PermissionsNotVisibleNodeText: 'Käyttöoikeusmääritykset eivät ole näkyvissä — oikeus Hallitse käyttöoikeuksia (sivuston omistaja tai korkeampi) vaaditaan nähdäksesi, kenellä on käyttöoikeus tähän kohteeseen.',
    NoExternalUsersDirectAccessText: 'Yhdelläkään ulkoisella käyttäjällä ei ole suoraa käyttöoikeutta tähän kohteeseen.',
    InheritedFromLabel: 'Peritty kohteesta:',
    ParentPermissionsNotVisibleText: 'Ylätason kohteen käyttöoikeusmääritykset eivät ole näkyvissä — vaatii oikeuden Hallitse käyttöoikeuksia (sivuston omistaja tai korkeampi).',
    NoPermissionsFoundOnParentText: 'Ylätason kohteesta ei löytynyt käyttöoikeuksia.',
    StartingScanStatus: 'Aloitetaan tarkistusta…',
    ScanCancelledStatus: 'Tarkistus peruutettu — {0} kohde(tta) kerätty ennen peruutusta.',
    ScanCompleteStatus: 'Tarkistus valmis — {0} kohde(tta) löytyi, {1} yksilöllisillä käyttöoikeuksilla.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Tarkistus valmis',
    ScanCompleteNotificationBody: '{0} kohdetta, {1} yksilöllisillä käyttöoikeuksilla.',
    CancelledStatus: 'Peruutettu.',
    GenericErrorPrefix: 'Virhe: {0}',
    ExportErrorPrefix: 'Vientivirhe: {0}',
    ScopeSiteOnly: 'Vain sivusto',
    ScopeLibraries: 'Kirjastot',
    ScopeFolders: 'Kansiot',
    ScopeFilesAndFolders: 'Tiedostot ja kansiot',
    ScanInProgressConfirm: 'Tarkistus on käynnissä. Poistu ja peruuta?',
    HistoryButton: 'Historia',
    BackToHistoryButton: 'Takaisin historiaan',
    ComparingLabel: 'Vertaillaan',
    CompareMismatchWarning: 'Nämä raportit otettiin eri sivustoilla tai tarkistusasetuksilla — alla olevat erot saattavat heijastaa muutettuja tarkistusasetuksia eivätkä todellisia käyttöoikeusmuutoksia.',
    NoPermissionDifferencesFound: 'Näiden kahden raportin välillä ei löytynyt käyttöoikeuseroja.',
    PermissionChangesHeaderSingular: 'Käyttöoikeusmuutokset ({0} kohde)',
    PermissionChangesHeaderPlural: 'Käyttöoikeusmuutokset ({0} kohdetta)',
    ChangeColumnHeader: 'Muutos',
    BeforeColumnHeader: 'Ennen',
    AfterColumnHeader: 'Jälkeen',
    AddedBadge: 'Lisätty',
    RemovedBadge: 'Poistettu',
    ChangedBadge: 'Muutettu',
    InheritanceChangedHeader: 'Periytyminen muuttunut ({0})',
    NameColumnHeader: 'Nimi',
    PathColumnHeader: 'Polku',
    NowColumnHeader: 'Nyt',
    UniqueInheritanceBrokenBadge: 'Yksilöllinen (periytyminen katkennut)',
    InheritedRestoredBadge: 'Peritty (palautettu)',
    NewObjectsHeader: 'Uudet kohteet',
    RemovedObjectsHeader: 'Poistetut kohteet',
    BackToScanButton: 'Takaisin tarkistukseen',
    CompareSelectedButton: 'Vertaa valittuja',
    NoReportsSavedYet: 'Ei vielä tallennettuja raportteja.',
    SelectForCompareLabel: 'Valitse vertailuun',
    DateTimeColumnHeader: 'Päivämäärä / Aika',
    SiteColumnHeader: 'Sivusto',
    ScopeColumnHeader: 'Laajuus',
    ObjectsColumnHeader: 'Kohteet',
    UniqueColumnHeader: 'Yksilölliset',
    SelectReportForCompareLabel: 'Valitse raportti ajalta {0} vertailuun',
    AllSitesPrefix: 'Kaikki sivustot · ',
    PlusSubsitesSuffix: ' + alisivustot',
    ExportingStatus: 'Viedään…',
    ExportButton: 'Vie',
    DeleteThisReportTitle: 'Poista tämä raportti',
    ScanAllSiteCollectionsLabel: 'Tarkista kaikki sivustokokoelmat tässä vuokraajassa (käytettävissä vain juurisivustolla)',
    AllSitesSearchCaveat: 'Sivustoluettelo tulee hausta eikä välttämättä sisällä kaikkia sivustokokoelmia — hyvin äskettäin luodut sivustot tai hakuindeksistä poissuljetut sivustot voivat puuttua.',
    IncludeSubsitesLabel: 'Sisällytä alisivustot (tarkistaa jokaisen tämän sivuston alla olevan alisivuston)',
    ScanDepthFieldLabel: 'Tarkistuksen syvyys',
    FolderDepthLimitLabel: 'Kansion syvyysraja:',
    ExpandGroupMembersInReportLabel: 'Laajenna ryhmän jäsenet raportissa (SharePoint-ryhmät, suojausryhmät ja M365-ryhmät)',
    LibrariesToScanLabel: 'Tarkistettavat kirjastot',
    OfSelectedCount: '{0}/{1} valittu',
    AllButton: 'Kaikki',
    NoneButton: 'Ei mitään',
    LoadingLibrariesStatus: 'Ladataan kirjastoja…',
    RunReportButton: 'Suorita raportti',
    ItemsFoundSoFar: '{0} kohdetta löytynyt tähän mennessä',
    LibraryOfProgress: 'Kirjasto {0}/{1}',
    ScanCancelledPartialResults: 'Tarkistus peruutettu — osittaiset tulokset',
    ScanCompleteLabel: 'Tarkistus valmis',
    ObjectsCountBadge: '{0} kohdetta',
    UniqueCountBadge: '{0} yksilöllistä',
    InheritedCountBadge: '{0} perittyä',
    GeneratingExcelStatus: 'Luodaan Excel-tiedostoa…',
    ExportFilteredRowsButton: 'Vie {0} suodatettua riviä',
    ExportToExcelButton: 'Vie Exceliin',
    ExportToCsvButton: 'Vie CSV:hen',
    ScanStoppedEarlyTitle: 'Tarkistus pysäytettiin ennenaikaisesti — SharePoint kuristaa tätä vuokraajaa.',
    SiteCollectionsScannedBeforeStopping: '{0}/{1} sivustokokoelmaa tarkistettiin ennen pysäytystä. ',
    ResultsBelowCoverOnlyPre: 'Alla olevat tulokset kattavat vain sen, mikä tarkistettiin, eivätkä ne ole',
    NotWord: 'ei',
    ResultsBelowCoverOnlyPost: 'täydellinen tarkastus. Tarkistus pysähtyy itsestään tässä tilanteessa, koska pyyntöjen lähettämisen jatkaminen ylläpitää kuristusta. Odota useita minuutteja ja suorita sitten uudelleen asetuksella',
    ConcurrentRequestsWord: 'Samanaikaiset pyynnöt',
    SetTo1Or2InSettings: 'asetettu arvoon 1 tai 2 Asetuksissa.',
    ThrottledScanMessage: 'SharePoint kuristi tätä tarkistusta ({0} pyyntöä rajoitettiin ja yritettiin uudelleen).',
    OfEverythingScannedPre: 'Kaikesta tarkistetusta,',
    ItemCountSingular: '{0} kohde',
    ItemCountPlural: '{0} kohdetta',
    CouldNotBeConfirmedText: 'ei voitu vahvistaa uudelleenyrityksen jälkeen (katso alla oleva ilmoitus "ei voitu lukea täysin" nähdäksesi tarkalleen mitkä) — kyseinen virhe liittyi kapasiteettiin, ei niiden todellisiin käyttöoikeuksiin. Kaikki muut tämän raportin kohteet luettiin onnistuneesti ja niihin voi luottaa.',
    DespiteThrottlingText: 'Kuristuksesta huolimatta jokainen kohde vahvistettiin silti onnistuneesti uudelleenyrityksen jälkeen, joten tämä raportti on täydellinen.',
    ForCleanRunPre: 'Puhdasta suoritusta varten odota muutama minuutti ja tarkista uudelleen pienemmällä arvolla asetukselle',
    ValueInSettingsPost: 'Asetuksissa.',
    OneItemWord: '1 kohde',
    NItemsWord: '{0} kohde(tta)',
    OutOfScannedCouldNotBeRead: '{0}:sta tarkistetusta ei voitu lukea nykyisillä käyttöoikeuksillasi —',
    PermissionAssignmentsForItAreNotShown: ' käyttöoikeusmäärityksiä ei näytetä, ',
    PermissionAssignmentsForThoseAreNotShown: ' käyttöoikeusmäärityksiä ei näytetä, ',
    RestOfReportReadSuccessfully: 'mutta tämän raportin loppuosa luettiin onnistuneesti.',
    RunScanAsSiteOwnerPre: 'Suorita tarkistus',
    SiteOwnerWord: 'sivuston omistajana',
    RunScanAsSiteOwnerPost: 'nähdäksesi täydelliset tiedot alla olevista evätyistä kohteista.',
    AndNMoreText: '…ja {0} muuta',
    GroupExpansionSkippedPre: 'Ryhmän jäsenten laajennus ohitettiin — Graph-käyttöoikeutta',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'ei ole hyväksytty tässä vuokraajassa. SharePoint- tai yleinen järjestelmänvalvoja voi hyväksyä sen kohdassa',
    SharePointAdminCenterPath: 'SharePoint-järjestelmänvalvojan keskus → Lisäasetukset → API-käyttöoikeudet',
    ScanIncompleteItemsMessage: '{0} kohdetta ei voitu lukea täysin väliaikaisen virheen vuoksi (ei käyttöoikeusongelma) ja ne näytetään ylätason kohteen käyttöoikeuksilla varavaihtoehtona — tämä ei välttämättä vastaa niiden todellista käyttöoikeutta. Suorita tarkistus uudelleen yrittääksesi näitä kohteita uudelleen.',
    FilterByNamePathUserPlaceholder: 'Suodata nimen, polun tai käyttäjän/ryhmän mukaan…',
    FilterResultsLabel: 'Suodata tulokset',
    ExternalUsersOnlyExtLabel: 'Vain ulkoiset käyttäjät (#ext#)',
    ShowingOfCount: 'Näytetään {0}/{1}',
    ScanResultsLabel: 'Tarkistuksen tulokset',
    PermissionsColumnHeader: 'Käyttöoikeudet',
    CollapsePermissionsLabel: 'Kutista käyttöoikeudet',
    ExpandPermissionsLabel: 'Laajenna käyttöoikeudet',
    HiddenFromSearchBadge: 'Piilotettu hausta',
    AssignmentCountSingular: '{0} määritys',
    AssignmentCountPlural: '{0} määritystä',
    LoadMoreRemainingButton: 'Lataa lisää ({0} jäljellä)',
    LoadingUsersStatus: 'Ladataan käyttäjiä…',
    ConnectedUserSingular: 'Yhdistetty — {0} käyttäjä löytyi',
    ConnectedUserPlural: 'Yhdistetty — {0} käyttäjää löytyi',
    CheckingAccessForStatus: 'Tarkistetaan käyttöoikeutta käyttäjälle {0}…',
    FullSiteAccessDetectedStatus: 'Täysi sivuston käyttöoikeus havaittu.',
    AccessibleLocationsFoundSingular: '{0} käytettävissä oleva sijainti löytyi.',
    AccessibleLocationsFoundPlural: '{0} käytettävissä olevaa sijaintia löytyi.',
    NoAccessibleLocationsFoundStatus: 'Käytettävissä olevia sijainteja ei löytynyt.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Käyttäjän käyttöoikeustarkistus valmis',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Uusi tarkistus',
    NoUserAccessScansSavedYet: 'Ei vielä tallennettuja käyttäjän käyttöoikeustarkistuksia.',
    UserColumnHeader: 'Käyttäjä',
    LocationsColumnHeader: 'Sijainnit',
    FullControlBadge: 'Täysi hallinta',
    DeleteThisRecordTitle: 'Poista tämä tietue',
    SelectAUserFieldLabel: 'Valitse käyttäjä',
    SearchUsersPlaceholder: 'Etsi käyttäjiä…',
    SelectAUserToCheckAccessLabel: 'Valitse käyttäjä tarkistaaksesi käyttöoikeuden',
    NotInThisSiteLabel: 'Ei tällä sivustolla',
    ScanInProgressLabel: 'Tarkistus käynnissä',
    ScanningUserAccessLabel: 'Tarkistetaan käyttäjän käyttöoikeutta',
    ScanningStatus: 'Tarkistetaan…',
    FullControlAccessPre: 'Tällä käyttäjällä on',
    FullControlWord: 'Täysi hallinta',
    FullControlAccessPost: 'tai omistajatason käyttöoikeus koko sivustoon — kaikki kirjastot ja kansiot ovat käytettävissä.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Sivustotason käyttöoikeutta ei voitu määrittää — tämä sivusto käyttää todennäköisesti Microsoft 365 -ryhmän käyttöoikeutta. Näyttääkseen sen SharePoint-järjestelmänvalvojan on hyväksyttävä käyttöoikeus',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'kohdassa',
    ShowingSiteLevelAccessOnlyPre: 'Näytetään vain',
    SiteLevelAccessOnlyWord: 'sivustotason käyttöoikeus',
    ShowingSiteLevelAccessOnlyMid: ', joka perustuu oletusarvoiseen SharePoint-ryhmän jäsenyyteen. Kirjastojen, kansioiden ja tiedostojen yksilöllisiä käyttöoikeuksia ei voitu lukea, eikä niitä näytetä. Täydellisiä tuloksia varten suorita tämä tarkistus',
    UserAccessCouldNotBeDeterminedPre: 'Tämän käyttäjän käyttöoikeutta ei voitu määrittää. Käyttöoikeusmääritysten lukeminen vaatii oikeuden',
    UserAccessCouldNotBeDeterminedPost: '(sivuston omistaja tai korkeampi), eikä tämä käyttäjä näytä olevan sivuston oletusarvoisten Omistajat-, Jäsenet- tai Vierailijat-ryhmien jäsen.',
    SiteLevelAccessBannerPre: 'Tällä käyttäjällä on sivustotason käyttöoikeus. Vain sijainnit, joilla on',
    UniquePermissionAssignmentsWord: 'yksilölliset käyttöoikeusmääritykset',
    SiteLevelAccessBannerPost: 'näkyvät alla — kaikki muu sisältö on käytettävissä luettelon yläreunassa näkyvän sivustotason käyttöoikeuden kautta.',
    UserAccessResultsLabel: 'Käyttäjän käyttöoikeuksien tulokset',
  };
});
