define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Configuration de Smart Permissions',
    PropertyPane_GroupName: 'Général',
    PropertyPane_DefaultViewLabel: 'Vue par défaut à l\'ouverture',
    PropertyPane_View_Home: 'Accueil',
    PropertyPane_View_Report: 'Rapport de permissions',
    PropertyPane_View_Explorer: 'Explorateur de permissions',
    PropertyPane_View_UserAccess: 'Accès utilisateur',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/monsite',
    ConnectButton: 'Connecter',
    CancelButton: 'Annuler',
    ChangeUrlButton: "Changer d'URL",
    SettingsLabel: 'Paramètres',
    RenderErrorTitle: 'Smart Permissions — Erreur de rendu',
    RenderErrorMessageLabel: 'Message :',
    RenderErrorStackLabel: 'Pile :',
    RenderErrorNoStack: '(pile non disponible)',
    BackButton: 'Retour',
    BackToHomeLabel: "Retour à l'accueil",

    ExplorerCardTitle: 'Explorateur de permissions',
    ExplorerCardAlt: "Explorateur de permissions avec arborescence de dossiers et panneau des permissions",
    ExplorerCardDesc: "Parcourez n'importe quel dossier ou fichier et découvrez instantanément qui y a accès — avec des vérifications en temps réel.",
    ExplorerCardButton: "Ouvrir l'explorateur de permissions",
    ReportCardTitle: 'Rapport de permissions',
    ReportCardAlt: 'Écran de configuration du rapport de permissions',
    ReportCardDesc: "Générez un rapport Excel codé par couleur de chaque attribution de permission unique sur votre site.",
    ReportCardButton: 'Exécuter le rapport de permissions',
    UserAccessCardTitle: 'Accès utilisateur',
    UserAccessCardAlt: "Écran d'accès utilisateur montrant les emplacements accessibles pour un utilisateur sélectionné",
    UserAccessCardDesc: "Recherchez un utilisateur pour voir tous les emplacements auxquels il a accès sur un site, avec son niveau de permission exact.",
    UserAccessCardButton: "Vérifier l'accès utilisateur",
    SiteOwnerRequiredTitle: 'Accès Propriétaire du site requis —',
    SiteOwnerRequiredDesc: 'Ces outils nécessitent un accès Propriétaire du site. Contactez un propriétaire du site pour toute question sur les permissions.',
    HomeSubtitle: 'Auditez et comprenez les permissions SharePoint — sans PowerShell.',
    RequiresSiteOwnerTooltip: 'Nécessite un accès Propriétaire du site',
    HomeNoteLabel: 'Remarque :',
    HomeNoteText: "Ce composant WebPart s'exécute avec l'identité de l'utilisateur connecté. Il ne voit que les sites et éléments auxquels cet utilisateur a accès. Pour une analyse complète du tenant, utilisez un compte disposant d'un accès en lecture sur tous les sites.",

    SettingsTitle: 'Paramètres',
    LibrariesSectionTitle: 'Bibliothèques',
    IncludeHiddenLabel: 'Inclure les bibliothèques système et masquées',
    IncludeHiddenTooltip: "Si coché, inclut la bibliothèque de styles, les modèles de formulaires, les ressources du site et d'autres bibliothèques masquées des vues par défaut. S'applique à tous les outils.",
    MoreInfoHiddenLibrariesLabel: 'Plus d’informations sur les bibliothèques masquées',
    ExcludeLimitedAccessLabel: 'Exclure les entrées Accès limité',
    ExcludeLimitedAccessTooltip: "Masque les utilisateurs et groupes dont la seule permission SharePoint est Accès limité — attribuée automatiquement lors du partage de fichiers via des liens. S'applique au rapport de permissions, à l'explorateur et à l'accès utilisateur.",
    MoreInfoLimitedAccessLabel: "Plus d'informations sur l'accès limité",
    ExcludeSharingLinksLabel: 'Exclure les entrées Liens de partage',
    ExcludeSharingLinksTooltip: 'Masque les groupes internes "SharingLinks.*" que SharePoint crée automatiquement pour les liens de partage "Tout le monde avec le lien" et "Personnes spécifiques". S\'applique au rapport de permissions, à l\'explorateur et à l\'accès utilisateur.',
    MoreInfoSharingLinksLabel: 'Plus d’informations sur les liens de partage',
    PerformanceSectionTitle: 'Performance',
    ConcurrentRequestsLabel: 'Requêtes API simultanées :',
    ConcurrencyTooltip: "Nombre de requêtes API SharePoint exécutées en parallèle lors des analyses de rapports de permissions, des analyses d'accès utilisateur et des vérifications en arrière-plan de l'explorateur. Des valeurs plus élevées sont plus rapides mais risquent davantage de déclencher un throttling (HTTP 429). 3 à 5 est recommandé.",
    MoreInfoConcurrencyLabel: 'Plus d’informations sur la simultanéité',
    ConcurrencyHint: 'Des valeurs plus élevées accélèrent l’analyse mais peuvent déclencher un throttling SharePoint. Recommandé : 3 à 5.',
    GroupMemberCapLabel: "Plafond d'affichage des membres du groupe :",
    GroupMemberCapTooltip: "Nombre maximal de membres affichés par groupe lorsque « Développer les membres du groupe » est activé. Les groupes plus grands sont plafonnés et un avis est affiché. Augmenter cette valeur utilise plus de mémoire.",
    MoreInfoGroupMemberCapLabel: 'Plus d’informations sur le plafond de membres',
    GroupMemberCapHint: 'Les groupes dépassant cette limite affichent un avis de troncature. Par défaut : 500.',
    DefaultViewSectionTitle: 'Vue par défaut au chargement',
    DefaultViewInstructionsIntro: "Pour modifier l'écran qui s'ouvre au premier chargement du composant WebPart, modifiez les propriétés du composant WebPart :",
    DefaultViewStep1Pre: 'Passez la page SharePoint en mode',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: "Cliquez sur l'icône",
    DefaultViewStep2Post: 'du composant WebPart Smart Permissions.',
    DefaultViewStep3Pre: 'Dans le panneau des propriétés, choisissez une vue dans la liste déroulante',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'la page pour enregistrer la modification.',
    EditModeWord: 'Modification',
    PencilEditWord: 'crayon (modifier)',
    DefaultViewOnOpenWord: "Vue par défaut à l'ouverture",
    RepublishWord: 'Republiez',

    SiteOwnersLabel: 'Propriétaires du site :',
    EveryoneClaimLabel: 'Tout le monde',
    EveryoneExceptExternalClaimLabel: 'Tout le monde sauf les utilisateurs externes',
    PermissionAssignmentsLabel: 'Attributions de permissions',
    UserGroupColumnHeader: 'Utilisateur / Groupe',
    TypeColumnHeader: 'Type',
    PermissionLevelColumnHeader: 'Niveau de permission',
    TenantWideAccessSuffix: '— accès à l’échelle du tenant',
    SecurityGroupType: 'Groupe de sécurité',
    SpGroupType: 'Groupe SP',
    UserType: 'Utilisateur',
    CheckAccessForLabel: "Vérifier l'accès de {0}",

    ContainsUniqueAndExternalTooltip: 'Contient des éléments avec des permissions uniques et un accès utilisateur externe',
    ContainsUniqueTooltip: 'Contient des éléments avec des permissions uniques',
    ContainsExternalTooltip: 'Contient des éléments avec un accès utilisateur externe',
    UniqueBadge: 'Unique',
    ExternalAccessDetectedTooltip: 'Accès utilisateur externe détecté',
    ConnectingStatus: 'Connexion…',
    ConnectedLibrarySingular: 'Connecté — {0} bibliothèque trouvée',
    ConnectedLibraryPlural: 'Connecté — {0} bibliothèques trouvées',
    ConnectionFailedError: 'Échec de la connexion : {0}',
    LibraryEmptyStatus: 'Cette bibliothèque est vide.',
    ErrorLoadingLibrary: 'Erreur lors du chargement de la bibliothèque : {0}',
    ErrorLoadingContents: 'Erreur lors du chargement du contenu',
    LibraryFieldLabel: 'Bibliothèque',
    HiddenFromSearchSuffix: '{0} (masqué de la recherche)',
    UniquePermissionsOnlyToggle: 'Permissions uniques uniquement',
    ExternalUsersOnlyToggle: 'Utilisateurs externes uniquement',
    LegendLabel: 'Légende :',
    LegendItemHasUnique: "L'élément a des permissions uniques",
    LegendContainsUniqueBelow: 'Contient des permissions uniques en dessous',
    LegendContainsExternalBelow: 'Contient un accès utilisateur externe en dessous',
    LegendExternalOnItem: 'Accès utilisateur externe sur cet élément',
    ViewingWithMemberAccessTitle: 'Affichage avec un accès Membre',
    ViewingWithMemberAccessDesc1: "— les attributions de permissions ne sont pas visibles. La lecture de qui a accès nécessite le droit",
    ManagePermissionsWord: 'Gérer les permissions',
    ViewingWithMemberAccessDesc2: "(Propriétaire du site ou supérieur). Vous pouvez toujours voir quels éléments ont une héritance rompue à l'aide des indicateurs ↓. Pour voir les emplacements auxquels vous avez accès, utilisez l'outil",
    UserAccessWord: 'Accès utilisateur',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Dossiers et fichiers',
    SelectFolderOrFilePrompt: 'Sélectionnez un dossier ou un fichier pour afficher ses permissions.',
    UniquePermissionsBadge: 'Permissions uniques',
    InheritedBadge: 'Hérité',
    ExpandGroupMembersLabel: 'Développer les membres du groupe',
    ShowParentPermissionsLabel: 'Afficher les permissions parentes',
    InheritsFromParentText: 'Cet élément hérite des permissions de son parent.',
    YourAccessLabel: 'Votre accès :',
    PermissionsNotVisibleNodeText: 'Les attributions de permissions ne sont pas visibles — le droit Gérer les permissions (Propriétaire du site ou supérieur) est requis pour voir qui a accès à cet élément.',
    NoExternalUsersDirectAccessText: "Aucun utilisateur externe n'a d'accès direct à cet élément.",
    InheritedFromLabel: 'Hérité de :',
    ParentPermissionsNotVisibleText: 'Les attributions de permissions du parent ne sont pas visibles — nécessite le droit Gérer les permissions (Propriétaire du site ou supérieur).',
    NoPermissionsFoundOnParentText: 'Aucune permission trouvée sur le parent.',

    StartingScanStatus: "Démarrage de l'analyse…",
    ScanCancelledStatus: 'Analyse annulée — {0} objet(s) collecté(s) avant annulation.',
    ScanCompleteStatus: 'Analyse terminée — {0} objet(s) trouvé(s), {1} avec des permissions uniques.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Analyse terminée',
    ScanCompleteNotificationBody: '{0} objets, {1} avec des permissions uniques.',
    CancelledStatus: 'Annulé.',
    GenericErrorPrefix: 'Erreur : {0}',
    ExportErrorPrefix: "Erreur d'exportation : {0}",
    ScopeSiteOnly: 'Site uniquement',
    ScopeLibraries: 'Bibliothèques',
    ScopeFolders: 'Dossiers',
    ScopeFilesAndFolders: 'Fichiers et dossiers',
    ScanInProgressConfirm: "Une analyse est en cours. Quitter et annuler ?",
    HistoryButton: 'Historique',
    BackToHistoryButton: "Retour à l'historique",
    ComparingLabel: 'Comparaison',
    CompareMismatchWarning: "Ces rapports ont été réalisés avec des sites ou des options d'analyse différents — les différences ci-dessous peuvent refléter les paramètres modifiés plutôt que de réels changements de permissions.",
    NoPermissionDifferencesFound: 'Aucune différence de permissions trouvée entre ces deux rapports.',
    PermissionChangesHeaderSingular: 'Changements de permissions ({0} objet)',
    PermissionChangesHeaderPlural: 'Changements de permissions ({0} objets)',
    ChangeColumnHeader: 'Changement',
    BeforeColumnHeader: 'Avant',
    AfterColumnHeader: 'Après',
    AddedBadge: 'Ajouté',
    RemovedBadge: 'Supprimé',
    ChangedBadge: 'Modifié',
    InheritanceChangedHeader: "Héritage modifié ({0})",
    NameColumnHeader: 'Nom',
    PathColumnHeader: 'Chemin',
    NowColumnHeader: 'Maintenant',
    UniqueInheritanceBrokenBadge: 'Unique (héritage rompu)',
    InheritedRestoredBadge: 'Hérité (restauré)',
    NewObjectsHeader: 'Nouveaux objets',
    RemovedObjectsHeader: 'Objets supprimés',
    BackToScanButton: "Retour à l'analyse",
    CompareSelectedButton: 'Comparer la sélection',
    NoReportsSavedYet: 'Aucun rapport enregistré pour le moment.',
    SelectForCompareLabel: 'Sélectionner pour comparer',
    DateTimeColumnHeader: 'Date / Heure',
    SiteColumnHeader: 'Site',
    ScopeColumnHeader: 'Portée',
    ObjectsColumnHeader: 'Objets',
    UniqueColumnHeader: 'Unique',
    SelectReportForCompareLabel: 'Sélectionner le rapport du {0} pour comparer',
    AllSitesPrefix: 'Tous les sites · ',
    PlusSubsitesSuffix: ' + sous-sites',
    ExportingStatus: 'Exportation…',
    ExportButton: 'Exporter',
    DeleteThisReportTitle: 'Supprimer ce rapport',
    ScanAllSiteCollectionsLabel: "Analyser toutes les collections de sites de ce tenant (disponible uniquement sur le site racine)",
    AllSitesSearchCaveat: "La liste des sites provient de la recherche et peut ne pas inclure toutes les collections de sites — les sites très récemment créés, ou exclus de l'index de recherche, peuvent être manqués.",
    IncludeSubsitesLabel: 'Inclure les sous-sites (analyse chaque sous-site sous ce site)',
    ScanDepthFieldLabel: "Profondeur d'analyse",
    FolderDepthLimitLabel: 'Limite de profondeur des dossiers :',
    ExpandGroupMembersInReportLabel: 'Développer les membres du groupe dans le rapport (groupes SharePoint, groupes de sécurité et groupes M365)',
    LibrariesToScanLabel: 'Bibliothèques à analyser',
    OfSelectedCount: '{0} sur {1} sélectionnées',
    AllButton: 'Toutes',
    NoneButton: 'Aucune',
    LoadingLibrariesStatus: 'Chargement des bibliothèques…',
    RunReportButton: 'Exécuter le rapport',
    ItemsFoundSoFar: "{0} éléments trouvés jusqu'à présent",
    LibraryOfProgress: 'Bibliothèque {0} sur {1}',
    ScanCancelledPartialResults: 'Analyse annulée — résultats partiels',
    ScanCompleteLabel: 'Analyse terminée',
    ObjectsCountBadge: '{0} objets',
    UniqueCountBadge: '{0} uniques',
    InheritedCountBadge: '{0} hérités',
    GeneratingExcelStatus: 'Génération du fichier Excel…',
    ExportFilteredRowsButton: '{0} lignes filtrées à exporter',
    ExportToExcelButton: 'Exporter vers Excel',
    ExportToCsvButton: 'Exporter vers CSV',
    ScanStoppedEarlyTitle: 'Analyse arrêtée prématurément — SharePoint applique un throttling à ce tenant.',
    SiteCollectionsScannedBeforeStopping: '{0} collections de sites sur {1} ont été analysées avant l’arrêt. ',
    ResultsBelowCoverOnlyPre: "Les résultats ci-dessous ne couvrent que ce qui a été analysé et ne constituent",
    NotWord: 'pas',
    ResultsBelowCoverOnlyPost: "un audit complet. L'analyse s'arrête d'elle-même dans cette situation car continuer à envoyer des requêtes maintient le throttling. Attendez plusieurs minutes, puis relancez avec",
    ConcurrentRequestsWord: 'Requêtes simultanées',
    SetTo1Or2InSettings: 'réglé sur 1 ou 2 dans les Paramètres.',
    ThrottledScanMessage: 'SharePoint a limité cette analyse ({0} requête(s) ont été limitées puis retentées).',
    OfEverythingScannedPre: 'Sur tout ce qui a été analysé,',
    ItemCountSingular: '{0} élément',
    ItemCountPlural: '{0} éléments',
    CouldNotBeConfirmedText: "n'ont pas pu être confirmés après nouvelle tentative (voir l'avis « n'a pas pu être entièrement lu » ci-dessous pour savoir exactement lesquels) — cet échec était lié à la capacité, pas aux permissions réelles. Tous les autres éléments de ce rapport ont été lus avec succès et sont fiables.",
    DespiteThrottlingText: 'Malgré le throttling, chaque élément a tout de même été confirmé avec succès après nouvelle tentative, donc ce rapport est complet.',
    ForCleanRunPre: 'Pour une exécution propre, attendez quelques minutes et relancez avec une valeur',
    ValueInSettingsPost: 'plus basse dans les Paramètres.',
    OneItemWord: '1 élément',
    NItemsWord: '{0} élément(s)',
    OutOfScannedCouldNotBeRead: "sur {0} analysés n'ont pas pu être lus avec votre accès actuel —",
    PermissionAssignmentsForItAreNotShown: " les attributions de permissions ne sont pas affichées, ",
    PermissionAssignmentsForThoseAreNotShown: " les attributions de permissions ne sont pas affichées, ",
    RestOfReportReadSuccessfully: 'mais le reste de ce rapport a été lu avec succès.',
    RunScanAsSiteOwnerPre: "Exécutez l'analyse en tant que",
    SiteOwnerWord: 'Propriétaire du site',
    RunScanAsSiteOwnerPost: 'pour voir les détails complets des éléments refusés ci-dessous.',
    AndNMoreText: '…et {0} de plus',
    GroupExpansionSkippedPre: "L'expansion des membres du groupe a été ignorée — la permission Graph",
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: "n'a pas été approuvée dans ce tenant. Un administrateur SharePoint ou Global peut l'approuver dans",
    SharePointAdminCenterPath: 'Centre d’administration SharePoint → Avancé → Accès API',
    ScanIncompleteItemsMessage: "{0} élément(s) n'ont pas pu être entièrement lus en raison d'une erreur temporaire (pas un problème de permissions) et sont affichés avec les permissions de leur parent comme solution de repli — cela peut ne pas refléter leur accès réel. Relancez l'analyse pour réessayer ces éléments.",
    FilterByNamePathUserPlaceholder: 'Filtrer par nom, chemin ou utilisateur/groupe…',
    FilterResultsLabel: 'Filtrer les résultats',
    ExternalUsersOnlyExtLabel: 'Utilisateurs externes uniquement (#ext#)',
    ShowingOfCount: 'Affichage de {0} sur {1}',
    ScanResultsLabel: "Résultats de l'analyse",
    PermissionsColumnHeader: 'Permissions',
    CollapsePermissionsLabel: 'Réduire les permissions',
    ExpandPermissionsLabel: 'Développer les permissions',
    HiddenFromSearchBadge: 'Masqué de la recherche',
    AssignmentCountSingular: '{0} attribution',
    AssignmentCountPlural: '{0} attributions',
    LoadMoreRemainingButton: 'Charger plus ({0} restant(s))',

    LoadingUsersStatus: 'Chargement des utilisateurs…',
    ConnectedUserSingular: 'Connecté — {0} utilisateur trouvé',
    ConnectedUserPlural: 'Connecté — {0} utilisateurs trouvés',
    CheckingAccessForStatus: "Vérification de l'accès de {0}…",
    FullSiteAccessDetectedStatus: 'Accès complet au site détecté.',
    AccessibleLocationsFoundSingular: '{0} emplacement accessible trouvé.',
    AccessibleLocationsFoundPlural: '{0} emplacements accessibles trouvés.',
    NoAccessibleLocationsFoundStatus: 'Aucun emplacement accessible trouvé.',
    UserAccessScanCompleteNotificationTitle: "Smart Permissions — Analyse de l'accès utilisateur terminée",
    UserAccessScanCompleteNotificationBody: '{0} : {1}',
    NewScanButton: 'Nouvelle analyse',
    NoUserAccessScansSavedYet: "Aucune analyse d'accès utilisateur enregistrée pour le moment.",
    UserColumnHeader: 'Utilisateur',
    LocationsColumnHeader: 'Emplacements',
    FullControlBadge: 'Contrôle total',
    DeleteThisRecordTitle: 'Supprimer cet enregistrement',
    SelectAUserFieldLabel: 'Sélectionner un utilisateur',
    SearchUsersPlaceholder: 'Rechercher des utilisateurs…',
    SelectAUserToCheckAccessLabel: "Sélectionner un utilisateur pour vérifier l'accès",
    NotInThisSiteLabel: 'Pas sur ce site',
    ScanInProgressLabel: 'Analyse en cours',
    ScanningUserAccessLabel: "Analyse de l'accès utilisateur",
    ScanningStatus: 'Analyse en cours…',
    FullControlAccessPre: 'Cet utilisateur dispose du',
    FullControlWord: 'Contrôle total',
    FullControlAccessPost: "ou d'un accès de niveau Propriétaire sur l'ensemble du site — toutes les bibliothèques et tous les dossiers sont accessibles.",
    SiteLevelPermissionCouldNotBeDeterminedPre: "La permission au niveau du site n'a pas pu être déterminée — ce site utilise probablement un accès par groupe Microsoft 365. Pour l'afficher, un administrateur SharePoint doit approuver la permission",
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph dans',
    ShowingSiteLevelAccessOnlyPre: 'Affichage de',
    SiteLevelAccessOnlyWord: "l'accès au niveau du site uniquement",
    ShowingSiteLevelAccessOnlyMid: ', basé sur l’appartenance par défaut aux groupes SharePoint. Les permissions uniques sur les bibliothèques, dossiers et fichiers n’ont pas pu être lues et ne sont pas affichées. Pour des résultats complets, exécutez cette analyse en tant que',
    UserAccessCouldNotBeDeterminedPre: "L'accès de cet utilisateur n'a pas pu être déterminé. La lecture des attributions de permissions nécessite le droit",
    UserAccessCouldNotBeDeterminedPost: "(Propriétaire du site ou supérieur), et cet utilisateur ne semble pas être membre des groupes Propriétaires, Membres ou Visiteurs par défaut du site.",
    SiteLevelAccessBannerPre: 'Cet utilisateur a un accès au niveau du site. Seuls les emplacements avec des',
    UniquePermissionAssignmentsWord: 'attributions de permissions uniques',
    SiteLevelAccessBannerPost: "apparaissent ci-dessous — tout autre contenu est accessible via la permission au niveau du site indiquée en haut de la liste.",
    UserAccessResultsLabel: "Résultats de l'accès utilisateur",
  };
});
