define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'תצורת Smart Permissions',
    PropertyPane_GroupName: 'כללי',
    PropertyPane_DefaultViewLabel: 'תצוגת ברירת מחדל בפתיחה',
    PropertyPane_View_Home: 'בית',
    PropertyPane_View_Report: 'דוח הרשאות',
    PropertyPane_View_Explorer: 'סייר הרשאות',
    PropertyPane_View_UserAccess: 'גישת משתמש',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: 'התחבר',
    CancelButton: 'ביטול',
    ChangeUrlButton: 'שנה כתובת URL',
    SettingsLabel: 'הגדרות',
    RenderErrorTitle: 'Smart Permissions — שגיאת עיבוד',
    RenderErrorMessageLabel: 'הודעה:',
    RenderErrorStackLabel: 'מחסנית:',
    RenderErrorNoStack: '(המחסנית אינה זמינה)',
    BackButton: 'חזרה',
    BackToHomeLabel: 'חזרה לדף הבית',
    ExplorerCardTitle: 'סייר הרשאות',
    ExplorerCardAlt: 'סייר הרשאות עם עץ תיקיות ולוח הרשאות',
    ExplorerCardDesc: 'עיין בכל תיקייה או קובץ וראה מיד למי יש גישה — עם בדיקות הרשאה בזמן אמת.',
    ExplorerCardButton: 'פתח את סייר ההרשאות',
    ReportCardTitle: 'דוח הרשאות',
    ReportCardAlt: 'מסך תצורה של דוח הרשאות',
    ReportCardDesc: 'צור דוח Excel מקודד צבעונית של כל הקצאת הרשאה ייחודית באתר שלך.',
    ReportCardButton: 'הפעל דוח הרשאות',
    UserAccessCardTitle: 'גישת משתמש',
    UserAccessCardAlt: 'מסך גישת משתמש המציג מיקומים נגישים עבור משתמש נבחר',
    UserAccessCardDesc: 'חפש כל משתמש כדי לראות כל מיקום שהוא יכול לגשת אליו באתר, עם רמת ההרשאה המדויקת שלו.',
    UserAccessCardButton: 'בדוק גישת משתמש',
    SiteOwnerRequiredTitle: 'נדרשת גישת בעל אתר —',
    SiteOwnerRequiredDesc: 'כלים אלה דורשים גישת בעל אתר. פנה לבעל אתר אם יש לך שאלות לגבי הרשאות.',
    HomeSubtitle: 'בקר והבן הרשאות SharePoint — ללא PowerShell.',
    RequiresSiteOwnerTooltip: 'דורש גישת בעל אתר',
    HomeNoteLabel: 'הערה:',
    HomeNoteText: 'חלק אינטרנט זה פועל בתור המשתמש המחובר הנוכחי. הוא יכול לראות רק אתרים ופריטים שלמשתמש זה יש הרשאה לגשת אליהם. לסריקת שוכר מלאה, השתמש בחשבון עם גישת קריאה מתאימה בכל האתרים.',
    SettingsTitle: 'הגדרות',
    LibrariesSectionTitle: 'ספריות',
    IncludeHiddenLabel: 'כלול ספריות מערכת וספריות מוסתרות',
    IncludeHiddenTooltip: 'אם מסומן, כולל ספריית סגנונות, תבניות טפסים, נכסי אתר וספריות נוספות המוסתרות מתצוגות ברירת המחדל. חל על כל הכלים.',
    MoreInfoHiddenLibrariesLabel: 'מידע נוסף על ספריות מוסתרות',
    ExcludeLimitedAccessLabel: 'החרג רשומות גישה מוגבלת',
    ExcludeLimitedAccessTooltip: 'מסתיר משתמשים וקבוצות שההרשאה היחידה שלהם ב-SharePoint היא גישה מוגבלת — מוקצית אוטומטית כאשר קבצים משותפים באמצעות קישורים. חל על דוח ההרשאות, הסייר וגישת המשתמש.',
    MoreInfoLimitedAccessLabel: 'מידע נוסף על גישה מוגבלת',
    ExcludeSharingLinksLabel: 'החרג רשומות קישורי שיתוף',
    ExcludeSharingLinksTooltip: 'מסתיר את קבוצות "SharingLinks.*" הפנימיות ש-SharePoint יוצר אוטומטית עבור קישורי שיתוף "כל מי שיש לו את הקישור" ו"אנשים ספציפיים". חל על דוח ההרשאות, הסייר וגישת המשתמש.',
    MoreInfoSharingLinksLabel: 'מידע נוסף על קישורי שיתוף',
    PerformanceSectionTitle: 'ביצועים',
    ConcurrentRequestsLabel: 'בקשות API בו-זמניות:',
    ConcurrencyTooltip: 'כמה בקשות API של SharePoint פועלות במקביל במהלך סריקות דוח ההרשאות, סריקות גישת משתמש ובדיקות רקע של הסייר. ערכים גבוהים יותר מהירים יותר אך נוטים יותר להפעיל הגבלה (HTTP 429). מומלץ 3–5.',
    MoreInfoConcurrencyLabel: 'מידע נוסף על בו-זמניות',
    ConcurrencyHint: 'ערכים גבוהים יותר סורקים מהר יותר אך עלולים להפעיל הגבלה של SharePoint. מומלץ: 3–5.',
    GroupMemberCapLabel: 'מגבלת תצוגת חברי קבוצה:',
    GroupMemberCapTooltip: 'מספר החברים המרבי המוצג לכל קבוצה כאשר "הרחב חברי קבוצה" מופעל. קבוצות גדולות יותר מוגבלות ומוצגת הודעה. הגדלת ערך זה משתמשת בזיכרון רב יותר.',
    MoreInfoGroupMemberCapLabel: 'מידע נוסף על מגבלת חברי הקבוצה',
    GroupMemberCapHint: 'קבוצות גדולות ממגבלה זו מציגות הודעת קיצוץ. ברירת מחדל: 500.',
    DefaultViewSectionTitle: 'תצוגת ברירת מחדל בטעינה',
    DefaultViewInstructionsIntro: 'כדי לשנות איזה מסך נפתח כאשר חלק האינטרנט נטען לראשונה, ערוך את מאפייני חלק האינטרנט:',
    DefaultViewStep1Pre: 'הכנס את דף ה-SharePoint למצב',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'לחץ על סמל',
    DefaultViewStep2Post: 'בחלק האינטרנט Smart Permissions.',
    DefaultViewStep3Pre: 'בחלונית המאפיינים, בחר תצוגה מהרשימה הנפתחת',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'את הדף כדי לשמור את השינוי.',
    EditModeWord: 'עריכה',
    PencilEditWord: 'עיפרון (עריכה)',
    DefaultViewOnOpenWord: 'תצוגת ברירת מחדל בפתיחה',
    RepublishWord: 'פרסם מחדש',
    SiteOwnersLabel: 'בעלי אתר:',
    EveryoneClaimLabel: 'כולם',
    EveryoneExceptExternalClaimLabel: 'כולם למעט משתמשים חיצוניים',
    PermissionAssignmentsLabel: 'הקצאות הרשאה',
    UserGroupColumnHeader: 'משתמש / קבוצה',
    TypeColumnHeader: 'סוג',
    PermissionLevelColumnHeader: 'רמת הרשאה',
    TenantWideAccessSuffix: '— גישה ברמת השוכר כולו',
    SecurityGroupType: 'קבוצת אבטחה',
    SpGroupType: 'קבוצת SP',
    UserType: 'משתמש',
    CheckAccessForLabel: 'בדוק גישה עבור {0}',
    ContainsUniqueAndExternalTooltip: 'מכיל פריטים עם הרשאות ייחודיות וגישת משתמשים חיצוניים',
    ContainsUniqueTooltip: 'מכיל פריטים עם הרשאות ייחודיות',
    ContainsExternalTooltip: 'מכיל פריטים עם גישת משתמשים חיצוניים',
    UniqueBadge: 'ייחודי',
    ExternalAccessDetectedTooltip: 'זוהתה גישת משתמש חיצוני',
    ConnectingStatus: 'מתחבר…',
    ConnectedLibrarySingular: 'מחובר — נמצאה {0} ספרייה',
    ConnectedLibraryPlural: 'מחובר — נמצאו {0} ספריות',
    ConnectionFailedError: 'החיבור נכשל: {0}',
    LibraryEmptyStatus: 'ספרייה זו ריקה.',
    ErrorLoadingLibrary: 'שגיאה בטעינת הספרייה: {0}',
    ErrorLoadingContents: 'שגיאה בטעינת התוכן',
    LibraryFieldLabel: 'ספרייה',
    HiddenFromSearchSuffix: '{0} (מוסתר מחיפוש)',
    UniquePermissionsOnlyToggle: 'הרשאות ייחודיות בלבד',
    ExternalUsersOnlyToggle: 'משתמשים חיצוניים בלבד',
    LegendLabel: 'מקרא:',
    LegendItemHasUnique: 'לפריט יש הרשאות ייחודיות',
    LegendContainsUniqueBelow: 'מכיל הרשאות ייחודיות למטה',
    LegendContainsExternalBelow: 'מכיל גישת משתמש חיצוני למטה',
    LegendExternalOnItem: 'גישת משתמש חיצוני לפריט זה',
    ViewingWithMemberAccessTitle: 'צפייה עם גישת חבר',
    ViewingWithMemberAccessDesc1: '— הקצאות הרשאה אינן גלויות. קריאת מי יש לו גישה דורשת את הזכות',
    ManagePermissionsWord: 'ניהול הרשאות',
    ViewingWithMemberAccessDesc2: '(בעל אתר ומעלה). עדיין ניתן לראות אילו פריטים ניתקו את הירושה שלהם באמצעות המחוונים ↓. כדי לראות מיקומים שאליהם יש לך גישה, השתמש בכלי',
    UserAccessWord: 'גישת משתמש',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'תיקיות וקבצים',
    SelectFolderOrFilePrompt: 'בחר תיקייה או קובץ כדי להציג את ההרשאות שלו.',
    UniquePermissionsBadge: 'הרשאות ייחודיות',
    InheritedBadge: 'ירושה',
    ExpandGroupMembersLabel: 'הרחב חברי קבוצה',
    ShowParentPermissionsLabel: 'הצג הרשאות הורה',
    InheritsFromParentText: 'פריט זה יורש הרשאות מפריט האב שלו.',
    YourAccessLabel: 'הגישה שלך:',
    PermissionsNotVisibleNodeText: 'הקצאות הרשאה אינן גלויות — נדרשת הזכות ניהול הרשאות (בעל אתר ומעלה) כדי לראות מי יש לו גישה לפריט זה.',
    NoExternalUsersDirectAccessText: 'לאף משתמש חיצוני אין גישה ישירה לפריט זה.',
    InheritedFromLabel: 'ירושה מ:',
    ParentPermissionsNotVisibleText: 'הקצאות ההרשאה של פריט האב אינן גלויות — דורש את הזכות ניהול הרשאות (בעל אתר ומעלה).',
    NoPermissionsFoundOnParentText: 'לא נמצאו הרשאות בפריט האב.',
    StartingScanStatus: 'מתחיל סריקה…',
    ScanCancelledStatus: 'הסריקה בוטלה — נאספו {0} אובייקט(ים) לפני הביטול.',
    ScanCompleteStatus: 'הסריקה הושלמה — נמצאו {0} אובייקט(ים), {1} עם הרשאות ייחודיות.',
    ScanCompleteNotificationTitle: 'Smart Permissions — הסריקה הושלמה',
    ScanCompleteNotificationBody: '{0} אובייקטים, {1} עם הרשאות ייחודיות.',
    CancelledStatus: 'בוטל.',
    GenericErrorPrefix: 'שגיאה: {0}',
    ExportErrorPrefix: 'שגיאת ייצוא: {0}',
    ScopeSiteOnly: 'אתר בלבד',
    ScopeLibraries: 'ספריות',
    ScopeFolders: 'תיקיות',
    ScopeFilesAndFolders: 'קבצים ותיקיות',
    ScanInProgressConfirm: 'סריקה מתבצעת כעת. לצאת ולבטל?',
    HistoryButton: 'היסטוריה',
    BackToHistoryButton: 'חזרה להיסטוריה',
    ComparingLabel: 'משווה',
    CompareMismatchWarning: 'דוחות אלה נלקחו עם אתרים או אפשרויות סריקה שונים — ההבדלים שלהלן עשויים לשקף את הגדרות הסריקה שהשתנו ולא שינויי הרשאה בפועל.',
    NoPermissionDifferencesFound: 'לא נמצאו הבדלי הרשאה בין שני דוחות אלה.',
    PermissionChangesHeaderSingular: 'שינויי הרשאה ({0} אובייקט)',
    PermissionChangesHeaderPlural: 'שינויי הרשאה ({0} אובייקטים)',
    ChangeColumnHeader: 'שינוי',
    BeforeColumnHeader: 'לפני',
    AfterColumnHeader: 'אחרי',
    AddedBadge: 'נוסף',
    RemovedBadge: 'הוסר',
    ChangedBadge: 'שונה',
    InheritanceChangedHeader: 'הירושה השתנתה ({0})',
    NameColumnHeader: 'שם',
    PathColumnHeader: 'נתיב',
    NowColumnHeader: 'עכשיו',
    UniqueInheritanceBrokenBadge: 'ייחודי (הירושה נותקה)',
    InheritedRestoredBadge: 'ירושה (שוחזרה)',
    NewObjectsHeader: 'אובייקטים חדשים',
    RemovedObjectsHeader: 'אובייקטים שהוסרו',
    BackToScanButton: 'חזרה לסריקה',
    CompareSelectedButton: 'השווה נבחרים',
    NoReportsSavedYet: 'עדיין לא נשמרו דוחות.',
    SelectForCompareLabel: 'בחר להשוואה',
    DateTimeColumnHeader: 'תאריך / שעה',
    SiteColumnHeader: 'אתר',
    ScopeColumnHeader: 'היקף',
    ObjectsColumnHeader: 'אובייקטים',
    UniqueColumnHeader: 'ייחודיים',
    SelectReportForCompareLabel: 'בחר דוח מ-{0} להשוואה',
    AllSitesPrefix: 'כל האתרים · ',
    PlusSubsitesSuffix: ' + אתרי משנה',
    ExportingStatus: 'מייצא…',
    ExportButton: 'ייצוא',
    DeleteThisReportTitle: 'מחק דוח זה',
    ScanAllSiteCollectionsLabel: 'סרוק את כל אוספי האתרים בשוכר זה (זמין רק באתר השורש)',
    AllSitesSearchCaveat: 'רשימת האתרים מגיעה מחיפוש וייתכן שאינה כוללת כל אוסף אתרים — אתרים שנוצרו לאחרונה מאוד, או אתרים שהוחרגו מאינדקס החיפוש, עשויים להיות חסרים.',
    IncludeSubsitesLabel: 'כלול אתרי משנה (סורק כל אתר משנה מתחת לאתר זה)',
    ScanDepthFieldLabel: 'עומק הסריקה',
    FolderDepthLimitLabel: 'מגבלת עומק תיקייה:',
    ExpandGroupMembersInReportLabel: 'הרחב חברי קבוצה בדוח (קבוצות SharePoint, קבוצות אבטחה וקבוצות M365)',
    LibrariesToScanLabel: 'ספריות לסריקה',
    OfSelectedCount: '{0} מתוך {1} נבחרו',
    AllButton: 'הכל',
    NoneButton: 'ללא',
    LoadingLibrariesStatus: 'טוען ספריות…',
    RunReportButton: 'הפעל דוח',
    ItemsFoundSoFar: 'נמצאו {0} פריטים עד כה',
    LibraryOfProgress: 'ספרייה {0} מתוך {1}',
    ScanCancelledPartialResults: 'הסריקה בוטלה — תוצאות חלקיות',
    ScanCompleteLabel: 'הסריקה הושלמה',
    ObjectsCountBadge: '{0} אובייקטים',
    UniqueCountBadge: '{0} ייחודיים',
    InheritedCountBadge: '{0} בירושה',
    GeneratingExcelStatus: 'יוצר Excel…',
    ExportFilteredRowsButton: 'ייצא {0} שורות מסוננות',
    ExportToExcelButton: 'ייצא ל-Excel',
    ExportToCsvButton: 'ייצא ל-CSV',
    ScanStoppedEarlyTitle: 'הסריקה נעצרה מוקדם — SharePoint מגביל שוכר זה.',
    SiteCollectionsScannedBeforeStopping: '{0} מתוך {1} אוספי אתרים נסרקו לפני העצירה. ',
    ResultsBelowCoverOnlyPre: 'התוצאות שלהלן מכסות רק את מה שנסרק ואינן',
    NotWord: 'אינן',
    ResultsBelowCoverOnlyPost: 'ביקורת מלאה. הסריקה עוצרת את עצמה במצב זה מכיוון שהמשך שליחת בקשות הוא מה שמשאיר את ההגבלה פעילה. המתן מספר דקות, ולאחר מכן הפעל מחדש עם',
    ConcurrentRequestsWord: 'בקשות בו-זמניות',
    SetTo1Or2InSettings: 'מוגדר ל-1 או 2 בהגדרות.',
    ThrottledScanMessage: 'SharePoint הגביל סריקה זו ({0} בקשה(ות) הוגבלו בקצב ונוסו שוב).',
    OfEverythingScannedPre: 'מכל מה שנסרק,',
    ItemCountSingular: '{0} פריט',
    ItemCountPlural: '{0} פריטים',
    CouldNotBeConfirmedText: 'לא ניתן היה לאשר לאחר ניסיון חוזר (ראה את ההודעה "לא ניתן היה לקרוא במלואו" שלהלן כדי לדעת בדיוק אילו) — כשל זה היה קשור לקיבולת, לא שיקוף של ההרשאות בפועל שלהם. כל שאר הפריטים בדוח זה נקראו בהצלחה וניתן לסמוך עליהם.',
    DespiteThrottlingText: 'למרות ההגבלה, כל פריט עדיין אושר בהצלחה לאחר ניסיון חוזר, כך שדוח זה שלם.',
    ForCleanRunPre: 'לריצה נקייה, המתן מספר דקות וסרוק שוב עם ערך נמוך יותר עבור',
    ValueInSettingsPost: 'בהגדרות.',
    OneItemWord: 'פריט אחד',
    NItemsWord: '{0} פריט(ים)',
    OutOfScannedCouldNotBeRead: 'מתוך {0} שנסרקו לא ניתן היה לקרוא עם הגישה הנוכחית שלך —',
    PermissionAssignmentsForItAreNotShown: ' הקצאות הרשאה אינן מוצגות, ',
    PermissionAssignmentsForThoseAreNotShown: ' הקצאות הרשאה אינן מוצגות, ',
    RestOfReportReadSuccessfully: 'אך שאר הדוח הזה נקרא בהצלחה.',
    RunScanAsSiteOwnerPre: 'הפעל את הסריקה בתור',
    SiteOwnerWord: 'בעל אתר',
    RunScanAsSiteOwnerPost: 'כדי לראות פרטים מלאים עבור הפריטים שנדחו שלהלן.',
    AndNMoreText: '…ועוד {0}',
    GroupExpansionSkippedPre: 'הרחבת חברי הקבוצה דולגה — הרשאת Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'לא אושרה בשוכר זה. מנהל SharePoint או מנהל גלובלי יכול לאשר אותה ב',
    SharePointAdminCenterPath: 'מרכז הניהול של SharePoint ← מתקדם ← גישת API',
    ScanIncompleteItemsMessage: 'לא ניתן היה לקרוא {0} פריט(ים) במלואם עקב שגיאה זמנית (לא בעיית הרשאה) והם מוצגים עם ההרשאות של פריט האב שלהם כפתרון חלופי — ייתכן שהדבר אינו משקף את הגישה בפועל שלהם. הפעל מחדש את הסריקה כדי לנסות שוב פריטים אלה.',
    FilterByNamePathUserPlaceholder: 'סנן לפי שם, נתיב או משתמש/קבוצה…',
    FilterResultsLabel: 'סנן תוצאות',
    ExternalUsersOnlyExtLabel: 'משתמשים חיצוניים בלבד (#ext#)',
    ShowingOfCount: 'מציג {0} מתוך {1}',
    ScanResultsLabel: 'תוצאות הסריקה',
    PermissionsColumnHeader: 'הרשאות',
    CollapsePermissionsLabel: 'כווץ הרשאות',
    ExpandPermissionsLabel: 'הרחב הרשאות',
    HiddenFromSearchBadge: 'מוסתר מחיפוש',
    AssignmentCountSingular: '{0} הקצאה',
    AssignmentCountPlural: '{0} הקצאות',
    LoadMoreRemainingButton: 'טען עוד (נותרו {0})',
    LoadingUsersStatus: 'טוען משתמשים…',
    ConnectedUserSingular: 'מחובר — נמצא {0} משתמש',
    ConnectedUserPlural: 'מחובר — נמצאו {0} משתמשים',
    CheckingAccessForStatus: 'בודק גישה עבור {0}…',
    FullSiteAccessDetectedStatus: 'זוהתה גישה מלאה לאתר.',
    AccessibleLocationsFoundSingular: 'נמצא {0} מיקום נגיש.',
    AccessibleLocationsFoundPlural: 'נמצאו {0} מיקומים נגישים.',
    NoAccessibleLocationsFoundStatus: 'לא נמצאו מיקומים נגישים.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — סריקת גישת משתמש הושלמה',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'סריקה חדשה',
    NoUserAccessScansSavedYet: 'עדיין לא נשמרו סריקות גישת משתמש.',
    UserColumnHeader: 'משתמש',
    LocationsColumnHeader: 'מיקומים',
    FullControlBadge: 'שליטה מלאה',
    DeleteThisRecordTitle: 'מחק רשומה זו',
    SelectAUserFieldLabel: 'בחר משתמש',
    SearchUsersPlaceholder: 'חפש משתמשים…',
    SelectAUserToCheckAccessLabel: 'בחר משתמש כדי לבדוק גישה',
    NotInThisSiteLabel: 'לא באתר זה',
    ScanInProgressLabel: 'סריקה מתבצעת',
    ScanningUserAccessLabel: 'סורק גישת משתמש',
    ScanningStatus: 'סורק…',
    FullControlAccessPre: 'למשתמש זה יש',
    FullControlWord: 'שליטה מלאה',
    FullControlAccessPost: 'או גישה ברמת בעלים לכל האתר — כל הספריות והתיקיות נגישות.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'לא ניתן היה לקבוע הרשאה ברמת האתר — אתר זה כנראה משתמש בגישת קבוצת Microsoft 365. כדי להציג זאת, מנהל SharePoint חייב לאשר את הרשאת',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph ב',
    ShowingSiteLevelAccessOnlyPre: 'מוצגת רק',
    SiteLevelAccessOnlyWord: 'גישה ברמת האתר',
    ShowingSiteLevelAccessOnlyMid: ', בהתבסס על חברות ברירת המחדל בקבוצת SharePoint. לא ניתן היה לקרוא הרשאות ייחודיות בספריות, תיקיות וקבצים והן אינן מוצגות. לתוצאות מלאות, הפעל סריקה זו בתור',
    UserAccessCouldNotBeDeterminedPre: 'לא ניתן היה לקבוע את הגישה של משתמש זה. קריאת הקצאות הרשאה דורשת את הזכות',
    UserAccessCouldNotBeDeterminedPost: '(בעל אתר ומעלה), ומשתמש זה אינו נראה כחבר בקבוצות ברירת המחדל של בעלים, חברים או מבקרים באתר.',
    SiteLevelAccessBannerPre: 'למשתמש זה יש גישה ברמת האתר. רק מיקומים עם',
    UniquePermissionAssignmentsWord: 'הקצאות הרשאה ייחודיות',
    SiteLevelAccessBannerPost: 'מופיעים להלן — כל שאר התוכן נגיש דרך ההרשאה ברמת האתר המוצגת בראש הרשימה.',
    UserAccessResultsLabel: 'תוצאות גישת משתמש',
  };
});
