define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'स्मार्ट परमिशंस कॉन्फ़िगरेशन',
    PropertyPane_GroupName: 'सामान्य',
    PropertyPane_DefaultViewLabel: 'खुलने पर डिफ़ॉल्ट व्यू',
    PropertyPane_View_Home: 'होम',
    PropertyPane_View_Report: 'परमिशंस रिपोर्ट',
    PropertyPane_View_Explorer: 'परमिशंस एक्सप्लोरर',
    PropertyPane_View_UserAccess: 'यूज़र एक्सेस',

    // App shell
    AppTitle: 'शेयरपॉइंट स्मार्ट परमिशंस',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: 'कनेक्ट करें',
    CancelButton: 'रद्द करें',
    ChangeUrlButton: 'URL बदलें',
    SettingsLabel: 'सेटिंग्स',
    RenderErrorTitle: 'स्मार्ट परमिशंस — रेंडर एरर',
    RenderErrorMessageLabel: 'संदेश:',
    RenderErrorStackLabel: 'स्टैक:',
    RenderErrorNoStack: '(कोई स्टैक उपलब्ध नहीं है)',
    BackButton: 'वापस',
    BackToHomeLabel: 'होम पर वापस जाएँ',

    // Home view
    ExplorerCardTitle: 'परमिशंस एक्सप्लोरर',
    ExplorerCardAlt: 'फ़ोल्डर ट्री और परमिशंस पैनल के साथ परमिशंस एक्सप्लोरर',
    ExplorerCardDesc: 'किसी भी फ़ोल्डर या फ़ाइल को ब्राउज़ करें और तुरंत देखें कि किसके पास एक्सेस है — लाइव, रीयल-टाइम परमिशन लुकअप के साथ।',
    ExplorerCardButton: 'परमिशंस एक्सप्लोरर खोलें',
    ReportCardTitle: 'परमिशंस रिपोर्ट',
    ReportCardAlt: 'परमिशंस रिपोर्ट कॉन्फ़िगरेशन स्क्रीन',
    ReportCardDesc: 'अपनी साइट के हर यूनीक परमिशन असाइनमेंट की एक कलर-कोडेड एक्सेल रिपोर्ट जनरेट करें।',
    ReportCardButton: 'परमिशंस रिपोर्ट चलाएँ',
    UserAccessCardTitle: 'यूज़र एक्सेस',
    UserAccessCardAlt: 'चुने गए यूज़र के लिए एक्सेस योग्य स्थान दिखाने वाली यूज़र एक्सेस स्क्रीन',
    UserAccessCardDesc: 'किसी भी यूज़र को खोजें और देखें कि साइट पर उनकी पहुँच किन-किन स्थानों तक है, उनके सटीक परमिशन स्तर के साथ।',
    UserAccessCardButton: 'यूज़र एक्सेस जाँचें',
    SiteOwnerRequiredTitle: 'साइट ओनर एक्सेस आवश्यक है —',
    SiteOwnerRequiredDesc: 'इन टूल्स के लिए साइट ओनर एक्सेस आवश्यक है। परमिशंस से संबंधित प्रश्नों के लिए किसी साइट ओनर से संपर्क करें।',
    HomeSubtitle: 'शेयरपॉइंट परमिशंस का ऑडिट करें और समझें — कोई पावरशेल आवश्यक नहीं।',
    RequiresSiteOwnerTooltip: 'साइट ओनर एक्सेस आवश्यक है',
    HomeNoteLabel: 'नोट:',
    HomeNoteText: 'यह वेब पार्ट वर्तमान में साइन-इन किए गए यूज़र के रूप में चलता है। यह केवल उन्हीं साइटों और आइटम को देख सकता है जिन्हें देखने की अनुमति उस यूज़र के पास है। पूरे टेनेंट के स्कैन के लिए, सभी साइटों पर उपयुक्त रीड एक्सेस वाले खाते का उपयोग करें।',

    // Settings view
    SettingsTitle: 'सेटिंग्स',
    LibrariesSectionTitle: 'लाइब्रेरीज़',
    IncludeHiddenLabel: 'सिस्टम और छिपी हुई लाइब्रेरीज़ शामिल करें',
    IncludeHiddenTooltip: 'चेक किए जाने पर, स्टाइल लाइब्रेरी, फ़ॉर्म टेम्प्लेट, साइट एसेट्स और डिफ़ॉल्ट व्यू से छिपी अन्य लाइब्रेरीज़ शामिल करता है। यह सभी टूल्स पर लागू होता है।',
    MoreInfoHiddenLibrariesLabel: 'छिपी हुई लाइब्रेरीज़ के बारे में अधिक जानकारी',
    ExcludeLimitedAccessLabel: 'लिमिटेड एक्सेस प्रविष्टियाँ बाहर रखें',
    ExcludeLimitedAccessTooltip: 'उन यूज़र और ग्रुप को छिपाता है जिनकी एकमात्र शेयरपॉइंट परमिशन लिमिटेड एक्सेस है — जो लिंक के माध्यम से शेयर की गई फ़ाइलों के लिए स्वचालित रूप से असाइन होती है। यह परमिशंस रिपोर्ट, एक्सप्लोरर और यूज़र एक्सेस पर लागू होता है।',
    MoreInfoLimitedAccessLabel: 'लिमिटेड एक्सेस के बारे में अधिक जानकारी',
    ExcludeSharingLinksLabel: 'शेयरिंग लिंक प्रविष्टियाँ बाहर रखें',
    ExcludeSharingLinksTooltip: '"किसी के भी पास लिंक हो" और "विशिष्ट लोगों" वाले शेयरिंग लिंक के लिए शेयरपॉइंट द्वारा स्वतः बनाए गए आंतरिक "SharingLinks.*" ग्रुप को छिपाता है। यह परमिशंस रिपोर्ट, एक्सप्लोरर और यूज़र एक्सेस पर लागू होता है।',
    MoreInfoSharingLinksLabel: 'शेयरिंग लिंक के बारे में अधिक जानकारी',
    PerformanceSectionTitle: 'परफ़ॉर्मेंस',
    ConcurrentRequestsLabel: 'समवर्ती API अनुरोध:',
    ConcurrencyTooltip: 'परमिशंस रिपोर्ट स्कैन, यूज़र एक्सेस स्कैन और एक्सप्लोरर बैकग्राउंड जाँच के दौरान समानांतर में कितने शेयरपॉइंट API अनुरोध चलते हैं। अधिक मान तेज़ होते हैं लेकिन थ्रॉटलिंग (HTTP 429) होने की संभावना अधिक होती है। 3–5 की सिफ़ारिश की जाती है।',
    MoreInfoConcurrencyLabel: 'समवर्तीता के बारे में अधिक जानकारी',
    ConcurrencyHint: 'अधिक मान स्कैनिंग तेज़ करते हैं लेकिन शेयरपॉइंट थ्रॉटलिंग का कारण बन सकते हैं। सिफ़ारिश: 3–5।',
    GroupMemberCapLabel: 'ग्रुप सदस्य प्रदर्शन सीमा:',
    GroupMemberCapTooltip: "'ग्रुप सदस्य विस्तृत करें' सक्षम होने पर प्रति ग्रुप अधिकतम कितने सदस्य दिखाए जाते हैं। बड़े ग्रुप सीमित कर दिए जाते हैं और एक सूचना दिखाई जाती है। इस मान को बढ़ाने से अधिक मेमोरी उपयोग होती है।",
    MoreInfoGroupMemberCapLabel: 'ग्रुप सदस्य सीमा के बारे में अधिक जानकारी',
    GroupMemberCapHint: 'इस सीमा से बड़े ग्रुप एक ट्रंकेशन सूचना दिखाते हैं। डिफ़ॉल्ट: 500।',
    DefaultViewSectionTitle: 'लोड होने पर डिफ़ॉल्ट व्यू',
    DefaultViewInstructionsIntro: 'वेब पार्ट पहली बार लोड होने पर कौन सी स्क्रीन खुलेगी, यह बदलने के लिए वेब पार्ट प्रॉपर्टीज़ संपादित करें:',
    DefaultViewStep1Pre: 'शेयरपॉइंट पेज को',
    DefaultViewStep1Post: 'मोड में डालें।',
    DefaultViewStep2Pre: 'क्लिक करें',
    DefaultViewStep2Post: 'स्मार्ट परमिशंस वेब पार्ट पर आइकन।',
    DefaultViewStep3Pre: 'प्रॉपर्टी पैनल में, इससे एक व्यू चुनें',
    DefaultViewStep3Post: 'ड्रॉपडाउन।',
    DefaultViewStep4Post: 'परिवर्तन सहेजने के लिए पेज।',
    EditModeWord: 'संपादित करें',
    PencilEditWord: 'पेंसिल (संपादित करें)',
    DefaultViewOnOpenWord: 'खुलने पर डिफ़ॉल्ट व्यू',
    RepublishWord: 'फिर से प्रकाशित करें',

    // Shared
    SiteOwnersLabel: 'साइट ओनर:',
    EveryoneClaimLabel: 'सभी',
    EveryoneExceptExternalClaimLabel: 'बाहरी यूज़र को छोड़कर सभी',
    PermissionAssignmentsLabel: 'परमिशन असाइनमेंट',
    UserGroupColumnHeader: 'यूज़र / ग्रुप',
    TypeColumnHeader: 'प्रकार',
    PermissionLevelColumnHeader: 'परमिशन स्तर',
    TenantWideAccessSuffix: '— टेनेंट-व्यापी एक्सेस',
    SecurityGroupType: 'सिक्योरिटी ग्रुप',
    SpGroupType: 'SP ग्रुप',
    UserType: 'यूज़र',
    CheckAccessForLabel: '{0} के लिए एक्सेस जाँचें',

    // Explorer view
    ContainsUniqueAndExternalTooltip: 'इसमें यूनीक परमिशंस और बाहरी यूज़र एक्सेस वाले आइटम शामिल हैं',
    ContainsUniqueTooltip: 'इसमें यूनीक परमिशंस वाले आइटम शामिल हैं',
    ContainsExternalTooltip: 'इसमें बाहरी यूज़र एक्सेस वाले आइटम शामिल हैं',
    UniqueBadge: 'यूनीक',
    ExternalAccessDetectedTooltip: 'बाहरी यूज़र एक्सेस का पता चला',
    ConnectingStatus: 'कनेक्ट हो रहा है…',
    ConnectedLibrarySingular: 'कनेक्टेड — {0} लाइब्रेरी मिली',
    ConnectedLibraryPlural: 'कनेक्टेड — {0} लाइब्रेरीज़ मिलीं',
    ConnectionFailedError: 'कनेक्शन विफल: {0}',
    LibraryEmptyStatus: 'यह लाइब्रेरी खाली है।',
    ErrorLoadingLibrary: 'लाइब्रेरी लोड करने में त्रुटि: {0}',
    ErrorLoadingContents: 'सामग्री लोड करने में त्रुटि',
    LibraryFieldLabel: 'लाइब्रेरी',
    HiddenFromSearchSuffix: '{0} (खोज से छिपा हुआ)',
    UniquePermissionsOnlyToggle: 'केवल यूनीक परमिशंस',
    ExternalUsersOnlyToggle: 'केवल बाहरी यूज़र',
    LegendLabel: 'लीजेंड:',
    LegendItemHasUnique: 'आइटम में यूनीक परमिशंस हैं',
    LegendContainsUniqueBelow: 'नीचे यूनीक परमिशंस शामिल हैं',
    LegendContainsExternalBelow: 'नीचे बाहरी यूज़र एक्सेस शामिल है',
    LegendExternalOnItem: 'इस आइटम पर बाहरी यूज़र एक्सेस',
    ViewingWithMemberAccessTitle: 'मेंबर एक्सेस के साथ देखा जा रहा है',
    ViewingWithMemberAccessDesc1: '— परमिशन असाइनमेंट दिखाई नहीं देते। किसके पास एक्सेस है यह पढ़ने के लिए आवश्यक है',
    ManagePermissionsWord: 'परमिशंस प्रबंधित करें',
    ViewingWithMemberAccessDesc2: 'राइट (साइट ओनर या उच्चतर)। आप अभी भी ↓ इंडिकेटर का उपयोग करके देख सकते हैं कि किन आइटम की इनहेरिटेंस टूटी हुई है। आप जिन स्थानों तक पहुँच सकते हैं उन्हें देखने के लिए, इसका उपयोग करें',
    UserAccessWord: 'यूज़र एक्सेस',
    ViewingWithMemberAccessDesc3: 'टूल।',
    FoldersAndFilesLabel: 'फ़ोल्डर और फ़ाइलें',
    SelectFolderOrFilePrompt: 'इसकी परमिशंस देखने के लिए एक फ़ोल्डर या फ़ाइल चुनें।',
    UniquePermissionsBadge: 'यूनीक परमिशंस',
    InheritedBadge: 'इनहेरिटेड',
    ExpandGroupMembersLabel: 'ग्रुप सदस्य विस्तृत करें',
    ShowParentPermissionsLabel: 'पैरेंट परमिशंस दिखाएँ',
    InheritsFromParentText: 'यह आइटम अपने पैरेंट से परमिशंस इनहेरिट करता है।',
    YourAccessLabel: 'आपकी एक्सेस:',
    PermissionsNotVisibleNodeText: 'परमिशन असाइनमेंट दिखाई नहीं देते — इस आइटम तक किसकी पहुँच है यह पढ़ने के लिए मैनेज परमिशंस राइट (साइट ओनर या उच्चतर) आवश्यक है।',
    NoExternalUsersDirectAccessText: 'इस आइटम तक किसी बाहरी यूज़र की सीधी पहुँच नहीं है।',
    InheritedFromLabel: 'इससे इनहेरिट किया गया:',
    ParentPermissionsNotVisibleText: 'पैरेंट परमिशन असाइनमेंट दिखाई नहीं देते — इसके लिए मैनेज परमिशंस राइट (साइट ओनर या उच्चतर) आवश्यक है।',
    NoPermissionsFoundOnParentText: 'पैरेंट पर कोई परमिशन नहीं मिली।',

    // Report view
    StartingScanStatus: 'स्कैन शुरू हो रहा है…',
    ScanCancelledStatus: 'स्कैन रद्द किया गया — रद्द करने से पहले {0} ऑब्जेक्ट एकत्र किए गए।',
    ScanCompleteStatus: 'स्कैन पूर्ण — {0} ऑब्जेक्ट मिले, जिनमें से {1} यूनीक परमिशंस वाले हैं।',
    ScanCompleteNotificationTitle: 'स्मार्ट परमिशंस — स्कैन पूर्ण',
    ScanCompleteNotificationBody: '{0} ऑब्जेक्ट, {1} यूनीक परमिशंस वाले।',
    CancelledStatus: 'रद्द किया गया।',
    GenericErrorPrefix: 'त्रुटि: {0}',
    ExportErrorPrefix: 'एक्सपोर्ट त्रुटि: {0}',
    ScopeSiteOnly: 'केवल साइट',
    ScopeLibraries: 'लाइब्रेरीज़',
    ScopeFolders: 'फ़ोल्डर',
    ScopeFilesAndFolders: 'फ़ाइलें और फ़ोल्डर',
    ScanInProgressConfirm: 'एक स्कैन प्रगति पर है। छोड़ें और रद्द करें?',
    HistoryButton: 'इतिहास',
    BackToHistoryButton: 'इतिहास पर वापस जाएँ',
    ComparingLabel: 'तुलना की जा रही है',
    CompareMismatchWarning: 'ये रिपोर्ट अलग-अलग साइटों या स्कैन विकल्पों के साथ ली गई थीं — नीचे दिए गए अंतर वास्तविक परमिशन परिवर्तनों के बजाय बदली गई स्कैन सेटिंग्स को दर्शा सकते हैं।',
    NoPermissionDifferencesFound: 'इन दोनों रिपोर्ट के बीच कोई परमिशन अंतर नहीं मिला।',
    PermissionChangesHeaderSingular: 'परमिशन परिवर्तन ({0} ऑब्जेक्ट)',
    PermissionChangesHeaderPlural: 'परमिशन परिवर्तन ({0} ऑब्जेक्ट)',
    ChangeColumnHeader: 'परिवर्तन',
    BeforeColumnHeader: 'पहले',
    AfterColumnHeader: 'बाद में',
    AddedBadge: 'जोड़ा गया',
    RemovedBadge: 'हटाया गया',
    ChangedBadge: 'बदला गया',
    InheritanceChangedHeader: 'इनहेरिटेंस बदली गई ({0})',
    NameColumnHeader: 'नाम',
    PathColumnHeader: 'पथ',
    NowColumnHeader: 'अभी',
    UniqueInheritanceBrokenBadge: 'यूनीक (इनहेरिटेंस टूटी हुई)',
    InheritedRestoredBadge: 'इनहेरिटेड (पुनर्स्थापित)',
    NewObjectsHeader: 'नए ऑब्जेक्ट',
    RemovedObjectsHeader: 'हटाए गए ऑब्जेक्ट',
    BackToScanButton: 'स्कैन पर वापस जाएँ',
    CompareSelectedButton: 'चयनित की तुलना करें',
    NoReportsSavedYet: 'अभी तक कोई रिपोर्ट सहेजी नहीं गई है।',
    SelectForCompareLabel: 'तुलना के लिए चुनें',
    DateTimeColumnHeader: 'दिनांक / समय',
    SiteColumnHeader: 'साइट',
    ScopeColumnHeader: 'स्कोप',
    ObjectsColumnHeader: 'ऑब्जेक्ट',
    UniqueColumnHeader: 'यूनीक',
    SelectReportForCompareLabel: 'तुलना के लिए {0} से रिपोर्ट चुनें',
    AllSitesPrefix: 'सभी साइटें · ',
    PlusSubsitesSuffix: ' + सबसाइटें',
    ExportingStatus: 'एक्सपोर्ट हो रहा है…',
    ExportButton: 'एक्सपोर्ट',
    DeleteThisReportTitle: 'इस रिपोर्ट को हटाएँ',
    ScanAllSiteCollectionsLabel: 'इस टेनेंट में सभी साइट कलेक्शन स्कैन करें (केवल रूट साइट में उपलब्ध)',
    AllSitesSearchCaveat: 'साइट सूची सर्च से प्राप्त होती है और इसमें हर साइट कलेक्शन शामिल नहीं हो सकता — बहुत हाल ही में बनाई गई साइटें, या सर्च इंडेक्स से बाहर रखी गई साइटें छूट सकती हैं।',
    IncludeSubsitesLabel: 'सबसाइट्स शामिल करें (इस साइट के नीचे हर सबसाइट को स्कैन करता है)',
    ScanDepthFieldLabel: 'स्कैन गहराई',
    FolderDepthLimitLabel: 'फ़ोल्डर गहराई सीमा:',
    ExpandGroupMembersInReportLabel: 'रिपोर्ट में ग्रुप सदस्य विस्तृत करें (शेयरपॉइंट ग्रुप, सिक्योरिटी ग्रुप और M365 ग्रुप)',
    LibrariesToScanLabel: 'स्कैन करने के लिए लाइब्रेरीज़',
    OfSelectedCount: '{1} में से {0} चयनित',
    AllButton: 'सभी',
    NoneButton: 'कोई नहीं',
    LoadingLibrariesStatus: 'लाइब्रेरीज़ लोड हो रही हैं…',
    RunReportButton: 'रिपोर्ट चलाएँ',
    ItemsFoundSoFar: 'अब तक {0} आइटम मिले',
    LibraryOfProgress: 'लाइब्रेरी {1} में से {0}',
    ScanCancelledPartialResults: 'स्कैन रद्द किया गया — आंशिक परिणाम',
    ScanCompleteLabel: 'स्कैन पूर्ण',
    ObjectsCountBadge: '{0} ऑब्जेक्ट',
    UniqueCountBadge: '{0} यूनीक',
    InheritedCountBadge: '{0} इनहेरिटेड',
    GeneratingExcelStatus: 'एक्सेल तैयार हो रहा है…',
    ExportFilteredRowsButton: '{0} फ़िल्टर की गई पंक्तियाँ एक्सपोर्ट करें',
    ExportToExcelButton: 'एक्सेल में एक्सपोर्ट करें',
    ExportToCsvButton: 'CSV में एक्सपोर्ट करें',
    ScanStoppedEarlyTitle: 'स्कैन जल्दी रुक गया — शेयरपॉइंट इस टेनेंट को थ्रॉटल कर रहा है।',
    SiteCollectionsScannedBeforeStopping: 'रुकने से पहले {1} में से {0} साइट कलेक्शन स्कैन किए गए। ',
    ResultsBelowCoverOnlyPre: 'नीचे दिए गए परिणाम केवल उसी को कवर करते हैं जो स्कैन किया गया था और ये',
    NotWord: 'नहीं हैं',
    ResultsBelowCoverOnlyPost: 'एक पूर्ण ऑडिट। इस स्थिति में स्कैन खुद-ब-खुद रुक जाता है क्योंकि अनुरोध भेजते रहना ही थ्रॉटल को बनाए रखता है। कुछ मिनट प्रतीक्षा करें, फिर इसके साथ फिर से चलाएँ',
    ConcurrentRequestsWord: 'समवर्ती अनुरोध',
    SetTo1Or2InSettings: 'सेटिंग्स में 1 या 2 पर सेट करें।',
    ThrottledScanMessage: 'शेयरपॉइंट ने इस स्कैन को थ्रॉटल किया ({0} अनुरोध रेट-लिमिटेड और पुनः प्रयास किए गए)।',
    OfEverythingScannedPre: 'जो कुछ भी स्कैन किया गया उसमें से,',
    ItemCountSingular: '{0} आइटम',
    ItemCountPlural: '{0} आइटम',
    CouldNotBeConfirmedText: "पुनः प्रयास के बाद भी पुष्टि नहीं हो सकी (देखें कि कौन से आइटम में — नीचे दी गई \"पूरी तरह से पढ़ी नहीं जा सकी\" सूचना देखें) — यह विफलता क्षमता से संबंधित थी, न कि उनकी वास्तविक परमिशंस को दर्शाती है। इस रिपोर्ट में हर अन्य आइटम सफलतापूर्वक पढ़ा गया और उस पर भरोसा किया जा सकता है।",
    DespiteThrottlingText: 'थ्रॉटलिंग के बावजूद, पुनः प्रयास के बाद हर आइटम की सफलतापूर्वक पुष्टि हो गई, इसलिए यह रिपोर्ट पूर्ण है।',
    ForCleanRunPre: 'स्वच्छ रन के लिए, कुछ मिनट प्रतीक्षा करें और कम',
    ValueInSettingsPost: 'मान के साथ सेटिंग्स में फिर से स्कैन करें।',
    OneItemWord: '1 आइटम',
    NItemsWord: '{0} आइटम',
    OutOfScannedCouldNotBeRead: 'स्कैन किए गए {0} में से आपकी वर्तमान एक्सेस से पढ़े नहीं जा सके —',
    PermissionAssignmentsForItAreNotShown: ' इसके लिए परमिशन असाइनमेंट नहीं दिखाए गए हैं, ',
    PermissionAssignmentsForThoseAreNotShown: ' उनके लिए परमिशन असाइनमेंट नहीं दिखाए गए हैं, ',
    RestOfReportReadSuccessfully: 'लेकिन इस रिपोर्ट का बाकी हिस्सा सफलतापूर्वक पढ़ा गया। स्कैन को इस रूप में चलाएँ',
    RunScanAsSiteOwnerPre: 'स्कैन को इस रूप में चलाएँ',
    SiteOwnerWord: 'साइट ओनर',
    RunScanAsSiteOwnerPost: 'नीचे दिए गए अस्वीकृत आइटम के लिए पूर्ण विवरण देखने हेतु।',
    AndNMoreText: '…और {0} और',
    GroupExpansionSkippedPre: 'ग्रुप सदस्य विस्तार छोड़ दिया गया — यह',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'ग्राफ़ परमिशन इस टेनेंट में स्वीकृत नहीं की गई है। एक शेयरपॉइंट या ग्लोबल एडमिनिस्ट्रेटर इसे यहाँ स्वीकृत कर सकता है',
    SharePointAdminCenterPath: 'शेयरपॉइंट एडमिन सेंटर → एडवांस्ड → API एक्सेस',
    ScanIncompleteItemsMessage: "{0} आइटम एक अस्थायी त्रुटि (परमिशन समस्या नहीं) के कारण पूरी तरह से नहीं पढ़े जा सके और उन्हें उनके पैरेंट की परमिशंस के साथ बेस्ट-एफर्ट फ़ॉलबैक के रूप में दिखाया गया है — यह उनकी वास्तविक एक्सेस को नहीं दर्शा सकता। इन आइटम को फिर से जाँचने के लिए स्कैन को फिर से चलाएँ।",
    FilterByNamePathUserPlaceholder: 'नाम, पथ, या यूज़र/ग्रुप द्वारा फ़िल्टर करें…',
    FilterResultsLabel: 'परिणाम फ़िल्टर करें',
    ExternalUsersOnlyExtLabel: 'केवल बाहरी यूज़र (#ext#)',
    ShowingOfCount: '{1} में से {0} दिखाए जा रहे हैं',
    ScanResultsLabel: 'स्कैन परिणाम',
    PermissionsColumnHeader: 'परमिशंस',
    CollapsePermissionsLabel: 'परमिशंस संक्षिप्त करें',
    ExpandPermissionsLabel: 'परमिशंस विस्तृत करें',
    HiddenFromSearchBadge: 'खोज से छिपा हुआ',
    AssignmentCountSingular: '{0} असाइनमेंट',
    AssignmentCountPlural: '{0} असाइनमेंट',
    LoadMoreRemainingButton: 'और लोड करें ({0} शेष)',

    // User Access view
    LoadingUsersStatus: 'यूज़र लोड हो रहे हैं…',
    ConnectedUserSingular: 'कनेक्टेड — {0} यूज़र मिला',
    ConnectedUserPlural: 'कनेक्टेड — {0} यूज़र मिले',
    CheckingAccessForStatus: '{0} के लिए एक्सेस जाँची जा रही है…',
    FullSiteAccessDetectedStatus: 'पूर्ण साइट एक्सेस का पता चला।',
    AccessibleLocationsFoundSingular: '{0} एक्सेस योग्य स्थान मिला।',
    AccessibleLocationsFoundPlural: '{0} एक्सेस योग्य स्थान मिले।',
    NoAccessibleLocationsFoundStatus: 'कोई एक्सेस योग्य स्थान नहीं मिला।',
    UserAccessScanCompleteNotificationTitle: 'स्मार्ट परमिशंस — यूज़र एक्सेस स्कैन पूर्ण',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'नया स्कैन',
    NoUserAccessScansSavedYet: 'अभी तक कोई यूज़र एक्सेस स्कैन सहेजा नहीं गया है।',
    UserColumnHeader: 'यूज़र',
    LocationsColumnHeader: 'स्थान',
    FullControlBadge: 'फ़ुल कंट्रोल',
    DeleteThisRecordTitle: 'इस रिकॉर्ड को हटाएँ',
    SelectAUserFieldLabel: 'एक यूज़र चुनें',
    SearchUsersPlaceholder: 'यूज़र खोजें…',
    SelectAUserToCheckAccessLabel: 'एक्सेस जाँचने के लिए एक यूज़र चुनें',
    NotInThisSiteLabel: 'इस साइट में नहीं',
    ScanInProgressLabel: 'स्कैन प्रगति पर है',
    ScanningUserAccessLabel: 'यूज़र एक्सेस स्कैन किया जा रहा है',
    ScanningStatus: 'स्कैन किया जा रहा है…',
    FullControlAccessPre: 'इस यूज़र के पास है',
    FullControlWord: 'फ़ुल कंट्रोल',
    FullControlAccessPost: 'या ओनर-स्तर की एक्सेस पूरी साइट तक — सभी लाइब्रेरीज़ और फ़ोल्डर एक्सेस योग्य हैं।',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'साइट-स्तरीय परमिशन निर्धारित नहीं की जा सकी — यह साइट संभवतः Microsoft 365 ग्रुप एक्सेस का उपयोग करती है। इसे दिखाने के लिए, एक शेयरपॉइंट एडमिनिस्ट्रेटर को स्वीकृत करना होगा',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'परमिशन यहाँ',
    ShowingSiteLevelAccessOnlyPre: 'दिखाया जा रहा है',
    SiteLevelAccessOnlyWord: 'केवल साइट-स्तरीय एक्सेस',
    ShowingSiteLevelAccessOnlyMid: ', डिफ़ॉल्ट शेयरपॉइंट ग्रुप सदस्यता के आधार पर। लाइब्रेरीज़, फ़ोल्डर और फ़ाइलों पर यूनीक परमिशंस पढ़ी नहीं जा सकीं और दिखाई नहीं गई हैं। पूर्ण परिणामों के लिए, इस स्कैन को इस रूप में चलाएँ',
    UserAccessCouldNotBeDeterminedPre: "इस यूज़र की एक्सेस निर्धारित नहीं की जा सकी। परमिशन असाइनमेंट पढ़ने के लिए आवश्यक है",
    UserAccessCouldNotBeDeterminedPost: "राइट (साइट ओनर या उच्चतर), और यह यूज़र साइट के डिफ़ॉल्ट ओनर, मेंबर, या विज़िटर ग्रुप का सदस्य नहीं दिखता है।",
    SiteLevelAccessBannerPre: 'इस यूज़र के पास साइट-स्तरीय एक्सेस है। केवल वे स्थान जिनमें',
    UniquePermissionAssignmentsWord: 'यूनीक परमिशन असाइनमेंट',
    SiteLevelAccessBannerPost: 'नीचे दिखाई देते हैं — बाकी सारी सामग्री सूची के शीर्ष पर दिखाई गई साइट-स्तरीय परमिशन के माध्यम से एक्सेस योग्य है।',
    UserAccessResultsLabel: 'यूज़र एक्सेस परिणाम',
  };
});
