define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions konfiguráció',
    PropertyPane_GroupName: 'Általános',
    PropertyPane_DefaultViewLabel: 'Alapértelmezett nézet megnyitáskor',
    PropertyPane_View_Home: 'Kezdőlap',
    PropertyPane_View_Report: 'Jogosultsági jelentés',
    PropertyPane_View_Explorer: 'Jogosultság-felfedező',
    PropertyPane_View_UserAccess: 'Felhasználói hozzáférés',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/sajatoldal',
    ConnectButton: 'Csatlakozás',
    CancelButton: 'Mégse',
    ChangeUrlButton: 'URL módosítása',
    SettingsLabel: 'Beállítások',
    RenderErrorTitle: 'Smart Permissions — Megjelenítési hiba',
    RenderErrorMessageLabel: 'Üzenet:',
    RenderErrorStackLabel: 'Verem:',
    RenderErrorNoStack: '(verem nem érhető el)',
    BackButton: 'Vissza',
    BackToHomeLabel: 'Vissza a kezdőlapra',
    ExplorerCardTitle: 'Jogosultság-felfedező',
    ExplorerCardAlt: 'Jogosultság-felfedező mappafával és jogosultsági panellel',
    ExplorerCardDesc: 'Böngésszen bármely mappában vagy fájlban, és azonnal lássa, ki fér hozzá — valós idejű jogosultság-lekérdezésekkel.',
    ExplorerCardButton: 'Jogosultság-felfedező megnyitása',
    ReportCardTitle: 'Jogosultsági jelentés',
    ReportCardAlt: 'Jogosultsági jelentés konfigurációs képernyője',
    ReportCardDesc: 'Készítsen színkódolt Excel-jelentést a webhelyén található minden egyedi jogosultság-hozzárendelésről.',
    ReportCardButton: 'Jogosultsági jelentés futtatása',
    UserAccessCardTitle: 'Felhasználói hozzáférés',
    UserAccessCardAlt: 'Felhasználói hozzáférés képernyő, amely megjeleníti a kiválasztott felhasználó elérhető helyeit',
    UserAccessCardDesc: 'Keressen meg egy felhasználót, hogy lássa, mely helyekhez fér hozzá egy webhelyen, a pontos jogosultsági szinttel együtt.',
    UserAccessCardButton: 'Felhasználói hozzáférés ellenőrzése',
    SiteOwnerRequiredTitle: 'Webhelytulajdonosi hozzáférés szükséges —',
    SiteOwnerRequiredDesc: 'Ezek az eszközök webhelytulajdonosi hozzáférést igényelnek. Jogosultságokkal kapcsolatos kérdés esetén forduljon a webhely tulajdonosához.',
    HomeSubtitle: 'Ellenőrizze és értse meg a SharePoint jogosultságokat — PowerShell nélkül.',
    RequiresSiteOwnerTooltip: 'Webhelytulajdonosi hozzáférést igényel',
    HomeNoteLabel: 'Megjegyzés:',
    HomeNoteText: 'Ez a webrész az éppen bejelentkezett felhasználóként fut. Csak azokat a webhelyeket és elemeket látja, amelyekhez ennek a felhasználónak van jogosultsága. A teljes bérlői vizsgálathoz használjon olyan fiókot, amely minden webhelyhez megfelelő olvasási hozzáféréssel rendelkezik.',
    SettingsTitle: 'Beállítások',
    LibrariesSectionTitle: 'Könyvtárak',
    IncludeHiddenLabel: 'Rendszer- és rejtett könyvtárak belefoglalása',
    IncludeHiddenTooltip: 'Ha be van jelölve, tartalmazza a Stílusok könyvtárát, az Űrlapsablonokat, a Webhelyeszközöket és más, alapértelmezett nézetekből elrejtett könyvtárakat. Minden eszközre vonatkozik.',
    MoreInfoHiddenLibrariesLabel: 'További információ a rejtett könyvtárakról',
    ExcludeLimitedAccessLabel: 'Korlátozott hozzáférésű bejegyzések kizárása',
    ExcludeLimitedAccessTooltip: 'Elrejti azokat a felhasználókat és csoportokat, akiknek egyetlen SharePoint-jogosultsága a Korlátozott hozzáférés — ez automatikusan hozzárendelődik, amikor fájlokat linkeken keresztül osztanak meg. A Jogosultsági jelentésre, a Felfedezőre és a Felhasználói hozzáférésre vonatkozik.',
    MoreInfoLimitedAccessLabel: 'További információ a korlátozott hozzáférésről',
    ExcludeSharingLinksLabel: 'Megosztási hivatkozás bejegyzések kizárása',
    ExcludeSharingLinksTooltip: 'Elrejti a "SharingLinks.*" belső csoportokat, amelyeket a SharePoint automatikusan létrehoz a "Bárki, aki rendelkezik a hivatkozással" és a "Meghatározott személyek" megosztási hivatkozásokhoz. A Jogosultsági jelentésre, a Felfedezőre és a Felhasználói hozzáférésre vonatkozik.',
    MoreInfoSharingLinksLabel: 'További információ a megosztási hivatkozásokról',
    PerformanceSectionTitle: 'Teljesítmény',
    ConcurrentRequestsLabel: 'Egyidejű API-kérések:',
    ConcurrencyTooltip: 'Hány SharePoint API-kérés fut párhuzamosan a Jogosultsági jelentés, a Felhasználói hozzáférés vizsgálatai és a Felfedező háttérellenőrzései során. A magasabb értékek gyorsabbak, de nagyobb valószínűséggel váltanak ki korlátozást (HTTP 429). 3–5 ajánlott.',
    MoreInfoConcurrencyLabel: 'További információ az egyidejűségről',
    ConcurrencyHint: 'A magasabb értékek gyorsabban vizsgálnak, de SharePoint-korlátozást válthatnak ki. Ajánlott: 3–5.',
    GroupMemberCapLabel: 'Csoporttag-megjelenítési korlát:',
    GroupMemberCapTooltip: 'Csoportonként megjelenített tagok maximális száma, ha a "Csoporttagok kibontása" be van kapcsolva. A nagyobb csoportok korlátozva vannak, és megjelenik egy értesítés. Ennek növelése több memóriát használ.',
    MoreInfoGroupMemberCapLabel: 'További információ a csoporttag-korlátról',
    GroupMemberCapHint: 'Az ennél a korlátnál nagyobb csoportok csonkítási értesítést jelenítenek meg. Alapértelmezett: 500.',
    DefaultViewSectionTitle: 'Alapértelmezett nézet betöltéskor',
    DefaultViewInstructionsIntro: 'Ha meg szeretné változtatni, hogy melyik képernyő nyílik meg a webrész első betöltésekor, szerkessze a webrész tulajdonságait:',
    DefaultViewStep1Pre: 'Állítsa a SharePoint-oldalt',
    DefaultViewStep1Post: 'módba.',
    DefaultViewStep2Pre: 'Kattintson a',
    DefaultViewStep2Post: 'ikonra a Smart Permissions webrészen.',
    DefaultViewStep3Pre: 'A tulajdonságok panelen válasszon egy nézetet a',
    DefaultViewStep3Post: 'legördülő listából.',
    DefaultViewStep4Post: 'az oldalt a módosítás mentéséhez.',
    EditModeWord: 'Szerkesztés',
    PencilEditWord: 'ceruza (szerkesztés)',
    DefaultViewOnOpenWord: 'Alapértelmezett nézet megnyitáskor',
    RepublishWord: 'Publikálja újra',
    SiteOwnersLabel: 'Webhelytulajdonosok:',
    EveryoneClaimLabel: 'Mindenki',
    EveryoneExceptExternalClaimLabel: 'Mindenki, kivéve a külső felhasználókat',
    PermissionAssignmentsLabel: 'Jogosultság-hozzárendelések',
    UserGroupColumnHeader: 'Felhasználó / Csoport',
    TypeColumnHeader: 'Típus',
    PermissionLevelColumnHeader: 'Jogosultsági szint',
    TenantWideAccessSuffix: '— bérlő-szintű hozzáférés',
    SecurityGroupType: 'Biztonsági csoport',
    SpGroupType: 'SP-csoport',
    UserType: 'Felhasználó',
    CheckAccessForLabel: 'Hozzáférés ellenőrzése: {0}',
    ContainsUniqueAndExternalTooltip: 'Egyedi jogosultságú és külső felhasználói hozzáférésű elemeket tartalmaz',
    ContainsUniqueTooltip: 'Egyedi jogosultságú elemeket tartalmaz',
    ContainsExternalTooltip: 'Külső felhasználói hozzáférésű elemeket tartalmaz',
    UniqueBadge: 'Egyedi',
    ExternalAccessDetectedTooltip: 'Külső felhasználói hozzáférés észlelve',
    ConnectingStatus: 'Csatlakozás…',
    ConnectedLibrarySingular: 'Csatlakozva — {0} könyvtár található',
    ConnectedLibraryPlural: 'Csatlakozva — {0} könyvtár található',
    ConnectionFailedError: 'A csatlakozás sikertelen: {0}',
    LibraryEmptyStatus: 'Ez a könyvtár üres.',
    ErrorLoadingLibrary: 'Hiba a könyvtár betöltésekor: {0}',
    ErrorLoadingContents: 'Hiba a tartalom betöltésekor',
    LibraryFieldLabel: 'Könyvtár',
    HiddenFromSearchSuffix: '{0} (elrejtve a keresésből)',
    UniquePermissionsOnlyToggle: 'Csak egyedi jogosultságok',
    ExternalUsersOnlyToggle: 'Csak külső felhasználók',
    LegendLabel: 'Jelmagyarázat:',
    LegendItemHasUnique: 'Az elem egyedi jogosultságokkal rendelkezik',
    LegendContainsUniqueBelow: 'Egyedi jogosultságokat tartalmaz alább',
    LegendContainsExternalBelow: 'Külső felhasználói hozzáférést tartalmaz alább',
    LegendExternalOnItem: 'Külső felhasználói hozzáférés ezen az elemen',
    ViewingWithMemberAccessTitle: 'Megtekintés tag hozzáféréssel',
    ViewingWithMemberAccessDesc1: '— a jogosultság-hozzárendelések nem láthatók. Annak megtekintéséhez, hogy ki fér hozzá, szükséges a',
    ManagePermissionsWord: 'Jogosultságok kezelése',
    ViewingWithMemberAccessDesc2: 'jog (webhelytulajdonos vagy magasabb). Továbbra is láthatja, mely elemek öröklése szakadt meg a ↓ jelzők segítségével. Az elérhető helyek megtekintéséhez használja a',
    UserAccessWord: 'Felhasználói hozzáférés',
    ViewingWithMemberAccessDesc3: 'eszközt.',
    FoldersAndFilesLabel: 'Mappák és fájlok',
    SelectFolderOrFilePrompt: 'Válasszon egy mappát vagy fájlt a jogosultságainak megtekintéséhez.',
    UniquePermissionsBadge: 'Egyedi jogosultságok',
    InheritedBadge: 'Örökölt',
    ExpandGroupMembersLabel: 'Csoporttagok kibontása',
    ShowParentPermissionsLabel: 'Szülő jogosultságainak megjelenítése',
    InheritsFromParentText: 'Ez az elem örökli a jogosultságokat a szülő elemétől.',
    YourAccessLabel: 'Az Ön hozzáférése:',
    PermissionsNotVisibleNodeText: 'A jogosultság-hozzárendelések nem láthatók — a Jogosultságok kezelése jog (webhelytulajdonos vagy magasabb) szükséges annak megtekintéséhez, hogy ki fér hozzá ehhez az elemhez.',
    NoExternalUsersDirectAccessText: 'Egyetlen külső felhasználónak sincs közvetlen hozzáférése ehhez az elemhez.',
    InheritedFromLabel: 'Örökölve innen:',
    ParentPermissionsNotVisibleText: 'A szülő elem jogosultság-hozzárendelései nem láthatók — a Jogosultságok kezelése jogot igényli (webhelytulajdonos vagy magasabb).',
    NoPermissionsFoundOnParentText: 'A szülő elemen nem található jogosultság.',
    StartingScanStatus: 'Vizsgálat indítása…',
    ScanCancelledStatus: 'A vizsgálat megszakítva — {0} objektum gyűjtve a megszakítás előtt.',
    ScanCompleteStatus: 'A vizsgálat befejeződött — {0} objektum található, {1} egyedi jogosultsággal.',
    ScanCompleteNotificationTitle: 'Smart Permissions — A vizsgálat befejeződött',
    ScanCompleteNotificationBody: '{0} objektum, {1} egyedi jogosultsággal.',
    CancelledStatus: 'Megszakítva.',
    GenericErrorPrefix: 'Hiba: {0}',
    ExportErrorPrefix: 'Exportálási hiba: {0}',
    ScopeSiteOnly: 'Csak webhely',
    ScopeLibraries: 'Könyvtárak',
    ScopeFolders: 'Mappák',
    ScopeFilesAndFolders: 'Fájlok és mappák',
    ScanInProgressConfirm: 'Vizsgálat van folyamatban. Kilépés és megszakítás?',
    HistoryButton: 'Előzmények',
    BackToHistoryButton: 'Vissza az előzményekhez',
    ComparingLabel: 'Összehasonlítás',
    CompareMismatchWarning: 'Ezeket a jelentéseket eltérő webhelyekkel vagy vizsgálati beállításokkal készítették — az alábbi különbségek a módosított vizsgálati beállításokat tükrözhetik, nem a tényleges jogosultságváltozásokat.',
    NoPermissionDifferencesFound: 'Nem található jogosultsági különbség e két jelentés között.',
    PermissionChangesHeaderSingular: 'Jogosultságváltozások ({0} objektum)',
    PermissionChangesHeaderPlural: 'Jogosultságváltozások ({0} objektum)',
    ChangeColumnHeader: 'Változás',
    BeforeColumnHeader: 'Előtte',
    AfterColumnHeader: 'Utána',
    AddedBadge: 'Hozzáadva',
    RemovedBadge: 'Eltávolítva',
    ChangedBadge: 'Módosítva',
    InheritanceChangedHeader: 'Öröklés megváltozott ({0})',
    NameColumnHeader: 'Név',
    PathColumnHeader: 'Útvonal',
    NowColumnHeader: 'Most',
    UniqueInheritanceBrokenBadge: 'Egyedi (öröklés megszakadt)',
    InheritedRestoredBadge: 'Örökölt (visszaállítva)',
    NewObjectsHeader: 'Új objektumok',
    RemovedObjectsHeader: 'Eltávolított objektumok',
    BackToScanButton: 'Vissza a vizsgálathoz',
    CompareSelectedButton: 'Kijelöltek összehasonlítása',
    NoReportsSavedYet: 'Még nincsenek mentett jelentések.',
    SelectForCompareLabel: 'Kiválasztás összehasonlításhoz',
    DateTimeColumnHeader: 'Dátum / Idő',
    SiteColumnHeader: 'Webhely',
    ScopeColumnHeader: 'Hatókör',
    ObjectsColumnHeader: 'Objektumok',
    UniqueColumnHeader: 'Egyedi',
    SelectReportForCompareLabel: '{0} jelentés kiválasztása összehasonlításhoz',
    AllSitesPrefix: 'Minden webhely · ',
    PlusSubsitesSuffix: ' + alwebhelyek',
    ExportingStatus: 'Exportálás…',
    ExportButton: 'Exportálás',
    DeleteThisReportTitle: 'Jelentés törlése',
    ScanAllSiteCollectionsLabel: 'Az összes webhelygyűjtemény vizsgálata ebben a bérlőben (csak a gyökér webhelyen érhető el)',
    AllSitesSearchCaveat: 'A webhelylista a keresésből származik, és előfordulhat, hogy nem tartalmaz minden webhelygyűjteményt — nagyon nemrég létrehozott, vagy a keresési indexből kizárt webhelyek hiányozhatnak.',
    IncludeSubsitesLabel: 'Alwebhelyek belefoglalása (minden alwebhelyet megvizsgál ez alatt a webhely alatt)',
    ScanDepthFieldLabel: 'Vizsgálati mélység',
    FolderDepthLimitLabel: 'Mappamélység korlátja:',
    ExpandGroupMembersInReportLabel: 'Csoporttagok kibontása a jelentésben (SharePoint-csoportok, biztonsági csoportok és M365-csoportok)',
    LibrariesToScanLabel: 'Vizsgálandó könyvtárak',
    OfSelectedCount: '{0}/{1} kiválasztva',
    AllButton: 'Összes',
    NoneButton: 'Egyik sem',
    LoadingLibrariesStatus: 'Könyvtárak betöltése…',
    RunReportButton: 'Jelentés futtatása',
    ItemsFoundSoFar: 'Eddig {0} elem található',
    LibraryOfProgress: '{0}/{1} könyvtár',
    ScanCancelledPartialResults: 'Vizsgálat megszakítva — részleges eredmények',
    ScanCompleteLabel: 'Vizsgálat befejezve',
    ObjectsCountBadge: '{0} objektum',
    UniqueCountBadge: '{0} egyedi',
    InheritedCountBadge: '{0} örökölt',
    GeneratingExcelStatus: 'Excel generálása…',
    ExportFilteredRowsButton: '{0} szűrt sor exportálása',
    ExportToExcelButton: 'Exportálás Excelbe',
    ExportToCsvButton: 'Exportálás CSV-be',
    ScanStoppedEarlyTitle: 'A vizsgálat idő előtt leállt — a SharePoint korlátozza ezt a bérlőt.',
    SiteCollectionsScannedBeforeStopping: 'Leállás előtt {0}/{1} webhelygyűjtemény lett megvizsgálva. ',
    ResultsBelowCoverOnlyPre: 'Az alábbi eredmények csak a megvizsgáltakat fedik le, és',
    NotWord: 'nem',
    ResultsBelowCoverOnlyPost: 'teljes körű ellenőrzés. A vizsgálat ebben a helyzetben magától leáll, mert a kérések folyamatos küldése tartja fenn a korlátozást. Várjon néhány percet, majd futtassa újra a következővel:',
    ConcurrentRequestsWord: 'Egyidejű kérések',
    SetTo1Or2InSettings: '1-re vagy 2-re állítva a Beállításokban.',
    ThrottledScanMessage: 'A SharePoint korlátozta ezt a vizsgálatot ({0} kérés lett sebességkorlátozva és megismételve).',
    OfEverythingScannedPre: 'A megvizsgáltak közül',
    ItemCountSingular: '{0} elemet',
    ItemCountPlural: '{0} elemet',
    CouldNotBeConfirmedText: 'nem sikerült megerősíteni az újrapróbálkozás után (lásd alább a "nem sikerült teljesen beolvasni" értesítést a pontos részletekért) — ez a hiba kapacitással kapcsolatos volt, nem a tényleges jogosultságaikat tükrözi. A jelentés összes többi eleme sikeresen beolvasásra került, és megbízható.',
    DespiteThrottlingText: 'A korlátozás ellenére minden elem sikeresen megerősítésre került az újrapróbálkozás után, így ez a jelentés teljes.',
    ForCleanRunPre: 'A tiszta futtatáshoz várjon néhány percet, majd vizsgáljon újra alacsonyabb értékkel az alábbihoz:',
    ValueInSettingsPost: 'a Beállításokban.',
    OneItemWord: '1 elemet',
    NItemsWord: '{0} elemet',
    OutOfScannedCouldNotBeRead: 'a {0} megvizsgáltból nem sikerült beolvasni az Ön jelenlegi hozzáférésével —',
    PermissionAssignmentsForItAreNotShown: ' a jogosultság-hozzárendelések nem jelennek meg, ',
    PermissionAssignmentsForThoseAreNotShown: ' a jogosultság-hozzárendelések nem jelennek meg, ',
    RestOfReportReadSuccessfully: 'de a jelentés többi része sikeresen beolvasásra került.',
    RunScanAsSiteOwnerPre: 'Futtassa a vizsgálatot',
    SiteOwnerWord: 'webhelytulajdonosként',
    RunScanAsSiteOwnerPost: 'a lenti elutasított elemek teljes részleteinek megtekintéséhez.',
    AndNMoreText: '…és még {0}',
    GroupExpansionSkippedPre: 'A csoporttagok kibontása kimaradt — a Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'jogosultságot nem hagyták jóvá ebben a bérlőben. Egy SharePoint- vagy globális rendszergazda jóváhagyhatja itt:',
    SharePointAdminCenterPath: 'SharePoint Felügyeleti Központ → Speciális → API-hozzáférés',
    ScanIncompleteItemsMessage: '{0} elemet nem sikerült teljesen beolvasni átmeneti hiba miatt (nem jogosultsági probléma), és a szülő elem jogosultságaival jelennek meg tartalék megoldásként — ez esetleg nem tükrözi a tényleges hozzáférésüket. Futtassa újra a vizsgálatot ezen elemek újbóli megkísérléséhez.',
    FilterByNamePathUserPlaceholder: 'Szűrés név, útvonal vagy felhasználó/csoport szerint…',
    FilterResultsLabel: 'Eredmények szűrése',
    ExternalUsersOnlyExtLabel: 'Csak külső felhasználók (#ext#)',
    ShowingOfCount: '{0}/{1} megjelenítve',
    ScanResultsLabel: 'Vizsgálati eredmények',
    PermissionsColumnHeader: 'Jogosultságok',
    CollapsePermissionsLabel: 'Jogosultságok összecsukása',
    ExpandPermissionsLabel: 'Jogosultságok kibontása',
    HiddenFromSearchBadge: 'Elrejtve a keresésből',
    AssignmentCountSingular: '{0} hozzárendelés',
    AssignmentCountPlural: '{0} hozzárendelés',
    LoadMoreRemainingButton: 'Továbbiak betöltése ({0} hátravan)',
    LoadingUsersStatus: 'Felhasználók betöltése…',
    ConnectedUserSingular: 'Csatlakozva — {0} felhasználó található',
    ConnectedUserPlural: 'Csatlakozva — {0} felhasználó található',
    CheckingAccessForStatus: 'Hozzáférés ellenőrzése: {0}…',
    FullSiteAccessDetectedStatus: 'Teljes webhely-hozzáférés észlelve.',
    AccessibleLocationsFoundSingular: '{0} elérhető hely található.',
    AccessibleLocationsFoundPlural: '{0} elérhető hely található.',
    NoAccessibleLocationsFoundStatus: 'Nem található elérhető hely.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Felhasználói hozzáférés-vizsgálat befejeződött',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Új vizsgálat',
    NoUserAccessScansSavedYet: 'Még nincsenek mentett felhasználói hozzáférés-vizsgálatok.',
    UserColumnHeader: 'Felhasználó',
    LocationsColumnHeader: 'Helyek',
    FullControlBadge: 'Teljes felügyelet',
    DeleteThisRecordTitle: 'Rekord törlése',
    SelectAUserFieldLabel: 'Válasszon felhasználót',
    SearchUsersPlaceholder: 'Felhasználók keresése…',
    SelectAUserToCheckAccessLabel: 'Válasszon felhasználót a hozzáférés ellenőrzéséhez',
    NotInThisSiteLabel: 'Nincs ezen a webhelyen',
    ScanInProgressLabel: 'Vizsgálat folyamatban',
    ScanningUserAccessLabel: 'Felhasználói hozzáférés vizsgálata',
    ScanningStatus: 'Vizsgálat…',
    FullControlAccessPre: 'Ez a felhasználó rendelkezik',
    FullControlWord: 'Teljes felügyelettel',
    FullControlAccessPost: 'vagy tulajdonosi szintű hozzáféréssel az egész webhelyhez — minden könyvtár és mappa elérhető.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'A webhelyszintű jogosultságot nem sikerült megállapítani — ez a webhely valószínűleg Microsoft 365-csoport hozzáférést használ. Ennek megjelenítéséhez egy SharePoint-rendszergazdának jóvá kell hagynia a',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph-jogosultságot itt:',
    ShowingSiteLevelAccessOnlyPre: 'Csak a',
    SiteLevelAccessOnlyWord: 'webhelyszintű hozzáférés',
    ShowingSiteLevelAccessOnlyMid: 'jelenik meg, az alapértelmezett SharePoint-csoporttagság alapján. A könyvtárakon, mappákon és fájlokon lévő egyedi jogosultságokat nem sikerült beolvasni, ezért nem jelennek meg. A teljes eredményekért futtassa ezt a vizsgálatot',
    UserAccessCouldNotBeDeterminedPre: 'Ennek a felhasználónak a hozzáférését nem sikerült megállapítani. A jogosultság-hozzárendelések beolvasásához a',
    UserAccessCouldNotBeDeterminedPost: 'jog szükséges (webhelytulajdonos vagy magasabb), és úgy tűnik, ez a felhasználó nem tagja a webhely alapértelmezett Tulajdonosok, Tagok vagy Látogatók csoportjainak.',
    SiteLevelAccessBannerPre: 'Ez a felhasználó webhelyszintű hozzáféréssel rendelkezik. Csak a',
    UniquePermissionAssignmentsWord: 'egyedi jogosultság-hozzárendelésekkel',
    SiteLevelAccessBannerPost: 'rendelkező helyek jelennek meg alább — minden más tartalom a lista tetején látható webhelyszintű jogosultságon keresztül érhető el.',
    UserAccessResultsLabel: 'Felhasználói hozzáférés eredményei',
  };
});
