define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Konfigurasi Smart Permissions',
    PropertyPane_GroupName: 'Umum',
    PropertyPane_DefaultViewLabel: 'Tampilan default saat dibuka',
    PropertyPane_View_Home: 'Beranda',
    PropertyPane_View_Report: 'Laporan Izin',
    PropertyPane_View_Explorer: 'Penjelajah Izin',
    PropertyPane_View_UserAccess: 'Akses Pengguna',

    // App shell
    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: 'Hubungkan',
    CancelButton: 'Batal',
    ChangeUrlButton: 'Ubah URL',
    SettingsLabel: 'Pengaturan',
    RenderErrorTitle: 'Smart Permissions — Kesalahan Render',
    RenderErrorMessageLabel: 'Pesan:',
    RenderErrorStackLabel: 'Stack:',
    RenderErrorNoStack: '(stack tidak tersedia)',
    BackButton: 'Kembali',
    BackToHomeLabel: 'Kembali ke beranda',

    // Home view
    ExplorerCardTitle: 'Penjelajah Izin',
    ExplorerCardAlt: 'Penjelajah Izin dengan pohon folder dan panel izin',
    ExplorerCardDesc: 'Jelajahi folder atau file mana pun dan langsung lihat siapa yang memiliki akses — dengan pencarian izin secara langsung dan real-time.',
    ExplorerCardButton: 'Buka Penjelajah Izin',
    ReportCardTitle: 'Laporan Izin',
    ReportCardAlt: 'Layar konfigurasi Laporan Izin',
    ReportCardDesc: 'Hasilkan laporan Excel berkode warna untuk setiap penetapan izin unik di seluruh situs Anda.',
    ReportCardButton: 'Jalankan Laporan Izin',
    UserAccessCardTitle: 'Akses Pengguna',
    UserAccessCardAlt: 'Layar Akses Pengguna yang menampilkan lokasi yang dapat diakses untuk pengguna terpilih',
    UserAccessCardDesc: 'Cari pengguna mana pun untuk melihat setiap lokasi yang dapat mereka akses di suatu situs, beserta tingkat izin pastinya.',
    UserAccessCardButton: 'Periksa Akses Pengguna',
    SiteOwnerRequiredTitle: 'Diperlukan akses Pemilik Situs —',
    SiteOwnerRequiredDesc: 'Alat ini memerlukan akses Pemilik Situs. Hubungi pemilik situs jika Anda memiliki pertanyaan tentang izin.',
    HomeSubtitle: 'Audit dan pahami izin SharePoint — tanpa perlu PowerShell.',
    RequiresSiteOwnerTooltip: 'Memerlukan akses Pemilik Situs',
    HomeNoteLabel: 'Catatan:',
    HomeNoteText: 'Web part ini berjalan sebagai pengguna yang sedang masuk. Web part hanya dapat melihat situs dan item yang diizinkan untuk dilihat pengguna tersebut. Untuk pemindaian tenant secara penuh, gunakan akun dengan akses baca yang sesuai di semua situs.',

    // Settings view
    SettingsTitle: 'Pengaturan',
    LibrariesSectionTitle: 'Pustaka',
    IncludeHiddenLabel: 'Sertakan pustaka sistem dan tersembunyi',
    IncludeHiddenTooltip: 'Jika dicentang, menyertakan Style Library, Form Templates, Site Assets, dan pustaka lain yang disembunyikan dari tampilan default. Berlaku untuk semua alat.',
    MoreInfoHiddenLibrariesLabel: 'Info lebih lanjut tentang pustaka tersembunyi',
    ExcludeLimitedAccessLabel: 'Kecualikan entri Limited Access',
    ExcludeLimitedAccessTooltip: 'Menyembunyikan pengguna dan grup yang izin SharePoint-nya hanya Limited Access — yang secara otomatis diberikan saat file dibagikan melalui tautan. Berlaku untuk Laporan Izin, Penjelajah, dan Akses Pengguna.',
    MoreInfoLimitedAccessLabel: 'Info lebih lanjut tentang Limited Access',
    ExcludeSharingLinksLabel: 'Kecualikan entri Sharing Links',
    ExcludeSharingLinksTooltip: 'Menyembunyikan grup internal "SharingLinks.*" yang secara otomatis dibuat SharePoint untuk tautan berbagi "Semua orang dengan tautan ini" dan "Orang tertentu". Berlaku untuk Laporan Izin, Penjelajah, dan Akses Pengguna.',
    MoreInfoSharingLinksLabel: 'Info lebih lanjut tentang Sharing Links',
    PerformanceSectionTitle: 'Performa',
    ConcurrentRequestsLabel: 'Permintaan API bersamaan:',
    ConcurrencyTooltip: 'Berapa banyak permintaan API SharePoint yang berjalan secara paralel selama pemindaian Laporan Izin, pemindaian Akses Pengguna, dan pemeriksaan latar belakang Penjelajah. Nilai lebih tinggi lebih cepat tetapi lebih mungkin memicu pembatasan (HTTP 429). Disarankan 3–5.',
    MoreInfoConcurrencyLabel: 'Info lebih lanjut tentang konkurensi',
    ConcurrencyHint: 'Nilai lebih tinggi memindai lebih cepat tetapi dapat memicu pembatasan SharePoint. Disarankan: 3–5.',
    GroupMemberCapLabel: 'Batas tampilan anggota grup:',
    GroupMemberCapTooltip: "Jumlah maksimum anggota yang ditampilkan per grup ketika 'Perluas anggota grup' diaktifkan. Grup yang lebih besar akan dibatasi dan pemberitahuan akan ditampilkan. Menaikkan nilai ini menggunakan lebih banyak memori.",
    MoreInfoGroupMemberCapLabel: 'Info lebih lanjut tentang batas anggota grup',
    GroupMemberCapHint: 'Grup yang lebih besar dari batas ini menampilkan pemberitahuan pemotongan. Default: 500.',
    DefaultViewSectionTitle: 'Tampilan default saat dimuat',
    DefaultViewInstructionsIntro: 'Untuk mengubah layar mana yang terbuka saat web part pertama kali dimuat, edit properti web part:',
    DefaultViewStep1Pre: 'Masukkan halaman SharePoint ke mode',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Klik ikon',
    DefaultViewStep2Post: 'pada web part Smart Permissions.',
    DefaultViewStep3Pre: 'Pada panel properti, pilih tampilan dari dropdown',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'halaman untuk menyimpan perubahan.',
    EditModeWord: 'Edit',
    PencilEditWord: 'pensil (edit)',
    DefaultViewOnOpenWord: 'Tampilan default saat dibuka',
    RepublishWord: 'Terbitkan ulang',

    // Shared
    SiteOwnersLabel: 'Pemilik Situs:',
    EveryoneClaimLabel: 'Semua orang',
    EveryoneExceptExternalClaimLabel: 'Semua orang kecuali pengguna eksternal',
    PermissionAssignmentsLabel: 'Penetapan izin',
    UserGroupColumnHeader: 'Pengguna / Grup',
    TypeColumnHeader: 'Tipe',
    PermissionLevelColumnHeader: 'Tingkat Izin',
    TenantWideAccessSuffix: '— akses seluruh tenant',
    SecurityGroupType: 'Grup Keamanan',
    SpGroupType: 'Grup SP',
    UserType: 'Pengguna',
    CheckAccessForLabel: 'Periksa akses untuk {0}',

    // Explorer view
    ContainsUniqueAndExternalTooltip: 'Berisi item dengan izin unik dan akses pengguna eksternal',
    ContainsUniqueTooltip: 'Berisi item dengan izin unik',
    ContainsExternalTooltip: 'Berisi item dengan akses pengguna eksternal',
    UniqueBadge: 'Unik',
    ExternalAccessDetectedTooltip: 'Akses pengguna eksternal terdeteksi',
    ConnectingStatus: 'Menghubungkan…',
    ConnectedLibrarySingular: 'Terhubung — {0} pustaka ditemukan',
    ConnectedLibraryPlural: 'Terhubung — {0} pustaka ditemukan',
    ConnectionFailedError: 'Koneksi gagal: {0}',
    LibraryEmptyStatus: 'Pustaka ini kosong.',
    ErrorLoadingLibrary: 'Kesalahan memuat pustaka: {0}',
    ErrorLoadingContents: 'Kesalahan memuat konten',
    LibraryFieldLabel: 'Pustaka',
    HiddenFromSearchSuffix: '{0} (disembunyikan dari pencarian)',
    UniquePermissionsOnlyToggle: 'Hanya izin unik',
    ExternalUsersOnlyToggle: 'Hanya pengguna eksternal',
    LegendLabel: 'Keterangan:',
    LegendItemHasUnique: 'Item memiliki izin unik',
    LegendContainsUniqueBelow: 'Berisi izin unik di bawah',
    LegendContainsExternalBelow: 'Berisi akses pengguna eksternal di bawah',
    LegendExternalOnItem: 'Akses pengguna eksternal pada item ini',
    ViewingWithMemberAccessTitle: 'Melihat dengan akses Member',
    ViewingWithMemberAccessDesc1: '— penetapan izin tidak terlihat. Untuk melihat siapa yang memiliki akses diperlukan hak',
    ManagePermissionsWord: 'Manage Permissions',
    ViewingWithMemberAccessDesc2: '(Site Owner atau lebih tinggi). Anda tetap dapat melihat item mana yang memutus pewarisan menggunakan indikator ↓. Untuk melihat lokasi yang dapat Anda akses, gunakan alat',
    UserAccessWord: 'Akses Pengguna',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Folder dan file',
    SelectFolderOrFilePrompt: 'Pilih folder atau file untuk melihat izinnya.',
    UniquePermissionsBadge: 'Izin unik',
    InheritedBadge: 'Diwariskan',
    ExpandGroupMembersLabel: 'Perluas anggota grup',
    ShowParentPermissionsLabel: 'Tampilkan izin induk',
    InheritsFromParentText: 'Item ini mewarisi izin dari induknya.',
    YourAccessLabel: 'Akses Anda:',
    PermissionsNotVisibleNodeText: 'Penetapan izin tidak terlihat — hak Manage Permissions (Site Owner atau lebih tinggi) diperlukan untuk melihat siapa yang memiliki akses ke item ini.',
    NoExternalUsersDirectAccessText: 'Tidak ada pengguna eksternal yang memiliki akses langsung ke item ini.',
    InheritedFromLabel: 'Diwariskan dari:',
    ParentPermissionsNotVisibleText: 'Penetapan izin induk tidak terlihat — memerlukan hak Manage Permissions (Site Owner atau lebih tinggi).',
    NoPermissionsFoundOnParentText: 'Tidak ditemukan izin pada induk.',

    // Report view
    StartingScanStatus: 'Memulai pemindaian…',
    ScanCancelledStatus: 'Pemindaian dibatalkan — {0} objek terkumpul sebelum dibatalkan.',
    ScanCompleteStatus: 'Pemindaian selesai — {0} objek ditemukan, {1} dengan izin unik.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Pemindaian selesai',
    ScanCompleteNotificationBody: '{0} objek, {1} dengan izin unik.',
    CancelledStatus: 'Dibatalkan.',
    GenericErrorPrefix: 'Kesalahan: {0}',
    ExportErrorPrefix: 'Kesalahan ekspor: {0}',
    ScopeSiteOnly: 'Hanya situs',
    ScopeLibraries: 'Pustaka',
    ScopeFolders: 'Folder',
    ScopeFilesAndFolders: 'File & Folder',
    ScanInProgressConfirm: 'Pemindaian sedang berlangsung. Keluar dan batalkan?',
    HistoryButton: 'Riwayat',
    BackToHistoryButton: 'Kembali ke riwayat',
    ComparingLabel: 'Membandingkan',
    CompareMismatchWarning: 'Laporan ini diambil dengan situs atau opsi pemindaian yang berbeda — perbedaan di bawah mungkin mencerminkan perubahan pengaturan pemindaian, bukan perubahan izin yang sebenarnya.',
    NoPermissionDifferencesFound: 'Tidak ditemukan perbedaan izin antara kedua laporan ini.',
    PermissionChangesHeaderSingular: 'Perubahan izin ({0} objek)',
    PermissionChangesHeaderPlural: 'Perubahan izin ({0} objek)',
    ChangeColumnHeader: 'Perubahan',
    BeforeColumnHeader: 'Sebelum',
    AfterColumnHeader: 'Sesudah',
    AddedBadge: 'Ditambahkan',
    RemovedBadge: 'Dihapus',
    ChangedBadge: 'Diubah',
    InheritanceChangedHeader: 'Pewarisan berubah ({0})',
    NameColumnHeader: 'Nama',
    PathColumnHeader: 'Jalur',
    NowColumnHeader: 'Sekarang',
    UniqueInheritanceBrokenBadge: 'Unik (pewarisan terputus)',
    InheritedRestoredBadge: 'Diwariskan (dipulihkan)',
    NewObjectsHeader: 'Objek baru',
    RemovedObjectsHeader: 'Objek yang dihapus',
    BackToScanButton: 'Kembali ke pemindaian',
    CompareSelectedButton: 'Bandingkan yang dipilih',
    NoReportsSavedYet: 'Belum ada laporan yang disimpan.',
    SelectForCompareLabel: 'Pilih untuk dibandingkan',
    DateTimeColumnHeader: 'Tanggal / Waktu',
    SiteColumnHeader: 'Situs',
    ScopeColumnHeader: 'Cakupan',
    ObjectsColumnHeader: 'Objek',
    UniqueColumnHeader: 'Unik',
    SelectReportForCompareLabel: 'Pilih laporan dari {0} untuk dibandingkan',
    AllSitesPrefix: 'Semua situs · ',
    PlusSubsitesSuffix: ' + subsitus',
    ExportingStatus: 'Mengekspor…',
    ExportButton: 'Ekspor',
    DeleteThisReportTitle: 'Hapus laporan ini',
    ScanAllSiteCollectionsLabel: 'Pindai semua koleksi situs di tenant ini (hanya tersedia di situs root)',
    AllSitesSearchCaveat: 'Daftar situs berasal dari pencarian dan mungkin tidak menyertakan semua koleksi situs — situs yang baru saja dibuat, atau situs yang dikecualikan dari indeks pencarian, dapat terlewat.',
    IncludeSubsitesLabel: 'Sertakan subsitus (memindai setiap subsitus di bawah situs ini)',
    ScanDepthFieldLabel: 'Kedalaman pemindaian',
    FolderDepthLimitLabel: 'Batas kedalaman folder:',
    ExpandGroupMembersInReportLabel: 'Perluas anggota grup dalam laporan (grup SharePoint, Grup Keamanan, dan grup M365)',
    LibrariesToScanLabel: 'Pustaka yang akan dipindai',
    OfSelectedCount: '{0} dari {1} dipilih',
    AllButton: 'Semua',
    NoneButton: 'Tidak ada',
    LoadingLibrariesStatus: 'Memuat pustaka…',
    RunReportButton: 'Jalankan Laporan',
    ItemsFoundSoFar: '{0} item ditemukan sejauh ini',
    LibraryOfProgress: 'Pustaka {0} dari {1}',
    ScanCancelledPartialResults: 'Pemindaian dibatalkan — hasil sebagian',
    ScanCompleteLabel: 'Pemindaian selesai',
    ObjectsCountBadge: '{0} objek',
    UniqueCountBadge: '{0} unik',
    InheritedCountBadge: '{0} diwariskan',
    GeneratingExcelStatus: 'Membuat Excel…',
    ExportFilteredRowsButton: 'Ekspor {0} baris terfilter',
    ExportToExcelButton: 'Ekspor ke Excel',
    ExportToCsvButton: 'Ekspor ke CSV',
    ScanStoppedEarlyTitle: 'Pemindaian dihentikan lebih awal — SharePoint sedang membatasi tenant ini.',
    SiteCollectionsScannedBeforeStopping: '{0} dari {1} koleksi situs telah dipindai sebelum berhenti. ',
    ResultsBelowCoverOnlyPre: 'Hasil di bawah ini hanya mencakup apa yang telah dipindai dan',
    NotWord: 'bukan',
    ResultsBelowCoverOnlyPost: 'merupakan audit yang lengkap. Pemindaian berhenti sendiri dalam situasi ini karena terus mengirim permintaan justru mempertahankan pembatasan tersebut. Tunggu beberapa menit, lalu jalankan ulang dengan',
    ConcurrentRequestsWord: 'Permintaan bersamaan',
    SetTo1Or2InSettings: 'diatur ke 1 atau 2 di Pengaturan.',
    ThrottledScanMessage: 'SharePoint membatasi pemindaian ini ({0} permintaan dibatasi tarifnya dan dicoba ulang).',
    OfEverythingScannedPre: 'Dari semua yang dipindai,',
    ItemCountSingular: '{0} item',
    ItemCountPlural: '{0} item',
    CouldNotBeConfirmedText: 'tidak dapat dikonfirmasi setelah dicoba ulang (lihat pemberitahuan "tidak dapat dibaca sepenuhnya" di bawah untuk mengetahui secara pasti item mana) — kegagalan tersebut terkait kapasitas, bukan cerminan izin sebenarnya. Setiap item lain dalam laporan ini berhasil dibaca dan dapat dipercaya.',
    DespiteThrottlingText: 'Meskipun ada pembatasan, setiap item tetap berhasil dikonfirmasi setelah dicoba ulang, sehingga laporan ini lengkap.',
    ForCleanRunPre: 'Untuk hasil yang bersih, tunggu beberapa menit dan pindai ulang dengan nilai',
    ValueInSettingsPost: 'yang lebih rendah di Pengaturan.',
    OneItemWord: '1 item',
    NItemsWord: '{0} item',
    OutOfScannedCouldNotBeRead: 'dari {0} yang dipindai tidak dapat dibaca dengan akses Anda saat ini —',
    PermissionAssignmentsForItAreNotShown: ' penetapan izin untuknya tidak ditampilkan, ',
    PermissionAssignmentsForThoseAreNotShown: ' penetapan izin untuk item tersebut tidak ditampilkan, ',
    RestOfReportReadSuccessfully: 'tetapi sisa laporan ini berhasil dibaca. Jalankan pemindaian sebagai',
    RunScanAsSiteOwnerPre: 'Jalankan pemindaian sebagai',
    SiteOwnerWord: 'Site Owner',
    RunScanAsSiteOwnerPost: 'untuk melihat detail lengkap item yang ditolak di bawah.',
    AndNMoreText: '…dan {0} lainnya',
    GroupExpansionSkippedPre: 'Perluasan anggota grup dilewati — izin Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'belum disetujui di tenant ini. Administrator SharePoint atau Global dapat menyetujuinya di',
    SharePointAdminCenterPath: 'SharePoint Admin Center → Advanced → API access',
    ScanIncompleteItemsMessage: '{0} item tidak dapat dibaca sepenuhnya karena kesalahan sementara (bukan masalah izin) dan ditampilkan dengan izin induknya sebagai upaya terbaik — ini mungkin tidak mencerminkan akses sebenarnya. Jalankan ulang pemindaian untuk mencoba item ini kembali.',
    FilterByNamePathUserPlaceholder: 'Filter berdasarkan nama, jalur, atau pengguna/grup…',
    FilterResultsLabel: 'Filter hasil',
    ExternalUsersOnlyExtLabel: 'Hanya pengguna eksternal (#ext#)',
    ShowingOfCount: 'Menampilkan {0} dari {1}',
    ScanResultsLabel: 'Hasil pemindaian',
    PermissionsColumnHeader: 'Izin',
    CollapsePermissionsLabel: 'Ciutkan izin',
    ExpandPermissionsLabel: 'Perluas izin',
    HiddenFromSearchBadge: 'Disembunyikan dari pencarian',
    AssignmentCountSingular: '{0} penetapan',
    AssignmentCountPlural: '{0} penetapan',
    LoadMoreRemainingButton: 'Muat lebih banyak ({0} tersisa)',

    // User Access view
    LoadingUsersStatus: 'Memuat pengguna…',
    ConnectedUserSingular: 'Terhubung — {0} pengguna ditemukan',
    ConnectedUserPlural: 'Terhubung — {0} pengguna ditemukan',
    CheckingAccessForStatus: 'Memeriksa akses untuk {0}…',
    FullSiteAccessDetectedStatus: 'Akses situs penuh terdeteksi.',
    AccessibleLocationsFoundSingular: '{0} lokasi yang dapat diakses ditemukan.',
    AccessibleLocationsFoundPlural: '{0} lokasi yang dapat diakses ditemukan.',
    NoAccessibleLocationsFoundStatus: 'Tidak ada lokasi yang dapat diakses ditemukan.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Pemindaian Akses Pengguna selesai',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Pemindaian baru',
    NoUserAccessScansSavedYet: 'Belum ada pemindaian akses pengguna yang disimpan.',
    UserColumnHeader: 'Pengguna',
    LocationsColumnHeader: 'Lokasi',
    FullControlBadge: 'Full Control',
    DeleteThisRecordTitle: 'Hapus rekam ini',
    SelectAUserFieldLabel: 'Pilih pengguna',
    SearchUsersPlaceholder: 'Cari pengguna…',
    SelectAUserToCheckAccessLabel: 'Pilih pengguna untuk memeriksa akses',
    NotInThisSiteLabel: 'Tidak ada di situs ini',
    ScanInProgressLabel: 'Pemindaian sedang berlangsung',
    ScanningUserAccessLabel: 'Memindai akses pengguna',
    ScanningStatus: 'Memindai…',
    FullControlAccessPre: 'Pengguna ini memiliki',
    FullControlWord: 'Full Control',
    FullControlAccessPost: 'atau akses setingkat Owner ke seluruh situs — semua pustaka dan folder dapat diakses.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Izin tingkat situs tidak dapat ditentukan — situs ini kemungkinan menggunakan akses Microsoft 365 Group. Untuk menampilkannya, Administrator SharePoint harus menyetujui izin',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'di',
    ShowingSiteLevelAccessOnlyPre: 'Menampilkan',
    SiteLevelAccessOnlyWord: 'hanya akses tingkat situs',
    ShowingSiteLevelAccessOnlyMid: ', berdasarkan keanggotaan grup SharePoint default. Izin unik pada pustaka, folder, dan file tidak dapat dibaca dan tidak ditampilkan. Untuk hasil lengkap, jalankan pemindaian ini sebagai',
    UserAccessCouldNotBeDeterminedPre: 'Akses pengguna ini tidak dapat ditentukan. Membaca penetapan izin memerlukan hak',
    UserAccessCouldNotBeDeterminedPost: '(Site Owner atau lebih tinggi), dan pengguna ini tampaknya bukan anggota grup Owner, Member, atau Visitor default situs.',
    SiteLevelAccessBannerPre: 'Pengguna ini memiliki akses tingkat situs. Hanya lokasi dengan',
    UniquePermissionAssignmentsWord: 'penetapan izin unik',
    SiteLevelAccessBannerPost: 'yang muncul di bawah — semua konten lainnya dapat diakses melalui izin tingkat situs yang ditampilkan di bagian atas daftar.',
    UserAccessResultsLabel: 'Hasil akses pengguna',
  };
});
