define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Configurazione di Smart Permissions',
    PropertyPane_GroupName: 'Generale',
    PropertyPane_DefaultViewLabel: 'Vista predefinita all\'apertura',
    PropertyPane_View_Home: 'Home',
    PropertyPane_View_Report: 'Report permessi',
    PropertyPane_View_Explorer: 'Esplora permessi',
    PropertyPane_View_UserAccess: 'Accesso utente',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/miosito',
    ConnectButton: 'Connetti',
    CancelButton: 'Annulla',
    ChangeUrlButton: 'Cambia URL',
    SettingsLabel: 'Impostazioni',
    RenderErrorTitle: 'Smart Permissions — Errore di rendering',
    RenderErrorMessageLabel: 'Messaggio:',
    RenderErrorStackLabel: 'Stack:',
    RenderErrorNoStack: '(stack non disponibile)',
    BackButton: 'Indietro',
    BackToHomeLabel: 'Torna alla home',
    ExplorerCardTitle: 'Esplora permessi',
    ExplorerCardAlt: 'Esplora permessi con albero cartelle e pannello permessi',
    ExplorerCardDesc: 'Sfoglia qualsiasi cartella o file e scopri subito chi ha accesso, con ricerche di permessi in tempo reale.',
    ExplorerCardButton: 'Apri Esplora permessi',
    ReportCardTitle: 'Report permessi',
    ReportCardAlt: 'Schermata di configurazione del report permessi',
    ReportCardDesc: 'Genera un report Excel a colori di ogni assegnazione di permesso univoco nel tuo sito.',
    ReportCardButton: 'Esegui report permessi',
    UserAccessCardTitle: 'Accesso utente',
    UserAccessCardAlt: 'Schermata di accesso utente che mostra le posizioni accessibili per un utente selezionato',
    UserAccessCardDesc: 'Cerca un utente per vedere ogni posizione a cui può accedere in un sito, con il suo livello di permesso esatto.',
    UserAccessCardButton: 'Verifica accesso utente',
    SiteOwnerRequiredTitle: 'Accesso Proprietario del sito richiesto —',
    SiteOwnerRequiredDesc: 'Questi strumenti richiedono l\'accesso Proprietario del sito. Contatta un proprietario del sito per domande sui permessi.',
    HomeSubtitle: 'Verifica e comprendi i permessi di SharePoint, senza PowerShell.',
    RequiresSiteOwnerTooltip: 'Richiede accesso Proprietario del sito',
    HomeNoteLabel: 'Nota:',
    HomeNoteText: "Questo web part viene eseguito come l'utente attualmente connesso. Può vedere solo i siti e gli elementi a cui quell'utente ha accesso. Per una scansione completa del tenant, usa un account con accesso in lettura adeguato su tutti i siti.",
    SettingsTitle: 'Impostazioni',
    LibrariesSectionTitle: 'Raccolte',
    IncludeHiddenLabel: 'Includi raccolte di sistema e nascoste',
    IncludeHiddenTooltip: "Se selezionato, include Style Library, Modelli modulo, Risorse sito e altre raccolte nascoste dalle visualizzazioni predefinite. Si applica a tutti gli strumenti.",
    MoreInfoHiddenLibrariesLabel: 'Ulteriori informazioni sulle raccolte nascoste',
    ExcludeLimitedAccessLabel: 'Escludi voci Accesso limitato',
    ExcludeLimitedAccessTooltip: "Nasconde utenti e gruppi il cui unico permesso SharePoint è Accesso limitato, assegnato automaticamente quando i file vengono condivisi tramite link. Si applica a Report permessi, Esplora e Accesso utente.",
    MoreInfoLimitedAccessLabel: 'Ulteriori informazioni su Accesso limitato',
    ExcludeSharingLinksLabel: 'Escludi voci Link di condivisione',
    ExcludeSharingLinksTooltip: 'Nasconde i gruppi interni "SharingLinks.*" che SharePoint crea automaticamente per i link di condivisione "Chiunque abbia il link" e "Persone specifiche". Si applica a Report permessi, Esplora e Accesso utente.',
    MoreInfoSharingLinksLabel: 'Ulteriori informazioni sui link di condivisione',
    PerformanceSectionTitle: 'Prestazioni',
    ConcurrentRequestsLabel: 'Richieste API simultanee:',
    ConcurrencyTooltip: 'Quante richieste API di SharePoint vengono eseguite in parallelo durante le scansioni del Report permessi, Accesso utente e i controlli in background di Esplora. Valori più alti sono più veloci ma più soggetti a throttling (HTTP 429). Consigliato: 3–5.',
    MoreInfoConcurrencyLabel: 'Ulteriori informazioni sulla concorrenza',
    ConcurrencyHint: 'Valori più alti scansionano più velocemente ma possono attivare il throttling di SharePoint. Consigliato: 3–5.',
    GroupMemberCapLabel: 'Limite visualizzazione membri gruppo:',
    GroupMemberCapTooltip: 'Numero massimo di membri mostrati per gruppo quando "Espandi membri del gruppo" è abilitato. I gruppi più grandi vengono limitati e viene mostrato un avviso. Aumentare questo valore usa più memoria.',
    MoreInfoGroupMemberCapLabel: 'Ulteriori informazioni sul limite membri gruppo',
    GroupMemberCapHint: 'I gruppi più grandi di questo limite mostrano un avviso di troncamento. Predefinito: 500.',
    DefaultViewSectionTitle: 'Vista predefinita al caricamento',
    DefaultViewInstructionsIntro: 'Per cambiare quale schermata si apre quando il web part viene caricato per la prima volta, modifica le proprietà del web part:',
    DefaultViewStep1Pre: 'Metti la pagina SharePoint in modalità',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: "Fai clic sull'icona",
    DefaultViewStep2Post: 'nel web part Smart Permissions.',
    DefaultViewStep3Pre: 'Nel pannello delle proprietà, scegli una vista dal menu a discesa',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'la pagina per salvare la modifica.',
    EditModeWord: 'Modifica',
    PencilEditWord: 'matita (modifica)',
    DefaultViewOnOpenWord: "Vista predefinita all'apertura",
    RepublishWord: 'Ripubblica',
    SiteOwnersLabel: 'Proprietari del sito:',
    EveryoneClaimLabel: 'Tutti',
    EveryoneExceptExternalClaimLabel: 'Tutti tranne gli utenti esterni',
    PermissionAssignmentsLabel: 'Assegnazioni di permessi',
    UserGroupColumnHeader: 'Utente / Gruppo',
    TypeColumnHeader: 'Tipo',
    PermissionLevelColumnHeader: 'Livello di permesso',
    TenantWideAccessSuffix: '— accesso a livello di tenant',
    SecurityGroupType: 'Gruppo di sicurezza',
    SpGroupType: 'Gruppo SP',
    UserType: 'Utente',
    CheckAccessForLabel: 'Verifica accesso per {0}',
    ContainsUniqueAndExternalTooltip: 'Contiene elementi con permessi univoci e accesso di utenti esterni',
    ContainsUniqueTooltip: 'Contiene elementi con permessi univoci',
    ContainsExternalTooltip: 'Contiene elementi con accesso di utenti esterni',
    UniqueBadge: 'Univoco',
    ExternalAccessDetectedTooltip: 'Rilevato accesso di utente esterno',
    ConnectingStatus: 'Connessione in corso…',
    ConnectedLibrarySingular: 'Connesso — {0} raccolta trovata',
    ConnectedLibraryPlural: 'Connesso — {0} raccolte trovate',
    ConnectionFailedError: 'Connessione non riuscita: {0}',
    LibraryEmptyStatus: 'Questa raccolta è vuota.',
    ErrorLoadingLibrary: 'Errore durante il caricamento della raccolta: {0}',
    ErrorLoadingContents: 'Errore durante il caricamento del contenuto',
    LibraryFieldLabel: 'Raccolta',
    HiddenFromSearchSuffix: '{0} (nascosto dalla ricerca)',
    UniquePermissionsOnlyToggle: 'Solo permessi univoci',
    ExternalUsersOnlyToggle: 'Solo utenti esterni',
    LegendLabel: 'Legenda:',
    LegendItemHasUnique: "L'elemento ha permessi univoci",
    LegendContainsUniqueBelow: 'Contiene permessi univoci sotto',
    LegendContainsExternalBelow: 'Contiene accesso di utenti esterni sotto',
    LegendExternalOnItem: 'Accesso di utente esterno su questo elemento',
    ViewingWithMemberAccessTitle: 'Visualizzazione con accesso Membro',
    ViewingWithMemberAccessDesc1: '— le assegnazioni di permessi non sono visibili. Leggere chi ha accesso richiede il diritto',
    ManagePermissionsWord: 'Gestisci permessi',
    ViewingWithMemberAccessDesc2: '(Proprietario del sito o superiore). Puoi comunque vedere quali elementi hanno ereditarietà interrotta usando gli indicatori ↓. Per vedere le posizioni a cui puoi accedere, usa lo strumento',
    UserAccessWord: 'Accesso utente',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Cartelle e file',
    SelectFolderOrFilePrompt: 'Seleziona una cartella o un file per visualizzarne i permessi.',
    UniquePermissionsBadge: 'Permessi univoci',
    InheritedBadge: 'Ereditato',
    ExpandGroupMembersLabel: 'Espandi membri del gruppo',
    ShowParentPermissionsLabel: 'Mostra permessi padre',
    InheritsFromParentText: 'Questo elemento eredita i permessi dal suo elemento padre.',
    YourAccessLabel: 'Il tuo accesso:',
    PermissionsNotVisibleNodeText: "Le assegnazioni di permessi non sono visibili — è richiesto il diritto Gestisci permessi (Proprietario del sito o superiore) per vedere chi ha accesso a questo elemento.",
    NoExternalUsersDirectAccessText: 'Nessun utente esterno ha accesso diretto a questo elemento.',
    InheritedFromLabel: 'Ereditato da:',
    ParentPermissionsNotVisibleText: 'Le assegnazioni di permessi del padre non sono visibili — richiede il diritto Gestisci permessi (Proprietario del sito o superiore).',
    NoPermissionsFoundOnParentText: 'Nessun permesso trovato sul padre.',
    StartingScanStatus: 'Avvio scansione…',
    ScanCancelledStatus: 'Scansione annullata — {0} oggetto/i raccolti prima dell\'annullamento.',
    ScanCompleteStatus: 'Scansione completa — {0} oggetto/i trovato/i, {1} con permessi univoci.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Scansione completa',
    ScanCompleteNotificationBody: '{0} oggetti, {1} con permessi univoci.',
    CancelledStatus: 'Annullato.',
    GenericErrorPrefix: 'Errore: {0}',
    ExportErrorPrefix: 'Errore di esportazione: {0}',
    ScopeSiteOnly: 'Solo sito',
    ScopeLibraries: 'Raccolte',
    ScopeFolders: 'Cartelle',
    ScopeFilesAndFolders: 'File e cartelle',
    ScanInProgressConfirm: 'Una scansione è in corso. Uscire e annullare?',
    HistoryButton: 'Cronologia',
    BackToHistoryButton: 'Torna alla cronologia',
    ComparingLabel: 'Confronto',
    CompareMismatchWarning: 'Questi report sono stati acquisiti con siti o opzioni di scansione diverse — le differenze sottostanti possono riflettere le impostazioni di scansione modificate anziché effettivi cambiamenti di permessi.',
    NoPermissionDifferencesFound: 'Nessuna differenza di permessi trovata tra questi due report.',
    PermissionChangesHeaderSingular: 'Modifiche ai permessi ({0} oggetto)',
    PermissionChangesHeaderPlural: 'Modifiche ai permessi ({0} oggetti)',
    ChangeColumnHeader: 'Modifica',
    BeforeColumnHeader: 'Prima',
    AfterColumnHeader: 'Dopo',
    AddedBadge: 'Aggiunto',
    RemovedBadge: 'Rimosso',
    ChangedBadge: 'Modificato',
    InheritanceChangedHeader: 'Ereditarietà modificata ({0})',
    NameColumnHeader: 'Nome',
    PathColumnHeader: 'Percorso',
    NowColumnHeader: 'Ora',
    UniqueInheritanceBrokenBadge: 'Univoco (ereditarietà interrotta)',
    InheritedRestoredBadge: 'Ereditato (ripristinato)',
    NewObjectsHeader: 'Nuovi oggetti',
    RemovedObjectsHeader: 'Oggetti rimossi',
    BackToScanButton: 'Torna alla scansione',
    CompareSelectedButton: 'Confronta selezionati',
    NoReportsSavedYet: 'Nessun report salvato ancora.',
    SelectForCompareLabel: 'Seleziona per confrontare',
    DateTimeColumnHeader: 'Data / Ora',
    SiteColumnHeader: 'Sito',
    ScopeColumnHeader: 'Ambito',
    ObjectsColumnHeader: 'Oggetti',
    UniqueColumnHeader: 'Univoco',
    SelectReportForCompareLabel: 'Seleziona il report del {0} per confrontare',
    AllSitesPrefix: 'Tutti i siti · ',
    PlusSubsitesSuffix: ' + sottositi',
    ExportingStatus: 'Esportazione…',
    ExportButton: 'Esporta',
    DeleteThisReportTitle: 'Elimina questo report',
    ScanAllSiteCollectionsLabel: 'Analizza tutte le raccolte siti in questo tenant (disponibile solo nel sito radice)',
    AllSitesSearchCaveat: "L'elenco dei siti proviene dalla ricerca e potrebbe non includere ogni raccolta siti — i siti creati molto di recente, o esclusi dall'indice di ricerca, potrebbero mancare.",
    IncludeSubsitesLabel: 'Includi sottositi (analizza ogni sottosito sotto questo sito)',
    ScanDepthFieldLabel: 'Profondità di scansione',
    FolderDepthLimitLabel: 'Limite di profondità cartelle:',
    ExpandGroupMembersInReportLabel: 'Espandi i membri del gruppo nel report (gruppi SharePoint, gruppi di sicurezza e gruppi M365)',
    LibrariesToScanLabel: 'Raccolte da analizzare',
    OfSelectedCount: '{0} di {1} selezionate',
    AllButton: 'Tutte',
    NoneButton: 'Nessuna',
    LoadingLibrariesStatus: 'Caricamento raccolte…',
    RunReportButton: 'Esegui report',
    ItemsFoundSoFar: '{0} elementi trovati finora',
    LibraryOfProgress: 'Raccolta {0} di {1}',
    ScanCancelledPartialResults: 'Scansione annullata — risultati parziali',
    ScanCompleteLabel: 'Scansione completa',
    ObjectsCountBadge: '{0} oggetti',
    UniqueCountBadge: '{0} univoci',
    InheritedCountBadge: '{0} ereditati',
    GeneratingExcelStatus: 'Generazione Excel…',
    ExportFilteredRowsButton: 'Esporta {0} righe filtrate',
    ExportToExcelButton: 'Esporta in Excel',
    ExportToCsvButton: 'Esporta in CSV',
    ScanStoppedEarlyTitle: 'Scansione interrotta anticipatamente — SharePoint sta limitando questo tenant.',
    SiteCollectionsScannedBeforeStopping: '{0} di {1} raccolte siti sono state analizzate prima di fermarsi. ',
    ResultsBelowCoverOnlyPre: 'I risultati sottostanti coprono solo ciò che è stato analizzato e non sono',
    NotWord: 'non',
    ResultsBelowCoverOnlyPost: "un audit completo. La scansione si interrompe da sola in questa situazione perché continuare a inviare richieste è ciò che mantiene attivo il throttling. Attendi alcuni minuti, poi riesegui con",
    ConcurrentRequestsWord: 'Richieste simultanee',
    SetTo1Or2InSettings: 'impostato su 1 o 2 nelle Impostazioni.',
    ThrottledScanMessage: 'SharePoint ha limitato questa scansione ({0} richiesta/e sono state limitate e ritentate).',
    OfEverythingScannedPre: 'Di tutto ciò che è stato analizzato,',
    ItemCountSingular: '{0} elemento',
    ItemCountPlural: '{0} elementi',
    CouldNotBeConfirmedText: 'non hanno potuto essere confermati dopo il nuovo tentativo (vedi l\'avviso "non è stato possibile leggere completamente" sotto per sapere esattamente quali) — quel fallimento era legato alla capacità, non ai loro permessi reali. Tutti gli altri elementi in questo report sono stati letti con successo e sono affidabili.',
    DespiteThrottlingText: 'Nonostante il throttling, ogni elemento è stato comunque confermato con successo dopo il nuovo tentativo, quindi questo report è completo.',
    ForCleanRunPre: "Per un'esecuzione pulita, attendi qualche minuto e riesegui la scansione con un valore più basso di",
    ValueInSettingsPost: 'nelle Impostazioni.',
    OneItemWord: '1 elemento',
    NItemsWord: '{0} elemento/i',
    OutOfScannedCouldNotBeRead: 'su {0} analizzati non hanno potuto essere letti con il tuo accesso attuale —',
    PermissionAssignmentsForItAreNotShown: ' le assegnazioni di permessi non sono mostrate, ',
    PermissionAssignmentsForThoseAreNotShown: ' le assegnazioni di permessi non sono mostrate, ',
    RestOfReportReadSuccessfully: 'ma il resto di questo report è stato letto con successo.',
    RunScanAsSiteOwnerPre: 'Esegui la scansione come',
    SiteOwnerWord: 'Proprietario del sito',
    RunScanAsSiteOwnerPost: 'per vedere i dettagli completi degli elementi negati qui sotto.',
    AndNMoreText: '…e altri {0}',
    GroupExpansionSkippedPre: "L'espansione dei membri del gruppo è stata saltata — il permesso Graph",
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'non è stato approvato in questo tenant. Un amministratore SharePoint o globale può approvarlo in',
    SharePointAdminCenterPath: 'Centro amministrazione SharePoint → Avanzate → Accesso API',
    ScanIncompleteItemsMessage: "{0} elemento/i non hanno potuto essere letti completamente a causa di un errore temporaneo (non un problema di permessi) e sono mostrati con i permessi del loro elemento padre come soluzione di ripiego — questo potrebbe non riflettere il loro accesso reale. Riesegui la scansione per riprovare questi elementi.",
    FilterByNamePathUserPlaceholder: 'Filtra per nome, percorso o utente/gruppo…',
    FilterResultsLabel: 'Filtra risultati',
    ExternalUsersOnlyExtLabel: 'Solo utenti esterni (#ext#)',
    ShowingOfCount: 'Visualizzazione di {0} su {1}',
    ScanResultsLabel: 'Risultati della scansione',
    PermissionsColumnHeader: 'Permessi',
    CollapsePermissionsLabel: 'Comprimi permessi',
    ExpandPermissionsLabel: 'Espandi permessi',
    HiddenFromSearchBadge: 'Nascosto dalla ricerca',
    AssignmentCountSingular: '{0} assegnazione',
    AssignmentCountPlural: '{0} assegnazioni',
    LoadMoreRemainingButton: 'Carica altro ({0} rimanenti)',
    LoadingUsersStatus: 'Caricamento utenti…',
    ConnectedUserSingular: 'Connesso — {0} utente trovato',
    ConnectedUserPlural: 'Connesso — {0} utenti trovati',
    CheckingAccessForStatus: "Verifica dell'accesso per {0}…",
    FullSiteAccessDetectedStatus: 'Rilevato accesso completo al sito.',
    AccessibleLocationsFoundSingular: '{0} posizione accessibile trovata.',
    AccessibleLocationsFoundPlural: '{0} posizioni accessibili trovate.',
    NoAccessibleLocationsFoundStatus: 'Nessuna posizione accessibile trovata.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Scansione accesso utente completa',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Nuova scansione',
    NoUserAccessScansSavedYet: 'Nessuna scansione di accesso utente salvata ancora.',
    UserColumnHeader: 'Utente',
    LocationsColumnHeader: 'Posizioni',
    FullControlBadge: 'Controllo completo',
    DeleteThisRecordTitle: 'Elimina questo record',
    SelectAUserFieldLabel: 'Seleziona un utente',
    SearchUsersPlaceholder: 'Cerca utenti…',
    SelectAUserToCheckAccessLabel: "Seleziona un utente per verificare l'accesso",
    NotInThisSiteLabel: 'Non in questo sito',
    ScanInProgressLabel: 'Scansione in corso',
    ScanningUserAccessLabel: 'Scansione accesso utente in corso',
    ScanningStatus: 'Scansione in corso…',
    FullControlAccessPre: 'Questo utente ha',
    FullControlWord: 'Controllo completo',
    FullControlAccessPost: "o accesso di livello Proprietario all'intero sito — tutte le raccolte e le cartelle sono accessibili.",
    SiteLevelPermissionCouldNotBeDeterminedPre: "Non è stato possibile determinare il permesso a livello di sito — questo sito probabilmente usa l'accesso tramite gruppo Microsoft 365. Per mostrarlo, un amministratore SharePoint deve approvare il permesso",
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph in',
    ShowingSiteLevelAccessOnlyPre: 'Visualizzazione solo dell\'',
    SiteLevelAccessOnlyWord: 'accesso a livello di sito',
    ShowingSiteLevelAccessOnlyMid: ', basato sull\'appartenenza predefinita al gruppo SharePoint. I permessi univoci su raccolte, cartelle e file non hanno potuto essere letti e non sono mostrati. Per risultati completi, esegui questa scansione come',
    UserAccessCouldNotBeDeterminedPre: "L'accesso di questo utente non ha potuto essere determinato. Leggere le assegnazioni di permessi richiede il diritto",
    UserAccessCouldNotBeDeterminedPost: "(Proprietario del sito o superiore), e questo utente non sembra essere membro dei gruppi predefiniti Proprietari, Membri o Visitatori del sito.",
    SiteLevelAccessBannerPre: 'Questo utente ha accesso a livello di sito. Solo le posizioni con',
    UniquePermissionAssignmentsWord: 'assegnazioni di permessi univoche',
    SiteLevelAccessBannerPost: "appaiono di seguito — tutti gli altri contenuti sono accessibili tramite il permesso a livello di sito mostrato in cima all'elenco.",
    UserAccessResultsLabel: 'Risultati accesso utente',
  };
});
