define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions の構成',
    PropertyPane_GroupName: '全般',
    PropertyPane_DefaultViewLabel: '開いたときの既定のビュー',
    PropertyPane_View_Home: 'ホーム',
    PropertyPane_View_Report: '権限レポート',
    PropertyPane_View_Explorer: '権限エクスプローラー',
    PropertyPane_View_UserAccess: 'ユーザーアクセス',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: '接続',
    CancelButton: 'キャンセル',
    ChangeUrlButton: 'URL を変更',
    SettingsLabel: '設定',
    RenderErrorTitle: 'Smart Permissions — レンダリングエラー',
    RenderErrorMessageLabel: 'メッセージ:',
    RenderErrorStackLabel: 'スタック:',
    RenderErrorNoStack: '(スタックは利用できません)',
    BackButton: '戻る',
    BackToHomeLabel: 'ホームに戻る',
    ExplorerCardTitle: '権限エクスプローラー',
    ExplorerCardAlt: 'フォルダーツリーと権限パネルを備えた権限エクスプローラー',
    ExplorerCardDesc: '任意のフォルダーやファイルを参照し、誰がアクセスできるかをリアルタイムの権限検索で即座に確認できます。',
    ExplorerCardButton: '権限エクスプローラーを開く',
    ReportCardTitle: '権限レポート',
    ReportCardAlt: '権限レポートの構成画面',
    ReportCardDesc: 'サイト内のすべての一意の権限割り当てについて、色分けされた Excel レポートを生成します。',
    ReportCardButton: '権限レポートを実行',
    UserAccessCardTitle: 'ユーザーアクセス',
    UserAccessCardAlt: '選択したユーザーのアクセス可能な場所を表示するユーザーアクセス画面',
    UserAccessCardDesc: '任意のユーザーを検索して、サイト上でアクセスできるすべての場所を、正確な権限レベルとともに確認します。',
    UserAccessCardButton: 'ユーザーアクセスを確認',
    SiteOwnerRequiredTitle: 'サイト所有者のアクセス権が必要です —',
    SiteOwnerRequiredDesc: 'これらのツールにはサイト所有者のアクセス権が必要です。権限に関する質問がある場合はサイト所有者にお問い合わせください。',
    HomeSubtitle: 'PowerShell を使わずに SharePoint の権限を監査し理解できます。',
    RequiresSiteOwnerTooltip: 'サイト所有者のアクセス権が必要です',
    HomeNoteLabel: '注記:',
    HomeNoteText: 'この Web パーツは現在サインインしているユーザーとして実行されます。そのユーザーがアクセス権を持つサイトと項目のみを表示できます。テナント全体をスキャンするには、すべてのサイトに適切な読み取りアクセス権を持つアカウントを使用してください。',
    SettingsTitle: '設定',
    LibrariesSectionTitle: 'ライブラリ',
    IncludeHiddenLabel: 'システムライブラリと非表示ライブラリを含める',
    IncludeHiddenTooltip: 'チェックすると、スタイルライブラリ、フォームテンプレート、サイトアセットなど、既定のビューから非表示になっているライブラリが含まれます。すべてのツールに適用されます。',
    MoreInfoHiddenLibrariesLabel: '非表示のライブラリの詳細',
    ExcludeLimitedAccessLabel: '限定アクセスのエントリを除外する',
    ExcludeLimitedAccessTooltip: 'SharePoint の唯一の権限が限定アクセスであるユーザーとグループを非表示にします — リンク経由でファイルが共有されると自動的に割り当てられます。権限レポート、エクスプローラー、ユーザーアクセスに適用されます。',
    MoreInfoLimitedAccessLabel: '限定アクセスの詳細',
    ExcludeSharingLinksLabel: '共有リンクのエントリを除外する',
    ExcludeSharingLinksTooltip: '「リンクを知っている全員」および「特定のユーザー」の共有リンク用に SharePoint が自動作成する内部の "SharingLinks.*" グループを非表示にします。権限レポート、エクスプローラー、ユーザーアクセスに適用されます。',
    MoreInfoSharingLinksLabel: '共有リンクの詳細',
    PerformanceSectionTitle: 'パフォーマンス',
    ConcurrentRequestsLabel: '同時 API リクエスト数:',
    ConcurrencyTooltip: '権限レポートのスキャン、ユーザーアクセスのスキャン、エクスプローラーのバックグラウンドチェック中に並行して実行される SharePoint API リクエストの数。値を高くすると速くなりますが、スロットリング (HTTP 429) が発生しやすくなります。3〜5 を推奨します。',
    MoreInfoConcurrencyLabel: '同時実行の詳細',
    ConcurrencyHint: '値を高くするとスキャンは速くなりますが、SharePoint のスロットリングが発生する場合があります。推奨: 3〜5。',
    GroupMemberCapLabel: 'グループメンバー表示の上限:',
    GroupMemberCapTooltip: '「グループメンバーを展開」が有効な場合にグループごとに表示されるメンバーの最大数。より大きなグループは制限され、通知が表示されます。この値を増やすとメモリの使用量が増えます。',
    MoreInfoGroupMemberCapLabel: 'グループメンバーの上限の詳細',
    GroupMemberCapHint: 'この上限より大きいグループは切り捨て通知を表示します。既定値: 500。',
    DefaultViewSectionTitle: '読み込み時の既定のビュー',
    DefaultViewInstructionsIntro: 'Web パーツが最初に読み込まれたときに開く画面を変更するには、Web パーツのプロパティを編集します:',
    DefaultViewStep1Pre: 'SharePoint ページを',
    DefaultViewStep1Post: 'モードにします。',
    DefaultViewStep2Pre: 'Smart Permissions Web パーツの',
    DefaultViewStep2Post: 'アイコンをクリックします。',
    DefaultViewStep3Pre: 'プロパティパネルで、ドロップダウンリストからビューを選択します',
    DefaultViewStep3Post: '。',
    DefaultViewStep4Post: 'ページを実行し、変更を保存します。',
    EditModeWord: '編集',
    PencilEditWord: '鉛筆 (編集)',
    DefaultViewOnOpenWord: '開いたときの既定のビュー',
    RepublishWord: '再公開して',
    SiteOwnersLabel: 'サイト所有者:',
    EveryoneClaimLabel: '全員',
    EveryoneExceptExternalClaimLabel: '外部ユーザーを除く全員',
    PermissionAssignmentsLabel: '権限の割り当て',
    UserGroupColumnHeader: 'ユーザー / グループ',
    TypeColumnHeader: '種類',
    PermissionLevelColumnHeader: '権限レベル',
    TenantWideAccessSuffix: '— テナント全体のアクセス',
    SecurityGroupType: 'セキュリティグループ',
    SpGroupType: 'SP グループ',
    UserType: 'ユーザー',
    CheckAccessForLabel: '{0} のアクセスを確認',
    ContainsUniqueAndExternalTooltip: '一意の権限と外部ユーザーアクセスを持つ項目が含まれています',
    ContainsUniqueTooltip: '一意の権限を持つ項目が含まれています',
    ContainsExternalTooltip: '外部ユーザーアクセスを持つ項目が含まれています',
    UniqueBadge: '一意',
    ExternalAccessDetectedTooltip: '外部ユーザーアクセスが検出されました',
    ConnectingStatus: '接続中…',
    ConnectedLibrarySingular: '接続済み — {0} 件のライブラリが見つかりました',
    ConnectedLibraryPlural: '接続済み — {0} 件のライブラリが見つかりました',
    ConnectionFailedError: '接続に失敗しました: {0}',
    LibraryEmptyStatus: 'このライブラリは空です。',
    ErrorLoadingLibrary: 'ライブラリの読み込みエラー: {0}',
    ErrorLoadingContents: 'コンテンツの読み込みエラー',
    LibraryFieldLabel: 'ライブラリ',
    HiddenFromSearchSuffix: '{0}（検索から非表示）',
    UniquePermissionsOnlyToggle: '一意の権限のみ',
    ExternalUsersOnlyToggle: '外部ユーザーのみ',
    LegendLabel: '凡例:',
    LegendItemHasUnique: '項目には一意の権限があります',
    LegendContainsUniqueBelow: '以下に一意の権限が含まれています',
    LegendContainsExternalBelow: '以下に外部ユーザーアクセスが含まれています',
    LegendExternalOnItem: 'この項目に外部ユーザーアクセスがあります',
    ViewingWithMemberAccessTitle: 'メンバーアクセスで表示中',
    ViewingWithMemberAccessDesc1: '— 権限の割り当ては表示されません。誰がアクセスできるかを確認するには、',
    ManagePermissionsWord: '権限の管理',
    ViewingWithMemberAccessDesc2: '（サイト所有者以上）が必要です。↓ インジケーターを使用して、継承が中断された項目を確認できます。アクセスできる場所を確認するには、',
    UserAccessWord: 'ユーザーアクセス',
    ViewingWithMemberAccessDesc3: 'ツールを使用してください。',
    FoldersAndFilesLabel: 'フォルダーとファイル',
    SelectFolderOrFilePrompt: 'フォルダーまたはファイルを選択して、その権限を表示します。',
    UniquePermissionsBadge: '一意の権限',
    InheritedBadge: '継承済み',
    ExpandGroupMembersLabel: 'グループメンバーを展開',
    ShowParentPermissionsLabel: '親の権限を表示',
    InheritsFromParentText: 'この項目は親項目から権限を継承しています。',
    YourAccessLabel: 'あなたのアクセス:',
    PermissionsNotVisibleNodeText: '権限の割り当ては表示されません — この項目に誰がアクセスできるかを確認するには、権限の管理権限（サイト所有者以上）が必要です。',
    NoExternalUsersDirectAccessText: 'この項目に直接アクセスできる外部ユーザーはいません。',
    InheritedFromLabel: '継承元:',
    ParentPermissionsNotVisibleText: '親項目の権限の割り当ては表示されません — 権限の管理権限（サイト所有者以上）が必要です。',
    NoPermissionsFoundOnParentText: '親項目に権限が見つかりませんでした。',
    StartingScanStatus: 'スキャンを開始しています…',
    ScanCancelledStatus: 'スキャンがキャンセルされました — キャンセルまでに {0} 個のオブジェクトが収集されました。',
    ScanCompleteStatus: 'スキャンが完了しました — {0} 個のオブジェクトが見つかり、{1} 個に一意の権限があります。',
    ScanCompleteNotificationTitle: 'Smart Permissions — スキャンが完了しました',
    ScanCompleteNotificationBody: '{0} 個のオブジェクト、{1} 個に一意の権限があります。',
    CancelledStatus: 'キャンセルされました。',
    GenericErrorPrefix: 'エラー: {0}',
    ExportErrorPrefix: 'エクスポートエラー: {0}',
    ScopeSiteOnly: 'サイトのみ',
    ScopeLibraries: 'ライブラリ',
    ScopeFolders: 'フォルダー',
    ScopeFilesAndFolders: 'ファイルとフォルダー',
    ScanInProgressConfirm: 'スキャンが進行中です。中止してキャンセルしますか?',
    HistoryButton: '履歴',
    BackToHistoryButton: '履歴に戻る',
    ComparingLabel: '比較中',
    CompareMismatchWarning: 'これらのレポートは異なるサイトまたはスキャンオプションで取得されました — 以下の差異は、実際の権限変更ではなく、変更されたスキャン設定を反映している可能性があります。',
    NoPermissionDifferencesFound: 'これら 2 つのレポート間に権限の差異は見つかりませんでした。',
    PermissionChangesHeaderSingular: '権限の変更（{0} 個のオブジェクト）',
    PermissionChangesHeaderPlural: '権限の変更（{0} 個のオブジェクト）',
    ChangeColumnHeader: '変更',
    BeforeColumnHeader: '変更前',
    AfterColumnHeader: '変更後',
    AddedBadge: '追加',
    RemovedBadge: '削除',
    ChangedBadge: '変更',
    InheritanceChangedHeader: '継承が変更されました（{0}）',
    NameColumnHeader: '名前',
    PathColumnHeader: 'パス',
    NowColumnHeader: '現在',
    UniqueInheritanceBrokenBadge: '一意（継承が中断されました）',
    InheritedRestoredBadge: '継承済み（復元されました）',
    NewObjectsHeader: '新しいオブジェクト',
    RemovedObjectsHeader: '削除されたオブジェクト',
    BackToScanButton: 'スキャンに戻る',
    CompareSelectedButton: '選択項目を比較',
    NoReportsSavedYet: 'まだ保存されたレポートはありません。',
    SelectForCompareLabel: '比較用に選択',
    DateTimeColumnHeader: '日付 / 時刻',
    SiteColumnHeader: 'サイト',
    ScopeColumnHeader: '範囲',
    ObjectsColumnHeader: 'オブジェクト',
    UniqueColumnHeader: '一意',
    SelectReportForCompareLabel: '比較のために {0} のレポートを選択',
    AllSitesPrefix: 'すべてのサイト · ',
    PlusSubsitesSuffix: ' + サブサイト',
    ExportingStatus: 'エクスポート中…',
    ExportButton: 'エクスポート',
    DeleteThisReportTitle: 'このレポートを削除',
    ScanAllSiteCollectionsLabel: 'このテナント内のすべてのサイトコレクションをスキャンする（ルートサイトでのみ使用可能）',
    AllSitesSearchCaveat: 'サイトの一覧は検索から取得されるため、すべてのサイトコレクションが含まれるとは限りません — 最近作成されたサイトや検索インデックスから除外されたサイトが欠落する場合があります。',
    IncludeSubsitesLabel: 'サブサイトを含める（このサイトの下にあるすべてのサブサイトをスキャンします）',
    ScanDepthFieldLabel: 'スキャンの深さ',
    FolderDepthLimitLabel: 'フォルダーの深さの制限:',
    ExpandGroupMembersInReportLabel: 'レポートでグループメンバーを展開する（SharePoint グループ、セキュリティグループ、M365 グループ）',
    LibrariesToScanLabel: 'スキャンするライブラリ',
    OfSelectedCount: '{1} 件中 {0} 件選択',
    AllButton: 'すべて',
    NoneButton: 'なし',
    LoadingLibrariesStatus: 'ライブラリを読み込んでいます…',
    RunReportButton: 'レポートを実行',
    ItemsFoundSoFar: 'これまでに {0} 件の項目が見つかりました',
    LibraryOfProgress: 'ライブラリ {0}/{1}',
    ScanCancelledPartialResults: 'スキャンがキャンセルされました — 部分的な結果',
    ScanCompleteLabel: 'スキャンが完了しました',
    ObjectsCountBadge: '{0} 個のオブジェクト',
    UniqueCountBadge: '{0} 件が一意',
    InheritedCountBadge: '{0} 件が継承',
    GeneratingExcelStatus: 'Excel を生成しています…',
    ExportFilteredRowsButton: '{0} 件のフィルター済み行をエクスポート',
    ExportToExcelButton: 'Excel にエクスポート',
    ExportToCsvButton: 'CSV にエクスポート',
    ScanStoppedEarlyTitle: 'スキャンが早期に停止しました — SharePoint がこのテナントをスロットリングしています。',
    SiteCollectionsScannedBeforeStopping: '停止前に {1} 件中 {0} 件のサイトコレクションがスキャンされました。',
    ResultsBelowCoverOnlyPre: '以下の結果はスキャンされた範囲のみをカバーしており、',
    NotWord: '完全な監査ではありません',
    ResultsBelowCoverOnlyPost: '。この状況ではスキャンは自動的に停止します。リクエストの送信を続けることがスロットリングを維持する原因になるためです。数分待ってから、',
    ConcurrentRequestsWord: '同時リクエスト数',
    SetTo1Or2InSettings: 'を設定で 1 または 2 に設定して再実行してください。',
    ThrottledScanMessage: 'SharePoint はこのスキャンをスロットリングしました（{0} 件のリクエストがレート制限され、再試行されました）。',
    OfEverythingScannedPre: 'スキャンされたすべての項目のうち、',
    ItemCountSingular: '{0} 件の項目',
    ItemCountPlural: '{0} 件の項目',
    CouldNotBeConfirmedText: 'は再試行後も確認できませんでした（正確にどの項目かは以下の「完全に読み取れませんでした」の通知を参照してください）— この失敗は容量に関連するものであり、実際の権限を反映したものではありません。このレポート内の他のすべての項目は正常に読み取られており、信頼できます。',
    DespiteThrottlingText: 'スロットリングにもかかわらず、再試行後にすべての項目が正常に確認されたため、このレポートは完全です。',
    ForCleanRunPre: 'クリーンな実行のために、数分待ってから、より低い',
    ValueInSettingsPost: 'の値で設定から再スキャンしてください。',
    OneItemWord: '1 件の項目',
    NItemsWord: '{0} 件の項目',
    OutOfScannedCouldNotBeRead: 'スキャンされた {0} 件のうち、現在のアクセス権では読み取れませんでした —',
    PermissionAssignmentsForItAreNotShown: ' 権限の割り当ては表示されません。',
    PermissionAssignmentsForThoseAreNotShown: ' 権限の割り当ては表示されません。',
    RestOfReportReadSuccessfully: 'ただし、このレポートの残りは正常に読み取られました。',
    RunScanAsSiteOwnerPre: '以下の拒否された項目の完全な詳細を確認するには、',
    SiteOwnerWord: 'サイト所有者',
    RunScanAsSiteOwnerPost: 'としてスキャンを実行してください。',
    AndNMoreText: '…他 {0} 件',
    GroupExpansionSkippedPre: 'グループメンバーの展開はスキップされました — Graph 権限',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'はこのテナントで承認されていません。SharePoint 管理者またはグローバル管理者が',
    SharePointAdminCenterPath: 'SharePoint 管理センター → 詳細設定 → API アクセス',
    ScanIncompleteItemsMessage: '{0} 件の項目は一時的なエラー（権限の問題ではありません）のため完全に読み取れず、フォールバックとして親項目の権限で表示されています — これは実際のアクセス権を反映していない可能性があります。これらの項目を再試行するには、スキャンを再実行してください。',
    FilterByNamePathUserPlaceholder: '名前、パス、またはユーザー/グループでフィルター…',
    FilterResultsLabel: '結果をフィルター',
    ExternalUsersOnlyExtLabel: '外部ユーザーのみ (#ext#)',
    ShowingOfCount: '{1} 件中 {0} 件を表示中',
    ScanResultsLabel: 'スキャン結果',
    PermissionsColumnHeader: '権限',
    CollapsePermissionsLabel: '権限を折りたたむ',
    ExpandPermissionsLabel: '権限を展開',
    HiddenFromSearchBadge: '検索から非表示',
    AssignmentCountSingular: '{0} 件の割り当て',
    AssignmentCountPlural: '{0} 件の割り当て',
    LoadMoreRemainingButton: 'さらに読み込む（残り {0} 件）',
    LoadingUsersStatus: 'ユーザーを読み込んでいます…',
    ConnectedUserSingular: '接続済み — {0} 人のユーザーが見つかりました',
    ConnectedUserPlural: '接続済み — {0} 人のユーザーが見つかりました',
    CheckingAccessForStatus: '{0} のアクセスを確認しています…',
    FullSiteAccessDetectedStatus: 'サイトへの完全なアクセスが検出されました。',
    AccessibleLocationsFoundSingular: 'アクセス可能な場所が {0} 件見つかりました。',
    AccessibleLocationsFoundPlural: 'アクセス可能な場所が {0} 件見つかりました。',
    NoAccessibleLocationsFoundStatus: 'アクセス可能な場所は見つかりませんでした。',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — ユーザーアクセスのスキャンが完了しました',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: '新しいスキャン',
    NoUserAccessScansSavedYet: 'まだ保存されたユーザーアクセスのスキャンはありません。',
    UserColumnHeader: 'ユーザー',
    LocationsColumnHeader: '場所',
    FullControlBadge: 'フルコントロール',
    DeleteThisRecordTitle: 'このレコードを削除',
    SelectAUserFieldLabel: 'ユーザーを選択',
    SearchUsersPlaceholder: 'ユーザーを検索…',
    SelectAUserToCheckAccessLabel: 'アクセスを確認するユーザーを選択',
    NotInThisSiteLabel: 'このサイトにはいません',
    ScanInProgressLabel: 'スキャンが進行中です',
    ScanningUserAccessLabel: 'ユーザーアクセスをスキャン中',
    ScanningStatus: 'スキャン中…',
    FullControlAccessPre: 'このユーザーはサイト全体に対して',
    FullControlWord: 'フルコントロール',
    FullControlAccessPost: 'または所有者レベルのアクセス権を持っています — すべてのライブラリとフォルダーにアクセスできます。',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'サイトレベルの権限を判別できませんでした — このサイトは Microsoft 365 グループアクセスを使用している可能性があります。これを表示するには、SharePoint 管理者が',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'で Graph 権限を承認する必要があります。',
    ShowingSiteLevelAccessOnlyPre: '既定の SharePoint グループメンバーシップに基づいて、',
    SiteLevelAccessOnlyWord: 'サイトレベルのアクセスのみ',
    ShowingSiteLevelAccessOnlyMid: 'が表示されています。ライブラリ、フォルダー、ファイルの一意の権限は読み取れなかったため表示されません。完全な結果を得るには、このスキャンを',
    UserAccessCouldNotBeDeterminedPre: 'このユーザーのアクセスを判別できませんでした。権限の割り当てを読み取るには、',
    UserAccessCouldNotBeDeterminedPost: '権限（サイト所有者以上）が必要であり、このユーザーはサイトの既定の所有者、メンバー、または訪問者グループのメンバーではないようです。',
    SiteLevelAccessBannerPre: 'このユーザーはサイトレベルのアクセス権を持っています。以下には、',
    UniquePermissionAssignmentsWord: '一意の権限の割り当てを持つ',
    SiteLevelAccessBannerPost: '場所のみが表示されます — 他のすべてのコンテンツは、一覧の一番上に表示されているサイトレベルの権限を通じてアクセスできます。',
    UserAccessResultsLabel: 'ユーザーアクセスの結果',
  };
});
