define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions 구성',
    PropertyPane_GroupName: '일반',
    PropertyPane_DefaultViewLabel: '열 때의 기본 보기',
    PropertyPane_View_Home: '홈',
    PropertyPane_View_Report: '권한 보고서',
    PropertyPane_View_Explorer: '권한 탐색기',
    PropertyPane_View_UserAccess: '사용자 액세스',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: '연결',
    CancelButton: '취소',
    ChangeUrlButton: 'URL 변경',
    SettingsLabel: '설정',
    RenderErrorTitle: 'Smart Permissions — 렌더링 오류',
    RenderErrorMessageLabel: '메시지:',
    RenderErrorStackLabel: '스택:',
    RenderErrorNoStack: '(스택을 사용할 수 없음)',
    BackButton: '뒤로',
    BackToHomeLabel: '홈으로 돌아가기',
    ExplorerCardTitle: '권한 탐색기',
    ExplorerCardAlt: '폴더 트리와 권한 패널이 있는 권한 탐색기',
    ExplorerCardDesc: '모든 폴더나 파일을 탐색하고 실시간 권한 조회를 통해 누가 액세스할 수 있는지 즉시 확인하세요.',
    ExplorerCardButton: '권한 탐색기 열기',
    ReportCardTitle: '권한 보고서',
    ReportCardAlt: '권한 보고서 구성 화면',
    ReportCardDesc: '사이트의 모든 고유 권한 할당에 대해 색상으로 구분된 Excel 보고서를 생성합니다.',
    ReportCardButton: '권한 보고서 실행',
    UserAccessCardTitle: '사용자 액세스',
    UserAccessCardAlt: '선택한 사용자가 액세스할 수 있는 위치를 표시하는 사용자 액세스 화면',
    UserAccessCardDesc: '모든 사용자를 조회하여 사이트에서 액세스할 수 있는 모든 위치를 정확한 권한 수준과 함께 확인합니다.',
    UserAccessCardButton: '사용자 액세스 확인',
    SiteOwnerRequiredTitle: '사이트 소유자 액세스 권한이 필요합니다 —',
    SiteOwnerRequiredDesc: '이 도구를 사용하려면 사이트 소유자 액세스 권한이 필요합니다. 권한에 대한 질문이 있으면 사이트 소유자에게 문의하세요.',
    HomeSubtitle: 'PowerShell 없이 SharePoint 권한을 감사하고 이해하세요.',
    RequiresSiteOwnerTooltip: '사이트 소유자 액세스 권한이 필요합니다',
    HomeNoteLabel: '참고:',
    HomeNoteText: '이 웹 파트는 현재 로그인한 사용자로 실행됩니다. 해당 사용자가 액세스 권한이 있는 사이트와 항목만 볼 수 있습니다. 전체 테넌트 검사를 위해서는 모든 사이트에 대한 적절한 읽기 액세스 권한이 있는 계정을 사용하세요.',
    SettingsTitle: '설정',
    LibrariesSectionTitle: '라이브러리',
    IncludeHiddenLabel: '시스템 및 숨겨진 라이브러리 포함',
    IncludeHiddenTooltip: '선택하면 스타일 라이브러리, 양식 템플릿, 사이트 자산 및 기본 보기에서 숨겨진 기타 라이브러리가 포함됩니다. 모든 도구에 적용됩니다.',
    MoreInfoHiddenLibrariesLabel: '숨겨진 라이브러리에 대한 자세한 정보',
    ExcludeLimitedAccessLabel: '제한된 액세스 항목 제외',
    ExcludeLimitedAccessTooltip: 'SharePoint 권한이 제한된 액세스뿐인 사용자 및 그룹을 숨깁니다 — 링크를 통해 파일이 공유될 때 자동으로 할당됩니다. 권한 보고서, 탐색기 및 사용자 액세스에 적용됩니다.',
    MoreInfoLimitedAccessLabel: '제한된 액세스에 대한 자세한 정보',
    ExcludeSharingLinksLabel: '공유 링크 항목 제외',
    ExcludeSharingLinksTooltip: 'SharePoint가 "링크가 있는 모든 사용자" 및 "특정 사용자" 공유 링크에 대해 자동으로 만드는 내부 "SharingLinks.*" 그룹을 숨깁니다. 권한 보고서, 탐색기 및 사용자 액세스에 적용됩니다.',
    MoreInfoSharingLinksLabel: '공유 링크에 대한 자세한 정보',
    PerformanceSectionTitle: '성능',
    ConcurrentRequestsLabel: '동시 API 요청:',
    ConcurrencyTooltip: '권한 보고서 검사, 사용자 액세스 검사 및 탐색기 백그라운드 검사 중에 병렬로 실행되는 SharePoint API 요청 수입니다. 값이 높을수록 빠르지만 제한(HTTP 429)이 발생할 가능성이 높습니다. 3~5가 권장됩니다.',
    MoreInfoConcurrencyLabel: '동시성에 대한 자세한 정보',
    ConcurrencyHint: '값이 높을수록 더 빠르게 검사하지만 SharePoint 제한이 발생할 수 있습니다. 권장: 3~5.',
    GroupMemberCapLabel: '그룹 구성원 표시 제한:',
    GroupMemberCapTooltip: '"그룹 구성원 확장"이 활성화된 경우 그룹당 표시되는 최대 구성원 수입니다. 더 큰 그룹은 제한되며 알림이 표시됩니다. 이 값을 늘리면 더 많은 메모리를 사용합니다.',
    MoreInfoGroupMemberCapLabel: '그룹 구성원 제한에 대한 자세한 정보',
    GroupMemberCapHint: '이 제한보다 큰 그룹은 잘림 알림을 표시합니다. 기본값: 500.',
    DefaultViewSectionTitle: '로드 시 기본 보기',
    DefaultViewInstructionsIntro: '웹 파트가 처음 로드될 때 열리는 화면을 변경하려면 웹 파트 속성을 편집하세요:',
    DefaultViewStep1Pre: 'SharePoint 페이지를',
    DefaultViewStep1Post: '모드로 전환합니다.',
    DefaultViewStep2Pre: 'Smart Permissions 웹 파트의',
    DefaultViewStep2Post: '아이콘을 클릭합니다.',
    DefaultViewStep3Pre: '속성 패널에서 드롭다운 목록',
    DefaultViewStep3Post: '에서 보기를 선택합니다.',
    DefaultViewStep4Post: '페이지를 실행하여 변경 사항을 저장합니다.',
    EditModeWord: '편집',
    PencilEditWord: '연필 (편집)',
    DefaultViewOnOpenWord: '열 때의 기본 보기',
    RepublishWord: '다시 게시하세요',
    SiteOwnersLabel: '사이트 소유자:',
    EveryoneClaimLabel: '모든 사용자',
    EveryoneExceptExternalClaimLabel: '외부 사용자를 제외한 모든 사용자',
    PermissionAssignmentsLabel: '권한 할당',
    UserGroupColumnHeader: '사용자 / 그룹',
    TypeColumnHeader: '유형',
    PermissionLevelColumnHeader: '권한 수준',
    TenantWideAccessSuffix: '— 전체 테넌트 액세스',
    SecurityGroupType: '보안 그룹',
    SpGroupType: 'SP 그룹',
    UserType: '사용자',
    CheckAccessForLabel: '{0}에 대한 액세스 확인',
    ContainsUniqueAndExternalTooltip: '고유 권한과 외부 사용자 액세스가 있는 항목이 포함되어 있습니다',
    ContainsUniqueTooltip: '고유 권한이 있는 항목이 포함되어 있습니다',
    ContainsExternalTooltip: '외부 사용자 액세스가 있는 항목이 포함되어 있습니다',
    UniqueBadge: '고유',
    ExternalAccessDetectedTooltip: '외부 사용자 액세스가 감지되었습니다',
    ConnectingStatus: '연결 중…',
    ConnectedLibrarySingular: '연결됨 — {0}개 라이브러리를 찾았습니다',
    ConnectedLibraryPlural: '연결됨 — {0}개 라이브러리를 찾았습니다',
    ConnectionFailedError: '연결 실패: {0}',
    LibraryEmptyStatus: '이 라이브러리는 비어 있습니다.',
    ErrorLoadingLibrary: '라이브러리 로드 오류: {0}',
    ErrorLoadingContents: '콘텐츠 로드 오류',
    LibraryFieldLabel: '라이브러리',
    HiddenFromSearchSuffix: '{0}(검색에서 숨김)',
    UniquePermissionsOnlyToggle: '고유 권한만',
    ExternalUsersOnlyToggle: '외부 사용자만',
    LegendLabel: '범례:',
    LegendItemHasUnique: '항목에 고유 권한이 있습니다',
    LegendContainsUniqueBelow: '아래에 고유 권한이 포함되어 있습니다',
    LegendContainsExternalBelow: '아래에 외부 사용자 액세스가 포함되어 있습니다',
    LegendExternalOnItem: '이 항목에 외부 사용자 액세스가 있습니다',
    ViewingWithMemberAccessTitle: '구성원 액세스로 보기',
    ViewingWithMemberAccessDesc1: '— 권한 할당이 표시되지 않습니다. 누가 액세스할 수 있는지 확인하려면',
    ManagePermissionsWord: '권한 관리',
    ViewingWithMemberAccessDesc2: '권한(사이트 소유자 이상)이 필요합니다. ↓ 표시기를 사용하여 상속이 중단된 항목을 계속 확인할 수 있습니다. 액세스할 수 있는 위치를 보려면',
    UserAccessWord: '사용자 액세스',
    ViewingWithMemberAccessDesc3: '도구를 사용하세요.',
    FoldersAndFilesLabel: '폴더 및 파일',
    SelectFolderOrFilePrompt: '폴더 또는 파일을 선택하여 권한을 확인하세요.',
    UniquePermissionsBadge: '고유 권한',
    InheritedBadge: '상속됨',
    ExpandGroupMembersLabel: '그룹 구성원 확장',
    ShowParentPermissionsLabel: '상위 권한 표시',
    InheritsFromParentText: '이 항목은 상위 항목에서 권한을 상속합니다.',
    YourAccessLabel: '내 액세스:',
    PermissionsNotVisibleNodeText: '권한 할당이 표시되지 않습니다 — 이 항목에 누가 액세스할 수 있는지 확인하려면 권한 관리 권한(사이트 소유자 이상)이 필요합니다.',
    NoExternalUsersDirectAccessText: '이 항목에 직접 액세스할 수 있는 외부 사용자가 없습니다.',
    InheritedFromLabel: '상속 위치:',
    ParentPermissionsNotVisibleText: '상위 항목의 권한 할당이 표시되지 않습니다 — 권한 관리 권한(사이트 소유자 이상)이 필요합니다.',
    NoPermissionsFoundOnParentText: '상위 항목에서 권한을 찾을 수 없습니다.',
    StartingScanStatus: '검사를 시작하는 중…',
    ScanCancelledStatus: '검사가 취소되었습니다 — 취소 전에 {0}개 개체가 수집되었습니다.',
    ScanCompleteStatus: '검사가 완료되었습니다 — {0}개 개체를 찾았으며 {1}개에 고유 권한이 있습니다.',
    ScanCompleteNotificationTitle: 'Smart Permissions — 검사 완료',
    ScanCompleteNotificationBody: '{0}개 개체, {1}개에 고유 권한이 있습니다.',
    CancelledStatus: '취소되었습니다.',
    GenericErrorPrefix: '오류: {0}',
    ExportErrorPrefix: '내보내기 오류: {0}',
    ScopeSiteOnly: '사이트만',
    ScopeLibraries: '라이브러리',
    ScopeFolders: '폴더',
    ScopeFilesAndFolders: '파일 및 폴더',
    ScanInProgressConfirm: '검사가 진행 중입니다. 나가서 취소하시겠습니까?',
    HistoryButton: '기록',
    BackToHistoryButton: '기록으로 돌아가기',
    ComparingLabel: '비교 중',
    CompareMismatchWarning: '이 보고서들은 서로 다른 사이트나 검사 옵션으로 작성되었습니다 — 아래 차이는 실제 권한 변경이 아니라 변경된 검사 설정을 반영할 수 있습니다.',
    NoPermissionDifferencesFound: '이 두 보고서 간에 권한 차이가 발견되지 않았습니다.',
    PermissionChangesHeaderSingular: '권한 변경 사항({0}개 개체)',
    PermissionChangesHeaderPlural: '권한 변경 사항({0}개 개체)',
    ChangeColumnHeader: '변경',
    BeforeColumnHeader: '이전',
    AfterColumnHeader: '이후',
    AddedBadge: '추가됨',
    RemovedBadge: '제거됨',
    ChangedBadge: '변경됨',
    InheritanceChangedHeader: '상속이 변경되었습니다({0})',
    NameColumnHeader: '이름',
    PathColumnHeader: '경로',
    NowColumnHeader: '현재',
    UniqueInheritanceBrokenBadge: '고유(상속 중단됨)',
    InheritedRestoredBadge: '상속됨(복원됨)',
    NewObjectsHeader: '새 개체',
    RemovedObjectsHeader: '제거된 개체',
    BackToScanButton: '검사로 돌아가기',
    CompareSelectedButton: '선택 항목 비교',
    NoReportsSavedYet: '아직 저장된 보고서가 없습니다.',
    SelectForCompareLabel: '비교할 항목 선택',
    DateTimeColumnHeader: '날짜/시간',
    SiteColumnHeader: '사이트',
    ScopeColumnHeader: '범위',
    ObjectsColumnHeader: '개체',
    UniqueColumnHeader: '고유',
    SelectReportForCompareLabel: '비교를 위해 {0}의 보고서 선택',
    AllSitesPrefix: '모든 사이트 · ',
    PlusSubsitesSuffix: ' + 하위 사이트',
    ExportingStatus: '내보내는 중…',
    ExportButton: '내보내기',
    DeleteThisReportTitle: '이 보고서 삭제',
    ScanAllSiteCollectionsLabel: '이 테넌트의 모든 사이트 모음 검사(루트 사이트에서만 사용 가능)',
    AllSitesSearchCaveat: '사이트 목록은 검색에서 가져오며 모든 사이트 모음이 포함되지 않을 수 있습니다 — 매우 최근에 만든 사이트나 검색 인덱스에서 제외된 사이트가 누락될 수 있습니다.',
    IncludeSubsitesLabel: '하위 사이트 포함(이 사이트 아래의 모든 하위 사이트를 검사함)',
    ScanDepthFieldLabel: '검사 깊이',
    FolderDepthLimitLabel: '폴더 깊이 제한:',
    ExpandGroupMembersInReportLabel: '보고서에서 그룹 구성원 확장(SharePoint 그룹, 보안 그룹 및 M365 그룹)',
    LibrariesToScanLabel: '검사할 라이브러리',
    OfSelectedCount: '{1}개 중 {0}개 선택됨',
    AllButton: '전체',
    NoneButton: '없음',
    LoadingLibrariesStatus: '라이브러리를 로드하는 중…',
    RunReportButton: '보고서 실행',
    ItemsFoundSoFar: '지금까지 {0}개 항목을 찾았습니다',
    LibraryOfProgress: '라이브러리 {0}/{1}',
    ScanCancelledPartialResults: '검사가 취소되었습니다 — 부분 결과',
    ScanCompleteLabel: '검사가 완료되었습니다',
    ObjectsCountBadge: '{0}개 개체',
    UniqueCountBadge: '{0}개 고유',
    InheritedCountBadge: '{0}개 상속됨',
    GeneratingExcelStatus: 'Excel을 생성하는 중…',
    ExportFilteredRowsButton: '필터링된 {0}개 행 내보내기',
    ExportToExcelButton: 'Excel로 내보내기',
    ExportToCsvButton: 'CSV로 내보내기',
    ScanStoppedEarlyTitle: '검사가 조기에 중지되었습니다 — SharePoint가 이 테넌트를 제한하고 있습니다.',
    SiteCollectionsScannedBeforeStopping: '중지 전에 {1}개 사이트 모음 중 {0}개가 검사되었습니다. ',
    ResultsBelowCoverOnlyPre: '아래 결과는 검사된 항목만 다루며',
    NotWord: '완전한 감사가 아닙니다',
    ResultsBelowCoverOnlyPost: '. 이 상황에서 검사는 스스로 중지됩니다. 요청을 계속 보내는 것이 제한을 유지시키기 때문입니다. 몇 분 기다린 후',
    ConcurrentRequestsWord: '동시 요청',
    SetTo1Or2InSettings: '을 설정에서 1 또는 2로 설정하고 다시 실행하세요.',
    ThrottledScanMessage: 'SharePoint가 이 검사를 제한했습니다({0}개 요청이 속도 제한되어 재시도되었습니다).',
    OfEverythingScannedPre: '검사된 모든 항목 중,',
    ItemCountSingular: '{0}개 항목',
    ItemCountPlural: '{0}개 항목',
    CouldNotBeConfirmedText: '은(는) 재시도 후에도 확인할 수 없었습니다(정확히 어떤 항목인지는 아래의 "완전히 읽을 수 없음" 알림을 참조하세요) — 이 실패는 용량과 관련된 것이며 실제 권한을 반영한 것이 아닙니다. 이 보고서의 다른 모든 항목은 성공적으로 읽혔으며 신뢰할 수 있습니다.',
    DespiteThrottlingText: '제한에도 불구하고 재시도 후 모든 항목이 성공적으로 확인되었으므로 이 보고서는 완전합니다.',
    ForCleanRunPre: '깨끗한 실행을 위해 몇 분 기다린 후',
    ValueInSettingsPost: '값을 설정에서 낮춰 다시 검사하세요.',
    OneItemWord: '1개 항목',
    NItemsWord: '{0}개 항목',
    OutOfScannedCouldNotBeRead: '검사된 {0}개 항목 중 현재 액세스 권한으로 읽을 수 없었습니다 —',
    PermissionAssignmentsForItAreNotShown: ' 권한 할당이 표시되지 않습니다. ',
    PermissionAssignmentsForThoseAreNotShown: ' 권한 할당이 표시되지 않습니다. ',
    RestOfReportReadSuccessfully: '하지만 이 보고서의 나머지 부분은 성공적으로 읽혔습니다.',
    RunScanAsSiteOwnerPre: '아래의 거부된 항목에 대한 전체 세부 정보를 보려면',
    SiteOwnerWord: '사이트 소유자',
    RunScanAsSiteOwnerPost: '로 검사를 실행하세요.',
    AndNMoreText: '…외 {0}개 더',
    GroupExpansionSkippedPre: '그룹 구성원 확장이 건너뛰어졌습니다 — Graph 권한',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: '이(가) 이 테넌트에서 승인되지 않았습니다. SharePoint 관리자 또는 전역 관리자가',
    SharePointAdminCenterPath: 'SharePoint 관리 센터 → 고급 → API 액세스',
    ScanIncompleteItemsMessage: '{0}개 항목은 일시적인 오류(권한 문제 아님)로 인해 완전히 읽을 수 없어 대체 방법으로 상위 항목의 권한과 함께 표시됩니다 — 이는 실제 액세스 권한을 반영하지 않을 수 있습니다. 이러한 항목을 다시 시도하려면 검사를 다시 실행하세요.',
    FilterByNamePathUserPlaceholder: '이름, 경로 또는 사용자/그룹으로 필터링…',
    FilterResultsLabel: '결과 필터링',
    ExternalUsersOnlyExtLabel: '외부 사용자만 (#ext#)',
    ShowingOfCount: '{1}개 중 {0}개 표시 중',
    ScanResultsLabel: '검사 결과',
    PermissionsColumnHeader: '권한',
    CollapsePermissionsLabel: '권한 축소',
    ExpandPermissionsLabel: '권한 확장',
    HiddenFromSearchBadge: '검색에서 숨김',
    AssignmentCountSingular: '{0}개 할당',
    AssignmentCountPlural: '{0}개 할당',
    LoadMoreRemainingButton: '더 불러오기(남은 {0}개)',
    LoadingUsersStatus: '사용자를 로드하는 중…',
    ConnectedUserSingular: '연결됨 — {0}명의 사용자를 찾았습니다',
    ConnectedUserPlural: '연결됨 — {0}명의 사용자를 찾았습니다',
    CheckingAccessForStatus: '{0}에 대한 액세스를 확인하는 중…',
    FullSiteAccessDetectedStatus: '전체 사이트 액세스가 감지되었습니다.',
    AccessibleLocationsFoundSingular: '액세스 가능한 위치 {0}개를 찾았습니다.',
    AccessibleLocationsFoundPlural: '액세스 가능한 위치 {0}개를 찾았습니다.',
    NoAccessibleLocationsFoundStatus: '액세스 가능한 위치를 찾을 수 없습니다.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — 사용자 액세스 검사 완료',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: '새 검사',
    NoUserAccessScansSavedYet: '아직 저장된 사용자 액세스 검사가 없습니다.',
    UserColumnHeader: '사용자',
    LocationsColumnHeader: '위치',
    FullControlBadge: '모든 권한',
    DeleteThisRecordTitle: '이 레코드 삭제',
    SelectAUserFieldLabel: '사용자 선택',
    SearchUsersPlaceholder: '사용자 검색…',
    SelectAUserToCheckAccessLabel: '액세스를 확인할 사용자 선택',
    NotInThisSiteLabel: '이 사이트에 없음',
    ScanInProgressLabel: '검사가 진행 중입니다',
    ScanningUserAccessLabel: '사용자 액세스 검사 중',
    ScanningStatus: '검사 중…',
    FullControlAccessPre: '이 사용자는 전체 사이트에 대해',
    FullControlWord: '모든 권한',
    FullControlAccessPost: '또는 소유자 수준 액세스 권한을 가지고 있습니다 — 모든 라이브러리와 폴더에 액세스할 수 있습니다.',
    SiteLevelPermissionCouldNotBeDeterminedPre: '사이트 수준 권한을 확인할 수 없습니다 — 이 사이트는 Microsoft 365 그룹 액세스를 사용하는 것으로 보입니다. 이를 표시하려면 SharePoint 관리자가',
    SiteLevelPermissionCouldNotBeDeterminedMid: '에서 Graph 권한을 승인해야 합니다.',
    ShowingSiteLevelAccessOnlyPre: '기본 SharePoint 그룹 멤버십을 기반으로',
    SiteLevelAccessOnlyWord: '사이트 수준 액세스만',
    ShowingSiteLevelAccessOnlyMid: '표시됩니다. 라이브러리, 폴더 및 파일의 고유 권한을 읽을 수 없어 표시되지 않습니다. 전체 결과를 얻으려면 이 검사를',
    UserAccessCouldNotBeDeterminedPre: '이 사용자의 액세스를 확인할 수 없습니다. 권한 할당을 읽으려면',
    UserAccessCouldNotBeDeterminedPost: '권한(사이트 소유자 이상)이 필요하며, 이 사용자는 사이트의 기본 소유자, 구성원 또는 방문자 그룹의 구성원이 아닌 것으로 보입니다.',
    SiteLevelAccessBannerPre: '이 사용자는 사이트 수준 액세스 권한을 가지고 있습니다. 아래에는',
    UniquePermissionAssignmentsWord: '고유한 권한 할당이 있는',
    SiteLevelAccessBannerPost: '위치만 표시됩니다 — 다른 모든 콘텐츠는 목록 상단에 표시된 사이트 수준 권한을 통해 액세스할 수 있습니다.',
    UserAccessResultsLabel: '사용자 액세스 결과',
  };
});
