define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions-konfigurasjon',
    PropertyPane_GroupName: 'Generelt',
    PropertyPane_DefaultViewLabel: 'Standardvisning ved åpning',
    PropertyPane_View_Home: 'Hjem',
    PropertyPane_View_Report: 'Tillatelsesrapport',
    PropertyPane_View_Explorer: 'Tillatelsesutforsker',
    PropertyPane_View_UserAccess: 'Brukertilgang',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/minnettsted',
    ConnectButton: 'Opret forbindelse',
    CancelButton: 'Annuller',
    ChangeUrlButton: 'Skift URL',
    SettingsLabel: 'Innstillinger',
    RenderErrorTitle: 'Smart Permissions — Gengivelsesfejl',
    RenderErrorMessageLabel: 'Meddelelse:',
    RenderErrorStackLabel: 'Stak:',
    RenderErrorNoStack: '(ingen stak tilgængelig)',
    BackButton: 'Tilbage',
    BackToHomeLabel: 'Tilbage til startside',
    ExplorerCardTitle: 'Tillatelsesudforsker',
    ExplorerCardAlt: 'Tillatelsesudforsker med mappetræ og tillatelsespanel',
    ExplorerCardDesc: 'Gennemse enhver mappe eller fil og se øjeblikkeligt, hvem der har tilgang — med opslag i realtid.',
    ExplorerCardButton: 'Åbn tillatelsesudforsker',
    ReportCardTitle: 'Tillatelsesrapport',
    ReportCardAlt: 'Konfigurationsskærm til tillatelsesrapport',
    ReportCardDesc: 'Generér en farvekodet Excel-rapport over hver unik tillatelsestildeling på dit nettsted.',
    ReportCardButton: 'Kør tillatelsesrapport',
    UserAccessCardTitle: 'Brukertilgang',
    UserAccessCardAlt: 'Skærmbillede for brukertilgang med tilgængelige placeringer for en valgt bruker',
    UserAccessCardDesc: 'Slå en bruker op for at se alle steder, de kan tilgå på et nettsted, med deres nøjagtige tillatelsesniveau.',
    UserAccessCardButton: 'Kontrollér brukertilgang',
    SiteOwnerRequiredTitle: 'Tilgang som nettstedseier er påkrævet —',
    SiteOwnerRequiredDesc: 'Disse værktøjer kræver tilgang som nettstedseier. Kontakt en nettstedseier, hvis du har spørgsmål om tillatelser.',
    HomeSubtitle: 'Undersøg og forstå SharePoint-tillatelser — uden PowerShell.',
    RequiresSiteOwnerTooltip: 'Kræver tilgang som nettstedseier',
    HomeNoteLabel: 'Bemærk:',
    HomeNoteText: 'Denne webdel kører som den aktuelt loggede bruker. Den kan kun se nettsteder og elementer, som denne bruker har tilgang til. Brug en konto med passende læsetilgang til alle nettsteder for et fuldt leietakerscan.',
    SettingsTitle: 'Innstillinger',
    LibrariesSectionTitle: 'Biblioteker',
    IncludeHiddenLabel: 'Inkluder system- og skjulte biblioteker',
    IncludeHiddenTooltip: 'Hvis markeret, inkluderes stilbibliotek, formularskabeloner, nettstedsaktiver og andre biblioteker, der er skjult fra standardvisninger. Gælder for alle værktøjer.',
    MoreInfoHiddenLibrariesLabel: 'Mere information om skjulte biblioteker',
    ExcludeLimitedAccessLabel: 'Udelad poster med begrænset tilgang',
    ExcludeLimitedAccessTooltip: 'Skjuler brukere og grupper, hvis eneste SharePoint-tillatelse er Begrænset tilgang — tildeles automatisk, når filer deles via links. Gælder for tillatelsesrapport, Udforsker og brukertilgang.',
    MoreInfoLimitedAccessLabel: 'Mere information om begrænset tilgang',
    ExcludeSharingLinksLabel: 'Udelad poster for delingslinks',
    ExcludeSharingLinksTooltip: 'Skjuler de interne "SharingLinks.*"-grupper, som SharePoint automatisk opretter til "Alle med linket" og "Bestemte personer"-delingslinks. Gælder for tillatelsesrapport, Udforsker og brukertilgang.',
    MoreInfoSharingLinksLabel: 'Mere information om delingslinks',
    PerformanceSectionTitle: 'Ydeevne',
    ConcurrentRequestsLabel: 'Samtidige API-anmodninger:',
    ConcurrencyTooltip: 'Hvor mange SharePoint API-anmodninger der køres parallelt under skanninger af tillatelsesrapport, brukertilgang og baggrundskontroller i Udforsker. Højere værdier er hurtigere, men udløser oftere begrænsning (HTTP 429). 3–5 anbefales.',
    MoreInfoConcurrencyLabel: 'Mere information om samtidighed',
    ConcurrencyHint: 'Højere værdier scanner hurtigere, men kan udløse SharePoint-begrænsning. Anbefalet: 3–5.',
    GroupMemberCapLabel: 'Grænse for visning af gruppemedlemmer:',
    GroupMemberCapTooltip: 'Maksimalt antal medlemmer vist pr. gruppe, når "Udvid gruppemedlemmer" er aktiveret. Større grupper begrænses, og der vises en meddelelse. Forøgelse bruker mere hukommelse.',
    MoreInfoGroupMemberCapLabel: 'Mere information om grænsen for gruppemedlemmer',
    GroupMemberCapHint: 'Grupper større end denne grænse viser en afkortningsmeddelelse. Standard: 500.',
    DefaultViewSectionTitle: 'Standardvisning ved indlæsning',
    DefaultViewInstructionsIntro: 'For at ændre, hvilken skærm der åbnes, når webdelen indlæses første gang, skal du redigere webdelens egenskaber:',
    DefaultViewStep1Pre: 'Sæt SharePoint-siden i',
    DefaultViewStep1Post: '-tilstand.',
    DefaultViewStep2Pre: 'Klik på',
    DefaultViewStep2Post: '-ikonet på Smart Permissions-webdelen.',
    DefaultViewStep3Pre: 'I egenskabspanelet skal du vælge en visning fra rullelisten',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'siden for at gemme ændringen.',
    EditModeWord: 'Redigerings',
    PencilEditWord: 'blyant (rediger)',
    DefaultViewOnOpenWord: 'Standardvisning ved åbning',
    RepublishWord: 'Genudgiv',
    SiteOwnersLabel: 'Nettstedseiere:',
    EveryoneClaimLabel: 'Alle',
    EveryoneExceptExternalClaimLabel: 'Alle undtagen eksterne brukere',
    PermissionAssignmentsLabel: 'Tillatelsestildelinger',
    UserGroupColumnHeader: 'Bruker / Gruppe',
    TypeColumnHeader: 'Type',
    PermissionLevelColumnHeader: 'Tillatelsesniveau',
    TenantWideAccessSuffix: '— leietakerdækkende tilgang',
    SecurityGroupType: 'Sikkerhedsgruppe',
    SpGroupType: 'SP-gruppe',
    UserType: 'Bruker',
    CheckAccessForLabel: 'Kontrollér tilgang for {0}',
    ContainsUniqueAndExternalTooltip: 'Indeholder elementer med unikke tillatelser og ekstern brukertilgang',
    ContainsUniqueTooltip: 'Indeholder elementer med unikke tillatelser',
    ContainsExternalTooltip: 'Indeholder elementer med ekstern brukertilgang',
    UniqueBadge: 'Unik',
    ExternalAccessDetectedTooltip: 'Ekstern brukertilgang registreret',
    ConnectingStatus: 'Opretter forbindelse…',
    ConnectedLibrarySingular: 'Forbundet — {0} bibliotek fundet',
    ConnectedLibraryPlural: 'Forbundet — {0} biblioteker fundet',
    ConnectionFailedError: 'Forbindelsen mislykkedes: {0}',
    LibraryEmptyStatus: 'Dette bibliotek er tomt.',
    ErrorLoadingLibrary: 'Fejl ved indlæsning af bibliotek: {0}',
    ErrorLoadingContents: 'Fejl ved indlæsning af indhold',
    LibraryFieldLabel: 'Bibliotek',
    HiddenFromSearchSuffix: '{0} (skjult fra søgning)',
    UniquePermissionsOnlyToggle: 'Kun unikke tillatelser',
    ExternalUsersOnlyToggle: 'Kun eksterne brukere',
    LegendLabel: 'Forklaring:',
    LegendItemHasUnique: 'Element har unikke tillatelser',
    LegendContainsUniqueBelow: 'Indeholder unikke tillatelser nedenfor',
    LegendContainsExternalBelow: 'Indeholder ekstern brukertilgang nedenfor',
    LegendExternalOnItem: 'Ekstern brukertilgang på dette element',
    ViewingWithMemberAccessTitle: 'Ser med medlemstilgang',
    ViewingWithMemberAccessDesc1: '— tillatelsestildelinger er ikke synlige. At se, hvem der har tilgang, kræver rettigheden',
    ManagePermissionsWord: 'Administrer tillatelser',
    ViewingWithMemberAccessDesc2: '(nettstedseier eller højere). Du kan stadig se, hvilke elementer der har brudt nedarvning, ved hjælp af ↓-indikatorerne. Brug værktøjet',
    UserAccessWord: 'Brukertilgang',
    ViewingWithMemberAccessDesc3: 'for at se steder, du kan tilgå.',
    FoldersAndFilesLabel: 'Mapper og filer',
    SelectFolderOrFilePrompt: 'Vælg en mappe eller fil for at se dens tillatelser.',
    UniquePermissionsBadge: 'Unikke tillatelser',
    InheritedBadge: 'Nedarvet',
    ExpandGroupMembersLabel: 'Udvid gruppemedlemmer',
    ShowParentPermissionsLabel: 'Vis overordnede tillatelser',
    InheritsFromParentText: 'Dette element nedarver tillatelser fra sit overordnede element.',
    YourAccessLabel: 'Din tilgang:',
    PermissionsNotVisibleNodeText: 'Tillatelsestildelinger er ikke synlige — rettigheden Administrer tillatelser (nettstedseier eller højere) kræves for at se, hvem der har tilgang til dette element.',
    NoExternalUsersDirectAccessText: 'Ingen eksterne brukere har direkte tilgang til dette element.',
    InheritedFromLabel: 'Nedarvet fra:',
    ParentPermissionsNotVisibleText: 'Det overordnede elements tillatelsestildelinger er ikke synlige — kræver rettigheden Administrer tillatelser (nettstedseier eller højere).',
    NoPermissionsFoundOnParentText: 'Ingen tillatelser fundet på det overordnede element.',
    StartingScanStatus: 'Starter skanning…',
    ScanCancelledStatus: 'Skanning annulleret — {0} objekt(er) indsamlet før annullering.',
    ScanCompleteStatus: 'Skanning fuldført — {0} objekt(er) fundet, {1} med unikke tillatelser.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Skanning fuldført',
    ScanCompleteNotificationBody: '{0} objekter, {1} med unikke tillatelser.',
    CancelledStatus: 'Annulleret.',
    GenericErrorPrefix: 'Fejl: {0}',
    ExportErrorPrefix: 'Eksportfejl: {0}',
    ScopeSiteOnly: 'Kun nettsted',
    ScopeLibraries: 'Biblioteker',
    ScopeFolders: 'Mapper',
    ScopeFilesAndFolders: 'Filer og mapper',
    ScanInProgressConfirm: 'En skanning er i gang. Forlad og annuller?',
    HistoryButton: 'Historik',
    BackToHistoryButton: 'Tilbage til historik',
    ComparingLabel: 'Sammenligner',
    CompareMismatchWarning: 'Disse rapporter blev taget med forskellige nettsteder eller skanningsinnstillinger — forskellene nedenfor kan afspejle de ændrede skanningsinnstillinger snarere end faktiske tillatelsesændringer.',
    NoPermissionDifferencesFound: 'Ingen tillatelsesforskelle fundet mellem disse to rapporter.',
    PermissionChangesHeaderSingular: 'Tillatelsesændringer ({0} objekt)',
    PermissionChangesHeaderPlural: 'Tillatelsesændringer ({0} objekter)',
    ChangeColumnHeader: 'Ændring',
    BeforeColumnHeader: 'Før',
    AfterColumnHeader: 'Efter',
    AddedBadge: 'Tilføjet',
    RemovedBadge: 'Fjernet',
    ChangedBadge: 'Ændret',
    InheritanceChangedHeader: 'Nedarvning ændret ({0})',
    NameColumnHeader: 'Navn',
    PathColumnHeader: 'Sti',
    NowColumnHeader: 'Nu',
    UniqueInheritanceBrokenBadge: 'Unik (nedarvning brudt)',
    InheritedRestoredBadge: 'Nedarvet (gendannet)',
    NewObjectsHeader: 'Nye objekter',
    RemovedObjectsHeader: 'Fjernede objekter',
    BackToScanButton: 'Tilbage til skanning',
    CompareSelectedButton: 'Sammenlign valgte',
    NoReportsSavedYet: 'Ingen rapporter gemt endnu.',
    SelectForCompareLabel: 'Vælg til sammenligning',
    DateTimeColumnHeader: 'Dato / Tid',
    SiteColumnHeader: 'Nettsted',
    ScopeColumnHeader: 'Omfang',
    ObjectsColumnHeader: 'Objekter',
    UniqueColumnHeader: 'Unikke',
    SelectReportForCompareLabel: 'Vælg rapport fra {0} til sammenligning',
    AllSitesPrefix: 'Alle nettsteder · ',
    PlusSubsitesSuffix: ' + undernettsteder',
    ExportingStatus: 'Eksporterer…',
    ExportButton: 'Eksporter',
    DeleteThisReportTitle: 'Slet denne rapport',
    ScanAllSiteCollectionsLabel: 'Skann alle nettstedssamlinger i denne leietaker (kun tilgængelig på rodnettstedet)',
    AllSitesSearchCaveat: 'Nettstedslisten kommer fra søgning og medtager muligvis ikke alle nettstedssamlinger — meget nyoprettede nettsteder, eller nettsteder udelukket fra søgeindekset, kan mangle.',
    IncludeSubsitesLabel: 'Inkluder undernettsteder (scanner hvert undernettsted under dette nettsted)',
    ScanDepthFieldLabel: 'Skanningsdybde',
    FolderDepthLimitLabel: 'Grænse for mappedybde:',
    ExpandGroupMembersInReportLabel: 'Udvid gruppemedlemmer i rapporten (SharePoint-grupper, sikkerhedsgrupper og M365-grupper)',
    LibrariesToScanLabel: 'Biblioteker der skal scannes',
    OfSelectedCount: '{0} af {1} valgt',
    AllButton: 'Alle',
    NoneButton: 'Ingen',
    LoadingLibrariesStatus: 'Indlæser biblioteker…',
    RunReportButton: 'Kør rapport',
    ItemsFoundSoFar: '{0} elementer fundet indtil videre',
    LibraryOfProgress: 'Bibliotek {0} af {1}',
    ScanCancelledPartialResults: 'Skanning annulleret — delvise resultater',
    ScanCompleteLabel: 'Skanning fuldført',
    ObjectsCountBadge: '{0} objekter',
    UniqueCountBadge: '{0} unikke',
    InheritedCountBadge: '{0} nedarvet',
    GeneratingExcelStatus: 'Genererer Excel…',
    ExportFilteredRowsButton: 'Eksporter {0} filtrerede rækker',
    ExportToExcelButton: 'Eksporter til Excel',
    ExportToCsvButton: 'Eksporter til CSV',
    ScanStoppedEarlyTitle: 'Skanning stoppet tidligt — SharePoint begrænser denne leietaker.',
    SiteCollectionsScannedBeforeStopping: '{0} af {1} nettstedssamlinger blev scannet, før den stoppede. ',
    ResultsBelowCoverOnlyPre: 'Resultaterne nedenfor dækker kun det, der blev scannet, og er',
    NotWord: 'ikke',
    ResultsBelowCoverOnlyPost: 'en fuldstændig revision. Skanningen stopper sig selv i denne situation, fordi det er fortsat afsendelse af anmodninger, der opretholder begrænsningen. Vent flere minutter, og kør derefter igen med',
    ConcurrentRequestsWord: 'Samtidige anmodninger',
    SetTo1Or2InSettings: 'sat til 1 eller 2 i Innstillinger.',
    ThrottledScanMessage: 'SharePoint begrænsede denne skanning ({0} anmodning(er) blev hastighedsbegrænset og gentaget).',
    OfEverythingScannedPre: 'Af alt det scannede,',
    ItemCountSingular: '{0} element',
    ItemCountPlural: '{0} elementer',
    CouldNotBeConfirmedText: 'kunne ikke bekræftes efter gentagelse (se meddelelsen "kunne ikke læses fuldt ud" nedenfor for at se præcis hvilke) — den fejl var kapacitetsrelateret, ikke en afspejling af deres faktiske tillatelser. Alle andre elementer i denne rapport blev læst med succes og kan stoles på.',
    DespiteThrottlingText: 'På trods af begrænsningen blev hvert element stadig bekræftet med succes efter gentagelse, så denne rapport er komplet.',
    ForCleanRunPre: 'For en ren kørsel, vent et par minutter, og skann igen med en lavere værdi for',
    ValueInSettingsPost: 'i Innstillinger.',
    OneItemWord: '1 element',
    NItemsWord: '{0} element(er)',
    OutOfScannedCouldNotBeRead: 'ud af {0} scannede kunne ikke læses med din nuværende tilgang —',
    PermissionAssignmentsForItAreNotShown: ' tillatelsestildelinger vises ikke, ',
    PermissionAssignmentsForThoseAreNotShown: ' tillatelsestildelinger vises ikke, ',
    RestOfReportReadSuccessfully: 'men resten af denne rapport blev læst med succes.',
    RunScanAsSiteOwnerPre: 'Kør skanningen som',
    SiteOwnerWord: 'nettstedseier',
    RunScanAsSiteOwnerPost: 'for at se fulde detaljer for de nægtede elementer nedenfor.',
    AndNMoreText: '…og {0} mere',
    GroupExpansionSkippedPre: 'Udvidelse af gruppemedlemmer blev sprunget over — Graph-tillatelsen',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'er ikke blevet godkendt i denne leietaker. En SharePoint- eller global administrator kan godkende den i',
    SharePointAdminCenterPath: 'SharePoint-administrationscenter → Avanceret → API-tilgang',
    ScanIncompleteItemsMessage: '{0} element(er) kunne ikke læses fuldt ud på grund af en midlertidig fejl (ikke et tillatelsesproblem) og vises med det overordnede elements tillatelser som en nødløsning — dette afspejler muligvis ikke deres faktiske tilgang. Kør skanningen igen for at prøve disse elementer igen.',
    FilterByNamePathUserPlaceholder: 'Filtrer efter navn, sti eller bruker/gruppe…',
    FilterResultsLabel: 'Filtrer resultater',
    ExternalUsersOnlyExtLabel: 'Kun eksterne brukere (#ext#)',
    ShowingOfCount: 'Viser {0} af {1}',
    ScanResultsLabel: 'Skanningsresultater',
    PermissionsColumnHeader: 'Tillatelser',
    CollapsePermissionsLabel: 'Skjul tillatelser',
    ExpandPermissionsLabel: 'Udvid tillatelser',
    HiddenFromSearchBadge: 'Skjult fra søgning',
    AssignmentCountSingular: '{0} tildeling',
    AssignmentCountPlural: '{0} tildelinger',
    LoadMoreRemainingButton: 'Indlæs flere ({0} tilbage)',
    LoadingUsersStatus: 'Indlæser brukere…',
    ConnectedUserSingular: 'Forbundet — {0} bruker fundet',
    ConnectedUserPlural: 'Forbundet — {0} brukere fundet',
    CheckingAccessForStatus: 'Kontrollerer tilgang for {0}…',
    FullSiteAccessDetectedStatus: 'Fuld nettstedstilgang registreret.',
    AccessibleLocationsFoundSingular: '{0} tilgængelig placering fundet.',
    AccessibleLocationsFoundPlural: '{0} tilgængelige placeringer fundet.',
    NoAccessibleLocationsFoundStatus: 'Ingen tilgængelige placeringer fundet.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Brukertilgangsskanning fuldført',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Ny skanning',
    NoUserAccessScansSavedYet: 'Ingen brukertilgangsskanninger gemt endnu.',
    UserColumnHeader: 'Bruker',
    LocationsColumnHeader: 'Placeringer',
    FullControlBadge: 'Fuld kontrol',
    DeleteThisRecordTitle: 'Slet denne post',
    SelectAUserFieldLabel: 'Vælg en bruker',
    SearchUsersPlaceholder: 'Søg brukere…',
    SelectAUserToCheckAccessLabel: 'Vælg en bruker for at kontrollere tilgang',
    NotInThisSiteLabel: 'Ikke på dette nettsted',
    ScanInProgressLabel: 'Skanning i gang',
    ScanningUserAccessLabel: 'Scanner brukertilgang',
    ScanningStatus: 'Scanner…',
    FullControlAccessPre: 'Denne bruker har',
    FullControlWord: 'Fuld kontrol',
    FullControlAccessPost: 'eller eierniveau-tilgang til hele nettstedet — alle biblioteker og mapper er tilgængelige.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Tillatelse på nettstedsniveau kunne ikke bestemmes — dette nettsted bruker sandsynligvis Microsoft 365-gruppetilgang. For at vise det skal en SharePoint-administrator godkende tillatelsen',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'i',
    ShowingSiteLevelAccessOnlyPre: 'Viser kun',
    SiteLevelAccessOnlyWord: 'tilgang på nettstedsniveau',
    ShowingSiteLevelAccessOnlyMid: ', baseret på standard SharePoint-gruppemedlemskab. Unikke tillatelser på biblioteker, mapper og filer kunne ikke læses og vises ikke. For fuldstændige resultater, kør denne skanning som',
    UserAccessCouldNotBeDeterminedPre: 'Denne brukers tilgang kunne ikke bestemmes. At læse tillatelsestildelinger kræver rettigheden',
    UserAccessCouldNotBeDeterminedPost: '(nettstedseier eller højere), og denne bruker synes ikke at være medlem af nettstedets standardgrupper for eiere, medlemmer eller besøgende.',
    SiteLevelAccessBannerPre: 'Denne bruker har tilgang på nettstedsniveau. Kun placeringer med',
    UniquePermissionAssignmentsWord: 'unikke tillatelsestildelinger',
    SiteLevelAccessBannerPost: 'vises nedenfor — alt andet indhold er tilgængeligt via tillatelsen på nettstedsniveau vist øverst på listen.',
    UserAccessResultsLabel: 'Resultater for brukertilgang',
  };
});
