define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions-configuratie',
    PropertyPane_GroupName: 'Algemeen',
    PropertyPane_DefaultViewLabel: 'Standaardweergave bij openen',
    PropertyPane_View_Home: 'Start',
    PropertyPane_View_Report: 'Machtigingenrapport',
    PropertyPane_View_Explorer: 'Machtigingenverkenner',
    PropertyPane_View_UserAccess: 'Gebruikerstoegang',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mijnsite',
    ConnectButton: 'Verbinden',
    CancelButton: 'Annuleren',
    ChangeUrlButton: 'URL wijzigen',
    SettingsLabel: 'Instellingen',
    RenderErrorTitle: 'Smart Permissions — Weergavefout',
    RenderErrorMessageLabel: 'Bericht:',
    RenderErrorStackLabel: 'Stack:',
    RenderErrorNoStack: '(geen stack beschikbaar)',
    BackButton: 'Terug',
    BackToHomeLabel: 'Terug naar start',
    ExplorerCardTitle: 'Machtigingenverkenner',
    ExplorerCardAlt: 'Machtigingenverkenner met mappenstructuur en machtigingenpaneel',
    ExplorerCardDesc: 'Blader door elke map of bestand en zie direct wie toegang heeft — met live, realtime machtigingscontroles.',
    ExplorerCardButton: 'Machtigingenverkenner openen',
    ReportCardTitle: 'Machtigingenrapport',
    ReportCardAlt: 'Configuratiescherm voor machtigingenrapport',
    ReportCardDesc: 'Genereer een kleurgecodeerd Excel-rapport van elke unieke machtigingstoewijzing op uw site.',
    ReportCardButton: 'Machtigingenrapport uitvoeren',
    UserAccessCardTitle: 'Gebruikerstoegang',
    UserAccessCardAlt: 'Scherm voor gebruikerstoegang met toegankelijke locaties voor een geselecteerde gebruiker',
    UserAccessCardDesc: 'Zoek een gebruiker op om elke locatie te zien die deze op een site kan openen, met het exacte machtigingsniveau.',
    UserAccessCardButton: 'Gebruikerstoegang controleren',
    SiteOwnerRequiredTitle: 'Toegang als Site-eigenaar vereist —',
    SiteOwnerRequiredDesc: 'Deze tools vereisen toegang als Site-eigenaar. Neem contact op met een site-eigenaar als u vragen hebt over machtigingen.',
    HomeSubtitle: 'Controleer en begrijp SharePoint-machtigingen — zonder PowerShell.',
    RequiresSiteOwnerTooltip: 'Vereist toegang als Site-eigenaar',
    HomeNoteLabel: 'Opmerking:',
    HomeNoteText: 'Dit webonderdeel wordt uitgevoerd als de momenteel aangemelde gebruiker. Het kan alleen sites en items zien waartoe die gebruiker toegang heeft. Gebruik voor een volledige tenantscan een account met passende leestoegang tot alle sites.',
    SettingsTitle: 'Instellingen',
    LibrariesSectionTitle: 'Bibliotheken',
    IncludeHiddenLabel: 'Systeem- en verborgen bibliotheken opnemen',
    IncludeHiddenTooltip: 'Indien aangevinkt, worden Stijlbibliotheek, Formuliersjablonen, Site-assets en andere bibliotheken opgenomen die verborgen zijn in standaardweergaven. Geldt voor alle tools.',
    MoreInfoHiddenLibrariesLabel: 'Meer informatie over verborgen bibliotheken',
    ExcludeLimitedAccessLabel: 'Items met Beperkte toegang uitsluiten',
    ExcludeLimitedAccessTooltip: 'Verbergt gebruikers en groepen wier enige SharePoint-machtiging Beperkte toegang is — automatisch toegewezen wanneer bestanden via links worden gedeeld. Geldt voor Machtigingenrapport, Verkenner en Gebruikerstoegang.',
    MoreInfoLimitedAccessLabel: 'Meer informatie over Beperkte toegang',
    ExcludeSharingLinksLabel: 'Items met Deelkoppelingen uitsluiten',
    ExcludeSharingLinksTooltip: 'Verbergt de interne "SharingLinks.*"-groepen die SharePoint automatisch aanmaakt voor "Iedereen met de link" en "Specifieke personen"-deelkoppelingen. Geldt voor Machtigingenrapport, Verkenner en Gebruikerstoegang.',
    MoreInfoSharingLinksLabel: 'Meer informatie over deelkoppelingen',
    PerformanceSectionTitle: 'Prestaties',
    ConcurrentRequestsLabel: 'Gelijktijdige API-aanvragen:',
    ConcurrencyTooltip: 'Hoeveel SharePoint API-aanvragen parallel worden uitgevoerd tijdens scans voor Machtigingenrapport, Gebruikerstoegang en achtergrondcontroles van de Verkenner. Hogere waarden zijn sneller maar veroorzaken eerder throttling (HTTP 429). 3–5 wordt aanbevolen.',
    MoreInfoConcurrencyLabel: 'Meer informatie over gelijktijdigheid',
    ConcurrencyHint: 'Hogere waarden scannen sneller maar kunnen SharePoint-throttling veroorzaken. Aanbevolen: 3–5.',
    GroupMemberCapLabel: 'Weergavelimiet groepsleden:',
    GroupMemberCapTooltip: 'Maximaal aantal weergegeven leden per groep wanneer "Groepsleden uitvouwen" is ingeschakeld. Grotere groepen worden begrensd en er wordt een melding getoond. Verhogen gebruikt meer geheugen.',
    MoreInfoGroupMemberCapLabel: 'Meer informatie over de groepsledenlimiet',
    GroupMemberCapHint: 'Groepen groter dan deze limiet tonen een afkapmelding. Standaard: 500.',
    DefaultViewSectionTitle: 'Standaardweergave bij laden',
    DefaultViewInstructionsIntro: 'Om te wijzigen welk scherm opent wanneer het webonderdeel voor het eerst wordt geladen, bewerkt u de eigenschappen van het webonderdeel:',
    DefaultViewStep1Pre: 'Zet de SharePoint-pagina in',
    DefaultViewStep1Post: 'modus.',
    DefaultViewStep2Pre: 'Klik op het',
    DefaultViewStep2Post: 'pictogram op het Smart Permissions-webonderdeel.',
    DefaultViewStep3Pre: 'Kies in het eigenschappenvenster een weergave in de vervolgkeuzelijst',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'de pagina om de wijziging op te slaan.',
    EditModeWord: 'Bewerken',
    PencilEditWord: 'potlood (bewerken)',
    DefaultViewOnOpenWord: 'Standaardweergave bij openen',
    RepublishWord: 'Publiceer',
    SiteOwnersLabel: 'Site-eigenaren:',
    EveryoneClaimLabel: 'Iedereen',
    EveryoneExceptExternalClaimLabel: 'Iedereen behalve externe gebruikers',
    PermissionAssignmentsLabel: 'Machtigingstoewijzingen',
    UserGroupColumnHeader: 'Gebruiker / Groep',
    TypeColumnHeader: 'Type',
    PermissionLevelColumnHeader: 'Machtigingsniveau',
    TenantWideAccessSuffix: '— tenantbrede toegang',
    SecurityGroupType: 'Beveiligingsgroep',
    SpGroupType: 'SP-groep',
    UserType: 'Gebruiker',
    CheckAccessForLabel: 'Toegang controleren voor {0}',
    ContainsUniqueAndExternalTooltip: 'Bevat items met unieke machtigingen en externe gebruikerstoegang',
    ContainsUniqueTooltip: 'Bevat items met unieke machtigingen',
    ContainsExternalTooltip: 'Bevat items met externe gebruikerstoegang',
    UniqueBadge: 'Uniek',
    ExternalAccessDetectedTooltip: 'Externe gebruikerstoegang gedetecteerd',
    ConnectingStatus: 'Verbinden…',
    ConnectedLibrarySingular: 'Verbonden — {0} bibliotheek gevonden',
    ConnectedLibraryPlural: 'Verbonden — {0} bibliotheken gevonden',
    ConnectionFailedError: 'Verbinding mislukt: {0}',
    LibraryEmptyStatus: 'Deze bibliotheek is leeg.',
    ErrorLoadingLibrary: 'Fout bij laden van bibliotheek: {0}',
    ErrorLoadingContents: 'Fout bij laden van inhoud',
    LibraryFieldLabel: 'Bibliotheek',
    HiddenFromSearchSuffix: '{0} (verborgen voor zoeken)',
    UniquePermissionsOnlyToggle: 'Alleen unieke machtigingen',
    ExternalUsersOnlyToggle: 'Alleen externe gebruikers',
    LegendLabel: 'Legenda:',
    LegendItemHasUnique: 'Item heeft unieke machtigingen',
    LegendContainsUniqueBelow: 'Bevat hieronder unieke machtigingen',
    LegendContainsExternalBelow: 'Bevat hieronder externe gebruikerstoegang',
    LegendExternalOnItem: 'Externe gebruikerstoegang op dit item',
    ViewingWithMemberAccessTitle: 'Weergave met Lid-toegang',
    ViewingWithMemberAccessDesc1: '— machtigingstoewijzingen zijn niet zichtbaar. Om te zien wie toegang heeft, is het recht',
    ManagePermissionsWord: 'Machtigingen beheren',
    ViewingWithMemberAccessDesc2: 'vereist (Site-eigenaar of hoger). U kunt nog steeds zien welke items overgenomen machtigingen hebben verbroken via de ↓-indicatoren. Gebruik de tool',
    UserAccessWord: 'Gebruikerstoegang',
    ViewingWithMemberAccessDesc3: 'om locaties te zien waartoe u toegang hebt.',
    FoldersAndFilesLabel: 'Mappen en bestanden',
    SelectFolderOrFilePrompt: 'Selecteer een map of bestand om de machtigingen ervan te bekijken.',
    UniquePermissionsBadge: 'Unieke machtigingen',
    InheritedBadge: 'Overgenomen',
    ExpandGroupMembersLabel: 'Groepsleden uitvouwen',
    ShowParentPermissionsLabel: 'Machtigingen van bovenliggend item tonen',
    InheritsFromParentText: 'Dit item neemt machtigingen over van het bovenliggende item.',
    YourAccessLabel: 'Uw toegang:',
    PermissionsNotVisibleNodeText: 'Machtigingstoewijzingen zijn niet zichtbaar — het recht Machtigingen beheren (Site-eigenaar of hoger) is vereist om te zien wie toegang heeft tot dit item.',
    NoExternalUsersDirectAccessText: 'Geen externe gebruikers hebben directe toegang tot dit item.',
    InheritedFromLabel: 'Overgenomen van:',
    ParentPermissionsNotVisibleText: 'Machtigingstoewijzingen van het bovenliggende item zijn niet zichtbaar — vereist het recht Machtigingen beheren (Site-eigenaar of hoger).',
    NoPermissionsFoundOnParentText: 'Geen machtigingen gevonden op het bovenliggende item.',
    StartingScanStatus: 'Scan wordt gestart…',
    ScanCancelledStatus: 'Scan geannuleerd — {0} object(en) verzameld voor annulering.',
    ScanCompleteStatus: 'Scan voltooid — {0} object(en) gevonden, {1} met unieke machtigingen.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Scan voltooid',
    ScanCompleteNotificationBody: '{0} objecten, {1} met unieke machtigingen.',
    CancelledStatus: 'Geannuleerd.',
    GenericErrorPrefix: 'Fout: {0}',
    ExportErrorPrefix: 'Exportfout: {0}',
    ScopeSiteOnly: 'Alleen site',
    ScopeLibraries: 'Bibliotheken',
    ScopeFolders: 'Mappen',
    ScopeFilesAndFolders: 'Bestanden & mappen',
    ScanInProgressConfirm: 'Er loopt een scan. Verlaten en annuleren?',
    HistoryButton: 'Geschiedenis',
    BackToHistoryButton: 'Terug naar geschiedenis',
    ComparingLabel: 'Vergelijken',
    CompareMismatchWarning: 'Deze rapporten zijn gemaakt met verschillende sites of scanopties — de verschillen hieronder kunnen de gewijzigde scaninstellingen weerspiegelen in plaats van daadwerkelijke machtigingswijzigingen.',
    NoPermissionDifferencesFound: 'Geen verschillen in machtigingen gevonden tussen deze twee rapporten.',
    PermissionChangesHeaderSingular: 'Machtigingswijzigingen ({0} object)',
    PermissionChangesHeaderPlural: 'Machtigingswijzigingen ({0} objecten)',
    ChangeColumnHeader: 'Wijziging',
    BeforeColumnHeader: 'Voor',
    AfterColumnHeader: 'Na',
    AddedBadge: 'Toegevoegd',
    RemovedBadge: 'Verwijderd',
    ChangedBadge: 'Gewijzigd',
    InheritanceChangedHeader: 'Overerving gewijzigd ({0})',
    NameColumnHeader: 'Naam',
    PathColumnHeader: 'Pad',
    NowColumnHeader: 'Nu',
    UniqueInheritanceBrokenBadge: 'Uniek (overerving verbroken)',
    InheritedRestoredBadge: 'Overgenomen (hersteld)',
    NewObjectsHeader: 'Nieuwe objecten',
    RemovedObjectsHeader: 'Verwijderde objecten',
    BackToScanButton: 'Terug naar scan',
    CompareSelectedButton: 'Selectie vergelijken',
    NoReportsSavedYet: 'Nog geen rapporten opgeslagen.',
    SelectForCompareLabel: 'Selecteren om te vergelijken',
    DateTimeColumnHeader: 'Datum / Tijd',
    SiteColumnHeader: 'Site',
    ScopeColumnHeader: 'Bereik',
    ObjectsColumnHeader: 'Objecten',
    UniqueColumnHeader: 'Uniek',
    SelectReportForCompareLabel: 'Rapport van {0} selecteren om te vergelijken',
    AllSitesPrefix: 'Alle sites · ',
    PlusSubsitesSuffix: ' + subsites',
    ExportingStatus: 'Exporteren…',
    ExportButton: 'Exporteren',
    DeleteThisReportTitle: 'Dit rapport verwijderen',
    ScanAllSiteCollectionsLabel: 'Alle sitecollecties in deze tenant scannen (alleen beschikbaar op de hoofdsite)',
    AllSitesSearchCaveat: 'De sitelijst komt uit zoeken en bevat mogelijk niet elke sitecollectie — zeer recent gemaakte sites, of sites die zijn uitgesloten van de zoekindex, kunnen ontbreken.',
    IncludeSubsitesLabel: 'Subsites opnemen (scant elke subsite onder deze site)',
    ScanDepthFieldLabel: 'Scandiepte',
    FolderDepthLimitLabel: 'Mapdiepte-limiet:',
    ExpandGroupMembersInReportLabel: 'Groepsleden uitvouwen in rapport (SharePoint-groepen, beveiligingsgroepen en M365-groepen)',
    LibrariesToScanLabel: 'Te scannen bibliotheken',
    OfSelectedCount: '{0} van {1} geselecteerd',
    AllButton: 'Alle',
    NoneButton: 'Geen',
    LoadingLibrariesStatus: 'Bibliotheken laden…',
    RunReportButton: 'Rapport uitvoeren',
    ItemsFoundSoFar: 'Tot nu toe {0} items gevonden',
    LibraryOfProgress: 'Bibliotheek {0} van {1}',
    ScanCancelledPartialResults: 'Scan geannuleerd — gedeeltelijke resultaten',
    ScanCompleteLabel: 'Scan voltooid',
    ObjectsCountBadge: '{0} objecten',
    UniqueCountBadge: '{0} uniek',
    InheritedCountBadge: '{0} overgenomen',
    GeneratingExcelStatus: 'Excel genereren…',
    ExportFilteredRowsButton: '{0} gefilterde rijen exporteren',
    ExportToExcelButton: 'Exporteren naar Excel',
    ExportToCsvButton: 'Exporteren naar CSV',
    ScanStoppedEarlyTitle: 'Scan voortijdig gestopt — SharePoint beperkt deze tenant (throttling).',
    SiteCollectionsScannedBeforeStopping: '{0} van {1} sitecollecties zijn gescand voordat het stopte. ',
    ResultsBelowCoverOnlyPre: 'De resultaten hieronder dekken alleen wat is gescand en zijn',
    NotWord: 'geen',
    ResultsBelowCoverOnlyPost: 'volledige audit. De scan stopt zichzelf in deze situatie omdat het blijven verzenden van aanvragen de throttling in stand houdt. Wacht enkele minuten en voer opnieuw uit met',
    ConcurrentRequestsWord: 'Gelijktijdige aanvragen',
    SetTo1Or2InSettings: 'ingesteld op 1 of 2 in Instellingen.',
    ThrottledScanMessage: 'SharePoint heeft deze scan beperkt ({0} aanvra(a)g(en) werden beperkt en opnieuw geprobeerd).',
    OfEverythingScannedPre: 'Van alles wat is gescand,',
    ItemCountSingular: '{0} item',
    ItemCountPlural: '{0} items',
    CouldNotBeConfirmedText: 'kon(den) na een nieuwe poging niet worden bevestigd (zie de melding "kon niet volledig worden gelezen" hieronder voor precies welke) — die mislukking was gerelateerd aan capaciteit, geen weerspiegeling van hun werkelijke machtigingen. Alle andere items in dit rapport zijn succesvol gelezen en kunnen worden vertrouwd.',
    DespiteThrottlingText: 'Ondanks de throttling werd elk item na een nieuwe poging toch succesvol bevestigd, dus dit rapport is compleet.',
    ForCleanRunPre: 'Wacht voor een schone uitvoering enkele minuten en scan opnieuw met een lagere waarde voor',
    ValueInSettingsPost: 'in Instellingen.',
    OneItemWord: '1 item',
    NItemsWord: '{0} item(s)',
    OutOfScannedCouldNotBeRead: 'van {0} gescande konden niet worden gelezen met uw huidige toegang —',
    PermissionAssignmentsForItAreNotShown: ' machtigingstoewijzingen worden niet getoond, ',
    PermissionAssignmentsForThoseAreNotShown: ' machtigingstoewijzingen worden niet getoond, ',
    RestOfReportReadSuccessfully: 'maar de rest van dit rapport is succesvol gelezen.',
    RunScanAsSiteOwnerPre: 'Voer de scan uit als',
    SiteOwnerWord: 'Site-eigenaar',
    RunScanAsSiteOwnerPost: 'om volledige details voor de geweigerde item(s) hieronder te zien.',
    AndNMoreText: '…en nog {0}',
    GroupExpansionSkippedPre: 'Het uitvouwen van groepsleden is overgeslagen — de Graph-machtiging',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'is in deze tenant niet goedgekeurd. Een SharePoint- of Globale beheerder kan dit goedkeuren via',
    SharePointAdminCenterPath: 'SharePoint-beheercentrum → Geavanceerd → API-toegang',
    ScanIncompleteItemsMessage: '{0} item(s) konden niet volledig worden gelezen vanwege een tijdelijke fout (geen machtigingsprobleem) en worden getoond met de machtigingen van het bovenliggende item als noodoplossing — dit weerspiegelt mogelijk niet hun werkelijke toegang. Voer de scan opnieuw uit om deze items opnieuw te proberen.',
    FilterByNamePathUserPlaceholder: 'Filteren op naam, pad of gebruiker/groep…',
    FilterResultsLabel: 'Resultaten filteren',
    ExternalUsersOnlyExtLabel: 'Alleen externe gebruikers (#ext#)',
    ShowingOfCount: '{0} van {1} weergegeven',
    ScanResultsLabel: 'Scanresultaten',
    PermissionsColumnHeader: 'Machtigingen',
    CollapsePermissionsLabel: 'Machtigingen samenvouwen',
    ExpandPermissionsLabel: 'Machtigingen uitvouwen',
    HiddenFromSearchBadge: 'Verborgen voor zoeken',
    AssignmentCountSingular: '{0} toewijzing',
    AssignmentCountPlural: '{0} toewijzingen',
    LoadMoreRemainingButton: 'Meer laden ({0} resterend)',
    LoadingUsersStatus: 'Gebruikers laden…',
    ConnectedUserSingular: 'Verbonden — {0} gebruiker gevonden',
    ConnectedUserPlural: 'Verbonden — {0} gebruikers gevonden',
    CheckingAccessForStatus: 'Toegang controleren voor {0}…',
    FullSiteAccessDetectedStatus: 'Volledige sitetoegang gedetecteerd.',
    AccessibleLocationsFoundSingular: '{0} toegankelijke locatie gevonden.',
    AccessibleLocationsFoundPlural: '{0} toegankelijke locaties gevonden.',
    NoAccessibleLocationsFoundStatus: 'Geen toegankelijke locaties gevonden.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Scan gebruikerstoegang voltooid',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Nieuwe scan',
    NoUserAccessScansSavedYet: 'Nog geen gebruikerstoegangsscans opgeslagen.',
    UserColumnHeader: 'Gebruiker',
    LocationsColumnHeader: 'Locaties',
    FullControlBadge: 'Volledig beheer',
    DeleteThisRecordTitle: 'Dit record verwijderen',
    SelectAUserFieldLabel: 'Selecteer een gebruiker',
    SearchUsersPlaceholder: 'Gebruikers zoeken…',
    SelectAUserToCheckAccessLabel: 'Selecteer een gebruiker om de toegang te controleren',
    NotInThisSiteLabel: 'Niet op deze site',
    ScanInProgressLabel: 'Scan bezig',
    ScanningUserAccessLabel: 'Gebruikerstoegang scannen',
    ScanningStatus: 'Scannen…',
    FullControlAccessPre: 'Deze gebruiker heeft',
    FullControlWord: 'Volledig beheer',
    FullControlAccessPost: 'of Eigenaar-niveau-toegang tot de hele site — alle bibliotheken en mappen zijn toegankelijk.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'De machtiging op siteniveau kon niet worden bepaald — deze site gebruikt waarschijnlijk Microsoft 365-groepstoegang. Om dit te tonen, moet een SharePoint-beheerder de machtiging',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'goedkeuren in',
    ShowingSiteLevelAccessOnlyPre: 'Alleen',
    SiteLevelAccessOnlyWord: 'toegang op siteniveau',
    ShowingSiteLevelAccessOnlyMid: 'wordt getoond, op basis van standaard SharePoint-groepslidmaatschap. Unieke machtigingen op bibliotheken, mappen en bestanden konden niet worden gelezen en worden niet getoond. Voer voor volledige resultaten deze scan uit als',
    UserAccessCouldNotBeDeterminedPre: 'De toegang van deze gebruiker kon niet worden bepaald. Het lezen van machtigingstoewijzingen vereist het recht',
    UserAccessCouldNotBeDeterminedPost: '(Site-eigenaar of hoger), en deze gebruiker lijkt geen lid te zijn van de standaardgroepen Eigenaren, Leden of Bezoekers van de site.',
    SiteLevelAccessBannerPre: 'Deze gebruiker heeft toegang op siteniveau. Alleen locaties met',
    UniquePermissionAssignmentsWord: 'unieke machtigingstoewijzingen',
    SiteLevelAccessBannerPost: 'verschijnen hieronder — alle andere inhoud is toegankelijk via de machtiging op siteniveau die bovenaan de lijst wordt getoond.',
    UserAccessResultsLabel: 'Resultaten gebruikerstoegang',
  };
});
