define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Konfiguracja Smart Permissions',
    PropertyPane_GroupName: 'Ogólne',
    PropertyPane_DefaultViewLabel: 'Domyślny widok przy otwarciu',
    PropertyPane_View_Home: 'Strona główna',
    PropertyPane_View_Report: 'Raport uprawnień',
    PropertyPane_View_Explorer: 'Eksplorator uprawnień',
    PropertyPane_View_UserAccess: 'Dostęp użytkownika',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mojawitryna',
    ConnectButton: 'Połącz',
    CancelButton: 'Anuluj',
    ChangeUrlButton: 'Zmień adres URL',
    SettingsLabel: 'Ustawienia',
    RenderErrorTitle: 'Smart Permissions — Błąd renderowania',
    RenderErrorMessageLabel: 'Komunikat:',
    RenderErrorStackLabel: 'Stos:',
    RenderErrorNoStack: '(stos niedostępny)',
    BackButton: 'Wstecz',
    BackToHomeLabel: 'Powrót do strony głównej',
    ExplorerCardTitle: 'Eksplorator uprawnień',
    ExplorerCardAlt: 'Eksplorator uprawnień z drzewem folderów i panelem uprawnień',
    ExplorerCardDesc: 'Przeglądaj dowolny folder lub plik i natychmiast sprawdź, kto ma dostęp — z wyszukiwaniem uprawnień w czasie rzeczywistym.',
    ExplorerCardButton: 'Otwórz Eksplorator uprawnień',
    ReportCardTitle: 'Raport uprawnień',
    ReportCardAlt: 'Ekran konfiguracji raportu uprawnień',
    ReportCardDesc: 'Wygeneruj kolorowy raport Excel dla każdego unikalnego przypisania uprawnień w witrynie.',
    ReportCardButton: 'Uruchom raport uprawnień',
    UserAccessCardTitle: 'Dostęp użytkownika',
    UserAccessCardAlt: 'Ekran dostępu użytkownika pokazujący dostępne lokalizacje dla wybranego użytkownika',
    UserAccessCardDesc: 'Wyszukaj dowolnego użytkownika, aby zobaczyć każdą lokalizację, do której ma dostęp w witrynie, wraz z dokładnym poziomem uprawnień.',
    UserAccessCardButton: 'Sprawdź dostęp użytkownika',
    SiteOwnerRequiredTitle: 'Wymagany dostęp Właściciela witryny —',
    SiteOwnerRequiredDesc: 'Te narzędzia wymagają dostępu Właściciela witryny. Skontaktuj się z właścicielem witryny w razie pytań dotyczących uprawnień.',
    HomeSubtitle: 'Audytuj i rozumiej uprawnienia SharePoint — bez PowerShell.',
    RequiresSiteOwnerTooltip: 'Wymaga dostępu Właściciela witryny',
    HomeNoteLabel: 'Uwaga:',
    HomeNoteText: 'Ta część sieci Web działa jako aktualnie zalogowany użytkownik. Może widzieć tylko witryny i elementy, do których ten użytkownik ma uprawnienia. Aby przeprowadzić pełne skanowanie dzierżawy, użyj konta z odpowiednim dostępem do odczytu we wszystkich witrynach.',
    SettingsTitle: 'Ustawienia',
    LibrariesSectionTitle: 'Biblioteki',
    IncludeHiddenLabel: 'Uwzględnij biblioteki systemowe i ukryte',
    IncludeHiddenTooltip: 'Po zaznaczeniu obejmuje Bibliotekę stylów, Szablony formularzy, Zasoby witryny i inne biblioteki ukryte w widokach domyślnych. Dotyczy wszystkich narzędzi.',
    MoreInfoHiddenLibrariesLabel: 'Więcej informacji o ukrytych bibliotekach',
    ExcludeLimitedAccessLabel: 'Wyklucz wpisy z ograniczonym dostępem',
    ExcludeLimitedAccessTooltip: 'Ukrywa użytkowników i grupy, których jedynym uprawnieniem SharePoint jest Ograniczony dostęp — przydzielany automatycznie, gdy pliki są udostępniane za pomocą linków. Dotyczy raportu uprawnień, Eksploratora i dostępu użytkownika.',
    MoreInfoLimitedAccessLabel: 'Więcej informacji o ograniczonym dostępie',
    ExcludeSharingLinksLabel: 'Wyklucz wpisy linków udostępniania',
    ExcludeSharingLinksTooltip: 'Ukrywa wewnętrzne grupy "SharingLinks.*", które SharePoint automatycznie tworzy dla linków udostępniania "Każdy z linkiem" i "Określone osoby". Dotyczy raportu uprawnień, Eksploratora i dostępu użytkownika.',
    MoreInfoSharingLinksLabel: 'Więcej informacji o linkach udostępniania',
    PerformanceSectionTitle: 'Wydajność',
    ConcurrentRequestsLabel: 'Równoczesne żądania API:',
    ConcurrencyTooltip: 'Ile żądań API SharePoint jest wykonywanych równolegle podczas skanowania raportu uprawnień, skanowania dostępu użytkownika i kontroli w tle Eksploratora. Wyższe wartości są szybsze, ale bardziej narażone na ograniczanie przepustowości (HTTP 429). Zalecane: 3–5.',
    MoreInfoConcurrencyLabel: 'Więcej informacji o współbieżności',
    ConcurrencyHint: 'Wyższe wartości skanują szybciej, ale mogą wywołać ograniczanie przepustowości SharePoint. Zalecane: 3–5.',
    GroupMemberCapLabel: 'Limit wyświetlania członków grupy:',
    GroupMemberCapTooltip: 'Maksymalna liczba wyświetlanych członków na grupę, gdy włączona jest opcja "Rozwiń członków grupy". Większe grupy są ograniczane i wyświetlane jest powiadomienie. Zwiększenie tego zużywa więcej pamięci.',
    MoreInfoGroupMemberCapLabel: 'Więcej informacji o limicie członków grupy',
    GroupMemberCapHint: 'Grupy większe niż ten limit wyświetlają powiadomienie o obcięciu. Domyślnie: 500.',
    DefaultViewSectionTitle: 'Domyślny widok przy ładowaniu',
    DefaultViewInstructionsIntro: 'Aby zmienić, który ekran otwiera się przy pierwszym załadowaniu części sieci Web, edytuj właściwości części sieci Web:',
    DefaultViewStep1Pre: 'Przełącz stronę SharePoint w tryb',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Kliknij ikonę',
    DefaultViewStep2Post: 'w części sieci Web Smart Permissions.',
    DefaultViewStep3Pre: 'W panelu właściwości wybierz widok z listy rozwijanej',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'stronę, aby zapisać zmianę.',
    EditModeWord: 'Edycji',
    PencilEditWord: 'ołówka (edytuj)',
    DefaultViewOnOpenWord: 'Domyślny widok przy otwarciu',
    RepublishWord: 'Opublikuj ponownie',
    SiteOwnersLabel: 'Właściciele witryny:',
    EveryoneClaimLabel: 'Wszyscy',
    EveryoneExceptExternalClaimLabel: 'Wszyscy oprócz użytkowników zewnętrznych',
    PermissionAssignmentsLabel: 'Przypisania uprawnień',
    UserGroupColumnHeader: 'Użytkownik / Grupa',
    TypeColumnHeader: 'Typ',
    PermissionLevelColumnHeader: 'Poziom uprawnień',
    TenantWideAccessSuffix: '— dostęp w całej dzierżawie',
    SecurityGroupType: 'Grupa zabezpieczeń',
    SpGroupType: 'Grupa SP',
    UserType: 'Użytkownik',
    CheckAccessForLabel: 'Sprawdź dostęp dla {0}',
    ContainsUniqueAndExternalTooltip: 'Zawiera elementy z unikalnymi uprawnieniami i dostępem użytkowników zewnętrznych',
    ContainsUniqueTooltip: 'Zawiera elementy z unikalnymi uprawnieniami',
    ContainsExternalTooltip: 'Zawiera elementy z dostępem użytkowników zewnętrznych',
    UniqueBadge: 'Unikalne',
    ExternalAccessDetectedTooltip: 'Wykryto dostęp użytkownika zewnętrznego',
    ConnectingStatus: 'Łączenie…',
    ConnectedLibrarySingular: 'Połączono — znaleziono {0} bibliotekę',
    ConnectedLibraryPlural: 'Połączono — znaleziono {0} bibliotek',
    ConnectionFailedError: 'Połączenie nie powiodło się: {0}',
    LibraryEmptyStatus: 'Ta biblioteka jest pusta.',
    ErrorLoadingLibrary: 'Błąd podczas ładowania biblioteki: {0}',
    ErrorLoadingContents: 'Błąd podczas ładowania zawartości',
    LibraryFieldLabel: 'Biblioteka',
    HiddenFromSearchSuffix: '{0} (ukryte w wyszukiwaniu)',
    UniquePermissionsOnlyToggle: 'Tylko unikalne uprawnienia',
    ExternalUsersOnlyToggle: 'Tylko użytkownicy zewnętrzni',
    LegendLabel: 'Legenda:',
    LegendItemHasUnique: 'Element ma unikalne uprawnienia',
    LegendContainsUniqueBelow: 'Zawiera unikalne uprawnienia poniżej',
    LegendContainsExternalBelow: 'Zawiera dostęp użytkownika zewnętrznego poniżej',
    LegendExternalOnItem: 'Dostęp użytkownika zewnętrznego do tego elementu',
    ViewingWithMemberAccessTitle: 'Wyświetlanie z dostępem Członka',
    ViewingWithMemberAccessDesc1: '— przypisania uprawnień nie są widoczne. Odczytanie, kto ma dostęp, wymaga uprawnienia',
    ManagePermissionsWord: 'Zarządzaj uprawnieniami',
    ViewingWithMemberAccessDesc2: '(Właściciel witryny lub wyższy). Nadal możesz zobaczyć, które elementy mają przerwane dziedziczenie, korzystając ze wskaźników ↓. Aby zobaczyć lokalizacje, do których masz dostęp, użyj narzędzia',
    UserAccessWord: 'Dostęp użytkownika',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Foldery i pliki',
    SelectFolderOrFilePrompt: 'Wybierz folder lub plik, aby wyświetlić jego uprawnienia.',
    UniquePermissionsBadge: 'Unikalne uprawnienia',
    InheritedBadge: 'Dziedziczone',
    ExpandGroupMembersLabel: 'Rozwiń członków grupy',
    ShowParentPermissionsLabel: 'Pokaż uprawnienia nadrzędne',
    InheritsFromParentText: 'Ten element dziedziczy uprawnienia od elementu nadrzędnego.',
    YourAccessLabel: 'Twój dostęp:',
    PermissionsNotVisibleNodeText: 'Przypisania uprawnień nie są widoczne — do sprawdzenia, kto ma dostęp do tego elementu, wymagane jest uprawnienie Zarządzaj uprawnieniami (Właściciel witryny lub wyższy).',
    NoExternalUsersDirectAccessText: 'Żaden użytkownik zewnętrzny nie ma bezpośredniego dostępu do tego elementu.',
    InheritedFromLabel: 'Dziedziczone z:',
    ParentPermissionsNotVisibleText: 'Przypisania uprawnień elementu nadrzędnego nie są widoczne — wymaga uprawnienia Zarządzaj uprawnieniami (Właściciel witryny lub wyższy).',
    NoPermissionsFoundOnParentText: 'Nie znaleziono uprawnień w elemencie nadrzędnym.',
    StartingScanStatus: 'Rozpoczynanie skanowania…',
    ScanCancelledStatus: 'Skanowanie anulowane — zebrano {0} obiekt(ów) przed anulowaniem.',
    ScanCompleteStatus: 'Skanowanie zakończone — znaleziono {0} obiekt(ów), {1} z unikalnymi uprawnieniami.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Skanowanie zakończone',
    ScanCompleteNotificationBody: '{0} obiektów, {1} z unikalnymi uprawnieniami.',
    CancelledStatus: 'Anulowano.',
    GenericErrorPrefix: 'Błąd: {0}',
    ExportErrorPrefix: 'Błąd eksportu: {0}',
    ScopeSiteOnly: 'Tylko witryna',
    ScopeLibraries: 'Biblioteki',
    ScopeFolders: 'Foldery',
    ScopeFilesAndFolders: 'Pliki i foldery',
    ScanInProgressConfirm: 'Skanowanie jest w toku. Opuścić i anulować?',
    HistoryButton: 'Historia',
    BackToHistoryButton: 'Powrót do historii',
    ComparingLabel: 'Porównywanie',
    CompareMismatchWarning: 'Te raporty zostały wykonane z różnymi witrynami lub opcjami skanowania — różnice poniżej mogą odzwierciedlać zmienione ustawienia skanowania, a nie rzeczywiste zmiany uprawnień.',
    NoPermissionDifferencesFound: 'Nie znaleziono różnic w uprawnieniach między tymi dwoma raportami.',
    PermissionChangesHeaderSingular: 'Zmiany uprawnień ({0} obiekt)',
    PermissionChangesHeaderPlural: 'Zmiany uprawnień ({0} obiektów)',
    ChangeColumnHeader: 'Zmiana',
    BeforeColumnHeader: 'Przed',
    AfterColumnHeader: 'Po',
    AddedBadge: 'Dodano',
    RemovedBadge: 'Usunięto',
    ChangedBadge: 'Zmieniono',
    InheritanceChangedHeader: 'Zmieniono dziedziczenie ({0})',
    NameColumnHeader: 'Nazwa',
    PathColumnHeader: 'Ścieżka',
    NowColumnHeader: 'Teraz',
    UniqueInheritanceBrokenBadge: 'Unikalne (dziedziczenie przerwane)',
    InheritedRestoredBadge: 'Dziedziczone (przywrócone)',
    NewObjectsHeader: 'Nowe obiekty',
    RemovedObjectsHeader: 'Usunięte obiekty',
    BackToScanButton: 'Powrót do skanowania',
    CompareSelectedButton: 'Porównaj wybrane',
    NoReportsSavedYet: 'Nie zapisano jeszcze żadnych raportów.',
    SelectForCompareLabel: 'Wybierz do porównania',
    DateTimeColumnHeader: 'Data / Godzina',
    SiteColumnHeader: 'Witryna',
    ScopeColumnHeader: 'Zakres',
    ObjectsColumnHeader: 'Obiekty',
    UniqueColumnHeader: 'Unikalne',
    SelectReportForCompareLabel: 'Wybierz raport z {0} do porównania',
    AllSitesPrefix: 'Wszystkie witryny · ',
    PlusSubsitesSuffix: ' + witryny podrzędne',
    ExportingStatus: 'Eksportowanie…',
    ExportButton: 'Eksportuj',
    DeleteThisReportTitle: 'Usuń ten raport',
    ScanAllSiteCollectionsLabel: 'Skanuj wszystkie kolekcje witryn w tej dzierżawie (dostępne tylko w witrynie głównej)',
    AllSitesSearchCaveat: 'Lista witryn pochodzi z wyszukiwania i może nie zawierać każdej kolekcji witryn — witryny utworzone bardzo niedawno lub wykluczone z indeksu wyszukiwania mogą zostać pominięte.',
    IncludeSubsitesLabel: 'Uwzględnij witryny podrzędne (skanuje każdą witrynę podrzędną poniżej tej witryny)',
    ScanDepthFieldLabel: 'Głębokość skanowania',
    FolderDepthLimitLabel: 'Limit głębokości folderów:',
    ExpandGroupMembersInReportLabel: 'Rozwiń członków grupy w raporcie (grupy SharePoint, grupy zabezpieczeń i grupy M365)',
    LibrariesToScanLabel: 'Biblioteki do zeskanowania',
    OfSelectedCount: 'Wybrano {0} z {1}',
    AllButton: 'Wszystkie',
    NoneButton: 'Żadne',
    LoadingLibrariesStatus: 'Ładowanie bibliotek…',
    RunReportButton: 'Uruchom raport',
    ItemsFoundSoFar: 'Dotychczas znaleziono {0} elementów',
    LibraryOfProgress: 'Biblioteka {0} z {1}',
    ScanCancelledPartialResults: 'Skanowanie anulowane — wyniki częściowe',
    ScanCompleteLabel: 'Skanowanie zakończone',
    ObjectsCountBadge: '{0} obiektów',
    UniqueCountBadge: '{0} unikalnych',
    InheritedCountBadge: '{0} dziedziczonych',
    GeneratingExcelStatus: 'Generowanie pliku Excel…',
    ExportFilteredRowsButton: 'Eksportuj {0} przefiltrowanych wierszy',
    ExportToExcelButton: 'Eksportuj do Excel',
    ExportToCsvButton: 'Eksportuj do CSV',
    ScanStoppedEarlyTitle: 'Skanowanie zatrzymane przedwcześnie — SharePoint ogranicza przepustowość tej dzierżawy.',
    SiteCollectionsScannedBeforeStopping: 'Zeskanowano {0} z {1} kolekcji witryn przed zatrzymaniem. ',
    ResultsBelowCoverOnlyPre: 'Poniższe wyniki obejmują tylko to, co zostało zeskanowane, i nie są',
    NotWord: 'nie są',
    ResultsBelowCoverOnlyPost: 'pełnym audytem. Skanowanie zatrzymuje się samoczynnie w tej sytuacji, ponieważ dalsze wysyłanie żądań podtrzymuje ograniczanie przepustowości. Poczekaj kilka minut, a następnie uruchom ponownie z',
    ConcurrentRequestsWord: 'Równoczesne żądania',
    SetTo1Or2InSettings: 'ustawionym na 1 lub 2 w Ustawieniach.',
    ThrottledScanMessage: 'SharePoint ograniczył to skanowanie ({0} żądanie(a) zostało ograniczone i ponowione).',
    OfEverythingScannedPre: 'Ze wszystkiego, co zeskanowano,',
    ItemCountSingular: '{0} element',
    ItemCountPlural: '{0} elementów',
    CouldNotBeConfirmedText: 'nie udało się potwierdzić po ponowieniu (zobacz poniższe powiadomienie "nie udało się odczytać w pełni", aby dowiedzieć się dokładnie które) — ten błąd był związany z przepustowością, a nie z ich rzeczywistymi uprawnieniami. Wszystkie inne elementy w tym raporcie zostały odczytane pomyślnie i można im ufać.',
    DespiteThrottlingText: 'Pomimo ograniczania przepustowości, każdy element został pomyślnie potwierdzony po ponowieniu, więc ten raport jest kompletny.',
    ForCleanRunPre: 'Aby uzyskać czysty przebieg, poczekaj kilka minut i zeskanuj ponownie z niższą wartością dla',
    ValueInSettingsPost: 'w Ustawieniach.',
    OneItemWord: '1 element',
    NItemsWord: '{0} element(ów)',
    OutOfScannedCouldNotBeRead: 'z {0} zeskanowanych nie udało się odczytać z Twoim obecnym dostępem —',
    PermissionAssignmentsForItAreNotShown: ' przypisania uprawnień nie są pokazane, ',
    PermissionAssignmentsForThoseAreNotShown: ' przypisania uprawnień nie są pokazane, ',
    RestOfReportReadSuccessfully: 'ale reszta tego raportu została odczytana pomyślnie.',
    RunScanAsSiteOwnerPre: 'Uruchom skanowanie jako',
    SiteOwnerWord: 'Właściciel witryny',
    RunScanAsSiteOwnerPost: 'aby zobaczyć pełne szczegóły odrzuconych elementów poniżej.',
    AndNMoreText: '…i {0} więcej',
    GroupExpansionSkippedPre: 'Rozwijanie członków grupy zostało pominięte — uprawnienie Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'nie zostało zatwierdzone w tej dzierżawie. Administrator SharePoint lub globalny może je zatwierdzić w',
    SharePointAdminCenterPath: 'Centrum administracyjne SharePoint → Zaawansowane → Dostęp API',
    ScanIncompleteItemsMessage: '{0} element(ów) nie udało się w pełni odczytać z powodu tymczasowego błędu (nie problemu z uprawnieniami) i są pokazywane z uprawnieniami elementu nadrzędnego jako rozwiązanie zastępcze — może to nie odzwierciedlać ich rzeczywistego dostępu. Uruchom skanowanie ponownie, aby ponowić próbę dla tych elementów.',
    FilterByNamePathUserPlaceholder: 'Filtruj według nazwy, ścieżki lub użytkownika/grupy…',
    FilterResultsLabel: 'Filtruj wyniki',
    ExternalUsersOnlyExtLabel: 'Tylko użytkownicy zewnętrzni (#ext#)',
    ShowingOfCount: 'Wyświetlanie {0} z {1}',
    ScanResultsLabel: 'Wyniki skanowania',
    PermissionsColumnHeader: 'Uprawnienia',
    CollapsePermissionsLabel: 'Zwiń uprawnienia',
    ExpandPermissionsLabel: 'Rozwiń uprawnienia',
    HiddenFromSearchBadge: 'Ukryte w wyszukiwaniu',
    AssignmentCountSingular: '{0} przypisanie',
    AssignmentCountPlural: '{0} przypisań',
    LoadMoreRemainingButton: 'Załaduj więcej (pozostało {0})',
    LoadingUsersStatus: 'Ładowanie użytkowników…',
    ConnectedUserSingular: 'Połączono — znaleziono {0} użytkownika',
    ConnectedUserPlural: 'Połączono — znaleziono {0} użytkowników',
    CheckingAccessForStatus: 'Sprawdzanie dostępu dla {0}…',
    FullSiteAccessDetectedStatus: 'Wykryto pełny dostęp do witryny.',
    AccessibleLocationsFoundSingular: 'Znaleziono {0} dostępną lokalizację.',
    AccessibleLocationsFoundPlural: 'Znaleziono {0} dostępnych lokalizacji.',
    NoAccessibleLocationsFoundStatus: 'Nie znaleziono dostępnych lokalizacji.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Skanowanie dostępu użytkownika zakończone',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Nowe skanowanie',
    NoUserAccessScansSavedYet: 'Nie zapisano jeszcze żadnych skanów dostępu użytkownika.',
    UserColumnHeader: 'Użytkownik',
    LocationsColumnHeader: 'Lokalizacje',
    FullControlBadge: 'Pełna kontrola',
    DeleteThisRecordTitle: 'Usuń ten rekord',
    SelectAUserFieldLabel: 'Wybierz użytkownika',
    SearchUsersPlaceholder: 'Szukaj użytkowników…',
    SelectAUserToCheckAccessLabel: 'Wybierz użytkownika, aby sprawdzić dostęp',
    NotInThisSiteLabel: 'Nie w tej witrynie',
    ScanInProgressLabel: 'Skanowanie w toku',
    ScanningUserAccessLabel: 'Skanowanie dostępu użytkownika',
    ScanningStatus: 'Skanowanie…',
    FullControlAccessPre: 'Ten użytkownik ma',
    FullControlWord: 'Pełną kontrolę',
    FullControlAccessPost: 'lub dostęp na poziomie Właściciela do całej witryny — wszystkie biblioteki i foldery są dostępne.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Nie udało się określić uprawnień na poziomie witryny — ta witryna prawdopodobnie korzysta z dostępu grupy Microsoft 365. Aby to pokazać, administrator SharePoint musi zatwierdzić uprawnienie',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph w',
    ShowingSiteLevelAccessOnlyPre: 'Wyświetlanie tylko',
    SiteLevelAccessOnlyWord: 'dostępu na poziomie witryny',
    ShowingSiteLevelAccessOnlyMid: ', na podstawie domyślnego członkostwa w grupie SharePoint. Unikalnych uprawnień do bibliotek, folderów i plików nie udało się odczytać i nie są pokazywane. Aby uzyskać pełne wyniki, uruchom to skanowanie jako',
    UserAccessCouldNotBeDeterminedPre: 'Nie udało się określić dostępu tego użytkownika. Odczytanie przypisań uprawnień wymaga uprawnienia',
    UserAccessCouldNotBeDeterminedPost: '(Właściciel witryny lub wyższy), a ten użytkownik nie wydaje się być członkiem domyślnych grup Właścicieli, Członków lub Odwiedzających witryny.',
    SiteLevelAccessBannerPre: 'Ten użytkownik ma dostęp na poziomie witryny. Tylko lokalizacje z',
    UniquePermissionAssignmentsWord: 'unikalnymi przypisaniami uprawnień',
    SiteLevelAccessBannerPost: 'pojawiają się poniżej — cała pozostała zawartość jest dostępna poprzez uprawnienie na poziomie witryny pokazane u góry listy.',
    UserAccessResultsLabel: 'Wyniki dostępu użytkownika',
  };
});
