define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Configuração do Smart Permissions',
    PropertyPane_GroupName: 'Geral',
    PropertyPane_DefaultViewLabel: 'Exibição padrão ao abrir',
    PropertyPane_View_Home: 'Início',
    PropertyPane_View_Report: 'Relatório de permissões',
    PropertyPane_View_Explorer: 'Explorador de permissões',
    PropertyPane_View_UserAccess: 'Acesso do usuário',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/meusite',
    ConnectButton: 'Conectar',
    CancelButton: 'Cancelar',
    ChangeUrlButton: 'Alterar URL',
    SettingsLabel: 'Configurações',
    RenderErrorTitle: 'Smart Permissions — Erro de renderização',
    RenderErrorMessageLabel: 'Mensagem:',
    RenderErrorStackLabel: 'Pilha:',
    RenderErrorNoStack: '(pilha não disponível)',
    BackButton: 'Voltar',
    BackToHomeLabel: 'Voltar para o início',
    ExplorerCardTitle: 'Explorador de permissões',
    ExplorerCardAlt: 'Explorador de permissões com árvore de pastas e painel de permissões',
    ExplorerCardDesc: 'Navegue por qualquer pasta ou arquivo e veja instantaneamente quem tem acesso, com consultas de permissão em tempo real.',
    ExplorerCardButton: 'Abrir Explorador de permissões',
    ReportCardTitle: 'Relatório de permissões',
    ReportCardAlt: 'Tela de configuração do relatório de permissões',
    ReportCardDesc: 'Gere um relatório do Excel colorido de cada atribuição de permissão exclusiva no seu site.',
    ReportCardButton: 'Executar relatório de permissões',
    UserAccessCardTitle: 'Acesso do usuário',
    UserAccessCardAlt: 'Tela de acesso do usuário mostrando os locais acessíveis para um usuário selecionado',
    UserAccessCardDesc: 'Pesquise qualquer usuário para ver todos os locais que ele pode acessar em um site, com seu nível de permissão exato.',
    UserAccessCardButton: 'Verificar acesso do usuário',
    SiteOwnerRequiredTitle: 'Acesso de Proprietário do site necessário —',
    SiteOwnerRequiredDesc: 'Essas ferramentas exigem acesso de Proprietário do site. Entre em contato com um proprietário do site se tiver dúvidas sobre permissões.',
    HomeSubtitle: 'Audite e entenda as permissões do SharePoint — sem PowerShell.',
    RequiresSiteOwnerTooltip: 'Requer acesso de Proprietário do site',
    HomeNoteLabel: 'Observação:',
    HomeNoteText: 'Este web part é executado como o usuário conectado no momento. Ele só pode ver sites e itens aos quais esse usuário tem permissão de acesso. Para uma varredura completa do tenant, use uma conta com acesso de leitura adequado em todos os sites.',
    SettingsTitle: 'Configurações',
    LibrariesSectionTitle: 'Bibliotecas',
    IncludeHiddenLabel: 'Incluir bibliotecas do sistema e ocultas',
    IncludeHiddenTooltip: 'Quando marcado, inclui a Biblioteca de Estilos, Modelos de Formulário, Ativos do Site e outras bibliotecas ocultas das exibições padrão. Aplica-se a todas as ferramentas.',
    MoreInfoHiddenLibrariesLabel: 'Mais informações sobre bibliotecas ocultas',
    ExcludeLimitedAccessLabel: 'Excluir entradas de Acesso limitado',
    ExcludeLimitedAccessTooltip: 'Oculta usuários e grupos cuja única permissão do SharePoint é Acesso limitado — atribuída automaticamente quando arquivos são compartilhados por meio de links. Aplica-se ao Relatório de permissões, Explorador e Acesso do usuário.',
    MoreInfoLimitedAccessLabel: 'Mais informações sobre Acesso limitado',
    ExcludeSharingLinksLabel: 'Excluir entradas de Links de compartilhamento',
    ExcludeSharingLinksTooltip: 'Oculta os grupos internos "SharingLinks.*" que o SharePoint cria automaticamente para links de compartilhamento "Qualquer pessoa com o link" e "Pessoas específicas". Aplica-se ao Relatório de permissões, Explorador e Acesso do usuário.',
    MoreInfoSharingLinksLabel: 'Mais informações sobre links de compartilhamento',
    PerformanceSectionTitle: 'Desempenho',
    ConcurrentRequestsLabel: 'Solicitações de API simultâneas:',
    ConcurrencyTooltip: 'Quantas solicitações de API do SharePoint são executadas em paralelo durante varreduras do Relatório de permissões, varreduras de Acesso do usuário e verificações em segundo plano do Explorador. Valores mais altos são mais rápidos, mas mais propensos a acionar limitação (HTTP 429). Recomenda-se 3–5.',
    MoreInfoConcurrencyLabel: 'Mais informações sobre simultaneidade',
    ConcurrencyHint: 'Valores mais altos verificam mais rápido, mas podem acionar a limitação do SharePoint. Recomendado: 3–5.',
    GroupMemberCapLabel: 'Limite de exibição de membros do grupo:',
    GroupMemberCapTooltip: 'Número máximo de membros mostrados por grupo quando "Expandir membros do grupo" está habilitado. Grupos maiores são limitados e um aviso é mostrado. Aumentar isso usa mais memória.',
    MoreInfoGroupMemberCapLabel: 'Mais informações sobre o limite de membros do grupo',
    GroupMemberCapHint: 'Grupos maiores que este limite mostram um aviso de truncamento. Padrão: 500.',
    DefaultViewSectionTitle: 'Exibição padrão ao carregar',
    DefaultViewInstructionsIntro: 'Para alterar qual tela abre quando o web part carrega pela primeira vez, edite as propriedades do web part:',
    DefaultViewStep1Pre: 'Coloque a página do SharePoint no modo',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Clique no ícone de',
    DefaultViewStep2Post: 'no web part Smart Permissions.',
    DefaultViewStep3Pre: 'No painel de propriedades, escolha uma exibição na lista suspensa',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'a página para salvar a alteração.',
    EditModeWord: 'Edição',
    PencilEditWord: 'lápis (editar)',
    DefaultViewOnOpenWord: 'Exibição padrão ao abrir',
    RepublishWord: 'Republique',
    SiteOwnersLabel: 'Proprietários do site:',
    EveryoneClaimLabel: 'Todos',
    EveryoneExceptExternalClaimLabel: 'Todos, exceto usuários externos',
    PermissionAssignmentsLabel: 'Atribuições de permissão',
    UserGroupColumnHeader: 'Usuário / Grupo',
    TypeColumnHeader: 'Tipo',
    PermissionLevelColumnHeader: 'Nível de permissão',
    TenantWideAccessSuffix: '— acesso em todo o tenant',
    SecurityGroupType: 'Grupo de segurança',
    SpGroupType: 'Grupo SP',
    UserType: 'Usuário',
    CheckAccessForLabel: 'Verificar acesso de {0}',
    ContainsUniqueAndExternalTooltip: 'Contém itens com permissões exclusivas e acesso de usuário externo',
    ContainsUniqueTooltip: 'Contém itens com permissões exclusivas',
    ContainsExternalTooltip: 'Contém itens com acesso de usuário externo',
    UniqueBadge: 'Exclusivo',
    ExternalAccessDetectedTooltip: 'Acesso de usuário externo detectado',
    ConnectingStatus: 'Conectando…',
    ConnectedLibrarySingular: 'Conectado — {0} biblioteca encontrada',
    ConnectedLibraryPlural: 'Conectado — {0} bibliotecas encontradas',
    ConnectionFailedError: 'Falha na conexão: {0}',
    LibraryEmptyStatus: 'Esta biblioteca está vazia.',
    ErrorLoadingLibrary: 'Erro ao carregar a biblioteca: {0}',
    ErrorLoadingContents: 'Erro ao carregar o conteúdo',
    LibraryFieldLabel: 'Biblioteca',
    HiddenFromSearchSuffix: '{0} (oculto da pesquisa)',
    UniquePermissionsOnlyToggle: 'Somente permissões exclusivas',
    ExternalUsersOnlyToggle: 'Somente usuários externos',
    LegendLabel: 'Legenda:',
    LegendItemHasUnique: 'O item tem permissões exclusivas',
    LegendContainsUniqueBelow: 'Contém permissões exclusivas abaixo',
    LegendContainsExternalBelow: 'Contém acesso de usuário externo abaixo',
    LegendExternalOnItem: 'Acesso de usuário externo neste item',
    ViewingWithMemberAccessTitle: 'Visualizando com acesso de Membro',
    ViewingWithMemberAccessDesc1: '— as atribuições de permissão não estão visíveis. Ler quem tem acesso requer o direito',
    ManagePermissionsWord: 'Gerenciar Permissões',
    ViewingWithMemberAccessDesc2: '(Proprietário do site ou superior). Você ainda pode ver quais itens têm herança quebrada usando os indicadores ↓. Para ver locais aos quais você pode acessar, use a ferramenta',
    UserAccessWord: 'Acesso do usuário',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Pastas e arquivos',
    SelectFolderOrFilePrompt: 'Selecione uma pasta ou arquivo para ver suas permissões.',
    UniquePermissionsBadge: 'Permissões exclusivas',
    InheritedBadge: 'Herdado',
    ExpandGroupMembersLabel: 'Expandir membros do grupo',
    ShowParentPermissionsLabel: 'Mostrar permissões do item pai',
    InheritsFromParentText: 'Este item herda permissões de seu item pai.',
    YourAccessLabel: 'Seu acesso:',
    PermissionsNotVisibleNodeText: 'As atribuições de permissão não estão visíveis — o direito Gerenciar Permissões (Proprietário do site ou superior) é necessário para ver quem tem acesso a este item.',
    NoExternalUsersDirectAccessText: 'Nenhum usuário externo tem acesso direto a este item.',
    InheritedFromLabel: 'Herdado de:',
    ParentPermissionsNotVisibleText: 'As atribuições de permissão do item pai não estão visíveis — requer o direito Gerenciar Permissões (Proprietário do site ou superior).',
    NoPermissionsFoundOnParentText: 'Nenhuma permissão encontrada no item pai.',
    StartingScanStatus: 'Iniciando varredura…',
    ScanCancelledStatus: 'Varredura cancelada — {0} objeto(s) coletado(s) antes do cancelamento.',
    ScanCompleteStatus: 'Varredura concluída — {0} objeto(s) encontrado(s), {1} com permissões exclusivas.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Varredura concluída',
    ScanCompleteNotificationBody: '{0} objetos, {1} com permissões exclusivas.',
    CancelledStatus: 'Cancelado.',
    GenericErrorPrefix: 'Erro: {0}',
    ExportErrorPrefix: 'Erro de exportação: {0}',
    ScopeSiteOnly: 'Somente site',
    ScopeLibraries: 'Bibliotecas',
    ScopeFolders: 'Pastas',
    ScopeFilesAndFolders: 'Arquivos e pastas',
    ScanInProgressConfirm: 'Uma varredura está em andamento. Sair e cancelar?',
    HistoryButton: 'Histórico',
    BackToHistoryButton: 'Voltar ao histórico',
    ComparingLabel: 'Comparando',
    CompareMismatchWarning: 'Esses relatórios foram feitos com sites ou opções de varredura diferentes — as diferenças abaixo podem refletir as configurações de varredura alteradas, não mudanças reais de permissão.',
    NoPermissionDifferencesFound: 'Nenhuma diferença de permissão encontrada entre esses dois relatórios.',
    PermissionChangesHeaderSingular: 'Alterações de permissão ({0} objeto)',
    PermissionChangesHeaderPlural: 'Alterações de permissão ({0} objetos)',
    ChangeColumnHeader: 'Alteração',
    BeforeColumnHeader: 'Antes',
    AfterColumnHeader: 'Depois',
    AddedBadge: 'Adicionado',
    RemovedBadge: 'Removido',
    ChangedBadge: 'Alterado',
    InheritanceChangedHeader: 'Herança alterada ({0})',
    NameColumnHeader: 'Nome',
    PathColumnHeader: 'Caminho',
    NowColumnHeader: 'Agora',
    UniqueInheritanceBrokenBadge: 'Exclusivo (herança quebrada)',
    InheritedRestoredBadge: 'Herdado (restaurado)',
    NewObjectsHeader: 'Novos objetos',
    RemovedObjectsHeader: 'Objetos removidos',
    BackToScanButton: 'Voltar à varredura',
    CompareSelectedButton: 'Comparar selecionados',
    NoReportsSavedYet: 'Nenhum relatório salvo ainda.',
    SelectForCompareLabel: 'Selecionar para comparar',
    DateTimeColumnHeader: 'Data / Hora',
    SiteColumnHeader: 'Site',
    ScopeColumnHeader: 'Escopo',
    ObjectsColumnHeader: 'Objetos',
    UniqueColumnHeader: 'Exclusivo',
    SelectReportForCompareLabel: 'Selecionar relatório de {0} para comparar',
    AllSitesPrefix: 'Todos os sites · ',
    PlusSubsitesSuffix: ' + subsites',
    ExportingStatus: 'Exportando…',
    ExportButton: 'Exportar',
    DeleteThisReportTitle: 'Excluir este relatório',
    ScanAllSiteCollectionsLabel: 'Verificar todas as coleções de sites neste tenant (disponível apenas no site raiz)',
    AllSitesSearchCaveat: 'A lista de sites vem da pesquisa e pode não incluir todas as coleções de sites — sites criados muito recentemente, ou excluídos do índice de pesquisa, podem estar ausentes.',
    IncludeSubsitesLabel: 'Incluir subsites (verifica cada subsite abaixo deste site)',
    ScanDepthFieldLabel: 'Profundidade da varredura',
    FolderDepthLimitLabel: 'Limite de profundidade da pasta:',
    ExpandGroupMembersInReportLabel: 'Expandir membros do grupo no relatório (grupos do SharePoint, grupos de segurança e grupos M365)',
    LibrariesToScanLabel: 'Bibliotecas a serem verificadas',
    OfSelectedCount: '{0} de {1} selecionadas',
    AllButton: 'Todas',
    NoneButton: 'Nenhuma',
    LoadingLibrariesStatus: 'Carregando bibliotecas…',
    RunReportButton: 'Executar relatório',
    ItemsFoundSoFar: '{0} itens encontrados até agora',
    LibraryOfProgress: 'Biblioteca {0} de {1}',
    ScanCancelledPartialResults: 'Varredura cancelada — resultados parciais',
    ScanCompleteLabel: 'Varredura concluída',
    ObjectsCountBadge: '{0} objetos',
    UniqueCountBadge: '{0} exclusivos',
    InheritedCountBadge: '{0} herdados',
    GeneratingExcelStatus: 'Gerando Excel…',
    ExportFilteredRowsButton: 'Exportar {0} linhas filtradas',
    ExportToExcelButton: 'Exportar para Excel',
    ExportToCsvButton: 'Exportar para CSV',
    ScanStoppedEarlyTitle: 'Varredura interrompida antecipadamente — o SharePoint está limitando este tenant.',
    SiteCollectionsScannedBeforeStopping: '{0} de {1} coleções de sites foram verificadas antes de parar. ',
    ResultsBelowCoverOnlyPre: 'Os resultados abaixo cobrem apenas o que foi verificado e não são',
    NotWord: 'não',
    ResultsBelowCoverOnlyPost: 'uma auditoria completa. A varredura para sozinha nessa situação porque continuar enviando solicitações é o que mantém a limitação ativa. Aguarde vários minutos e execute novamente com',
    ConcurrentRequestsWord: 'Solicitações simultâneas',
    SetTo1Or2InSettings: 'definido como 1 ou 2 nas Configurações.',
    ThrottledScanMessage: 'O SharePoint limitou esta varredura ({0} solicitação(ões) foram limitadas e repetidas).',
    OfEverythingScannedPre: 'De tudo o que foi verificado,',
    ItemCountSingular: '{0} item',
    ItemCountPlural: '{0} itens',
    CouldNotBeConfirmedText: 'não puderam ser confirmados após a nova tentativa (veja o aviso "não foi possível ler completamente" abaixo para saber exatamente quais) — essa falha foi relacionada à capacidade, não uma reflexão de suas permissões reais. Todos os outros itens neste relatório foram lidos com sucesso e podem ser confiáveis.',
    DespiteThrottlingText: 'Apesar da limitação, cada item ainda foi confirmado com sucesso após a nova tentativa, então este relatório está completo.',
    ForCleanRunPre: 'Para uma execução limpa, aguarde alguns minutos e verifique novamente com um valor mais baixo de',
    ValueInSettingsPost: 'nas Configurações.',
    OneItemWord: '1 item',
    NItemsWord: '{0} item(ns)',
    OutOfScannedCouldNotBeRead: 'de {0} verificados não puderam ser lidos com seu acesso atual —',
    PermissionAssignmentsForItAreNotShown: ' as atribuições de permissão não são mostradas, ',
    PermissionAssignmentsForThoseAreNotShown: ' as atribuições de permissão não são mostradas, ',
    RestOfReportReadSuccessfully: 'mas o restante deste relatório foi lido com sucesso.',
    RunScanAsSiteOwnerPre: 'Execute a varredura como',
    SiteOwnerWord: 'Proprietário do site',
    RunScanAsSiteOwnerPost: 'para ver os detalhes completos dos itens negados abaixo.',
    AndNMoreText: '…e mais {0}',
    GroupExpansionSkippedPre: 'A expansão de membros do grupo foi ignorada — a permissão do Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'não foi aprovada neste tenant. Um administrador do SharePoint ou global pode aprová-la em',
    SharePointAdminCenterPath: 'Central de administração do SharePoint → Avançado → Acesso à API',
    ScanIncompleteItemsMessage: '{0} item(ns) não puderam ser lidos completamente devido a um erro temporário (não um problema de permissão) e são mostrados com as permissões de seu item pai como solução alternativa — isso pode não refletir seu acesso real. Execute a varredura novamente para tentar novamente esses itens.',
    FilterByNamePathUserPlaceholder: 'Filtrar por nome, caminho ou usuário/grupo…',
    FilterResultsLabel: 'Filtrar resultados',
    ExternalUsersOnlyExtLabel: 'Somente usuários externos (#ext#)',
    ShowingOfCount: 'Mostrando {0} de {1}',
    ScanResultsLabel: 'Resultados da varredura',
    PermissionsColumnHeader: 'Permissões',
    CollapsePermissionsLabel: 'Recolher permissões',
    ExpandPermissionsLabel: 'Expandir permissões',
    HiddenFromSearchBadge: 'Oculto da pesquisa',
    AssignmentCountSingular: '{0} atribuição',
    AssignmentCountPlural: '{0} atribuições',
    LoadMoreRemainingButton: 'Carregar mais ({0} restante(s))',
    LoadingUsersStatus: 'Carregando usuários…',
    ConnectedUserSingular: 'Conectado — {0} usuário encontrado',
    ConnectedUserPlural: 'Conectado — {0} usuários encontrados',
    CheckingAccessForStatus: 'Verificando acesso de {0}…',
    FullSiteAccessDetectedStatus: 'Acesso total ao site detectado.',
    AccessibleLocationsFoundSingular: '{0} local acessível encontrado.',
    AccessibleLocationsFoundPlural: '{0} locais acessíveis encontrados.',
    NoAccessibleLocationsFoundStatus: 'Nenhum local acessível encontrado.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Varredura de acesso do usuário concluída',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Nova varredura',
    NoUserAccessScansSavedYet: 'Nenhuma varredura de acesso do usuário salva ainda.',
    UserColumnHeader: 'Usuário',
    LocationsColumnHeader: 'Locais',
    FullControlBadge: 'Controle total',
    DeleteThisRecordTitle: 'Excluir este registro',
    SelectAUserFieldLabel: 'Selecionar um usuário',
    SearchUsersPlaceholder: 'Pesquisar usuários…',
    SelectAUserToCheckAccessLabel: 'Selecionar um usuário para verificar o acesso',
    NotInThisSiteLabel: 'Não está neste site',
    ScanInProgressLabel: 'Varredura em andamento',
    ScanningUserAccessLabel: 'Verificando acesso do usuário',
    ScanningStatus: 'Verificando…',
    FullControlAccessPre: 'Este usuário tem',
    FullControlWord: 'Controle total',
    FullControlAccessPost: 'ou acesso de nível Proprietário a todo o site — todas as bibliotecas e pastas são acessíveis.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'A permissão em nível de site não pôde ser determinada — este site provavelmente usa acesso de grupo do Microsoft 365. Para mostrá-la, um administrador do SharePoint deve aprovar a permissão',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'do Graph em',
    ShowingSiteLevelAccessOnlyPre: 'Mostrando apenas',
    SiteLevelAccessOnlyWord: 'acesso em nível de site',
    ShowingSiteLevelAccessOnlyMid: ', com base na associação padrão de grupo do SharePoint. Permissões exclusivas em bibliotecas, pastas e arquivos não puderam ser lidas e não são mostradas. Para resultados completos, execute esta varredura como',
    UserAccessCouldNotBeDeterminedPre: 'O acesso deste usuário não pôde ser determinado. Ler atribuições de permissão requer o direito',
    UserAccessCouldNotBeDeterminedPost: '(Proprietário do site ou superior), e este usuário não parece ser membro dos grupos padrão de Proprietários, Membros ou Visitantes do site.',
    SiteLevelAccessBannerPre: 'Este usuário tem acesso em nível de site. Somente locais com',
    UniquePermissionAssignmentsWord: 'atribuições de permissão exclusivas',
    SiteLevelAccessBannerPost: 'aparecem abaixo — todo o outro conteúdo é acessível através da permissão em nível de site mostrada no topo da lista.',
    UserAccessResultsLabel: 'Resultados de acesso do usuário',
  };
});
