define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Configurația Smart Permissions',
    PropertyPane_GroupName: 'General',
    PropertyPane_DefaultViewLabel: 'Vizualizare implicită la deschidere',
    PropertyPane_View_Home: 'Acasă',
    PropertyPane_View_Report: 'Raport de permisiuni',
    PropertyPane_View_Explorer: 'Explorator de permisiuni',
    PropertyPane_View_UserAccess: 'Acces utilizator',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/situlmeu',
    ConnectButton: 'Conectare',
    CancelButton: 'Anulare',
    ChangeUrlButton: 'Schimbă URL',
    SettingsLabel: 'Setări',
    RenderErrorTitle: 'Smart Permissions — Eroare de randare',
    RenderErrorMessageLabel: 'Mesaj:',
    RenderErrorStackLabel: 'Stivă:',
    RenderErrorNoStack: '(stiva nu este disponibilă)',
    BackButton: 'Înapoi',
    BackToHomeLabel: 'Înapoi la pagina principală',
    ExplorerCardTitle: 'Explorator de permisiuni',
    ExplorerCardAlt: 'Explorator de permisiuni cu arbore de foldere și panou de permisiuni',
    ExplorerCardDesc: 'Răsfoiți orice folder sau fișier și vedeți instantaneu cine are acces — cu verificări de permisiuni în timp real.',
    ExplorerCardButton: 'Deschide Exploratorul de permisiuni',
    ReportCardTitle: 'Raport de permisiuni',
    ReportCardAlt: 'Ecran de configurare a raportului de permisiuni',
    ReportCardDesc: 'Generați un raport Excel colorat pentru fiecare atribuire unică de permisiuni din site-ul dvs.',
    ReportCardButton: 'Rulează raportul de permisiuni',
    UserAccessCardTitle: 'Acces utilizator',
    UserAccessCardAlt: 'Ecran de acces utilizator care arată locațiile accesibile pentru un utilizator selectat',
    UserAccessCardDesc: 'Căutați orice utilizator pentru a vedea fiecare locație la care poate accesa pe un site, cu nivelul exact de permisiune.',
    UserAccessCardButton: 'Verifică accesul utilizatorului',
    SiteOwnerRequiredTitle: 'Este necesar acces de Proprietar al site-ului —',
    SiteOwnerRequiredDesc: 'Aceste instrumente necesită acces de Proprietar al site-ului. Contactați un proprietar al site-ului dacă aveți întrebări despre permisiuni.',
    HomeSubtitle: 'Auditați și înțelegeți permisiunile SharePoint — fără PowerShell.',
    RequiresSiteOwnerTooltip: 'Necesită acces de Proprietar al site-ului',
    HomeNoteLabel: 'Notă:',
    HomeNoteText: 'Această componentă web rulează ca utilizatorul conectat în prezent. Poate vedea doar site-urile și elementele la care acest utilizator are permisiune de acces. Pentru o scanare completă a chiriașului, folosiți un cont cu acces de citire adecvat pe toate site-urile.',
    SettingsTitle: 'Setări',
    LibrariesSectionTitle: 'Biblioteci',
    IncludeHiddenLabel: 'Include bibliotecile de sistem și ascunse',
    IncludeHiddenTooltip: 'Dacă este bifat, include Biblioteca de stiluri, Șabloanele de formulare, Activele site-ului și alte biblioteci ascunse din vizualizările implicite. Se aplică tuturor instrumentelor.',
    MoreInfoHiddenLibrariesLabel: 'Mai multe informații despre bibliotecile ascunse',
    ExcludeLimitedAccessLabel: 'Exclude intrările cu acces limitat',
    ExcludeLimitedAccessTooltip: 'Ascunde utilizatorii și grupurile a căror unică permisiune SharePoint este Acces limitat — atribuită automat când fișierele sunt partajate prin linkuri. Se aplică Raportului de permisiuni, Exploratorului și Accesului utilizatorului.',
    MoreInfoLimitedAccessLabel: 'Mai multe informații despre accesul limitat',
    ExcludeSharingLinksLabel: 'Exclude intrările pentru linkuri de partajare',
    ExcludeSharingLinksTooltip: 'Ascunde grupurile interne "SharingLinks.*" pe care SharePoint le creează automat pentru linkurile de partajare "Oricine cu linkul" și "Persoane specifice". Se aplică Raportului de permisiuni, Exploratorului și Accesului utilizatorului.',
    MoreInfoSharingLinksLabel: 'Mai multe informații despre linkurile de partajare',
    PerformanceSectionTitle: 'Performanță',
    ConcurrentRequestsLabel: 'Solicitări API simultane:',
    ConcurrencyTooltip: 'Câte solicitări API SharePoint rulează în paralel în timpul scanărilor Raportului de permisiuni, scanărilor Accesului utilizatorului și verificărilor din fundal ale Exploratorului. Valorile mai mari sunt mai rapide, dar mai predispuse să declanșeze limitarea (HTTP 429). Se recomandă 3–5.',
    MoreInfoConcurrencyLabel: 'Mai multe informații despre concurență',
    ConcurrencyHint: 'Valorile mai mari scanează mai rapid, dar pot declanșa limitarea SharePoint. Recomandat: 3–5.',
    GroupMemberCapLabel: 'Limita de afișare a membrilor grupului:',
    GroupMemberCapTooltip: 'Numărul maxim de membri afișați per grup atunci când "Extinde membrii grupului" este activat. Grupurile mai mari sunt limitate și se afișează o notificare. Creșterea acestei valori folosește mai multă memorie.',
    MoreInfoGroupMemberCapLabel: 'Mai multe informații despre limita membrilor grupului',
    GroupMemberCapHint: 'Grupurile mai mari decât această limită afișează o notificare de trunchiere. Implicit: 500.',
    DefaultViewSectionTitle: 'Vizualizare implicită la încărcare',
    DefaultViewInstructionsIntro: 'Pentru a schimba ce ecran se deschide când componenta web este încărcată prima dată, editați proprietățile componentei web:',
    DefaultViewStep1Pre: 'Puneți pagina SharePoint în modul',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Faceți clic pe pictograma',
    DefaultViewStep2Post: 'de pe componenta web Smart Permissions.',
    DefaultViewStep3Pre: 'În panoul de proprietăți, alegeți o vizualizare din lista derulantă',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'pagina pentru a salva modificarea.',
    EditModeWord: 'Editare',
    PencilEditWord: 'creion (editare)',
    DefaultViewOnOpenWord: 'Vizualizare implicită la deschidere',
    RepublishWord: 'Republicați',
    SiteOwnersLabel: 'Proprietari site:',
    EveryoneClaimLabel: 'Toată lumea',
    EveryoneExceptExternalClaimLabel: 'Toată lumea, cu excepția utilizatorilor externi',
    PermissionAssignmentsLabel: 'Atribuiri de permisiuni',
    UserGroupColumnHeader: 'Utilizator / Grup',
    TypeColumnHeader: 'Tip',
    PermissionLevelColumnHeader: 'Nivel de permisiune',
    TenantWideAccessSuffix: '— acces la nivelul întregului chiriaș',
    SecurityGroupType: 'Grup de securitate',
    SpGroupType: 'Grup SP',
    UserType: 'Utilizator',
    CheckAccessForLabel: 'Verifică accesul pentru {0}',
    ContainsUniqueAndExternalTooltip: 'Conține elemente cu permisiuni unice și acces al utilizatorilor externi',
    ContainsUniqueTooltip: 'Conține elemente cu permisiuni unice',
    ContainsExternalTooltip: 'Conține elemente cu acces al utilizatorilor externi',
    UniqueBadge: 'Unic',
    ExternalAccessDetectedTooltip: 'Acces al utilizatorului extern detectat',
    ConnectingStatus: 'Se conectează…',
    ConnectedLibrarySingular: 'Conectat — {0} bibliotecă găsită',
    ConnectedLibraryPlural: 'Conectat — {0} biblioteci găsite',
    ConnectionFailedError: 'Conexiune eșuată: {0}',
    LibraryEmptyStatus: 'Această bibliotecă este goală.',
    ErrorLoadingLibrary: 'Eroare la încărcarea bibliotecii: {0}',
    ErrorLoadingContents: 'Eroare la încărcarea conținutului',
    LibraryFieldLabel: 'Bibliotecă',
    HiddenFromSearchSuffix: '{0} (ascuns din căutare)',
    UniquePermissionsOnlyToggle: 'Doar permisiuni unice',
    ExternalUsersOnlyToggle: 'Doar utilizatori externi',
    LegendLabel: 'Legendă:',
    LegendItemHasUnique: 'Elementul are permisiuni unice',
    LegendContainsUniqueBelow: 'Conține permisiuni unice mai jos',
    LegendContainsExternalBelow: 'Conține acces al utilizatorilor externi mai jos',
    LegendExternalOnItem: 'Acces al utilizatorului extern pe acest element',
    ViewingWithMemberAccessTitle: 'Vizualizare cu acces de Membru',
    ViewingWithMemberAccessDesc1: '— atribuirile de permisiuni nu sunt vizibile. Pentru a vedea cine are acces, este necesar dreptul',
    ManagePermissionsWord: 'Gestionare permisiuni',
    ViewingWithMemberAccessDesc2: '(Proprietar al site-ului sau superior). Puteți vedea în continuare ce elemente au moștenirea întreruptă folosind indicatorii ↓. Pentru a vedea locațiile la care puteți accesa, folosiți instrumentul',
    UserAccessWord: 'Acces utilizator',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Foldere și fișiere',
    SelectFolderOrFilePrompt: 'Selectați un folder sau fișier pentru a vedea permisiunile acestuia.',
    UniquePermissionsBadge: 'Permisiuni unice',
    InheritedBadge: 'Moștenit',
    ExpandGroupMembersLabel: 'Extinde membrii grupului',
    ShowParentPermissionsLabel: 'Afișează permisiunile părinte',
    InheritsFromParentText: 'Acest element moștenește permisiunile de la elementul părinte.',
    YourAccessLabel: 'Accesul dvs.:',
    PermissionsNotVisibleNodeText: 'Atribuirile de permisiuni nu sunt vizibile — dreptul Gestionare permisiuni (Proprietar al site-ului sau superior) este necesar pentru a vedea cine are acces la acest element.',
    NoExternalUsersDirectAccessText: 'Niciun utilizator extern nu are acces direct la acest element.',
    InheritedFromLabel: 'Moștenit de la:',
    ParentPermissionsNotVisibleText: 'Atribuirile de permisiuni ale elementului părinte nu sunt vizibile — necesită dreptul Gestionare permisiuni (Proprietar al site-ului sau superior).',
    NoPermissionsFoundOnParentText: 'Nu s-au găsit permisiuni pe elementul părinte.',
    StartingScanStatus: 'Se pornește scanarea…',
    ScanCancelledStatus: 'Scanare anulată — {0} obiect(e) colectat(e) înainte de anulare.',
    ScanCompleteStatus: 'Scanare finalizată — {0} obiect(e) găsit(e), {1} cu permisiuni unice.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Scanare finalizată',
    ScanCompleteNotificationBody: '{0} obiecte, {1} cu permisiuni unice.',
    CancelledStatus: 'Anulat.',
    GenericErrorPrefix: 'Eroare: {0}',
    ExportErrorPrefix: 'Eroare de export: {0}',
    ScopeSiteOnly: 'Doar site',
    ScopeLibraries: 'Biblioteci',
    ScopeFolders: 'Foldere',
    ScopeFilesAndFolders: 'Fișiere și foldere',
    ScanInProgressConfirm: 'O scanare este în curs. Părăsiți și anulați?',
    HistoryButton: 'Istoric',
    BackToHistoryButton: 'Înapoi la istoric',
    ComparingLabel: 'Comparare',
    CompareMismatchWarning: 'Aceste rapoarte au fost realizate cu site-uri sau opțiuni de scanare diferite — diferențele de mai jos pot reflecta setările de scanare modificate, nu modificări reale ale permisiunilor.',
    NoPermissionDifferencesFound: 'Nu s-au găsit diferențe de permisiuni între aceste două rapoarte.',
    PermissionChangesHeaderSingular: 'Modificări de permisiuni ({0} obiect)',
    PermissionChangesHeaderPlural: 'Modificări de permisiuni ({0} obiecte)',
    ChangeColumnHeader: 'Modificare',
    BeforeColumnHeader: 'Înainte',
    AfterColumnHeader: 'După',
    AddedBadge: 'Adăugat',
    RemovedBadge: 'Eliminat',
    ChangedBadge: 'Modificat',
    InheritanceChangedHeader: 'Moștenire modificată ({0})',
    NameColumnHeader: 'Nume',
    PathColumnHeader: 'Cale',
    NowColumnHeader: 'Acum',
    UniqueInheritanceBrokenBadge: 'Unic (moștenire întreruptă)',
    InheritedRestoredBadge: 'Moștenit (restaurat)',
    NewObjectsHeader: 'Obiecte noi',
    RemovedObjectsHeader: 'Obiecte eliminate',
    BackToScanButton: 'Înapoi la scanare',
    CompareSelectedButton: 'Compară selectate',
    NoReportsSavedYet: 'Niciun raport salvat încă.',
    SelectForCompareLabel: 'Selectați pentru comparare',
    DateTimeColumnHeader: 'Data / Ora',
    SiteColumnHeader: 'Site',
    ScopeColumnHeader: 'Domeniu',
    ObjectsColumnHeader: 'Obiecte',
    UniqueColumnHeader: 'Unice',
    SelectReportForCompareLabel: 'Selectați raportul din {0} pentru comparare',
    AllSitesPrefix: 'Toate site-urile · ',
    PlusSubsitesSuffix: ' + subsite-uri',
    ExportingStatus: 'Se exportă…',
    ExportButton: 'Export',
    DeleteThisReportTitle: 'Șterge acest raport',
    ScanAllSiteCollectionsLabel: 'Scanează toate colecțiile de site-uri din acest chiriaș (disponibil doar pe site-ul rădăcină)',
    AllSitesSearchCaveat: 'Lista de site-uri provine din căutare și poate să nu includă fiecare colecție de site-uri — site-urile create foarte recent, sau excluse din indexul de căutare, pot lipsi.',
    IncludeSubsitesLabel: 'Include subsite-uri (scanează fiecare subsite sub acest site)',
    ScanDepthFieldLabel: 'Adâncimea scanării',
    FolderDepthLimitLabel: 'Limita adâncimii folderelor:',
    ExpandGroupMembersInReportLabel: 'Extinde membrii grupului în raport (grupuri SharePoint, grupuri de securitate și grupuri M365)',
    LibrariesToScanLabel: 'Biblioteci de scanat',
    OfSelectedCount: '{0} din {1} selectate',
    AllButton: 'Toate',
    NoneButton: 'Niciunul',
    LoadingLibrariesStatus: 'Se încarcă bibliotecile…',
    RunReportButton: 'Rulează raportul',
    ItemsFoundSoFar: '{0} elemente găsite până acum',
    LibraryOfProgress: 'Biblioteca {0} din {1}',
    ScanCancelledPartialResults: 'Scanare anulată — rezultate parțiale',
    ScanCompleteLabel: 'Scanare finalizată',
    ObjectsCountBadge: '{0} obiecte',
    UniqueCountBadge: '{0} unice',
    InheritedCountBadge: '{0} moștenite',
    GeneratingExcelStatus: 'Se generează Excel…',
    ExportFilteredRowsButton: 'Exportă {0} rânduri filtrate',
    ExportToExcelButton: 'Exportă în Excel',
    ExportToCsvButton: 'Exportă în CSV',
    ScanStoppedEarlyTitle: 'Scanarea s-a oprit devreme — SharePoint limitează acest chiriaș.',
    SiteCollectionsScannedBeforeStopping: '{0} din {1} colecții de site-uri au fost scanate înainte de oprire. ',
    ResultsBelowCoverOnlyPre: 'Rezultatele de mai jos acoperă doar ceea ce a fost scanat și nu sunt',
    NotWord: 'nu',
    ResultsBelowCoverOnlyPost: 'un audit complet. Scanarea se oprește singură în această situație deoarece continuarea trimiterii cererilor menține limitarea activă. Așteptați câteva minute, apoi rulați din nou cu',
    ConcurrentRequestsWord: 'Cereri simultane',
    SetTo1Or2InSettings: 'setat la 1 sau 2 în Setări.',
    ThrottledScanMessage: 'SharePoint a limitat această scanare ({0} cerere(i) au fost limitate de rată și reîncercate).',
    OfEverythingScannedPre: 'Din tot ce a fost scanat,',
    ItemCountSingular: '{0} element',
    ItemCountPlural: '{0} elemente',
    CouldNotBeConfirmedText: 'nu au putut fi confirmate după reîncercare (vezi notificarea "nu a putut fi citit complet" de mai jos pentru a afla exact care) — acel eșec a fost legat de capacitate, nu o reflectare a permisiunilor lor reale. Toate celelalte elemente din acest raport au fost citite cu succes și pot fi de încredere.',
    DespiteThrottlingText: 'În ciuda limitării, fiecare element a fost totuși confirmat cu succes după reîncercare, deci acest raport este complet.',
    ForCleanRunPre: 'Pentru o execuție curată, așteptați câteva minute și scanați din nou cu o valoare mai mică pentru',
    ValueInSettingsPost: 'în Setări.',
    OneItemWord: '1 element',
    NItemsWord: '{0} element(e)',
    OutOfScannedCouldNotBeRead: 'din {0} scanate nu au putut fi citite cu accesul dvs. actual —',
    PermissionAssignmentsForItAreNotShown: ' atribuirile de permisiuni nu sunt afișate, ',
    PermissionAssignmentsForThoseAreNotShown: ' atribuirile de permisiuni nu sunt afișate, ',
    RestOfReportReadSuccessfully: 'dar restul acestui raport a fost citit cu succes.',
    RunScanAsSiteOwnerPre: 'Rulați scanarea ca',
    SiteOwnerWord: 'Proprietar al site-ului',
    RunScanAsSiteOwnerPost: 'pentru a vedea detalii complete pentru elementele refuzate de mai jos.',
    AndNMoreText: '…și încă {0}',
    GroupExpansionSkippedPre: 'Extinderea membrilor grupului a fost omisă — permisiunea Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'nu a fost aprobată în acest chiriaș. Un administrator SharePoint sau global o poate aproba în',
    SharePointAdminCenterPath: 'Centrul de administrare SharePoint → Avansat → Acces API',
    ScanIncompleteItemsMessage: '{0} element(e) nu au putut fi citite complet din cauza unei erori temporare (nu o problemă de permisiuni) și sunt afișate cu permisiunile elementului părinte ca soluție de rezervă — acest lucru poate să nu reflecte accesul lor real. Rulați din nou scanarea pentru a reîncerca aceste elemente.',
    FilterByNamePathUserPlaceholder: 'Filtrează după nume, cale sau utilizator/grup…',
    FilterResultsLabel: 'Filtrează rezultatele',
    ExternalUsersOnlyExtLabel: 'Doar utilizatori externi (#ext#)',
    ShowingOfCount: 'Se afișează {0} din {1}',
    ScanResultsLabel: 'Rezultatele scanării',
    PermissionsColumnHeader: 'Permisiuni',
    CollapsePermissionsLabel: 'Restrânge permisiunile',
    ExpandPermissionsLabel: 'Extinde permisiunile',
    HiddenFromSearchBadge: 'Ascuns din căutare',
    AssignmentCountSingular: '{0} atribuire',
    AssignmentCountPlural: '{0} atribuiri',
    LoadMoreRemainingButton: 'Încarcă mai multe ({0} rămase)',
    LoadingUsersStatus: 'Se încarcă utilizatorii…',
    ConnectedUserSingular: 'Conectat — {0} utilizator găsit',
    ConnectedUserPlural: 'Conectat — {0} utilizatori găsiți',
    CheckingAccessForStatus: 'Se verifică accesul pentru {0}…',
    FullSiteAccessDetectedStatus: 'Acces complet la site detectat.',
    AccessibleLocationsFoundSingular: '{0} locație accesibilă găsită.',
    AccessibleLocationsFoundPlural: '{0} locații accesibile găsite.',
    NoAccessibleLocationsFoundStatus: 'Nu s-au găsit locații accesibile.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Scanarea accesului utilizatorului finalizată',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Scanare nouă',
    NoUserAccessScansSavedYet: 'Nicio scanare a accesului utilizatorului salvată încă.',
    UserColumnHeader: 'Utilizator',
    LocationsColumnHeader: 'Locații',
    FullControlBadge: 'Control total',
    DeleteThisRecordTitle: 'Șterge această înregistrare',
    SelectAUserFieldLabel: 'Selectați un utilizator',
    SearchUsersPlaceholder: 'Căutați utilizatori…',
    SelectAUserToCheckAccessLabel: 'Selectați un utilizator pentru a verifica accesul',
    NotInThisSiteLabel: 'Nu este pe acest site',
    ScanInProgressLabel: 'Scanare în curs',
    ScanningUserAccessLabel: 'Se scanează accesul utilizatorului',
    ScanningStatus: 'Se scanează…',
    FullControlAccessPre: 'Acest utilizator are',
    FullControlWord: 'Control total',
    FullControlAccessPost: 'sau acces la nivel de Proprietar la întregul site — toate bibliotecile și folderele sunt accesibile.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Permisiunea la nivel de site nu a putut fi determinată — acest site probabil folosește acces prin grup Microsoft 365. Pentru a-l afișa, un administrator SharePoint trebuie să aprobe permisiunea',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph în',
    ShowingSiteLevelAccessOnlyPre: 'Se afișează doar',
    SiteLevelAccessOnlyWord: 'accesul la nivel de site',
    ShowingSiteLevelAccessOnlyMid: ', bazat pe apartenența implicită la grupul SharePoint. Permisiunile unice pe biblioteci, foldere și fișiere nu au putut fi citite și nu sunt afișate. Pentru rezultate complete, rulați această scanare ca',
    UserAccessCouldNotBeDeterminedPre: 'Accesul acestui utilizator nu a putut fi determinat. Citirea atribuirilor de permisiuni necesită dreptul',
    UserAccessCouldNotBeDeterminedPost: '(Proprietar al site-ului sau superior), și acest utilizator nu pare să fie membru al grupurilor implicite Proprietari, Membri sau Vizitatori ale site-ului.',
    SiteLevelAccessBannerPre: 'Acest utilizator are acces la nivel de site. Doar locațiile cu',
    UniquePermissionAssignmentsWord: 'atribuiri unice de permisiuni',
    SiteLevelAccessBannerPost: 'apar mai jos — tot celălalt conținut este accesibil prin permisiunea la nivel de site afișată în partea de sus a listei.',
    UserAccessResultsLabel: 'Rezultatele accesului utilizatorului',
  };
});
