define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Конфигурация Smart Permissions',
    PropertyPane_GroupName: 'Общие',
    PropertyPane_DefaultViewLabel: 'Представление по умолчанию при открытии',
    PropertyPane_View_Home: 'Главная',
    PropertyPane_View_Report: 'Отчет о разрешениях',
    PropertyPane_View_Explorer: 'Обозреватель разрешений',
    PropertyPane_View_UserAccess: 'Доступ пользователя',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/moisite',
    ConnectButton: 'Подключить',
    CancelButton: 'Отмена',
    ChangeUrlButton: 'Изменить URL-адрес',
    SettingsLabel: 'Параметры',
    RenderErrorTitle: 'Smart Permissions — Ошибка отрисовки',
    RenderErrorMessageLabel: 'Сообщение:',
    RenderErrorStackLabel: 'Стек:',
    RenderErrorNoStack: '(стек недоступен)',
    BackButton: 'Назад',
    BackToHomeLabel: 'Назад на главную',
    ExplorerCardTitle: 'Обозреватель разрешений',
    ExplorerCardAlt: 'Обозреватель разрешений с деревом папок и панелью разрешений',
    ExplorerCardDesc: 'Просматривайте любую папку или файл и мгновенно узнавайте, у кого есть доступ — с проверками разрешений в реальном времени.',
    ExplorerCardButton: 'Открыть обозреватель разрешений',
    ReportCardTitle: 'Отчет о разрешениях',
    ReportCardAlt: 'Экран настройки отчета о разрешениях',
    ReportCardDesc: 'Создайте цветной отчет Excel для каждого уникального назначения разрешений на вашем сайте.',
    ReportCardButton: 'Запустить отчет о разрешениях',
    UserAccessCardTitle: 'Доступ пользователя',
    UserAccessCardAlt: 'Экран доступа пользователя, показывающий доступные места для выбранного пользователя',
    UserAccessCardDesc: 'Найдите любого пользователя, чтобы увидеть все места, к которым у него есть доступ на сайте, с точным уровнем разрешений.',
    UserAccessCardButton: 'Проверить доступ пользователя',
    SiteOwnerRequiredTitle: 'Требуется доступ владельца сайта —',
    SiteOwnerRequiredDesc: 'Эти инструменты требуют доступа владельца сайта. Обратитесь к владельцу сайта, если у вас есть вопросы о разрешениях.',
    HomeSubtitle: 'Проверяйте и понимайте разрешения SharePoint — без PowerShell.',
    RequiresSiteOwnerTooltip: 'Требуется доступ владельца сайта',
    HomeNoteLabel: 'Примечание:',
    HomeNoteText: 'Эта веб-часть работает от имени текущего вошедшего пользователя. Она может видеть только сайты и элементы, к которым у этого пользователя есть доступ. Для полного сканирования клиента используйте учетную запись с соответствующим доступом на чтение ко всем сайтам.',
    SettingsTitle: 'Параметры',
    LibrariesSectionTitle: 'Библиотеки',
    IncludeHiddenLabel: 'Включить системные и скрытые библиотеки',
    IncludeHiddenTooltip: 'Если установлен флажок, включает библиотеку стилей, шаблоны форм, ресурсы сайта и другие библиотеки, скрытые из представлений по умолчанию. Применяется ко всем инструментам.',
    MoreInfoHiddenLibrariesLabel: 'Дополнительные сведения о скрытых библиотеках',
    ExcludeLimitedAccessLabel: 'Исключить записи с ограниченным доступом',
    ExcludeLimitedAccessTooltip: 'Скрывает пользователей и группы, единственным разрешением SharePoint которых является Ограниченный доступ — назначается автоматически при совместном использовании файлов по ссылкам. Применяется к отчету о разрешениях, обозревателю и доступу пользователя.',
    MoreInfoLimitedAccessLabel: 'Дополнительные сведения об ограниченном доступе',
    ExcludeSharingLinksLabel: 'Исключить записи ссылок для общего доступа',
    ExcludeSharingLinksTooltip: 'Скрывает внутренние группы "SharingLinks.*", которые SharePoint автоматически создает для ссылок общего доступа "Все, у кого есть ссылка" и "Определенные пользователи". Применяется к отчету о разрешениях, обозревателю и доступу пользователя.',
    MoreInfoSharingLinksLabel: 'Дополнительные сведения о ссылках для общего доступа',
    PerformanceSectionTitle: 'Производительность',
    ConcurrentRequestsLabel: 'Одновременные запросы API:',
    ConcurrencyTooltip: 'Сколько запросов API SharePoint выполняется параллельно во время сканирования отчета о разрешениях, сканирования доступа пользователя и фоновых проверок обозревателя. Более высокие значения быстрее, но с большей вероятностью вызовут ограничение (HTTP 429). Рекомендуется 3–5.',
    MoreInfoConcurrencyLabel: 'Дополнительные сведения о параллелизме',
    ConcurrencyHint: 'Более высокие значения сканируют быстрее, но могут вызвать ограничение SharePoint. Рекомендуется: 3–5.',
    GroupMemberCapLabel: 'Лимит отображения участников группы:',
    GroupMemberCapTooltip: 'Максимальное количество участников, отображаемых на группу, когда включено "Развернуть участников группы". Более крупные группы ограничиваются, и отображается уведомление. Увеличение этого значения использует больше памяти.',
    MoreInfoGroupMemberCapLabel: 'Дополнительные сведения о лимите участников группы',
    GroupMemberCapHint: 'Группы, превышающие этот лимит, показывают уведомление об усечении. По умолчанию: 500.',
    DefaultViewSectionTitle: 'Представление по умолчанию при загрузке',
    DefaultViewInstructionsIntro: 'Чтобы изменить, какой экран открывается при первой загрузке веб-части, отредактируйте свойства веб-части:',
    DefaultViewStep1Pre: 'Переведите страницу SharePoint в режим',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Щелкните значок',
    DefaultViewStep2Post: 'на веб-части Smart Permissions.',
    DefaultViewStep3Pre: 'На панели свойств выберите представление из раскрывающегося списка',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'страницу, чтобы сохранить изменение.',
    EditModeWord: 'Редактирования',
    PencilEditWord: 'карандаш (редактировать)',
    DefaultViewOnOpenWord: 'Представление по умолчанию при открытии',
    RepublishWord: 'Опубликуйте повторно',
    SiteOwnersLabel: 'Владельцы сайта:',
    EveryoneClaimLabel: 'Все',
    EveryoneExceptExternalClaimLabel: 'Все, кроме внешних пользователей',
    PermissionAssignmentsLabel: 'Назначения разрешений',
    UserGroupColumnHeader: 'Пользователь / Группа',
    TypeColumnHeader: 'Тип',
    PermissionLevelColumnHeader: 'Уровень разрешений',
    TenantWideAccessSuffix: '— доступ на уровне всего клиента',
    SecurityGroupType: 'Группа безопасности',
    SpGroupType: 'Группа SP',
    UserType: 'Пользователь',
    CheckAccessForLabel: 'Проверить доступ для {0}',
    ContainsUniqueAndExternalTooltip: 'Содержит элементы с уникальными разрешениями и доступом внешних пользователей',
    ContainsUniqueTooltip: 'Содержит элементы с уникальными разрешениями',
    ContainsExternalTooltip: 'Содержит элементы с доступом внешних пользователей',
    UniqueBadge: 'Уникальное',
    ExternalAccessDetectedTooltip: 'Обнаружен доступ внешнего пользователя',
    ConnectingStatus: 'Подключение…',
    ConnectedLibrarySingular: 'Подключено — найдена {0} библиотека',
    ConnectedLibraryPlural: 'Подключено — найдено {0} библиотек',
    ConnectionFailedError: 'Не удалось подключиться: {0}',
    LibraryEmptyStatus: 'Эта библиотека пуста.',
    ErrorLoadingLibrary: 'Ошибка при загрузке библиотеки: {0}',
    ErrorLoadingContents: 'Ошибка при загрузке содержимого',
    LibraryFieldLabel: 'Библиотека',
    HiddenFromSearchSuffix: '{0} (скрыто из поиска)',
    UniquePermissionsOnlyToggle: 'Только уникальные разрешения',
    ExternalUsersOnlyToggle: 'Только внешние пользователи',
    LegendLabel: 'Легенда:',
    LegendItemHasUnique: 'Элемент имеет уникальные разрешения',
    LegendContainsUniqueBelow: 'Содержит уникальные разрешения ниже',
    LegendContainsExternalBelow: 'Содержит доступ внешнего пользователя ниже',
    LegendExternalOnItem: 'Доступ внешнего пользователя к этому элементу',
    ViewingWithMemberAccessTitle: 'Просмотр с доступом участника',
    ViewingWithMemberAccessDesc1: '— назначения разрешений не отображаются. Чтобы узнать, у кого есть доступ, требуется право',
    ManagePermissionsWord: 'Управление разрешениями',
    ViewingWithMemberAccessDesc2: '(владелец сайта или выше). Вы по-прежнему можете видеть, какие элементы имеют нарушенное наследование, используя индикаторы ↓. Чтобы увидеть места, к которым у вас есть доступ, используйте инструмент',
    UserAccessWord: 'Доступ пользователя',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Папки и файлы',
    SelectFolderOrFilePrompt: 'Выберите папку или файл, чтобы просмотреть его разрешения.',
    UniquePermissionsBadge: 'Уникальные разрешения',
    InheritedBadge: 'Унаследовано',
    ExpandGroupMembersLabel: 'Развернуть участников группы',
    ShowParentPermissionsLabel: 'Показать родительские разрешения',
    InheritsFromParentText: 'Этот элемент наследует разрешения от родительского элемента.',
    YourAccessLabel: 'Ваш доступ:',
    PermissionsNotVisibleNodeText: 'Назначения разрешений не отображаются — требуется право Управление разрешениями (владелец сайта или выше), чтобы увидеть, у кого есть доступ к этому элементу.',
    NoExternalUsersDirectAccessText: 'Ни у одного внешнего пользователя нет прямого доступа к этому элементу.',
    InheritedFromLabel: 'Унаследовано от:',
    ParentPermissionsNotVisibleText: 'Назначения разрешений родительского элемента не отображаются — требуется право Управление разрешениями (владелец сайта или выше).',
    NoPermissionsFoundOnParentText: 'На родительском элементе не найдено разрешений.',
    StartingScanStatus: 'Запуск сканирования…',
    ScanCancelledStatus: 'Сканирование отменено — собрано {0} объект(ов) до отмены.',
    ScanCompleteStatus: 'Сканирование завершено — найдено {0} объект(ов), {1} с уникальными разрешениями.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Сканирование завершено',
    ScanCompleteNotificationBody: '{0} объектов, {1} с уникальными разрешениями.',
    CancelledStatus: 'Отменено.',
    GenericErrorPrefix: 'Ошибка: {0}',
    ExportErrorPrefix: 'Ошибка экспорта: {0}',
    ScopeSiteOnly: 'Только сайт',
    ScopeLibraries: 'Библиотеки',
    ScopeFolders: 'Папки',
    ScopeFilesAndFolders: 'Файлы и папки',
    ScanInProgressConfirm: 'Сканирование выполняется. Выйти и отменить?',
    HistoryButton: 'История',
    BackToHistoryButton: 'Назад к истории',
    ComparingLabel: 'Сравнение',
    CompareMismatchWarning: 'Эти отчеты были созданы с разными сайтами или параметрами сканирования — различия ниже могут отражать измененные параметры сканирования, а не фактические изменения разрешений.',
    NoPermissionDifferencesFound: 'Различий в разрешениях между этими двумя отчетами не найдено.',
    PermissionChangesHeaderSingular: 'Изменения разрешений ({0} объект)',
    PermissionChangesHeaderPlural: 'Изменения разрешений ({0} объектов)',
    ChangeColumnHeader: 'Изменение',
    BeforeColumnHeader: 'До',
    AfterColumnHeader: 'После',
    AddedBadge: 'Добавлено',
    RemovedBadge: 'Удалено',
    ChangedBadge: 'Изменено',
    InheritanceChangedHeader: 'Наследование изменено ({0})',
    NameColumnHeader: 'Имя',
    PathColumnHeader: 'Путь',
    NowColumnHeader: 'Сейчас',
    UniqueInheritanceBrokenBadge: 'Уникальное (наследование нарушено)',
    InheritedRestoredBadge: 'Унаследовано (восстановлено)',
    NewObjectsHeader: 'Новые объекты',
    RemovedObjectsHeader: 'Удаленные объекты',
    BackToScanButton: 'Назад к сканированию',
    CompareSelectedButton: 'Сравнить выбранные',
    NoReportsSavedYet: 'Отчеты еще не сохранены.',
    SelectForCompareLabel: 'Выбрать для сравнения',
    DateTimeColumnHeader: 'Дата / Время',
    SiteColumnHeader: 'Сайт',
    ScopeColumnHeader: 'Область',
    ObjectsColumnHeader: 'Объекты',
    UniqueColumnHeader: 'Уникальные',
    SelectReportForCompareLabel: 'Выбрать отчет от {0} для сравнения',
    AllSitesPrefix: 'Все сайты · ',
    PlusSubsitesSuffix: ' + подсайты',
    ExportingStatus: 'Экспорт…',
    ExportButton: 'Экспорт',
    DeleteThisReportTitle: 'Удалить этот отчет',
    ScanAllSiteCollectionsLabel: 'Сканировать все семейства сайтов в этом клиенте (доступно только на корневом сайте)',
    AllSitesSearchCaveat: 'Список сайтов получен из поиска и может не включать все семейства сайтов — очень недавно созданные сайты или сайты, исключенные из индекса поиска, могут отсутствовать.',
    IncludeSubsitesLabel: 'Включить подсайты (сканирует каждый подсайт под этим сайтом)',
    ScanDepthFieldLabel: 'Глубина сканирования',
    FolderDepthLimitLabel: 'Ограничение глубины папок:',
    ExpandGroupMembersInReportLabel: 'Развернуть участников группы в отчете (группы SharePoint, группы безопасности и группы M365)',
    LibrariesToScanLabel: 'Библиотеки для сканирования',
    OfSelectedCount: 'Выбрано {0} из {1}',
    AllButton: 'Все',
    NoneButton: 'Нет',
    LoadingLibrariesStatus: 'Загрузка библиотек…',
    RunReportButton: 'Запустить отчет',
    ItemsFoundSoFar: 'Пока найдено {0} элементов',
    LibraryOfProgress: 'Библиотека {0} из {1}',
    ScanCancelledPartialResults: 'Сканирование отменено — частичные результаты',
    ScanCompleteLabel: 'Сканирование завершено',
    ObjectsCountBadge: '{0} объектов',
    UniqueCountBadge: '{0} уникальных',
    InheritedCountBadge: '{0} унаследованных',
    GeneratingExcelStatus: 'Создание Excel…',
    ExportFilteredRowsButton: 'Экспортировать {0} отфильтрованных строк',
    ExportToExcelButton: 'Экспорт в Excel',
    ExportToCsvButton: 'Экспорт в CSV',
    ScanStoppedEarlyTitle: 'Сканирование остановлено досрочно — SharePoint ограничивает этого клиента.',
    SiteCollectionsScannedBeforeStopping: '{0} из {1} семейств сайтов были просканированы до остановки. ',
    ResultsBelowCoverOnlyPre: 'Результаты ниже охватывают только то, что было просканировано, и не являются',
    NotWord: 'не являются',
    ResultsBelowCoverOnlyPost: 'полной проверкой. Сканирование останавливается само в этой ситуации, потому что продолжение отправки запросов поддерживает ограничение активным. Подождите несколько минут, затем запустите снова с',
    ConcurrentRequestsWord: 'Одновременные запросы',
    SetTo1Or2InSettings: 'установлено на 1 или 2 в Параметрах.',
    ThrottledScanMessage: 'SharePoint ограничил это сканирование ({0} запрос(ов) были ограничены и повторены).',
    OfEverythingScannedPre: 'Из всего просканированного,',
    ItemCountSingular: '{0} элемент',
    ItemCountPlural: '{0} элементов',
    CouldNotBeConfirmedText: 'не удалось подтвердить после повторной попытки (см. уведомление "не удалось полностью прочитать" ниже, чтобы узнать, какие именно) — этот сбой был связан с емкостью, а не отражением их фактических разрешений. Все остальные элементы в этом отчете были успешно прочитаны и им можно доверять.',
    DespiteThrottlingText: 'Несмотря на ограничение, каждый элемент все же был успешно подтвержден после повторной попытки, поэтому этот отчет полный.',
    ForCleanRunPre: 'Для чистого выполнения подождите несколько минут и просканируйте снова с более низким значением для',
    ValueInSettingsPost: 'в Параметрах.',
    OneItemWord: '1 элемент',
    NItemsWord: '{0} элемент(ов)',
    OutOfScannedCouldNotBeRead: 'из {0} просканированных не удалось прочитать с вашим текущим доступом —',
    PermissionAssignmentsForItAreNotShown: ' назначения разрешений не отображаются, ',
    PermissionAssignmentsForThoseAreNotShown: ' назначения разрешений не отображаются, ',
    RestOfReportReadSuccessfully: 'но остальная часть этого отчета была успешно прочитана.',
    RunScanAsSiteOwnerPre: 'Запустите сканирование как',
    SiteOwnerWord: 'владелец сайта',
    RunScanAsSiteOwnerPost: 'чтобы увидеть полные сведения об отклоненных элементах ниже.',
    AndNMoreText: '…и еще {0}',
    GroupExpansionSkippedPre: 'Разворачивание участников группы было пропущено — разрешение Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'не было утверждено в этом клиенте. Администратор SharePoint или глобальный администратор может утвердить его в',
    SharePointAdminCenterPath: 'Центр администрирования SharePoint → Дополнительно → Доступ к API',
    ScanIncompleteItemsMessage: '{0} элемент(ов) не удалось полностью прочитать из-за временной ошибки (не проблемы с разрешениями), и они отображаются с разрешениями родительского элемента в качестве резервного варианта — это может не отражать их фактический доступ. Запустите сканирование снова, чтобы повторить попытку для этих элементов.',
    FilterByNamePathUserPlaceholder: 'Фильтр по имени, пути или пользователю/группе…',
    FilterResultsLabel: 'Фильтровать результаты',
    ExternalUsersOnlyExtLabel: 'Только внешние пользователи (#ext#)',
    ShowingOfCount: 'Показано {0} из {1}',
    ScanResultsLabel: 'Результаты сканирования',
    PermissionsColumnHeader: 'Разрешения',
    CollapsePermissionsLabel: 'Свернуть разрешения',
    ExpandPermissionsLabel: 'Развернуть разрешения',
    HiddenFromSearchBadge: 'Скрыто из поиска',
    AssignmentCountSingular: '{0} назначение',
    AssignmentCountPlural: '{0} назначений',
    LoadMoreRemainingButton: 'Загрузить еще (осталось {0})',
    LoadingUsersStatus: 'Загрузка пользователей…',
    ConnectedUserSingular: 'Подключено — найден {0} пользователь',
    ConnectedUserPlural: 'Подключено — найдено {0} пользователей',
    CheckingAccessForStatus: 'Проверка доступа для {0}…',
    FullSiteAccessDetectedStatus: 'Обнаружен полный доступ к сайту.',
    AccessibleLocationsFoundSingular: 'Найдено {0} доступное место.',
    AccessibleLocationsFoundPlural: 'Найдено {0} доступных мест.',
    NoAccessibleLocationsFoundStatus: 'Доступных мест не найдено.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Сканирование доступа пользователя завершено',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Новое сканирование',
    NoUserAccessScansSavedYet: 'Сканирования доступа пользователя еще не сохранены.',
    UserColumnHeader: 'Пользователь',
    LocationsColumnHeader: 'Места',
    FullControlBadge: 'Полный контроль',
    DeleteThisRecordTitle: 'Удалить эту запись',
    SelectAUserFieldLabel: 'Выберите пользователя',
    SearchUsersPlaceholder: 'Поиск пользователей…',
    SelectAUserToCheckAccessLabel: 'Выберите пользователя для проверки доступа',
    NotInThisSiteLabel: 'Не на этом сайте',
    ScanInProgressLabel: 'Сканирование выполняется',
    ScanningUserAccessLabel: 'Сканирование доступа пользователя',
    ScanningStatus: 'Сканирование…',
    FullControlAccessPre: 'У этого пользователя есть',
    FullControlWord: 'Полный контроль',
    FullControlAccessPost: 'или доступ уровня владельца ко всему сайту — все библиотеки и папки доступны.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Не удалось определить разрешение на уровне сайта — этот сайт, вероятно, использует доступ через группу Microsoft 365. Чтобы показать его, администратор SharePoint должен утвердить разрешение',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph в',
    ShowingSiteLevelAccessOnlyPre: 'Отображается только',
    SiteLevelAccessOnlyWord: 'доступ на уровне сайта',
    ShowingSiteLevelAccessOnlyMid: ', основанный на членстве в группе SharePoint по умолчанию. Уникальные разрешения для библиотек, папок и файлов не удалось прочитать, и они не отображаются. Для полных результатов запустите это сканирование как',
    UserAccessCouldNotBeDeterminedPre: 'Не удалось определить доступ этого пользователя. Для чтения назначений разрешений требуется право',
    UserAccessCouldNotBeDeterminedPost: '(владелец сайта или выше), и этот пользователь, похоже, не является участником групп по умолчанию Владельцы, Участники или Посетители сайта.',
    SiteLevelAccessBannerPre: 'У этого пользователя есть доступ на уровне сайта. Ниже отображаются только места с',
    UniquePermissionAssignmentsWord: 'уникальными назначениями разрешений',
    SiteLevelAccessBannerPost: '— все остальное содержимое доступно через разрешение на уровне сайта, показанное в верхней части списка.',
    UserAccessResultsLabel: 'Результаты доступа пользователя',
  };
});
