define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions-konfiguration',
    PropertyPane_GroupName: 'Allmänt',
    PropertyPane_DefaultViewLabel: 'Standardvy vid öppning',
    PropertyPane_View_Home: 'Start',
    PropertyPane_View_Report: 'Behörighetsrapport',
    PropertyPane_View_Explorer: 'Behörighetsutforskare',
    PropertyPane_View_UserAccess: 'Användaråtkomst',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/minwebbplats',
    ConnectButton: 'Anslut',
    CancelButton: 'Avbryt',
    ChangeUrlButton: 'Ändra URL',
    SettingsLabel: 'Inställningar',
    RenderErrorTitle: 'Smart Permissions — Renderingsfel',
    RenderErrorMessageLabel: 'Meddelande:',
    RenderErrorStackLabel: 'Stack:',
    RenderErrorNoStack: '(ingen stack tillgänglig)',
    BackButton: 'Tillbaka',
    BackToHomeLabel: 'Tillbaka till start',
    ExplorerCardTitle: 'Behörighetsutforskare',
    ExplorerCardAlt: 'Behörighetsutforskare med mappträd och behörighetspanel',
    ExplorerCardDesc: 'Bläddra i valfri mapp eller fil och se direkt vem som har åtkomst — med realtidskontroller.',
    ExplorerCardButton: 'Öppna behörighetsutforskaren',
    ReportCardTitle: 'Behörighetsrapport',
    ReportCardAlt: 'Konfigurationsskärm för behörighetsrapport',
    ReportCardDesc: 'Generera en färgkodad Excel-rapport över varje unik behörighetstilldelning på din webbplats.',
    ReportCardButton: 'Kör behörighetsrapport',
    UserAccessCardTitle: 'Användaråtkomst',
    UserAccessCardAlt: 'Skärm för användaråtkomst som visar tillgängliga platser för en vald användare',
    UserAccessCardDesc: 'Slå upp valfri användare för att se varje plats de kan komma åt på en webbplats, med exakt behörighetsnivå.',
    UserAccessCardButton: 'Kontrollera användaråtkomst',
    SiteOwnerRequiredTitle: 'Åtkomst som webbplatsägare krävs —',
    SiteOwnerRequiredDesc: 'Dessa verktyg kräver åtkomst som webbplatsägare. Kontakta en webbplatsägare om du har frågor om behörigheter.',
    HomeSubtitle: 'Granska och förstå SharePoint-behörigheter — utan PowerShell.',
    RequiresSiteOwnerTooltip: 'Kräver åtkomst som webbplatsägare',
    HomeNoteLabel: 'Obs:',
    HomeNoteText: 'Denna webbdel körs som den aktuellt inloggade användaren. Den kan bara se webbplatser och objekt som den användaren har behörighet till. Använd ett konto med lämplig läsåtkomst till alla webbplatser för en fullständig genomsökning av klientorganisationen.',
    SettingsTitle: 'Inställningar',
    LibrariesSectionTitle: 'Bibliotek',
    IncludeHiddenLabel: 'Inkludera system- och dolda bibliotek',
    IncludeHiddenTooltip: 'Om markerad, inkluderas Formatmall, Formulärmallar, Webbplatstillgångar och andra bibliotek som är dolda från standardvyer. Gäller alla verktyg.',
    MoreInfoHiddenLibrariesLabel: 'Mer information om dolda bibliotek',
    ExcludeLimitedAccessLabel: 'Exkludera poster med Begränsad åtkomst',
    ExcludeLimitedAccessTooltip: 'Döljer användare och grupper vars enda SharePoint-behörighet är Begränsad åtkomst — tilldelas automatiskt när filer delas via länkar. Gäller Behörighetsrapport, Utforskaren och Användaråtkomst.',
    MoreInfoLimitedAccessLabel: 'Mer information om Begränsad åtkomst',
    ExcludeSharingLinksLabel: 'Exkludera poster med delningslänkar',
    ExcludeSharingLinksTooltip: 'Döljer de interna "SharingLinks.*"-grupperna som SharePoint skapar automatiskt för delningslänkar av typen "Alla med länken" och "Specifika personer". Gäller Behörighetsrapport, Utforskaren och Användaråtkomst.',
    MoreInfoSharingLinksLabel: 'Mer information om delningslänkar',
    PerformanceSectionTitle: 'Prestanda',
    ConcurrentRequestsLabel: 'Samtidiga API-förfrågningar:',
    ConcurrencyTooltip: 'Hur många SharePoint-API-förfrågningar som körs parallellt under genomsökningar av Behörighetsrapport, Användaråtkomst och bakgrundskontroller i Utforskaren. Högre värden är snabbare men mer benägna att utlösa strypning (HTTP 429). 3–5 rekommenderas.',
    MoreInfoConcurrencyLabel: 'Mer information om samtidighet',
    ConcurrencyHint: 'Högre värden skannar snabbare men kan utlösa SharePoint-strypning. Rekommenderat: 3–5.',
    GroupMemberCapLabel: 'Visningsgräns för gruppmedlemmar:',
    GroupMemberCapTooltip: 'Max antal medlemmar som visas per grupp när "Expandera gruppmedlemmar" är aktiverat. Större grupper begränsas och ett meddelande visas. Att höja detta använder mer minne.',
    MoreInfoGroupMemberCapLabel: 'Mer information om gränsen för gruppmedlemmar',
    GroupMemberCapHint: 'Grupper större än denna gräns visar ett avkortningsmeddelande. Standard: 500.',
    DefaultViewSectionTitle: 'Standardvy vid inläsning',
    DefaultViewInstructionsIntro: 'För att ändra vilken skärm som öppnas när webbdelen först läses in, redigera webbdelens egenskaper:',
    DefaultViewStep1Pre: 'Sätt SharePoint-sidan i',
    DefaultViewStep1Post: '-läge.',
    DefaultViewStep2Pre: 'Klicka på',
    DefaultViewStep2Post: '-ikonen på Smart Permissions-webbdelen.',
    DefaultViewStep3Pre: 'Välj en vy i listrutan',
    DefaultViewStep3Post: 'i egenskapspanelen.',
    DefaultViewStep4Post: 'sidan för att spara ändringen.',
    EditModeWord: 'Redigerings',
    PencilEditWord: 'penn- (redigera)',
    DefaultViewOnOpenWord: 'Standardvy vid öppning',
    RepublishWord: 'Publicera om',
    SiteOwnersLabel: 'Webbplatsägare:',
    EveryoneClaimLabel: 'Alla',
    EveryoneExceptExternalClaimLabel: 'Alla utom externa användare',
    PermissionAssignmentsLabel: 'Behörighetstilldelningar',
    UserGroupColumnHeader: 'Användare / Grupp',
    TypeColumnHeader: 'Typ',
    PermissionLevelColumnHeader: 'Behörighetsnivå',
    TenantWideAccessSuffix: '— åtkomst i hela klientorganisationen',
    SecurityGroupType: 'Säkerhetsgrupp',
    SpGroupType: 'SP-grupp',
    UserType: 'Användare',
    CheckAccessForLabel: 'Kontrollera åtkomst för {0}',
    ContainsUniqueAndExternalTooltip: 'Innehåller objekt med unika behörigheter och extern användaråtkomst',
    ContainsUniqueTooltip: 'Innehåller objekt med unika behörigheter',
    ContainsExternalTooltip: 'Innehåller objekt med extern användaråtkomst',
    UniqueBadge: 'Unik',
    ExternalAccessDetectedTooltip: 'Extern användaråtkomst upptäckt',
    ConnectingStatus: 'Ansluter…',
    ConnectedLibrarySingular: 'Ansluten — {0} bibliotek hittades',
    ConnectedLibraryPlural: 'Ansluten — {0} bibliotek hittades',
    ConnectionFailedError: 'Anslutningen misslyckades: {0}',
    LibraryEmptyStatus: 'Det här biblioteket är tomt.',
    ErrorLoadingLibrary: 'Fel vid inläsning av bibliotek: {0}',
    ErrorLoadingContents: 'Fel vid inläsning av innehåll',
    LibraryFieldLabel: 'Bibliotek',
    HiddenFromSearchSuffix: '{0} (dold från sökning)',
    UniquePermissionsOnlyToggle: 'Endast unika behörigheter',
    ExternalUsersOnlyToggle: 'Endast externa användare',
    LegendLabel: 'Teckenförklaring:',
    LegendItemHasUnique: 'Objektet har unika behörigheter',
    LegendContainsUniqueBelow: 'Innehåller unika behörigheter nedan',
    LegendContainsExternalBelow: 'Innehåller extern användaråtkomst nedan',
    LegendExternalOnItem: 'Extern användaråtkomst på detta objekt',
    ViewingWithMemberAccessTitle: 'Visar med medlemsåtkomst',
    ViewingWithMemberAccessDesc1: '— behörighetstilldelningar är inte synliga. För att se vem som har åtkomst krävs rättigheten',
    ManagePermissionsWord: 'Hantera behörigheter',
    ViewingWithMemberAccessDesc2: '(webbplatsägare eller högre). Du kan fortfarande se vilka objekt som har bruten arvskedja med hjälp av ↓-indikatorerna. Använd verktyget',
    UserAccessWord: 'Användaråtkomst',
    ViewingWithMemberAccessDesc3: 'för att se platser du kan komma åt.',
    FoldersAndFilesLabel: 'Mappar och filer',
    SelectFolderOrFilePrompt: 'Välj en mapp eller fil för att visa dess behörigheter.',
    UniquePermissionsBadge: 'Unika behörigheter',
    InheritedBadge: 'Ärvd',
    ExpandGroupMembersLabel: 'Expandera gruppmedlemmar',
    ShowParentPermissionsLabel: 'Visa överordnade behörigheter',
    InheritsFromParentText: 'Detta objekt ärver behörigheter från sitt överordnade objekt.',
    YourAccessLabel: 'Din åtkomst:',
    PermissionsNotVisibleNodeText: 'Behörighetstilldelningar är inte synliga — rättigheten Hantera behörigheter (webbplatsägare eller högre) krävs för att se vem som har åtkomst till detta objekt.',
    NoExternalUsersDirectAccessText: 'Inga externa användare har direkt åtkomst till detta objekt.',
    InheritedFromLabel: 'Ärvd från:',
    ParentPermissionsNotVisibleText: 'Det överordnade objektets behörighetstilldelningar är inte synliga — kräver rättigheten Hantera behörigheter (webbplatsägare eller högre).',
    NoPermissionsFoundOnParentText: 'Inga behörigheter hittades på det överordnade objektet.',
    StartingScanStatus: 'Startar genomsökning…',
    ScanCancelledStatus: 'Genomsökning avbruten — {0} objekt insamlade före avbrott.',
    ScanCompleteStatus: 'Genomsökning klar — {0} objekt hittades, {1} med unika behörigheter.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Genomsökning klar',
    ScanCompleteNotificationBody: '{0} objekt, {1} med unika behörigheter.',
    CancelledStatus: 'Avbruten.',
    GenericErrorPrefix: 'Fel: {0}',
    ExportErrorPrefix: 'Exportfel: {0}',
    ScopeSiteOnly: 'Endast webbplats',
    ScopeLibraries: 'Bibliotek',
    ScopeFolders: 'Mappar',
    ScopeFilesAndFolders: 'Filer och mappar',
    ScanInProgressConfirm: 'En genomsökning pågår. Lämna och avbryt?',
    HistoryButton: 'Historik',
    BackToHistoryButton: 'Tillbaka till historik',
    ComparingLabel: 'Jämför',
    CompareMismatchWarning: 'Dessa rapporter togs med olika webbplatser eller genomsökningsalternativ — skillnaderna nedan kan spegla ändrade genomsökningsinställningar snarare än faktiska behörighetsändringar.',
    NoPermissionDifferencesFound: 'Inga behörighetsskillnader hittades mellan dessa två rapporter.',
    PermissionChangesHeaderSingular: 'Behörighetsändringar ({0} objekt)',
    PermissionChangesHeaderPlural: 'Behörighetsändringar ({0} objekt)',
    ChangeColumnHeader: 'Ändring',
    BeforeColumnHeader: 'Före',
    AfterColumnHeader: 'Efter',
    AddedBadge: 'Tillagd',
    RemovedBadge: 'Borttagen',
    ChangedBadge: 'Ändrad',
    InheritanceChangedHeader: 'Arv ändrat ({0})',
    NameColumnHeader: 'Namn',
    PathColumnHeader: 'Sökväg',
    NowColumnHeader: 'Nu',
    UniqueInheritanceBrokenBadge: 'Unik (arv brutet)',
    InheritedRestoredBadge: 'Ärvd (återställd)',
    NewObjectsHeader: 'Nya objekt',
    RemovedObjectsHeader: 'Borttagna objekt',
    BackToScanButton: 'Tillbaka till genomsökning',
    CompareSelectedButton: 'Jämför markerade',
    NoReportsSavedYet: 'Inga rapporter sparade än.',
    SelectForCompareLabel: 'Välj för jämförelse',
    DateTimeColumnHeader: 'Datum / Tid',
    SiteColumnHeader: 'Webbplats',
    ScopeColumnHeader: 'Omfattning',
    ObjectsColumnHeader: 'Objekt',
    UniqueColumnHeader: 'Unika',
    SelectReportForCompareLabel: 'Välj rapport från {0} för jämförelse',
    AllSitesPrefix: 'Alla webbplatser · ',
    PlusSubsitesSuffix: ' + underwebbplatser',
    ExportingStatus: 'Exporterar…',
    ExportButton: 'Exportera',
    DeleteThisReportTitle: 'Ta bort denna rapport',
    ScanAllSiteCollectionsLabel: 'Sök igenom alla webbplatssamlingar i denna klientorganisation (endast tillgängligt på rotwebbplatsen)',
    AllSitesSearchCaveat: 'Webbplatslistan kommer från sökning och kanske inte inkluderar varje webbplatssamling — mycket nyligen skapade webbplatser, eller webbplatser exkluderade från sökindexet, kan saknas.',
    IncludeSubsitesLabel: 'Inkludera underwebbplatser (söker igenom varje underwebbplats under denna webbplats)',
    ScanDepthFieldLabel: 'Genomsökningsdjup',
    FolderDepthLimitLabel: 'Gräns för mappdjup:',
    ExpandGroupMembersInReportLabel: 'Expandera gruppmedlemmar i rapporten (SharePoint-grupper, säkerhetsgrupper och M365-grupper)',
    LibrariesToScanLabel: 'Bibliotek att söka igenom',
    OfSelectedCount: '{0} av {1} valda',
    AllButton: 'Alla',
    NoneButton: 'Inga',
    LoadingLibrariesStatus: 'Läser in bibliotek…',
    RunReportButton: 'Kör rapport',
    ItemsFoundSoFar: '{0} objekt hittade hittills',
    LibraryOfProgress: 'Bibliotek {0} av {1}',
    ScanCancelledPartialResults: 'Genomsökning avbruten — delvisa resultat',
    ScanCompleteLabel: 'Genomsökning klar',
    ObjectsCountBadge: '{0} objekt',
    UniqueCountBadge: '{0} unika',
    InheritedCountBadge: '{0} ärvda',
    GeneratingExcelStatus: 'Genererar Excel…',
    ExportFilteredRowsButton: 'Exportera {0} filtrerade rader',
    ExportToExcelButton: 'Exportera till Excel',
    ExportToCsvButton: 'Exportera till CSV',
    ScanStoppedEarlyTitle: 'Genomsökningen stoppades tidigt — SharePoint strypar denna klientorganisation.',
    SiteCollectionsScannedBeforeStopping: '{0} av {1} webbplatssamlingar genomsöktes innan stopp. ',
    ResultsBelowCoverOnlyPre: 'Resultaten nedan täcker endast det som genomsöktes och är',
    NotWord: 'inte',
    ResultsBelowCoverOnlyPost: 'en fullständig granskning. Genomsökningen stoppar sig själv i denna situation eftersom fortsatt sändning av förfrågningar är det som håller strypningen aktiv. Vänta flera minuter och kör sedan om med',
    ConcurrentRequestsWord: 'Samtidiga förfrågningar',
    SetTo1Or2InSettings: 'inställt på 1 eller 2 i Inställningar.',
    ThrottledScanMessage: 'SharePoint strypte denna genomsökning ({0} förfrågan/förfrågningar hastighetsbegränsades och försöktes igen).',
    OfEverythingScannedPre: 'Av allt som genomsöktes,',
    ItemCountSingular: '{0} objekt',
    ItemCountPlural: '{0} objekt',
    CouldNotBeConfirmedText: 'kunde inte bekräftas efter att ha försökts igen (se meddelandet "kunde inte läsas fullständigt" nedan för exakt vilka) — det felet berodde på kapacitet, inte deras faktiska behörigheter. Alla andra objekt i denna rapport lästes framgångsrikt och kan lita på.',
    DespiteThrottlingText: 'Trots strypningen bekräftades varje objekt ändå framgångsrikt efter nytt försök, så denna rapport är komplett.',
    ForCleanRunPre: 'För en ren körning, vänta några minuter och sök igen med ett lägre värde för',
    ValueInSettingsPost: 'i Inställningar.',
    OneItemWord: '1 objekt',
    NItemsWord: '{0} objekt',
    OutOfScannedCouldNotBeRead: 'av {0} genomsökta kunde inte läsas med din nuvarande åtkomst —',
    PermissionAssignmentsForItAreNotShown: ' behörighetstilldelningar visas inte, ',
    PermissionAssignmentsForThoseAreNotShown: ' behörighetstilldelningar visas inte, ',
    RestOfReportReadSuccessfully: 'men resten av denna rapport lästes framgångsrikt.',
    RunScanAsSiteOwnerPre: 'Kör genomsökningen som',
    SiteOwnerWord: 'webbplatsägare',
    RunScanAsSiteOwnerPost: 'för att se fullständiga detaljer för de nekade objekten nedan.',
    AndNMoreText: '…och {0} till',
    GroupExpansionSkippedPre: 'Expansion av gruppmedlemmar hoppades över — Graph-behörigheten',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'har inte godkänts i denna klientorganisation. En SharePoint- eller global administratör kan godkänna den i',
    SharePointAdminCenterPath: 'SharePoint-administrationscenter → Avancerat → API-åtkomst',
    ScanIncompleteItemsMessage: '{0} objekt kunde inte läsas fullständigt på grund av ett tillfälligt fel (inte ett behörighetsproblem) och visas med det överordnade objektets behörigheter som reservlösning — detta kanske inte speglar deras faktiska åtkomst. Kör om genomsökningen för att försöka dessa objekt igen.',
    FilterByNamePathUserPlaceholder: 'Filtrera efter namn, sökväg eller användare/grupp…',
    FilterResultsLabel: 'Filtrera resultat',
    ExternalUsersOnlyExtLabel: 'Endast externa användare (#ext#)',
    ShowingOfCount: 'Visar {0} av {1}',
    ScanResultsLabel: 'Genomsökningsresultat',
    PermissionsColumnHeader: 'Behörigheter',
    CollapsePermissionsLabel: 'Fäll ihop behörigheter',
    ExpandPermissionsLabel: 'Expandera behörigheter',
    HiddenFromSearchBadge: 'Dold från sökning',
    AssignmentCountSingular: '{0} tilldelning',
    AssignmentCountPlural: '{0} tilldelningar',
    LoadMoreRemainingButton: 'Läs in fler ({0} återstår)',
    LoadingUsersStatus: 'Läser in användare…',
    ConnectedUserSingular: 'Ansluten — {0} användare hittades',
    ConnectedUserPlural: 'Ansluten — {0} användare hittades',
    CheckingAccessForStatus: 'Kontrollerar åtkomst för {0}…',
    FullSiteAccessDetectedStatus: 'Fullständig webbplatsåtkomst upptäckt.',
    AccessibleLocationsFoundSingular: '{0} tillgänglig plats hittades.',
    AccessibleLocationsFoundPlural: '{0} tillgängliga platser hittades.',
    NoAccessibleLocationsFoundStatus: 'Inga tillgängliga platser hittades.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Genomsökning av användaråtkomst klar',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Ny genomsökning',
    NoUserAccessScansSavedYet: 'Inga genomsökningar av användaråtkomst sparade än.',
    UserColumnHeader: 'Användare',
    LocationsColumnHeader: 'Platser',
    FullControlBadge: 'Fullständig kontroll',
    DeleteThisRecordTitle: 'Ta bort denna post',
    SelectAUserFieldLabel: 'Välj en användare',
    SearchUsersPlaceholder: 'Sök användare…',
    SelectAUserToCheckAccessLabel: 'Välj en användare för att kontrollera åtkomst',
    NotInThisSiteLabel: 'Inte på denna webbplats',
    ScanInProgressLabel: 'Genomsökning pågår',
    ScanningUserAccessLabel: 'Söker igenom användaråtkomst',
    ScanningStatus: 'Söker igenom…',
    FullControlAccessPre: 'Denna användare har',
    FullControlWord: 'Fullständig kontroll',
    FullControlAccessPost: 'eller ägarnivåtillgång till hela webbplatsen — alla bibliotek och mappar är tillgängliga.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Behörighet på webbplatsnivå kunde inte fastställas — denna webbplats använder troligen Microsoft 365-gruppåtkomst. För att visa den måste en SharePoint-administratör godkänna behörigheten',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'i',
    ShowingSiteLevelAccessOnlyPre: 'Visar endast',
    SiteLevelAccessOnlyWord: 'åtkomst på webbplatsnivå',
    ShowingSiteLevelAccessOnlyMid: ', baserat på standard SharePoint-gruppmedlemskap. Unika behörigheter på bibliotek, mappar och filer kunde inte läsas och visas inte. För fullständiga resultat, kör denna genomsökning som',
    UserAccessCouldNotBeDeterminedPre: 'Denna användares åtkomst kunde inte fastställas. Att läsa behörighetstilldelningar kräver rättigheten',
    UserAccessCouldNotBeDeterminedPost: '(webbplatsägare eller högre), och denna användare verkar inte vara medlem i webbplatsens standardgrupper för ägare, medlemmar eller besökare.',
    SiteLevelAccessBannerPre: 'Denna användare har åtkomst på webbplatsnivå. Endast platser med',
    UniquePermissionAssignmentsWord: 'unika behörighetstilldelningar',
    SiteLevelAccessBannerPost: 'visas nedan — allt annat innehåll är tillgängligt via behörigheten på webbplatsnivå som visas överst i listan.',
    UserAccessResultsLabel: 'Resultat för användaråtkomst',
  };
});
