define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'การกำหนดค่า Smart Permissions',
    PropertyPane_GroupName: 'ทั่วไป',
    PropertyPane_DefaultViewLabel: 'มุมมองเริ่มต้นเมื่อเปิด',
    PropertyPane_View_Home: 'หน้าแรก',
    PropertyPane_View_Report: 'รายงานสิทธิ์',
    PropertyPane_View_Explorer: 'ตัวสำรวจสิทธิ์',
    PropertyPane_View_UserAccess: 'การเข้าถึงของผู้ใช้',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: 'เชื่อมต่อ',
    CancelButton: 'ยกเลิก',
    ChangeUrlButton: 'เปลี่ยน URL',
    SettingsLabel: 'การตั้งค่า',
    RenderErrorTitle: 'Smart Permissions — ข้อผิดพลาดในการแสดงผล',
    RenderErrorMessageLabel: 'ข้อความ:',
    RenderErrorStackLabel: 'สแตก:',
    RenderErrorNoStack: '(ไม่มีสแตกให้ใช้งาน)',
    BackButton: 'กลับ',
    BackToHomeLabel: 'กลับไปหน้าแรก',
    ExplorerCardTitle: 'ตัวสำรวจสิทธิ์',
    ExplorerCardAlt: 'ตัวสำรวจสิทธิ์พร้อมโครงสร้างโฟลเดอร์และแผงสิทธิ์',
    ExplorerCardDesc: 'เรียกดูโฟลเดอร์หรือไฟล์ใด ๆ แล้วดูได้ทันทีว่าใครมีสิทธิ์เข้าถึง — ด้วยการตรวจสอบสิทธิ์แบบเรียลไทม์',
    ExplorerCardButton: 'เปิดตัวสำรวจสิทธิ์',
    ReportCardTitle: 'รายงานสิทธิ์',
    ReportCardAlt: 'หน้าจอกำหนดค่ารายงานสิทธิ์',
    ReportCardDesc: 'สร้างรายงาน Excel ที่มีรหัสสีสำหรับการกำหนดสิทธิ์เฉพาะทุกรายการในไซต์ของคุณ',
    ReportCardButton: 'เรียกใช้รายงานสิทธิ์',
    UserAccessCardTitle: 'การเข้าถึงของผู้ใช้',
    UserAccessCardAlt: 'หน้าจอการเข้าถึงของผู้ใช้ที่แสดงตำแหน่งที่เข้าถึงได้สำหรับผู้ใช้ที่เลือก',
    UserAccessCardDesc: 'ค้นหาผู้ใช้เพื่อดูตำแหน่งทั้งหมดที่พวกเขาสามารถเข้าถึงได้บนไซต์ พร้อมระดับสิทธิ์ที่แน่นอน',
    UserAccessCardButton: 'ตรวจสอบการเข้าถึงของผู้ใช้',
    SiteOwnerRequiredTitle: 'ต้องมีสิทธิ์เข้าถึงระดับเจ้าของไซต์ —',
    SiteOwnerRequiredDesc: 'เครื่องมือเหล่านี้ต้องการสิทธิ์เข้าถึงระดับเจ้าของไซต์ โปรดติดต่อเจ้าของไซต์หากคุณมีคำถามเกี่ยวกับสิทธิ์',
    HomeSubtitle: 'ตรวจสอบและทำความเข้าใจสิทธิ์ของ SharePoint — โดยไม่ต้องใช้ PowerShell',
    RequiresSiteOwnerTooltip: 'ต้องมีสิทธิ์เข้าถึงระดับเจ้าของไซต์',
    HomeNoteLabel: 'หมายเหตุ:',
    HomeNoteText: 'เว็บพาร์ตนี้ทำงานในฐานะผู้ใช้ที่ลงชื่อเข้าใช้ในปัจจุบัน โดยจะเห็นเฉพาะไซต์และรายการที่ผู้ใช้นั้นมีสิทธิ์เข้าถึงเท่านั้น สำหรับการสแกนผู้เช่าแบบเต็มรูปแบบ ให้ใช้บัญชีที่มีสิทธิ์อ่านที่เหมาะสมในทุกไซต์',
    SettingsTitle: 'การตั้งค่า',
    LibrariesSectionTitle: 'ไลบรารี',
    IncludeHiddenLabel: 'รวมไลบรารีระบบและไลบรารีที่ซ่อนอยู่',
    IncludeHiddenTooltip: 'หากเลือกไว้ จะรวม Style Library, Form Templates, Site Assets และไลบรารีอื่น ๆ ที่ซ่อนจากมุมมองเริ่มต้น ใช้กับเครื่องมือทั้งหมด',
    MoreInfoHiddenLibrariesLabel: 'ข้อมูลเพิ่มเติมเกี่ยวกับไลบรารีที่ซ่อนอยู่',
    ExcludeLimitedAccessLabel: 'ยกเว้นรายการการเข้าถึงแบบจำกัด',
    ExcludeLimitedAccessTooltip: 'ซ่อนผู้ใช้และกลุ่มที่มีสิทธิ์ SharePoint เดียวคือการเข้าถึงแบบจำกัด — ซึ่งจะถูกกำหนดโดยอัตโนมัติเมื่อมีการแชร์ไฟล์ผ่านลิงก์ ใช้กับรายงานสิทธิ์ ตัวสำรวจ และการเข้าถึงของผู้ใช้',
    MoreInfoLimitedAccessLabel: 'ข้อมูลเพิ่มเติมเกี่ยวกับการเข้าถึงแบบจำกัด',
    ExcludeSharingLinksLabel: 'ยกเว้นรายการลิงก์การแชร์',
    ExcludeSharingLinksTooltip: 'ซ่อนกลุ่มภายใน "SharingLinks.*" ที่ SharePoint สร้างขึ้นโดยอัตโนมัติสำหรับลิงก์การแชร์ "ทุกคนที่มีลิงก์" และ "บุคคลที่ระบุ" ใช้กับรายงานสิทธิ์ ตัวสำรวจ และการเข้าถึงของผู้ใช้',
    MoreInfoSharingLinksLabel: 'ข้อมูลเพิ่มเติมเกี่ยวกับลิงก์การแชร์',
    PerformanceSectionTitle: 'ประสิทธิภาพ',
    ConcurrentRequestsLabel: 'คำขอ API พร้อมกัน:',
    ConcurrencyTooltip: 'จำนวนคำขอ API ของ SharePoint ที่ทำงานพร้อมกันระหว่างการสแกนรายงานสิทธิ์ การสแกนการเข้าถึงของผู้ใช้ และการตรวจสอบพื้นหลังของตัวสำรวจ ค่าที่สูงขึ้นจะเร็วขึ้นแต่มีแนวโน้มที่จะทำให้เกิดการจำกัดอัตรา (HTTP 429) มากขึ้น แนะนำให้ใช้ 3–5',
    MoreInfoConcurrencyLabel: 'ข้อมูลเพิ่มเติมเกี่ยวกับการทำงานพร้อมกัน',
    ConcurrencyHint: 'ค่าที่สูงขึ้นจะสแกนได้เร็วขึ้นแต่อาจทำให้เกิดการจำกัดอัตราของ SharePoint แนะนำ: 3–5',
    GroupMemberCapLabel: 'ขีดจำกัดการแสดงสมาชิกกลุ่ม:',
    GroupMemberCapTooltip: 'จำนวนสมาชิกสูงสุดที่แสดงต่อกลุ่มเมื่อเปิดใช้งาน "ขยายสมาชิกกลุ่ม" กลุ่มที่ใหญ่กว่าจะถูกจำกัดและจะแสดงการแจ้งเตือน การเพิ่มค่านี้จะใช้หน่วยความจำมากขึ้น',
    MoreInfoGroupMemberCapLabel: 'ข้อมูลเพิ่มเติมเกี่ยวกับขีดจำกัดสมาชิกกลุ่ม',
    GroupMemberCapHint: 'กลุ่มที่ใหญ่กว่าขีดจำกัดนี้จะแสดงการแจ้งเตือนการตัดทอน ค่าเริ่มต้น: 500',
    DefaultViewSectionTitle: 'มุมมองเริ่มต้นเมื่อโหลด',
    DefaultViewInstructionsIntro: 'หากต้องการเปลี่ยนหน้าจอที่เปิดขึ้นเมื่อเว็บพาร์ตโหลดครั้งแรก ให้แก้ไขคุณสมบัติของเว็บพาร์ต:',
    DefaultViewStep1Pre: 'ทำให้หน้า SharePoint อยู่ในโหมด',
    DefaultViewStep1Post: '',
    DefaultViewStep2Pre: 'คลิกไอคอน',
    DefaultViewStep2Post: 'บนเว็บพาร์ต Smart Permissions',
    DefaultViewStep3Pre: 'ในแผงคุณสมบัติ ให้เลือกมุมมองจากรายการแบบเลื่อนลง',
    DefaultViewStep3Post: '',
    DefaultViewStep4Post: 'หน้าเพื่อบันทึกการเปลี่ยนแปลง',
    EditModeWord: 'แก้ไข',
    PencilEditWord: 'ดินสอ (แก้ไข)',
    DefaultViewOnOpenWord: 'มุมมองเริ่มต้นเมื่อเปิด',
    RepublishWord: 'เผยแพร่ซ้ำ',
    SiteOwnersLabel: 'เจ้าของไซต์:',
    EveryoneClaimLabel: 'ทุกคน',
    EveryoneExceptExternalClaimLabel: 'ทุกคนยกเว้นผู้ใช้ภายนอก',
    PermissionAssignmentsLabel: 'การกำหนดสิทธิ์',
    UserGroupColumnHeader: 'ผู้ใช้ / กลุ่ม',
    TypeColumnHeader: 'ประเภท',
    PermissionLevelColumnHeader: 'ระดับสิทธิ์',
    TenantWideAccessSuffix: '— การเข้าถึงทั่วทั้งผู้เช่า',
    SecurityGroupType: 'กลุ่มความปลอดภัย',
    SpGroupType: 'กลุ่ม SP',
    UserType: 'ผู้ใช้',
    CheckAccessForLabel: 'ตรวจสอบการเข้าถึงสำหรับ {0}',
    ContainsUniqueAndExternalTooltip: 'มีรายการที่มีสิทธิ์เฉพาะและการเข้าถึงของผู้ใช้ภายนอก',
    ContainsUniqueTooltip: 'มีรายการที่มีสิทธิ์เฉพาะ',
    ContainsExternalTooltip: 'มีรายการที่มีการเข้าถึงของผู้ใช้ภายนอก',
    UniqueBadge: 'เฉพาะ',
    ExternalAccessDetectedTooltip: 'ตรวจพบการเข้าถึงของผู้ใช้ภายนอก',
    ConnectingStatus: 'กำลังเชื่อมต่อ…',
    ConnectedLibrarySingular: 'เชื่อมต่อแล้ว — พบไลบรารี {0} รายการ',
    ConnectedLibraryPlural: 'เชื่อมต่อแล้ว — พบไลบรารี {0} รายการ',
    ConnectionFailedError: 'การเชื่อมต่อล้มเหลว: {0}',
    LibraryEmptyStatus: 'ไลบรารีนี้ว่างเปล่า',
    ErrorLoadingLibrary: 'เกิดข้อผิดพลาดขณะโหลดไลบรารี: {0}',
    ErrorLoadingContents: 'เกิดข้อผิดพลาดขณะโหลดเนื้อหา',
    LibraryFieldLabel: 'ไลบรารี',
    HiddenFromSearchSuffix: '{0} (ซ่อนจากการค้นหา)',
    UniquePermissionsOnlyToggle: 'เฉพาะสิทธิ์เฉพาะเท่านั้น',
    ExternalUsersOnlyToggle: 'เฉพาะผู้ใช้ภายนอกเท่านั้น',
    LegendLabel: 'คำอธิบาย:',
    LegendItemHasUnique: 'รายการมีสิทธิ์เฉพาะ',
    LegendContainsUniqueBelow: 'มีสิทธิ์เฉพาะอยู่ด้านล่าง',
    LegendContainsExternalBelow: 'มีการเข้าถึงของผู้ใช้ภายนอกอยู่ด้านล่าง',
    LegendExternalOnItem: 'การเข้าถึงของผู้ใช้ภายนอกในรายการนี้',
    ViewingWithMemberAccessTitle: 'กำลังดูด้วยสิทธิ์การเข้าถึงระดับสมาชิก',
    ViewingWithMemberAccessDesc1: '— ไม่สามารถแสดงการกำหนดสิทธิ์ได้ การดูว่าใครมีสิทธิ์เข้าถึงต้องใช้สิทธิ์',
    ManagePermissionsWord: 'จัดการสิทธิ์',
    ViewingWithMemberAccessDesc2: '(เจ้าของไซต์ขึ้นไป) คุณยังคงสามารถดูว่ารายการใดที่การสืบทอดขาดหายไปโดยใช้ตัวบ่งชี้ ↓ หากต้องการดูตำแหน่งที่คุณสามารถเข้าถึงได้ ให้ใช้เครื่องมือ',
    UserAccessWord: 'การเข้าถึงของผู้ใช้',
    ViewingWithMemberAccessDesc3: '',
    FoldersAndFilesLabel: 'โฟลเดอร์และไฟล์',
    SelectFolderOrFilePrompt: 'เลือกโฟลเดอร์หรือไฟล์เพื่อดูสิทธิ์ของรายการนั้น',
    UniquePermissionsBadge: 'สิทธิ์เฉพาะ',
    InheritedBadge: 'สืบทอด',
    ExpandGroupMembersLabel: 'ขยายสมาชิกกลุ่ม',
    ShowParentPermissionsLabel: 'แสดงสิทธิ์ของรายการหลัก',
    InheritsFromParentText: 'รายการนี้สืบทอดสิทธิ์จากรายการหลัก',
    YourAccessLabel: 'การเข้าถึงของคุณ:',
    PermissionsNotVisibleNodeText: 'ไม่สามารถแสดงการกำหนดสิทธิ์ได้ — ต้องมีสิทธิ์จัดการสิทธิ์ (เจ้าของไซต์ขึ้นไป) เพื่อดูว่าใครมีสิทธิ์เข้าถึงรายการนี้',
    NoExternalUsersDirectAccessText: 'ไม่มีผู้ใช้ภายนอกที่มีสิทธิ์เข้าถึงโดยตรงไปยังรายการนี้',
    InheritedFromLabel: 'สืบทอดจาก:',
    ParentPermissionsNotVisibleText: 'ไม่สามารถแสดงการกำหนดสิทธิ์ของรายการหลักได้ — ต้องมีสิทธิ์จัดการสิทธิ์ (เจ้าของไซต์ขึ้นไป)',
    NoPermissionsFoundOnParentText: 'ไม่พบสิทธิ์ในรายการหลัก',
    StartingScanStatus: 'กำลังเริ่มการสแกน…',
    ScanCancelledStatus: 'การสแกนถูกยกเลิก — รวบรวมได้ {0} รายการก่อนยกเลิก',
    ScanCompleteStatus: 'การสแกนเสร็จสมบูรณ์ — พบ {0} รายการ โดย {1} รายการมีสิทธิ์เฉพาะ',
    ScanCompleteNotificationTitle: 'Smart Permissions — การสแกนเสร็จสมบูรณ์',
    ScanCompleteNotificationBody: '{0} รายการ โดย {1} รายการมีสิทธิ์เฉพาะ',
    CancelledStatus: 'ยกเลิกแล้ว',
    GenericErrorPrefix: 'ข้อผิดพลาด: {0}',
    ExportErrorPrefix: 'ข้อผิดพลาดในการส่งออก: {0}',
    ScopeSiteOnly: 'ไซต์เท่านั้น',
    ScopeLibraries: 'ไลบรารี',
    ScopeFolders: 'โฟลเดอร์',
    ScopeFilesAndFolders: 'ไฟล์และโฟลเดอร์',
    ScanInProgressConfirm: 'กำลังสแกนอยู่ ต้องการออกและยกเลิกหรือไม่?',
    HistoryButton: 'ประวัติ',
    BackToHistoryButton: 'กลับไปยังประวัติ',
    ComparingLabel: 'กำลังเปรียบเทียบ',
    CompareMismatchWarning: 'รายงานเหล่านี้ถูกจัดทำด้วยไซต์หรือตัวเลือกการสแกนที่แตกต่างกัน — ความแตกต่างด้านล่างอาจสะท้อนถึงการตั้งค่าการสแกนที่เปลี่ยนแปลงมากกว่าการเปลี่ยนแปลงสิทธิ์ที่แท้จริง',
    NoPermissionDifferencesFound: 'ไม่พบความแตกต่างของสิทธิ์ระหว่างรายงานทั้งสองนี้',
    PermissionChangesHeaderSingular: 'การเปลี่ยนแปลงสิทธิ์ ({0} รายการ)',
    PermissionChangesHeaderPlural: 'การเปลี่ยนแปลงสิทธิ์ ({0} รายการ)',
    ChangeColumnHeader: 'การเปลี่ยนแปลง',
    BeforeColumnHeader: 'ก่อน',
    AfterColumnHeader: 'หลัง',
    AddedBadge: 'เพิ่มแล้ว',
    RemovedBadge: 'ลบแล้ว',
    ChangedBadge: 'เปลี่ยนแปลงแล้ว',
    InheritanceChangedHeader: 'การสืบทอดเปลี่ยนแปลง ({0})',
    NameColumnHeader: 'ชื่อ',
    PathColumnHeader: 'เส้นทาง',
    NowColumnHeader: 'ปัจจุบัน',
    UniqueInheritanceBrokenBadge: 'เฉพาะ (การสืบทอดขาดหาย)',
    InheritedRestoredBadge: 'สืบทอด (กู้คืนแล้ว)',
    NewObjectsHeader: 'อ็อบเจ็กต์ใหม่',
    RemovedObjectsHeader: 'อ็อบเจ็กต์ที่ถูกลบ',
    BackToScanButton: 'กลับไปยังการสแกน',
    CompareSelectedButton: 'เปรียบเทียบรายการที่เลือก',
    NoReportsSavedYet: 'ยังไม่มีรายงานที่บันทึกไว้',
    SelectForCompareLabel: 'เลือกเพื่อเปรียบเทียบ',
    DateTimeColumnHeader: 'วันที่ / เวลา',
    SiteColumnHeader: 'ไซต์',
    ScopeColumnHeader: 'ขอบเขต',
    ObjectsColumnHeader: 'อ็อบเจ็กต์',
    UniqueColumnHeader: 'เฉพาะ',
    SelectReportForCompareLabel: 'เลือกรายงานจาก {0} เพื่อเปรียบเทียบ',
    AllSitesPrefix: 'ไซต์ทั้งหมด · ',
    PlusSubsitesSuffix: ' + ไซต์ย่อย',
    ExportingStatus: 'กำลังส่งออก…',
    ExportButton: 'ส่งออก',
    DeleteThisReportTitle: 'ลบรายงานนี้',
    ScanAllSiteCollectionsLabel: 'สแกนคอลเลกชันไซต์ทั้งหมดในผู้เช่านี้ (ใช้ได้เฉพาะในไซต์รูทเท่านั้น)',
    AllSitesSearchCaveat: 'รายการไซต์มาจากการค้นหาและอาจไม่รวมคอลเลกชันไซต์ทั้งหมด — ไซต์ที่สร้างขึ้นเมื่อไม่นานมานี้ หรือไซต์ที่ถูกยกเว้นจากดัชนีการค้นหา อาจขาดหายไป',
    IncludeSubsitesLabel: 'รวมไซต์ย่อย (สแกนไซต์ย่อยทั้งหมดใต้ไซต์นี้)',
    ScanDepthFieldLabel: 'ความลึกในการสแกน',
    FolderDepthLimitLabel: 'ขีดจำกัดความลึกของโฟลเดอร์:',
    ExpandGroupMembersInReportLabel: 'ขยายสมาชิกกลุ่มในรายงาน (กลุ่ม SharePoint กลุ่มความปลอดภัย และกลุ่ม M365)',
    LibrariesToScanLabel: 'ไลบรารีที่จะสแกน',
    OfSelectedCount: 'เลือกแล้ว {0} จาก {1}',
    AllButton: 'ทั้งหมด',
    NoneButton: 'ไม่มี',
    LoadingLibrariesStatus: 'กำลังโหลดไลบรารี…',
    RunReportButton: 'เรียกใช้รายงาน',
    ItemsFoundSoFar: 'พบรายการแล้ว {0} รายการจนถึงตอนนี้',
    LibraryOfProgress: 'ไลบรารี {0} จาก {1}',
    ScanCancelledPartialResults: 'การสแกนถูกยกเลิก — ผลลัพธ์บางส่วน',
    ScanCompleteLabel: 'การสแกนเสร็จสมบูรณ์',
    ObjectsCountBadge: '{0} รายการ',
    UniqueCountBadge: '{0} รายการเฉพาะ',
    InheritedCountBadge: '{0} รายการสืบทอด',
    GeneratingExcelStatus: 'กำลังสร้าง Excel…',
    ExportFilteredRowsButton: 'ส่งออก {0} แถวที่กรองแล้ว',
    ExportToExcelButton: 'ส่งออกไปยัง Excel',
    ExportToCsvButton: 'ส่งออกไปยัง CSV',
    ScanStoppedEarlyTitle: 'การสแกนหยุดก่อนเวลา — SharePoint กำลังจำกัดผู้เช่ารายนี้',
    SiteCollectionsScannedBeforeStopping: 'สแกนไปแล้ว {0} จาก {1} คอลเลกชันไซต์ก่อนที่จะหยุด ',
    ResultsBelowCoverOnlyPre: 'ผลลัพธ์ด้านล่างครอบคลุมเฉพาะสิ่งที่สแกนแล้วเท่านั้น และ',
    NotWord: 'ไม่ใช่',
    ResultsBelowCoverOnlyPost: 'การตรวจสอบที่สมบูรณ์ การสแกนจะหยุดตัวเองในสถานการณ์นี้เนื่องจากการส่งคำขอต่อไปคือสิ่งที่ทำให้การจำกัดอัตรายังคงทำงานอยู่ โปรดรอสักครู่ จากนั้นเรียกใช้ใหม่อีกครั้งโดยตั้งค่า',
    ConcurrentRequestsWord: 'คำขอพร้อมกัน',
    SetTo1Or2InSettings: 'เป็น 1 หรือ 2 ในการตั้งค่า',
    ThrottledScanMessage: 'SharePoint จำกัดอัตราการสแกนนี้ ({0} คำขอถูกจำกัดอัตราและลองใหม่)',
    OfEverythingScannedPre: 'จากทุกสิ่งที่สแกนแล้ว',
    ItemCountSingular: '{0} รายการ',
    ItemCountPlural: '{0} รายการ',
    CouldNotBeConfirmedText: 'ไม่สามารถยืนยันได้หลังจากลองใหม่ (ดูการแจ้งเตือน "ไม่สามารถอ่านได้อย่างสมบูรณ์" ด้านล่างเพื่อดูว่ารายการใดบ้าง) — ความล้มเหลวนี้เกี่ยวข้องกับความจุ ไม่ใช่การสะท้อนสิทธิ์ที่แท้จริงของรายการเหล่านั้น รายการอื่น ๆ ทั้งหมดในรายงานนี้ถูกอ่านสำเร็จและสามารถเชื่อถือได้',
    DespiteThrottlingText: 'แม้จะมีการจำกัดอัตรา แต่ทุกรายการก็ยังคงได้รับการยืนยันสำเร็จหลังจากลองใหม่ ดังนั้นรายงานนี้จึงสมบูรณ์',
    ForCleanRunPre: 'สำหรับการทำงานที่สะอาด โปรดรอสักครู่และสแกนใหม่ด้วยค่าที่ต่ำกว่าสำหรับ',
    ValueInSettingsPost: 'ในการตั้งค่า',
    OneItemWord: '1 รายการ',
    NItemsWord: '{0} รายการ',
    OutOfScannedCouldNotBeRead: 'จาก {0} รายการที่สแกนแล้วไม่สามารถอ่านได้ด้วยสิทธิ์การเข้าถึงปัจจุบันของคุณ —',
    PermissionAssignmentsForItAreNotShown: ' การกำหนดสิทธิ์จะไม่แสดง ',
    PermissionAssignmentsForThoseAreNotShown: ' การกำหนดสิทธิ์จะไม่แสดง ',
    RestOfReportReadSuccessfully: 'แต่ส่วนที่เหลือของรายงานนี้ถูกอ่านสำเร็จ',
    RunScanAsSiteOwnerPre: 'เรียกใช้การสแกนในฐานะ',
    SiteOwnerWord: 'เจ้าของไซต์',
    RunScanAsSiteOwnerPost: 'เพื่อดูรายละเอียดทั้งหมดของรายการที่ถูกปฏิเสธด้านล่าง',
    AndNMoreText: '…และอีก {0} รายการ',
    GroupExpansionSkippedPre: 'ข้ามการขยายสมาชิกกลุ่ม — สิทธิ์ Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'ยังไม่ได้รับการอนุมัติในผู้เช่ารายนี้ ผู้ดูแลระบบ SharePoint หรือผู้ดูแลระบบส่วนกลางสามารถอนุมัติได้ใน',
    SharePointAdminCenterPath: 'ศูนย์การจัดการ SharePoint → ขั้นสูง → การเข้าถึง API',
    ScanIncompleteItemsMessage: '{0} รายการไม่สามารถอ่านได้อย่างสมบูรณ์เนื่องจากข้อผิดพลาดชั่วคราว (ไม่ใช่ปัญหาสิทธิ์) และจะแสดงด้วยสิทธิ์ของรายการหลักเป็นทางเลือกสำรอง — ซึ่งอาจไม่สะท้อนถึงการเข้าถึงที่แท้จริง เรียกใช้การสแกนใหม่เพื่อลองรายการเหล่านี้อีกครั้ง',
    FilterByNamePathUserPlaceholder: 'กรองตามชื่อ เส้นทาง หรือผู้ใช้/กลุ่ม…',
    FilterResultsLabel: 'กรองผลลัพธ์',
    ExternalUsersOnlyExtLabel: 'เฉพาะผู้ใช้ภายนอกเท่านั้น (#ext#)',
    ShowingOfCount: 'แสดง {0} จาก {1}',
    ScanResultsLabel: 'ผลลัพธ์การสแกน',
    PermissionsColumnHeader: 'สิทธิ์',
    CollapsePermissionsLabel: 'ยุบสิทธิ์',
    ExpandPermissionsLabel: 'ขยายสิทธิ์',
    HiddenFromSearchBadge: 'ซ่อนจากการค้นหา',
    AssignmentCountSingular: '{0} การกำหนด',
    AssignmentCountPlural: '{0} การกำหนด',
    LoadMoreRemainingButton: 'โหลดเพิ่มเติม (เหลืออีก {0})',
    LoadingUsersStatus: 'กำลังโหลดผู้ใช้…',
    ConnectedUserSingular: 'เชื่อมต่อแล้ว — พบผู้ใช้ {0} คน',
    ConnectedUserPlural: 'เชื่อมต่อแล้ว — พบผู้ใช้ {0} คน',
    CheckingAccessForStatus: 'กำลังตรวจสอบการเข้าถึงสำหรับ {0}…',
    FullSiteAccessDetectedStatus: 'ตรวจพบการเข้าถึงไซต์แบบเต็มรูปแบบ',
    AccessibleLocationsFoundSingular: 'พบตำแหน่งที่เข้าถึงได้ {0} รายการ',
    AccessibleLocationsFoundPlural: 'พบตำแหน่งที่เข้าถึงได้ {0} รายการ',
    NoAccessibleLocationsFoundStatus: 'ไม่พบตำแหน่งที่เข้าถึงได้',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — การสแกนการเข้าถึงของผู้ใช้เสร็จสมบูรณ์',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'การสแกนใหม่',
    NoUserAccessScansSavedYet: 'ยังไม่มีการสแกนการเข้าถึงของผู้ใช้ที่บันทึกไว้',
    UserColumnHeader: 'ผู้ใช้',
    LocationsColumnHeader: 'ตำแหน่ง',
    FullControlBadge: 'ควบคุมเต็มรูปแบบ',
    DeleteThisRecordTitle: 'ลบระเบียนนี้',
    SelectAUserFieldLabel: 'เลือกผู้ใช้',
    SearchUsersPlaceholder: 'ค้นหาผู้ใช้…',
    SelectAUserToCheckAccessLabel: 'เลือกผู้ใช้เพื่อตรวจสอบการเข้าถึง',
    NotInThisSiteLabel: 'ไม่อยู่ในไซต์นี้',
    ScanInProgressLabel: 'กำลังสแกน',
    ScanningUserAccessLabel: 'กำลังสแกนการเข้าถึงของผู้ใช้',
    ScanningStatus: 'กำลังสแกน…',
    FullControlAccessPre: 'ผู้ใช้รายนี้มี',
    FullControlWord: 'การควบคุมเต็มรูปแบบ',
    FullControlAccessPost: 'หรือการเข้าถึงระดับเจ้าของทั่วทั้งไซต์ — ไลบรารีและโฟลเดอร์ทั้งหมดสามารถเข้าถึงได้',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'ไม่สามารถระบุสิทธิ์ระดับไซต์ได้ — ไซต์นี้อาจใช้การเข้าถึงกลุ่ม Microsoft 365 หากต้องการแสดง ผู้ดูแลระบบ SharePoint ต้องอนุมัติสิทธิ์',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph ใน',
    ShowingSiteLevelAccessOnlyPre: 'แสดงเฉพาะ',
    SiteLevelAccessOnlyWord: 'การเข้าถึงระดับไซต์',
    ShowingSiteLevelAccessOnlyMid: 'ตามสมาชิกกลุ่ม SharePoint เริ่มต้น สิทธิ์เฉพาะในไลบรารี โฟลเดอร์ และไฟล์ไม่สามารถอ่านได้และจะไม่แสดง สำหรับผลลัพธ์ที่สมบูรณ์ ให้เรียกใช้การสแกนนี้ในฐานะ',
    UserAccessCouldNotBeDeterminedPre: 'ไม่สามารถระบุการเข้าถึงของผู้ใช้รายนี้ได้ การอ่านการกำหนดสิทธิ์ต้องใช้สิทธิ์',
    UserAccessCouldNotBeDeterminedPost: '(เจ้าของไซต์ขึ้นไป) และผู้ใช้รายนี้ดูเหมือนจะไม่ได้เป็นสมาชิกของกลุ่มเจ้าของ สมาชิก หรือผู้เยี่ยมชมเริ่มต้นของไซต์',
    SiteLevelAccessBannerPre: 'ผู้ใช้รายนี้มีการเข้าถึงระดับไซต์ เฉพาะตำแหน่งที่มี',
    UniquePermissionAssignmentsWord: 'การกำหนดสิทธิ์เฉพาะ',
    SiteLevelAccessBannerPost: 'เท่านั้นที่จะปรากฏด้านล่าง — เนื้อหาอื่น ๆ ทั้งหมดสามารถเข้าถึงได้ผ่านสิทธิ์ระดับไซต์ที่แสดงอยู่ด้านบนสุดของรายการ',
    UserAccessResultsLabel: 'ผลลัพธ์การเข้าถึงของผู้ใช้',
  };
});
