define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions yapılandırması',
    PropertyPane_GroupName: 'Genel',
    PropertyPane_DefaultViewLabel: 'Açılışta varsayılan görünüm',
    PropertyPane_View_Home: 'Ana Sayfa',
    PropertyPane_View_Report: 'İzin Raporu',
    PropertyPane_View_Explorer: 'İzin Gezgini',
    PropertyPane_View_UserAccess: 'Kullanıcı Erişimi',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/sitem',
    ConnectButton: 'Bağlan',
    CancelButton: 'İptal',
    ChangeUrlButton: "URL'yi Değiştir",
    SettingsLabel: 'Ayarlar',
    RenderErrorTitle: 'Smart Permissions — Oluşturma Hatası',
    RenderErrorMessageLabel: 'İleti:',
    RenderErrorStackLabel: 'Yığın:',
    RenderErrorNoStack: '(yığın kullanılamıyor)',
    BackButton: 'Geri',
    BackToHomeLabel: 'Ana sayfaya dön',
    ExplorerCardTitle: 'İzin Gezgini',
    ExplorerCardAlt: 'Klasör ağacı ve izin panosuna sahip İzin Gezgini',
    ExplorerCardDesc: 'Herhangi bir klasör veya dosyaya göz atın ve kimin erişimi olduğunu anında görün — gerçek zamanlı izin sorgularıyla.',
    ExplorerCardButton: 'İzin Gezginini Aç',
    ReportCardTitle: 'İzin Raporu',
    ReportCardAlt: 'İzin Raporu yapılandırma ekranı',
    ReportCardDesc: 'Sitenizdeki her benzersiz izin atamasının renk kodlu bir Excel raporunu oluşturun.',
    ReportCardButton: 'İzin Raporunu Çalıştır',
    UserAccessCardTitle: 'Kullanıcı Erişimi',
    UserAccessCardAlt: 'Seçilen bir kullanıcı için erişilebilir konumları gösteren Kullanıcı Erişimi ekranı',
    UserAccessCardDesc: 'Bir sitede erişebileceği her konumu tam izin düzeyiyle birlikte görmek için herhangi bir kullanıcıyı arayın.',
    UserAccessCardButton: 'Kullanıcı Erişimini Kontrol Et',
    SiteOwnerRequiredTitle: 'Site Sahibi erişimi gerekli —',
    SiteOwnerRequiredDesc: 'Bu araçlar Site Sahibi erişimi gerektirir. İzinlerle ilgili sorularınız varsa bir site sahibiyle iletişime geçin.',
    HomeSubtitle: "SharePoint izinlerini denetleyin ve anlayın — PowerShell olmadan.",
    RequiresSiteOwnerTooltip: 'Site Sahibi erişimi gerektirir',
    HomeNoteLabel: 'Not:',
    HomeNoteText: 'Bu web bölümü, oturum açmış geçerli kullanıcı olarak çalışır. Yalnızca bu kullanıcının erişim izni olduğu siteleri ve öğeleri görebilir. Tam kiracı taraması için tüm sitelerde uygun okuma erişimine sahip bir hesap kullanın.',
    SettingsTitle: 'Ayarlar',
    LibrariesSectionTitle: 'Kitaplıklar',
    IncludeHiddenLabel: 'Sistem ve gizli kitaplıkları dahil et',
    IncludeHiddenTooltip: 'İşaretlenirse, Stil Kitaplığı, Form Şablonları, Site Varlıkları ve varsayılan görünümlerden gizlenen diğer kitaplıkları içerir. Tüm araçlar için geçerlidir.',
    MoreInfoHiddenLibrariesLabel: 'Gizli kitaplıklar hakkında daha fazla bilgi',
    ExcludeLimitedAccessLabel: 'Sınırlı Erişim girişlerini hariç tut',
    ExcludeLimitedAccessTooltip: "Tek SharePoint izni Sınırlı Erişim olan kullanıcıları ve grupları gizler — dosyalar bağlantılar aracılığıyla paylaşıldığında otomatik olarak atanır. İzin Raporu, Gezgin ve Kullanıcı Erişimi için geçerlidir.",
    MoreInfoLimitedAccessLabel: 'Sınırlı Erişim hakkında daha fazla bilgi',
    ExcludeSharingLinksLabel: 'Paylaşım Bağlantısı girişlerini hariç tut',
    ExcludeSharingLinksTooltip: 'SharePoint\'in "Bağlantıya sahip herkes" ve "Belirli kişiler" paylaşım bağlantıları için otomatik olarak oluşturduğu dahili "SharingLinks.*" gruplarını gizler. İzin Raporu, Gezgin ve Kullanıcı Erişimi için geçerlidir.',
    MoreInfoSharingLinksLabel: 'Paylaşım bağlantıları hakkında daha fazla bilgi',
    PerformanceSectionTitle: 'Performans',
    ConcurrentRequestsLabel: 'Eşzamanlı API istekleri:',
    ConcurrencyTooltip: 'İzin Raporu taramaları, Kullanıcı Erişimi taramaları ve Gezgin arka plan denetimleri sırasında paralel olarak kaç SharePoint API isteğinin çalıştığı. Daha yüksek değerler daha hızlıdır ancak kısıtlamayı (HTTP 429) tetikleme olasılığı daha yüksektir. 3–5 önerilir.',
    MoreInfoConcurrencyLabel: 'Eşzamanlılık hakkında daha fazla bilgi',
    ConcurrencyHint: 'Daha yüksek değerler daha hızlı tarar ancak SharePoint kısıtlamasını tetikleyebilir. Önerilen: 3–5.',
    GroupMemberCapLabel: 'Grup üyesi görüntüleme sınırı:',
    GroupMemberCapTooltip: '"Grup üyelerini genişlet" etkinleştirildiğinde grup başına gösterilen maksimum üye sayısı. Daha büyük gruplar sınırlandırılır ve bir bildirim gösterilir. Bunu artırmak daha fazla bellek kullanır.',
    MoreInfoGroupMemberCapLabel: 'Grup üyesi sınırı hakkında daha fazla bilgi',
    GroupMemberCapHint: 'Bu sınırdan daha büyük gruplar bir kısaltma bildirimi gösterir. Varsayılan: 500.',
    DefaultViewSectionTitle: 'Yüklemede varsayılan görünüm',
    DefaultViewInstructionsIntro: 'Web bölümü ilk yüklendiğinde hangi ekranın açıldığını değiştirmek için web bölümü özelliklerini düzenleyin:',
    DefaultViewStep1Pre: 'SharePoint sayfasını',
    DefaultViewStep1Post: 'moduna alın.',
    DefaultViewStep2Pre: 'Smart Permissions web bölümündeki',
    DefaultViewStep2Post: 'simgesine tıklayın.',
    DefaultViewStep3Pre: 'Özellik panelinde',
    DefaultViewStep3Post: 'açılır listesinden bir görünüm seçin.',
    DefaultViewStep4Post: 'değişikliği kaydetmek için sayfayı.',
    EditModeWord: 'Düzenleme',
    PencilEditWord: 'kalem (düzenle)',
    DefaultViewOnOpenWord: 'Açılışta varsayılan görünüm',
    RepublishWord: 'Yeniden yayımlayın',
    SiteOwnersLabel: 'Site Sahipleri:',
    EveryoneClaimLabel: 'Herkes',
    EveryoneExceptExternalClaimLabel: 'Harici kullanıcılar hariç herkes',
    PermissionAssignmentsLabel: 'İzin Atamaları',
    UserGroupColumnHeader: 'Kullanıcı / Grup',
    TypeColumnHeader: 'Tür',
    PermissionLevelColumnHeader: 'İzin Düzeyi',
    TenantWideAccessSuffix: '— kiracı genelinde erişim',
    SecurityGroupType: 'Güvenlik Grubu',
    SpGroupType: 'SP Grubu',
    UserType: 'Kullanıcı',
    CheckAccessForLabel: '{0} için erişimi kontrol et',
    ContainsUniqueAndExternalTooltip: 'Benzersiz izinlere ve harici kullanıcı erişimine sahip öğeler içerir',
    ContainsUniqueTooltip: 'Benzersiz izinlere sahip öğeler içerir',
    ContainsExternalTooltip: 'Harici kullanıcı erişimine sahip öğeler içerir',
    UniqueBadge: 'Benzersiz',
    ExternalAccessDetectedTooltip: 'Harici kullanıcı erişimi algılandı',
    ConnectingStatus: 'Bağlanılıyor…',
    ConnectedLibrarySingular: 'Bağlandı — {0} kitaplık bulundu',
    ConnectedLibraryPlural: 'Bağlandı — {0} kitaplık bulundu',
    ConnectionFailedError: 'Bağlantı başarısız oldu: {0}',
    LibraryEmptyStatus: 'Bu kitaplık boş.',
    ErrorLoadingLibrary: 'Kitaplık yüklenirken hata oluştu: {0}',
    ErrorLoadingContents: 'İçerik yüklenirken hata oluştu',
    LibraryFieldLabel: 'Kitaplık',
    HiddenFromSearchSuffix: '{0} (aramadan gizlendi)',
    UniquePermissionsOnlyToggle: 'Yalnızca benzersiz izinler',
    ExternalUsersOnlyToggle: 'Yalnızca harici kullanıcılar',
    LegendLabel: 'Gösterge:',
    LegendItemHasUnique: 'Öğenin benzersiz izinleri var',
    LegendContainsUniqueBelow: 'Aşağıda benzersiz izinler içerir',
    LegendContainsExternalBelow: 'Aşağıda harici kullanıcı erişimi içerir',
    LegendExternalOnItem: 'Bu öğede harici kullanıcı erişimi',
    ViewingWithMemberAccessTitle: 'Üye erişimiyle görüntüleme',
    ViewingWithMemberAccessDesc1: '— izin atamaları görünmüyor. Kimin erişimi olduğunu okumak için',
    ManagePermissionsWord: 'İzinleri Yönet',
    ViewingWithMemberAccessDesc2: 'hakkı gerekir (Site Sahibi veya üstü). Hangi öğelerin devralma bağlantısının kesildiğini yine de ↓ göstergeleriyle görebilirsiniz. Erişebileceğiniz konumları görmek için',
    UserAccessWord: 'Kullanıcı Erişimi',
    ViewingWithMemberAccessDesc3: 'aracını kullanın.',
    FoldersAndFilesLabel: 'Klasörler ve dosyalar',
    SelectFolderOrFilePrompt: 'İzinlerini görüntülemek için bir klasör veya dosya seçin.',
    UniquePermissionsBadge: 'Benzersiz izinler',
    InheritedBadge: 'Devralınan',
    ExpandGroupMembersLabel: 'Grup üyelerini genişlet',
    ShowParentPermissionsLabel: 'Üst öğe izinlerini göster',
    InheritsFromParentText: 'Bu öğe, üst öğesinden izinleri devralır.',
    YourAccessLabel: 'Erişiminiz:',
    PermissionsNotVisibleNodeText: 'İzin atamaları görünmüyor — bu öğeye kimin erişimi olduğunu görmek için İzinleri Yönet hakkı (Site Sahibi veya üstü) gereklidir.',
    NoExternalUsersDirectAccessText: 'Hiçbir harici kullanıcının bu öğeye doğrudan erişimi yok.',
    InheritedFromLabel: 'Devralındığı yer:',
    ParentPermissionsNotVisibleText: 'Üst öğenin izin atamaları görünmüyor — İzinleri Yönet hakkı gerektirir (Site Sahibi veya üstü).',
    NoPermissionsFoundOnParentText: 'Üst öğede izin bulunamadı.',
    StartingScanStatus: 'Tarama başlatılıyor…',
    ScanCancelledStatus: 'Tarama iptal edildi — iptal edilmeden önce {0} nesne toplandı.',
    ScanCompleteStatus: 'Tarama tamamlandı — {0} nesne bulundu, {1} tanesi benzersiz izinlere sahip.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Tarama tamamlandı',
    ScanCompleteNotificationBody: '{0} nesne, {1} tanesi benzersiz izinlerle.',
    CancelledStatus: 'İptal edildi.',
    GenericErrorPrefix: 'Hata: {0}',
    ExportErrorPrefix: 'Dışa aktarma hatası: {0}',
    ScopeSiteOnly: 'Yalnızca site',
    ScopeLibraries: 'Kitaplıklar',
    ScopeFolders: 'Klasörler',
    ScopeFilesAndFolders: 'Dosyalar ve klasörler',
    ScanInProgressConfirm: 'Bir tarama devam ediyor. Çıkılsın ve iptal edilsin mi?',
    HistoryButton: 'Geçmiş',
    BackToHistoryButton: 'Geçmişe dön',
    ComparingLabel: 'Karşılaştırılıyor',
    CompareMismatchWarning: 'Bu raporlar farklı sitelerle veya tarama seçenekleriyle alındı — aşağıdaki farklar, gerçek izin değişikliklerinden ziyade değiştirilen tarama ayarlarını yansıtabilir.',
    NoPermissionDifferencesFound: 'Bu iki rapor arasında izin farkı bulunamadı.',
    PermissionChangesHeaderSingular: 'İzin değişiklikleri ({0} nesne)',
    PermissionChangesHeaderPlural: 'İzin değişiklikleri ({0} nesne)',
    ChangeColumnHeader: 'Değişiklik',
    BeforeColumnHeader: 'Önce',
    AfterColumnHeader: 'Sonra',
    AddedBadge: 'Eklendi',
    RemovedBadge: 'Kaldırıldı',
    ChangedBadge: 'Değiştirildi',
    InheritanceChangedHeader: 'Devralma değiştirildi ({0})',
    NameColumnHeader: 'Ad',
    PathColumnHeader: 'Yol',
    NowColumnHeader: 'Şimdi',
    UniqueInheritanceBrokenBadge: 'Benzersiz (devralma kesildi)',
    InheritedRestoredBadge: 'Devralınan (geri yüklendi)',
    NewObjectsHeader: 'Yeni nesneler',
    RemovedObjectsHeader: 'Kaldırılan nesneler',
    BackToScanButton: 'Taramaya dön',
    CompareSelectedButton: 'Seçilenleri karşılaştır',
    NoReportsSavedYet: 'Henüz kaydedilmiş rapor yok.',
    SelectForCompareLabel: 'Karşılaştırma için seç',
    DateTimeColumnHeader: 'Tarih / Saat',
    SiteColumnHeader: 'Site',
    ScopeColumnHeader: 'Kapsam',
    ObjectsColumnHeader: 'Nesneler',
    UniqueColumnHeader: 'Benzersiz',
    SelectReportForCompareLabel: 'Karşılaştırma için {0} tarihli raporu seçin',
    AllSitesPrefix: 'Tüm siteler · ',
    PlusSubsitesSuffix: ' + alt siteler',
    ExportingStatus: 'Dışa aktarılıyor…',
    ExportButton: 'Dışa Aktar',
    DeleteThisReportTitle: 'Bu raporu sil',
    ScanAllSiteCollectionsLabel: 'Bu kiracıdaki tüm site koleksiyonlarını tara (yalnızca kök sitede kullanılabilir)',
    AllSitesSearchCaveat: 'Site listesi aramadan gelir ve her site koleksiyonunu içermeyebilir — çok yakın zamanda oluşturulmuş veya arama dizininden hariç tutulmuş siteler eksik olabilir.',
    IncludeSubsitesLabel: 'Alt siteleri dahil et (bu sitenin altındaki her alt siteyi tarar)',
    ScanDepthFieldLabel: 'Tarama derinliği',
    FolderDepthLimitLabel: 'Klasör derinliği sınırı:',
    ExpandGroupMembersInReportLabel: 'Raporda grup üyelerini genişlet (SharePoint grupları, güvenlik grupları ve M365 grupları)',
    LibrariesToScanLabel: 'Taranacak kitaplıklar',
    OfSelectedCount: '{1} üzerinden {0} seçildi',
    AllButton: 'Tümü',
    NoneButton: 'Hiçbiri',
    LoadingLibrariesStatus: 'Kitaplıklar yükleniyor…',
    RunReportButton: 'Raporu Çalıştır',
    ItemsFoundSoFar: 'Şu ana kadar {0} öğe bulundu',
    LibraryOfProgress: '{1} üzerinden {0}. kitaplık',
    ScanCancelledPartialResults: 'Tarama iptal edildi — kısmi sonuçlar',
    ScanCompleteLabel: 'Tarama tamamlandı',
    ObjectsCountBadge: '{0} nesne',
    UniqueCountBadge: '{0} benzersiz',
    InheritedCountBadge: '{0} devralınan',
    GeneratingExcelStatus: 'Excel oluşturuluyor…',
    ExportFilteredRowsButton: '{0} filtrelenmiş satırı dışa aktar',
    ExportToExcelButton: "Excel'e Aktar",
    ExportToCsvButton: "CSV'ye Aktar",
    ScanStoppedEarlyTitle: 'Tarama erken durduruldu — SharePoint bu kiracıyı kısıtlıyor.',
    SiteCollectionsScannedBeforeStopping: 'Durmadan önce {1} site koleksiyonundan {0} tanesi tarandı. ',
    ResultsBelowCoverOnlyPre: 'Aşağıdaki sonuçlar yalnızca taranan kısmı kapsar ve',
    NotWord: 'değildir',
    ResultsBelowCoverOnlyPost: 'tam bir denetim değildir. Tarama bu durumda kendi kendini durdurur çünkü istekleri göndermeye devam etmek kısıtlamayı sürdüren şeydir. Birkaç dakika bekleyin, ardından şununla yeniden çalıştırın:',
    ConcurrentRequestsWord: 'Eşzamanlı istekler',
    SetTo1Or2InSettings: "Ayarlar'da 1 veya 2 olarak ayarlandı.",
    ThrottledScanMessage: 'SharePoint bu taramayı kısıtladı ({0} istek hız sınırlamasına tabi tutuldu ve yeniden denendi).',
    OfEverythingScannedPre: 'Taranan her şeyden,',
    ItemCountSingular: '{0} öğe',
    ItemCountPlural: '{0} öğe',
    CouldNotBeConfirmedText: "yeniden denendikten sonra doğrulanamadı (tam olarak hangileri olduğunu görmek için aşağıdaki \"tam olarak okunamadı\" bildirimine bakın) — bu hata kapasiteyle ilgiliydi, gerçek izinlerini yansıtmıyordu. Bu rapordaki diğer tüm öğeler başarıyla okundu ve güvenilebilir.",
    DespiteThrottlingText: 'Kısıtlamaya rağmen, her öğe yeniden denendikten sonra yine de başarıyla doğrulandı, bu nedenle bu rapor eksiksizdir.',
    ForCleanRunPre: 'Temiz bir çalıştırma için birkaç dakika bekleyin ve şunun için daha düşük bir değerle yeniden tarayın:',
    ValueInSettingsPost: "Ayarlar'da.",
    OneItemWord: '1 öğe',
    NItemsWord: '{0} öğe',
    OutOfScannedCouldNotBeRead: 'taranan {0} öğeden mevcut erişiminizle okunamadı —',
    PermissionAssignmentsForItAreNotShown: ' izin atamaları gösterilmiyor, ',
    PermissionAssignmentsForThoseAreNotShown: ' izin atamaları gösterilmiyor, ',
    RestOfReportReadSuccessfully: 'ancak bu raporun geri kalanı başarıyla okundu.',
    RunScanAsSiteOwnerPre: 'Taramayı',
    SiteOwnerWord: 'Site Sahibi',
    RunScanAsSiteOwnerPost: 'olarak çalıştırarak aşağıdaki reddedilen öğe(ler) için tam ayrıntıları görün.',
    AndNMoreText: '…ve {0} tane daha',
    GroupExpansionSkippedPre: 'Grup üyesi genişletme atlandı — Graph izni',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'bu kiracıda onaylanmadı. Bir SharePoint veya Genel yönetici bunu şurada onaylayabilir:',
    SharePointAdminCenterPath: 'SharePoint Yönetim Merkezi → Gelişmiş → API erişimi',
    ScanIncompleteItemsMessage: '{0} öğe geçici bir hata nedeniyle (izin sorunu değil) tam olarak okunamadı ve en iyi çaba çözümü olarak üst öğesinin izinleriyle gösteriliyor — bu, gerçek erişimlerini yansıtmayabilir. Bu öğeleri yeniden denemek için taramayı yeniden çalıştırın.',
    FilterByNamePathUserPlaceholder: 'Ad, yol veya kullanıcı/gruba göre filtrele…',
    FilterResultsLabel: 'Sonuçları filtrele',
    ExternalUsersOnlyExtLabel: 'Yalnızca harici kullanıcılar (#ext#)',
    ShowingOfCount: '{1} üzerinden {0} gösteriliyor',
    ScanResultsLabel: 'Tarama sonuçları',
    PermissionsColumnHeader: 'İzinler',
    CollapsePermissionsLabel: 'İzinleri daralt',
    ExpandPermissionsLabel: 'İzinleri genişlet',
    HiddenFromSearchBadge: 'Aramadan gizlendi',
    AssignmentCountSingular: '{0} atama',
    AssignmentCountPlural: '{0} atama',
    LoadMoreRemainingButton: 'Daha fazla yükle ({0} kaldı)',
    LoadingUsersStatus: 'Kullanıcılar yükleniyor…',
    ConnectedUserSingular: 'Bağlandı — {0} kullanıcı bulundu',
    ConnectedUserPlural: 'Bağlandı — {0} kullanıcı bulundu',
    CheckingAccessForStatus: '{0} için erişim kontrol ediliyor…',
    FullSiteAccessDetectedStatus: 'Tam site erişimi algılandı.',
    AccessibleLocationsFoundSingular: '{0} erişilebilir konum bulundu.',
    AccessibleLocationsFoundPlural: '{0} erişilebilir konum bulundu.',
    NoAccessibleLocationsFoundStatus: 'Erişilebilir konum bulunamadı.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Kullanıcı Erişimi taraması tamamlandı',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Yeni tarama',
    NoUserAccessScansSavedYet: 'Henüz kaydedilmiş kullanıcı erişimi taraması yok.',
    UserColumnHeader: 'Kullanıcı',
    LocationsColumnHeader: 'Konumlar',
    FullControlBadge: 'Tam Denetim',
    DeleteThisRecordTitle: 'Bu kaydı sil',
    SelectAUserFieldLabel: 'Bir kullanıcı seçin',
    SearchUsersPlaceholder: 'Kullanıcı ara…',
    SelectAUserToCheckAccessLabel: 'Erişimi kontrol etmek için bir kullanıcı seçin',
    NotInThisSiteLabel: 'Bu sitede değil',
    ScanInProgressLabel: 'Tarama devam ediyor',
    ScanningUserAccessLabel: 'Kullanıcı erişimi taranıyor',
    ScanningStatus: 'Taranıyor…',
    FullControlAccessPre: 'Bu kullanıcının',
    FullControlWord: 'Tam Denetimi',
    FullControlAccessPost: 'veya tüm siteye Sahip düzeyinde erişimi var — tüm kitaplıklar ve klasörler erişilebilir.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Site düzeyinde izin belirlenemedi — bu site muhtemelen Microsoft 365 Grup erişimi kullanıyor. Bunu göstermek için bir SharePoint yöneticisinin',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph iznini şurada onaylaması gerekir:',
    ShowingSiteLevelAccessOnlyPre: 'Yalnızca',
    SiteLevelAccessOnlyWord: 'site düzeyinde erişim',
    ShowingSiteLevelAccessOnlyMid: 'gösteriliyor, varsayılan SharePoint grup üyeliğine dayanarak. Kitaplıklar, klasörler ve dosyalardaki benzersiz izinler okunamadı ve gösterilmiyor. Tam sonuçlar için bu taramayı',
    UserAccessCouldNotBeDeterminedPre: 'Bu kullanıcının erişimi belirlenemedi. İzin atamalarını okumak için',
    UserAccessCouldNotBeDeterminedPost: 'hakkı gerekir (Site Sahibi veya üstü) ve bu kullanıcı, sitenin varsayılan Sahipler, Üyeler veya Ziyaretçiler gruplarının üyesi gibi görünmüyor.',
    SiteLevelAccessBannerPre: 'Bu kullanıcının site düzeyinde erişimi var. Yalnızca',
    UniquePermissionAssignmentsWord: 'benzersiz izin atamalarına',
    SiteLevelAccessBannerPost: 'sahip konumlar aşağıda görünür — diğer tüm içerik, listenin üstünde gösterilen site düzeyi izin aracılığıyla erişilebilir.',
    UserAccessResultsLabel: 'Kullanıcı erişimi sonuçları',
  };
});
