define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Конфігурація Smart Permissions',
    PropertyPane_GroupName: 'Загальні',
    PropertyPane_DefaultViewLabel: 'Подання за замовчуванням під час відкриття',
    PropertyPane_View_Home: 'Головна',
    PropertyPane_View_Report: 'Звіт про дозволи',
    PropertyPane_View_Explorer: 'Провідник дозволів',
    PropertyPane_View_UserAccess: 'Доступ користувача',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/moisait',
    ConnectButton: 'Підключити',
    CancelButton: 'Скасувати',
    ChangeUrlButton: 'Змінити URL-адресу',
    SettingsLabel: 'Параметри',
    RenderErrorTitle: 'Smart Permissions — Помилка візуалізації',
    RenderErrorMessageLabel: 'Повідомлення:',
    RenderErrorStackLabel: 'Стек:',
    RenderErrorNoStack: '(стек недоступний)',
    BackButton: 'Назад',
    BackToHomeLabel: 'Назад на головну',
    ExplorerCardTitle: 'Провідник дозволів',
    ExplorerCardAlt: 'Провідник дозволів із деревом папок і панеллю дозволів',
    ExplorerCardDesc: 'Переглядайте будь-яку папку чи файл і миттєво дізнавайтеся, хто має доступ — із перевіркою дозволів у реальному часі.',
    ExplorerCardButton: 'Відкрити Провідник дозволів',
    ReportCardTitle: 'Звіт про дозволи',
    ReportCardAlt: 'Екран налаштування звіту про дозволи',
    ReportCardDesc: 'Створіть кольоровий звіт Excel для кожного унікального призначення дозволу на вашому сайті.',
    ReportCardButton: 'Запустити звіт про дозволи',
    UserAccessCardTitle: 'Доступ користувача',
    UserAccessCardAlt: 'Екран доступу користувача, що показує доступні місця для вибраного користувача',
    UserAccessCardDesc: 'Знайдіть будь-якого користувача, щоб побачити всі місця, до яких він має доступ на сайті, з точним рівнем дозволу.',
    UserAccessCardButton: 'Перевірити доступ користувача',
    SiteOwnerRequiredTitle: 'Потрібен доступ власника сайту —',
    SiteOwnerRequiredDesc: 'Ці інструменти потребують доступу власника сайту. Зверніться до власника сайту, якщо у вас є запитання щодо дозволів.',
    HomeSubtitle: 'Перевіряйте та розумійте дозволи SharePoint — без PowerShell.',
    RequiresSiteOwnerTooltip: 'Потрібен доступ власника сайту',
    HomeNoteLabel: 'Примітка:',
    HomeNoteText: 'Ця веб-частина працює від імені поточного увійшовшого користувача. Вона може бачити лише сайти та елементи, до яких цей користувач має доступ. Для повного сканування орендаря використовуйте обліковий запис із відповідним доступом на читання до всіх сайтів.',
    SettingsTitle: 'Параметри',
    LibrariesSectionTitle: 'Бібліотеки',
    IncludeHiddenLabel: 'Включити системні та приховані бібліотеки',
    IncludeHiddenTooltip: 'Якщо позначено, включає бібліотеку стилів, шаблони форм, ресурси сайту та інші бібліотеки, приховані у поданнях за замовчуванням. Застосовується до всіх інструментів.',
    MoreInfoHiddenLibrariesLabel: 'Докладніше про приховані бібліотеки',
    ExcludeLimitedAccessLabel: 'Виключити записи з обмеженим доступом',
    ExcludeLimitedAccessTooltip: 'Приховує користувачів і групи, єдиним дозволом SharePoint яких є Обмежений доступ — призначається автоматично під час спільного використання файлів через посилання. Застосовується до звіту про дозволи, Провідника та доступу користувача.',
    MoreInfoLimitedAccessLabel: 'Докладніше про обмежений доступ',
    ExcludeSharingLinksLabel: 'Виключити записи посилань спільного доступу',
    ExcludeSharingLinksTooltip: 'Приховує внутрішні групи "SharingLinks.*", які SharePoint автоматично створює для посилань спільного доступу "Будь-хто з посиланням" і "Певні особи". Застосовується до звіту про дозволи, Провідника та доступу користувача.',
    MoreInfoSharingLinksLabel: 'Докладніше про посилання спільного доступу',
    PerformanceSectionTitle: 'Продуктивність',
    ConcurrentRequestsLabel: 'Одночасні запити API:',
    ConcurrencyTooltip: 'Скільки запитів API SharePoint виконується паралельно під час сканування звіту про дозволи, сканування доступу користувача та фонових перевірок Провідника. Вищі значення швидші, але з більшою ймовірністю спричинять обмеження (HTTP 429). Рекомендовано 3–5.',
    MoreInfoConcurrencyLabel: 'Докладніше про паралелізм',
    ConcurrencyHint: 'Вищі значення сканують швидше, але можуть спричинити обмеження SharePoint. Рекомендовано: 3–5.',
    GroupMemberCapLabel: 'Обмеження відображення учасників групи:',
    GroupMemberCapTooltip: 'Максимальна кількість учасників, що відображаються на групу, коли ввімкнено "Розгорнути учасників групи". Більші групи обмежуються, і відображається сповіщення. Збільшення цього значення використовує більше пам\'яті.',
    MoreInfoGroupMemberCapLabel: 'Докладніше про обмеження учасників групи',
    GroupMemberCapHint: 'Групи, більші за це обмеження, показують сповіщення про скорочення. За замовчуванням: 500.',
    DefaultViewSectionTitle: 'Подання за замовчуванням під час завантаження',
    DefaultViewInstructionsIntro: 'Щоб змінити, який екран відкривається під час першого завантаження веб-частини, відредагуйте властивості веб-частини:',
    DefaultViewStep1Pre: 'Переведіть сторінку SharePoint у режим',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Натисніть значок',
    DefaultViewStep2Post: 'на веб-частині Smart Permissions.',
    DefaultViewStep3Pre: 'На панелі властивостей виберіть подання зі спадного списку',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'сторінку, щоб зберегти зміну.',
    EditModeWord: 'Редагування',
    PencilEditWord: 'олівець (редагувати)',
    DefaultViewOnOpenWord: 'Подання за замовчуванням під час відкриття',
    RepublishWord: 'Опублікуйте повторно',
    SiteOwnersLabel: 'Власники сайту:',
    EveryoneClaimLabel: 'Усі',
    EveryoneExceptExternalClaimLabel: 'Усі, крім зовнішніх користувачів',
    PermissionAssignmentsLabel: 'Призначення дозволів',
    UserGroupColumnHeader: 'Користувач / Група',
    TypeColumnHeader: 'Тип',
    PermissionLevelColumnHeader: 'Рівень дозволу',
    TenantWideAccessSuffix: '— доступ у межах усього орендаря',
    SecurityGroupType: 'Група безпеки',
    SpGroupType: 'Група SP',
    UserType: 'Користувач',
    CheckAccessForLabel: 'Перевірити доступ для {0}',
    ContainsUniqueAndExternalTooltip: 'Містить елементи з унікальними дозволами та доступом зовнішніх користувачів',
    ContainsUniqueTooltip: 'Містить елементи з унікальними дозволами',
    ContainsExternalTooltip: 'Містить елементи з доступом зовнішніх користувачів',
    UniqueBadge: 'Унікальне',
    ExternalAccessDetectedTooltip: 'Виявлено доступ зовнішнього користувача',
    ConnectingStatus: 'Підключення…',
    ConnectedLibrarySingular: 'Підключено — знайдено {0} бібліотеку',
    ConnectedLibraryPlural: 'Підключено — знайдено {0} бібліотек',
    ConnectionFailedError: 'Не вдалося підключитися: {0}',
    LibraryEmptyStatus: 'Ця бібліотека порожня.',
    ErrorLoadingLibrary: 'Помилка завантаження бібліотеки: {0}',
    ErrorLoadingContents: 'Помилка завантаження вмісту',
    LibraryFieldLabel: 'Бібліотека',
    HiddenFromSearchSuffix: '{0} (приховано з пошуку)',
    UniquePermissionsOnlyToggle: 'Лише унікальні дозволи',
    ExternalUsersOnlyToggle: 'Лише зовнішні користувачі',
    LegendLabel: 'Умовні позначення:',
    LegendItemHasUnique: 'Елемент має унікальні дозволи',
    LegendContainsUniqueBelow: 'Містить унікальні дозволи нижче',
    LegendContainsExternalBelow: 'Містить доступ зовнішнього користувача нижче',
    LegendExternalOnItem: 'Доступ зовнішнього користувача до цього елемента',
    ViewingWithMemberAccessTitle: 'Перегляд із доступом учасника',
    ViewingWithMemberAccessDesc1: '— призначення дозволів не відображаються. Для перегляду, хто має доступ, потрібне право',
    ManagePermissionsWord: 'Керування дозволами',
    ViewingWithMemberAccessDesc2: '(власник сайту або вище). Ви все ще можете бачити, які елементи мають перерване успадкування, за допомогою індикаторів ↓. Щоб побачити місця, до яких у вас є доступ, скористайтеся інструментом',
    UserAccessWord: 'Доступ користувача',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Папки та файли',
    SelectFolderOrFilePrompt: 'Виберіть папку або файл, щоб переглянути його дозволи.',
    UniquePermissionsBadge: 'Унікальні дозволи',
    InheritedBadge: 'Успадковано',
    ExpandGroupMembersLabel: 'Розгорнути учасників групи',
    ShowParentPermissionsLabel: 'Показати батьківські дозволи',
    InheritsFromParentText: 'Цей елемент успадковує дозволи від батьківського елемента.',
    YourAccessLabel: 'Ваш доступ:',
    PermissionsNotVisibleNodeText: 'Призначення дозволів не відображаються — потрібне право Керування дозволами (власник сайту або вище), щоб побачити, хто має доступ до цього елемента.',
    NoExternalUsersDirectAccessText: 'Жоден зовнішній користувач не має прямого доступу до цього елемента.',
    InheritedFromLabel: 'Успадковано від:',
    ParentPermissionsNotVisibleText: 'Призначення дозволів батьківського елемента не відображаються — потрібне право Керування дозволами (власник сайту або вище).',
    NoPermissionsFoundOnParentText: 'На батьківському елементі дозволів не знайдено.',
    StartingScanStatus: 'Запуск сканування…',
    ScanCancelledStatus: 'Сканування скасовано — зібрано {0} об\'єкт(и/ів) до скасування.',
    ScanCompleteStatus: 'Сканування завершено — знайдено {0} об\'єкт(и/ів), {1} з унікальними дозволами.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Сканування завершено',
    ScanCompleteNotificationBody: '{0} об\'єктів, {1} з унікальними дозволами.',
    CancelledStatus: 'Скасовано.',
    GenericErrorPrefix: 'Помилка: {0}',
    ExportErrorPrefix: 'Помилка експорту: {0}',
    ScopeSiteOnly: 'Лише сайт',
    ScopeLibraries: 'Бібліотеки',
    ScopeFolders: 'Папки',
    ScopeFilesAndFolders: 'Файли та папки',
    ScanInProgressConfirm: 'Виконується сканування. Вийти й скасувати?',
    HistoryButton: 'Історія',
    BackToHistoryButton: 'Назад до історії',
    ComparingLabel: 'Порівняння',
    CompareMismatchWarning: 'Ці звіти було створено з різними сайтами або параметрами сканування — різниці нижче можуть відображати змінені параметри сканування, а не фактичні зміни дозволів.',
    NoPermissionDifferencesFound: 'Різниці в дозволах між цими двома звітами не знайдено.',
    PermissionChangesHeaderSingular: 'Зміни дозволів ({0} об\'єкт)',
    PermissionChangesHeaderPlural: 'Зміни дозволів ({0} об\'єктів)',
    ChangeColumnHeader: 'Зміна',
    BeforeColumnHeader: 'До',
    AfterColumnHeader: 'Після',
    AddedBadge: 'Додано',
    RemovedBadge: 'Видалено',
    ChangedBadge: 'Змінено',
    InheritanceChangedHeader: 'Успадкування змінено ({0})',
    NameColumnHeader: 'Назва',
    PathColumnHeader: 'Шлях',
    NowColumnHeader: 'Зараз',
    UniqueInheritanceBrokenBadge: 'Унікальне (успадкування перервано)',
    InheritedRestoredBadge: 'Успадковано (відновлено)',
    NewObjectsHeader: 'Нові об\'єкти',
    RemovedObjectsHeader: 'Видалені об\'єкти',
    BackToScanButton: 'Назад до сканування',
    CompareSelectedButton: 'Порівняти вибрані',
    NoReportsSavedYet: 'Звітів ще не збережено.',
    SelectForCompareLabel: 'Вибрати для порівняння',
    DateTimeColumnHeader: 'Дата / Час',
    SiteColumnHeader: 'Сайт',
    ScopeColumnHeader: 'Область',
    ObjectsColumnHeader: 'Об\'єкти',
    UniqueColumnHeader: 'Унікальні',
    SelectReportForCompareLabel: 'Вибрати звіт від {0} для порівняння',
    AllSitesPrefix: 'Усі сайти · ',
    PlusSubsitesSuffix: ' + підсайти',
    ExportingStatus: 'Експортування…',
    ExportButton: 'Експортувати',
    DeleteThisReportTitle: 'Видалити цей звіт',
    ScanAllSiteCollectionsLabel: 'Сканувати всі колекції сайтів у цьому орендарі (доступно лише на кореневому сайті)',
    AllSitesSearchCaveat: 'Список сайтів отримано з пошуку і може не включати всі колекції сайтів — щойно створені сайти або сайти, виключені з індексу пошуку, можуть бути відсутні.',
    IncludeSubsitesLabel: 'Включити підсайти (сканує кожен підсайт під цим сайтом)',
    ScanDepthFieldLabel: 'Глибина сканування',
    FolderDepthLimitLabel: 'Обмеження глибини папок:',
    ExpandGroupMembersInReportLabel: 'Розгорнути учасників групи у звіті (групи SharePoint, групи безпеки та групи M365)',
    LibrariesToScanLabel: 'Бібліотеки для сканування',
    OfSelectedCount: 'Вибрано {0} з {1}',
    AllButton: 'Усі',
    NoneButton: 'Жодної',
    LoadingLibrariesStatus: 'Завантаження бібліотек…',
    RunReportButton: 'Запустити звіт',
    ItemsFoundSoFar: 'Наразі знайдено {0} елементів',
    LibraryOfProgress: 'Бібліотека {0} з {1}',
    ScanCancelledPartialResults: 'Сканування скасовано — часткові результати',
    ScanCompleteLabel: 'Сканування завершено',
    ObjectsCountBadge: '{0} об\'єктів',
    UniqueCountBadge: '{0} унікальних',
    InheritedCountBadge: '{0} успадкованих',
    GeneratingExcelStatus: 'Створення Excel…',
    ExportFilteredRowsButton: 'Експортувати {0} відфільтрованих рядків',
    ExportToExcelButton: 'Експортувати в Excel',
    ExportToCsvButton: 'Експортувати в CSV',
    ScanStoppedEarlyTitle: 'Сканування зупинено достроково — SharePoint обмежує цього орендаря.',
    SiteCollectionsScannedBeforeStopping: '{0} з {1} колекцій сайтів було просканировано до зупинки. ',
    ResultsBelowCoverOnlyPre: 'Результати нижче охоплюють лише те, що було просканировано, і не є',
    NotWord: 'не є',
    ResultsBelowCoverOnlyPost: 'повною перевіркою. Сканування зупиняється саме в цій ситуації, оскільки продовження надсилання запитів підтримує обмеження активним. Зачекайте кілька хвилин, потім запустіть знову з',
    ConcurrentRequestsWord: 'Одночасні запити',
    SetTo1Or2InSettings: 'встановлено на 1 або 2 в Параметрах.',
    ThrottledScanMessage: 'SharePoint обмежив це сканування ({0} запит(и/ів) було обмежено та повторено).',
    OfEverythingScannedPre: 'З усього просканованого,',
    ItemCountSingular: '{0} елемент',
    ItemCountPlural: '{0} елементів',
    CouldNotBeConfirmedText: 'не вдалося підтвердити після повторної спроби (перегляньте сповіщення "не вдалося повністю прочитати" нижче, щоб дізнатися, які саме) — цей збій пов\'язаний із пропускною спроможністю, а не є відображенням їхніх фактичних дозволів. Усі інші елементи в цьому звіті було успішно прочитано, і їм можна довіряти.',
    DespiteThrottlingText: 'Незважаючи на обмеження, кожен елемент все ж було успішно підтверджено після повторної спроби, тож цей звіт повний.',
    ForCleanRunPre: 'Для чистого запуску зачекайте кілька хвилин і скануйте знову з нижчим значенням для',
    ValueInSettingsPost: 'в Параметрах.',
    OneItemWord: '1 елемент',
    NItemsWord: '{0} елемент(и/ів)',
    OutOfScannedCouldNotBeRead: 'з {0} просканованих не вдалося прочитати з вашим поточним доступом —',
    PermissionAssignmentsForItAreNotShown: ' призначення дозволів не відображаються, ',
    PermissionAssignmentsForThoseAreNotShown: ' призначення дозволів не відображаються, ',
    RestOfReportReadSuccessfully: 'але решту цього звіту було успішно прочитано.',
    RunScanAsSiteOwnerPre: 'Запустіть сканування як',
    SiteOwnerWord: 'власник сайту',
    RunScanAsSiteOwnerPost: 'щоб побачити повні відомості про відхилені елементи нижче.',
    AndNMoreText: '…і ще {0}',
    GroupExpansionSkippedPre: 'Розгортання учасників групи було пропущено — дозвіл Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'не було затверджено в цьому орендарі. Адміністратор SharePoint або глобальний адміністратор може затвердити його в',
    SharePointAdminCenterPath: 'Центр адміністрування SharePoint → Додатково → Доступ до API',
    ScanIncompleteItemsMessage: '{0} елемент(и/ів) не вдалося повністю прочитати через тимчасову помилку (не проблему з дозволами), і вони відображаються з дозволами батьківського елемента як резервне рішення — це може не відображати їхній фактичний доступ. Запустіть сканування знову, щоб повторити спробу для цих елементів.',
    FilterByNamePathUserPlaceholder: 'Фільтрувати за назвою, шляхом або користувачем/групою…',
    FilterResultsLabel: 'Фільтрувати результати',
    ExternalUsersOnlyExtLabel: 'Лише зовнішні користувачі (#ext#)',
    ShowingOfCount: 'Показано {0} з {1}',
    ScanResultsLabel: 'Результати сканування',
    PermissionsColumnHeader: 'Дозволи',
    CollapsePermissionsLabel: 'Згорнути дозволи',
    ExpandPermissionsLabel: 'Розгорнути дозволи',
    HiddenFromSearchBadge: 'Приховано з пошуку',
    AssignmentCountSingular: '{0} призначення',
    AssignmentCountPlural: '{0} призначень',
    LoadMoreRemainingButton: 'Завантажити більше (залишилося {0})',
    LoadingUsersStatus: 'Завантаження користувачів…',
    ConnectedUserSingular: 'Підключено — знайдено {0} користувача',
    ConnectedUserPlural: 'Підключено — знайдено {0} користувачів',
    CheckingAccessForStatus: 'Перевірка доступу для {0}…',
    FullSiteAccessDetectedStatus: 'Виявлено повний доступ до сайту.',
    AccessibleLocationsFoundSingular: 'Знайдено {0} доступне місце.',
    AccessibleLocationsFoundPlural: 'Знайдено {0} доступних місць.',
    NoAccessibleLocationsFoundStatus: 'Доступних місць не знайдено.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Сканування доступу користувача завершено',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Нове сканування',
    NoUserAccessScansSavedYet: 'Сканування доступу користувача ще не збережено.',
    UserColumnHeader: 'Користувач',
    LocationsColumnHeader: 'Місця',
    FullControlBadge: 'Повний контроль',
    DeleteThisRecordTitle: 'Видалити цей запис',
    SelectAUserFieldLabel: 'Виберіть користувача',
    SearchUsersPlaceholder: 'Пошук користувачів…',
    SelectAUserToCheckAccessLabel: 'Виберіть користувача для перевірки доступу',
    NotInThisSiteLabel: 'Немає на цьому сайті',
    ScanInProgressLabel: 'Виконується сканування',
    ScanningUserAccessLabel: 'Сканування доступу користувача',
    ScanningStatus: 'Сканування…',
    FullControlAccessPre: 'Цей користувач має',
    FullControlWord: 'Повний контроль',
    FullControlAccessPost: 'або доступ рівня власника до всього сайту — усі бібліотеки та папки доступні.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Не вдалося визначити дозвіл на рівні сайту — цей сайт, ймовірно, використовує доступ через групу Microsoft 365. Щоб показати його, адміністратор SharePoint повинен затвердити дозвіл',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph у',
    ShowingSiteLevelAccessOnlyPre: 'Відображається лише',
    SiteLevelAccessOnlyWord: 'доступ на рівні сайту',
    ShowingSiteLevelAccessOnlyMid: ', на основі членства в групі SharePoint за замовчуванням. Унікальні дозволи для бібліотек, папок і файлів не вдалося прочитати, і вони не відображаються. Для повних результатів запустіть це сканування як',
    UserAccessCouldNotBeDeterminedPre: 'Не вдалося визначити доступ цього користувача. Для читання призначень дозволів потрібне право',
    UserAccessCouldNotBeDeterminedPost: '(власник сайту або вище), і цей користувач, схоже, не є учасником груп за замовчуванням Власники, Учасники або Відвідувачі сайту.',
    SiteLevelAccessBannerPre: 'Цей користувач має доступ на рівні сайту. Нижче відображаються лише місця з',
    UniquePermissionAssignmentsWord: 'унікальними призначеннями дозволів',
    SiteLevelAccessBannerPost: '— увесь інший вміст доступний через дозвіл на рівні сайту, показаний угорі списку.',
    UserAccessResultsLabel: 'Результати доступу користувача',
  };
});
