define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Cấu hình Smart Permissions',
    PropertyPane_GroupName: 'Chung',
    PropertyPane_DefaultViewLabel: 'Chế độ xem mặc định khi mở',
    PropertyPane_View_Home: 'Trang chủ',
    PropertyPane_View_Report: 'Báo cáo quyền',
    PropertyPane_View_Explorer: 'Trình khám phá quyền',
    PropertyPane_View_UserAccess: 'Quyền truy cập của người dùng',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: 'Kết nối',
    CancelButton: 'Hủy',
    ChangeUrlButton: 'Thay đổi URL',
    SettingsLabel: 'Cài đặt',
    RenderErrorTitle: 'Smart Permissions — Lỗi kết xuất',
    RenderErrorMessageLabel: 'Thông báo:',
    RenderErrorStackLabel: 'Ngăn xếp:',
    RenderErrorNoStack: '(ngăn xếp không khả dụng)',
    BackButton: 'Quay lại',
    BackToHomeLabel: 'Quay lại trang chủ',
    ExplorerCardTitle: 'Trình khám phá quyền',
    ExplorerCardAlt: 'Trình khám phá quyền với cây thư mục và bảng quyền',
    ExplorerCardDesc: 'Duyệt bất kỳ thư mục hoặc tệp nào và xem ngay ai có quyền truy cập — với tra cứu quyền theo thời gian thực.',
    ExplorerCardButton: 'Mở Trình khám phá quyền',
    ReportCardTitle: 'Báo cáo quyền',
    ReportCardAlt: 'Màn hình cấu hình báo cáo quyền',
    ReportCardDesc: 'Tạo báo cáo Excel được mã hóa màu cho từng quyền duy nhất được gán trên trang web của bạn.',
    ReportCardButton: 'Chạy báo cáo quyền',
    UserAccessCardTitle: 'Quyền truy cập của người dùng',
    UserAccessCardAlt: 'Màn hình quyền truy cập của người dùng hiển thị các vị trí có thể truy cập cho người dùng đã chọn',
    UserAccessCardDesc: 'Tra cứu bất kỳ người dùng nào để xem mọi vị trí họ có thể truy cập trên một trang web, cùng với cấp quyền chính xác.',
    UserAccessCardButton: 'Kiểm tra quyền truy cập của người dùng',
    SiteOwnerRequiredTitle: 'Yêu cầu quyền truy cập của Chủ sở hữu trang web —',
    SiteOwnerRequiredDesc: 'Các công cụ này yêu cầu quyền truy cập của Chủ sở hữu trang web. Liên hệ với chủ sở hữu trang web nếu bạn có câu hỏi về quyền.',
    HomeSubtitle: 'Kiểm tra và hiểu các quyền của SharePoint — không cần PowerShell.',
    RequiresSiteOwnerTooltip: 'Yêu cầu quyền truy cập của Chủ sở hữu trang web',
    HomeNoteLabel: 'Lưu ý:',
    HomeNoteText: 'Web Part này chạy dưới danh nghĩa người dùng hiện đang đăng nhập. Nó chỉ có thể xem các trang web và mục mà người dùng đó có quyền truy cập. Để quét toàn bộ tenant, hãy sử dụng tài khoản có quyền đọc phù hợp trên tất cả các trang web.',
    SettingsTitle: 'Cài đặt',
    LibrariesSectionTitle: 'Thư viện',
    IncludeHiddenLabel: 'Bao gồm thư viện hệ thống và thư viện ẩn',
    IncludeHiddenTooltip: 'Nếu được chọn, bao gồm Style Library, Form Templates, Site Assets và các thư viện khác bị ẩn khỏi chế độ xem mặc định. Áp dụng cho tất cả các công cụ.',
    MoreInfoHiddenLibrariesLabel: 'Thêm thông tin về thư viện ẩn',
    ExcludeLimitedAccessLabel: 'Loại trừ các mục Truy cập hạn chế',
    ExcludeLimitedAccessTooltip: 'Ẩn người dùng và nhóm có quyền SharePoint duy nhất là Truy cập hạn chế — được tự động gán khi tệp được chia sẻ qua liên kết. Áp dụng cho Báo cáo quyền, Trình khám phá và Quyền truy cập của người dùng.',
    MoreInfoLimitedAccessLabel: 'Thêm thông tin về Truy cập hạn chế',
    ExcludeSharingLinksLabel: 'Loại trừ các mục Liên kết chia sẻ',
    ExcludeSharingLinksTooltip: 'Ẩn các nhóm nội bộ "SharingLinks.*" mà SharePoint tự động tạo cho các liên kết chia sẻ "Bất kỳ ai có liên kết" và "Người cụ thể". Áp dụng cho Báo cáo quyền, Trình khám phá và Quyền truy cập của người dùng.',
    MoreInfoSharingLinksLabel: 'Thêm thông tin về liên kết chia sẻ',
    PerformanceSectionTitle: 'Hiệu suất',
    ConcurrentRequestsLabel: 'Số yêu cầu API đồng thời:',
    ConcurrencyTooltip: 'Số lượng yêu cầu API của SharePoint chạy song song trong quá trình quét Báo cáo quyền, quét Quyền truy cập của người dùng và kiểm tra nền của Trình khám phá. Giá trị cao hơn nhanh hơn nhưng dễ gây ra giới hạn tốc độ (HTTP 429) hơn. Khuyến nghị 3–5.',
    MoreInfoConcurrencyLabel: 'Thêm thông tin về tính đồng thời',
    ConcurrencyHint: 'Giá trị cao hơn quét nhanh hơn nhưng có thể gây ra giới hạn tốc độ của SharePoint. Khuyến nghị: 3–5.',
    GroupMemberCapLabel: 'Giới hạn hiển thị thành viên nhóm:',
    GroupMemberCapTooltip: 'Số lượng thành viên tối đa được hiển thị cho mỗi nhóm khi "Mở rộng thành viên nhóm" được bật. Các nhóm lớn hơn sẽ bị giới hạn và hiển thị thông báo. Tăng giá trị này sẽ sử dụng nhiều bộ nhớ hơn.',
    MoreInfoGroupMemberCapLabel: 'Thêm thông tin về giới hạn thành viên nhóm',
    GroupMemberCapHint: 'Các nhóm lớn hơn giới hạn này sẽ hiển thị thông báo cắt bớt. Mặc định: 500.',
    DefaultViewSectionTitle: 'Chế độ xem mặc định khi tải',
    DefaultViewInstructionsIntro: 'Để thay đổi màn hình nào mở ra khi Web Part được tải lần đầu, hãy chỉnh sửa thuộc tính của Web Part:',
    DefaultViewStep1Pre: 'Đặt trang SharePoint vào chế độ',
    DefaultViewStep1Post: '.',
    DefaultViewStep2Pre: 'Nhấp vào biểu tượng',
    DefaultViewStep2Post: 'trên Web Part Smart Permissions.',
    DefaultViewStep3Pre: 'Trong bảng thuộc tính, chọn một chế độ xem từ danh sách thả xuống',
    DefaultViewStep3Post: '.',
    DefaultViewStep4Post: 'lại trang để lưu thay đổi.',
    EditModeWord: 'Chỉnh sửa',
    PencilEditWord: 'bút chì (chỉnh sửa)',
    DefaultViewOnOpenWord: 'Chế độ xem mặc định khi mở',
    RepublishWord: 'Xuất bản lại',
    SiteOwnersLabel: 'Chủ sở hữu trang web:',
    EveryoneClaimLabel: 'Mọi người',
    EveryoneExceptExternalClaimLabel: 'Mọi người trừ người dùng bên ngoài',
    PermissionAssignmentsLabel: 'Quyền được gán',
    UserGroupColumnHeader: 'Người dùng / Nhóm',
    TypeColumnHeader: 'Loại',
    PermissionLevelColumnHeader: 'Cấp quyền',
    TenantWideAccessSuffix: '— quyền truy cập trên toàn bộ tenant',
    SecurityGroupType: 'Nhóm bảo mật',
    SpGroupType: 'Nhóm SP',
    UserType: 'Người dùng',
    CheckAccessForLabel: 'Kiểm tra quyền truy cập cho {0}',
    ContainsUniqueAndExternalTooltip: 'Chứa các mục có quyền duy nhất và quyền truy cập của người dùng bên ngoài',
    ContainsUniqueTooltip: 'Chứa các mục có quyền duy nhất',
    ContainsExternalTooltip: 'Chứa các mục có quyền truy cập của người dùng bên ngoài',
    UniqueBadge: 'Duy nhất',
    ExternalAccessDetectedTooltip: 'Đã phát hiện quyền truy cập của người dùng bên ngoài',
    ConnectingStatus: 'Đang kết nối…',
    ConnectedLibrarySingular: 'Đã kết nối — tìm thấy {0} thư viện',
    ConnectedLibraryPlural: 'Đã kết nối — tìm thấy {0} thư viện',
    ConnectionFailedError: 'Kết nối không thành công: {0}',
    LibraryEmptyStatus: 'Thư viện này trống.',
    ErrorLoadingLibrary: 'Lỗi khi tải thư viện: {0}',
    ErrorLoadingContents: 'Lỗi khi tải nội dung',
    LibraryFieldLabel: 'Thư viện',
    HiddenFromSearchSuffix: '{0} (đã ẩn khỏi tìm kiếm)',
    UniquePermissionsOnlyToggle: 'Chỉ quyền duy nhất',
    ExternalUsersOnlyToggle: 'Chỉ người dùng bên ngoài',
    LegendLabel: 'Chú giải:',
    LegendItemHasUnique: 'Mục có quyền duy nhất',
    LegendContainsUniqueBelow: 'Chứa quyền duy nhất bên dưới',
    LegendContainsExternalBelow: 'Chứa quyền truy cập của người dùng bên ngoài bên dưới',
    LegendExternalOnItem: 'Quyền truy cập của người dùng bên ngoài trên mục này',
    ViewingWithMemberAccessTitle: 'Đang xem với quyền truy cập Thành viên',
    ViewingWithMemberAccessDesc1: '— các quyền được gán không hiển thị. Để xem ai có quyền truy cập, cần có quyền',
    ManagePermissionsWord: 'Quản lý quyền',
    ViewingWithMemberAccessDesc2: '(Chủ sở hữu trang web trở lên). Bạn vẫn có thể xem mục nào bị gián đoạn kế thừa bằng cách sử dụng các chỉ báo ↓. Để xem các vị trí bạn có thể truy cập, hãy sử dụng công cụ',
    UserAccessWord: 'Quyền truy cập của người dùng',
    ViewingWithMemberAccessDesc3: '.',
    FoldersAndFilesLabel: 'Thư mục và tệp',
    SelectFolderOrFilePrompt: 'Chọn một thư mục hoặc tệp để xem quyền của nó.',
    UniquePermissionsBadge: 'Quyền duy nhất',
    InheritedBadge: 'Được kế thừa',
    ExpandGroupMembersLabel: 'Mở rộng thành viên nhóm',
    ShowParentPermissionsLabel: 'Hiển thị quyền của mục cha',
    InheritsFromParentText: 'Mục này kế thừa quyền từ mục cha của nó.',
    YourAccessLabel: 'Quyền truy cập của bạn:',
    PermissionsNotVisibleNodeText: 'Các quyền được gán không hiển thị — cần có quyền Quản lý quyền (Chủ sở hữu trang web trở lên) để xem ai có quyền truy cập vào mục này.',
    NoExternalUsersDirectAccessText: 'Không có người dùng bên ngoài nào có quyền truy cập trực tiếp vào mục này.',
    InheritedFromLabel: 'Kế thừa từ:',
    ParentPermissionsNotVisibleText: 'Các quyền được gán của mục cha không hiển thị — cần có quyền Quản lý quyền (Chủ sở hữu trang web trở lên).',
    NoPermissionsFoundOnParentText: 'Không tìm thấy quyền nào trên mục cha.',
    StartingScanStatus: 'Đang bắt đầu quét…',
    ScanCancelledStatus: 'Quét đã bị hủy — đã thu thập {0} đối tượng trước khi hủy.',
    ScanCompleteStatus: 'Quét hoàn tất — tìm thấy {0} đối tượng, {1} đối tượng có quyền duy nhất.',
    ScanCompleteNotificationTitle: 'Smart Permissions — Quét hoàn tất',
    ScanCompleteNotificationBody: '{0} đối tượng, {1} đối tượng có quyền duy nhất.',
    CancelledStatus: 'Đã hủy.',
    GenericErrorPrefix: 'Lỗi: {0}',
    ExportErrorPrefix: 'Lỗi xuất: {0}',
    ScopeSiteOnly: 'Chỉ trang web',
    ScopeLibraries: 'Thư viện',
    ScopeFolders: 'Thư mục',
    ScopeFilesAndFolders: 'Tệp và thư mục',
    ScanInProgressConfirm: 'Đang quét. Rời khỏi và hủy?',
    HistoryButton: 'Lịch sử',
    BackToHistoryButton: 'Quay lại lịch sử',
    ComparingLabel: 'Đang so sánh',
    CompareMismatchWarning: 'Các báo cáo này được thực hiện với các trang web hoặc tùy chọn quét khác nhau — sự khác biệt bên dưới có thể phản ánh cài đặt quét đã thay đổi thay vì thay đổi quyền thực tế.',
    NoPermissionDifferencesFound: 'Không tìm thấy sự khác biệt về quyền giữa hai báo cáo này.',
    PermissionChangesHeaderSingular: 'Thay đổi quyền ({0} đối tượng)',
    PermissionChangesHeaderPlural: 'Thay đổi quyền ({0} đối tượng)',
    ChangeColumnHeader: 'Thay đổi',
    BeforeColumnHeader: 'Trước',
    AfterColumnHeader: 'Sau',
    AddedBadge: 'Đã thêm',
    RemovedBadge: 'Đã xóa',
    ChangedBadge: 'Đã thay đổi',
    InheritanceChangedHeader: 'Kế thừa đã thay đổi ({0})',
    NameColumnHeader: 'Tên',
    PathColumnHeader: 'Đường dẫn',
    NowColumnHeader: 'Hiện tại',
    UniqueInheritanceBrokenBadge: 'Duy nhất (kế thừa bị gián đoạn)',
    InheritedRestoredBadge: 'Được kế thừa (đã khôi phục)',
    NewObjectsHeader: 'Đối tượng mới',
    RemovedObjectsHeader: 'Đối tượng đã xóa',
    BackToScanButton: 'Quay lại quét',
    CompareSelectedButton: 'So sánh mục đã chọn',
    NoReportsSavedYet: 'Chưa có báo cáo nào được lưu.',
    SelectForCompareLabel: 'Chọn để so sánh',
    DateTimeColumnHeader: 'Ngày / Giờ',
    SiteColumnHeader: 'Trang web',
    ScopeColumnHeader: 'Phạm vi',
    ObjectsColumnHeader: 'Đối tượng',
    UniqueColumnHeader: 'Duy nhất',
    SelectReportForCompareLabel: 'Chọn báo cáo từ {0} để so sánh',
    AllSitesPrefix: 'Tất cả trang web · ',
    PlusSubsitesSuffix: ' + trang web con',
    ExportingStatus: 'Đang xuất…',
    ExportButton: 'Xuất',
    DeleteThisReportTitle: 'Xóa báo cáo này',
    ScanAllSiteCollectionsLabel: 'Quét tất cả các bộ sưu tập trang web trong tenant này (chỉ khả dụng trên trang web gốc)',
    AllSitesSearchCaveat: 'Danh sách trang web đến từ tìm kiếm và có thể không bao gồm mọi bộ sưu tập trang web — các trang web được tạo rất gần đây, hoặc bị loại trừ khỏi chỉ mục tìm kiếm, có thể bị thiếu.',
    IncludeSubsitesLabel: 'Bao gồm trang web con (quét mọi trang web con bên dưới trang web này)',
    ScanDepthFieldLabel: 'Độ sâu quét',
    FolderDepthLimitLabel: 'Giới hạn độ sâu thư mục:',
    ExpandGroupMembersInReportLabel: 'Mở rộng thành viên nhóm trong báo cáo (nhóm SharePoint, nhóm bảo mật và nhóm M365)',
    LibrariesToScanLabel: 'Thư viện cần quét',
    OfSelectedCount: 'Đã chọn {0} trong số {1}',
    AllButton: 'Tất cả',
    NoneButton: 'Không có',
    LoadingLibrariesStatus: 'Đang tải thư viện…',
    RunReportButton: 'Chạy báo cáo',
    ItemsFoundSoFar: 'Đã tìm thấy {0} mục cho đến nay',
    LibraryOfProgress: 'Thư viện {0}/{1}',
    ScanCancelledPartialResults: 'Quét đã bị hủy — kết quả một phần',
    ScanCompleteLabel: 'Quét hoàn tất',
    ObjectsCountBadge: '{0} đối tượng',
    UniqueCountBadge: '{0} duy nhất',
    InheritedCountBadge: '{0} được kế thừa',
    GeneratingExcelStatus: 'Đang tạo Excel…',
    ExportFilteredRowsButton: 'Xuất {0} hàng đã lọc',
    ExportToExcelButton: 'Xuất sang Excel',
    ExportToCsvButton: 'Xuất sang CSV',
    ScanStoppedEarlyTitle: 'Quét đã dừng sớm — SharePoint đang giới hạn tốc độ đối với tenant này.',
    SiteCollectionsScannedBeforeStopping: 'Đã quét {0} trong số {1} bộ sưu tập trang web trước khi dừng. ',
    ResultsBelowCoverOnlyPre: 'Các kết quả bên dưới chỉ bao gồm những gì đã được quét và không phải là',
    NotWord: 'không phải là',
    ResultsBelowCoverOnlyPost: 'một cuộc kiểm tra đầy đủ. Việc quét tự dừng trong tình huống này vì việc tiếp tục gửi yêu cầu là điều duy trì giới hạn tốc độ. Hãy đợi vài phút, sau đó chạy lại với',
    ConcurrentRequestsWord: 'Yêu cầu đồng thời',
    SetTo1Or2InSettings: 'được đặt thành 1 hoặc 2 trong Cài đặt.',
    ThrottledScanMessage: 'SharePoint đã giới hạn tốc độ quét này ({0} yêu cầu đã bị giới hạn tốc độ và thử lại).',
    OfEverythingScannedPre: 'Trong tất cả những gì đã quét,',
    ItemCountSingular: '{0} mục',
    ItemCountPlural: '{0} mục',
    CouldNotBeConfirmedText: 'không thể xác nhận sau khi thử lại (xem thông báo "không thể đọc đầy đủ" bên dưới để biết chính xác mục nào) — lỗi đó liên quan đến khả năng xử lý, không phải là sự phản ánh quyền thực tế của chúng. Tất cả các mục khác trong báo cáo này đã được đọc thành công và có thể tin cậy được.',
    DespiteThrottlingText: 'Mặc dù bị giới hạn tốc độ, mỗi mục vẫn được xác nhận thành công sau khi thử lại, vì vậy báo cáo này hoàn chỉnh.',
    ForCleanRunPre: 'Để có một lần chạy sạch, hãy đợi vài phút và quét lại với giá trị thấp hơn cho',
    ValueInSettingsPost: 'trong Cài đặt.',
    OneItemWord: '1 mục',
    NItemsWord: '{0} mục',
    OutOfScannedCouldNotBeRead: 'trong số {0} mục đã quét không thể đọc được với quyền truy cập hiện tại của bạn —',
    PermissionAssignmentsForItAreNotShown: ' các quyền được gán không được hiển thị, ',
    PermissionAssignmentsForThoseAreNotShown: ' các quyền được gán không được hiển thị, ',
    RestOfReportReadSuccessfully: 'nhưng phần còn lại của báo cáo này đã được đọc thành công.',
    RunScanAsSiteOwnerPre: 'Chạy quét với tư cách là',
    SiteOwnerWord: 'Chủ sở hữu trang web',
    RunScanAsSiteOwnerPost: 'để xem chi tiết đầy đủ về các mục bị từ chối bên dưới.',
    AndNMoreText: '…và {0} mục khác',
    GroupExpansionSkippedPre: 'Đã bỏ qua việc mở rộng thành viên nhóm — quyền Graph',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: 'chưa được phê duyệt trong tenant này. Quản trị viên SharePoint hoặc quản trị viên toàn cầu có thể phê duyệt quyền này trong',
    SharePointAdminCenterPath: 'Trung tâm quản trị SharePoint → Nâng cao → Quyền truy cập API',
    ScanIncompleteItemsMessage: '{0} mục không thể đọc đầy đủ do lỗi tạm thời (không phải vấn đề về quyền) và được hiển thị với quyền của mục cha như một giải pháp dự phòng — điều này có thể không phản ánh quyền truy cập thực tế của chúng. Chạy lại quét để thử lại các mục này.',
    FilterByNamePathUserPlaceholder: 'Lọc theo tên, đường dẫn hoặc người dùng/nhóm…',
    FilterResultsLabel: 'Lọc kết quả',
    ExternalUsersOnlyExtLabel: 'Chỉ người dùng bên ngoài (#ext#)',
    ShowingOfCount: 'Hiển thị {0} trong số {1}',
    ScanResultsLabel: 'Kết quả quét',
    PermissionsColumnHeader: 'Quyền',
    CollapsePermissionsLabel: 'Thu gọn quyền',
    ExpandPermissionsLabel: 'Mở rộng quyền',
    HiddenFromSearchBadge: 'Đã ẩn khỏi tìm kiếm',
    AssignmentCountSingular: '{0} lần gán',
    AssignmentCountPlural: '{0} lần gán',
    LoadMoreRemainingButton: 'Tải thêm (còn lại {0})',
    LoadingUsersStatus: 'Đang tải người dùng…',
    ConnectedUserSingular: 'Đã kết nối — tìm thấy {0} người dùng',
    ConnectedUserPlural: 'Đã kết nối — tìm thấy {0} người dùng',
    CheckingAccessForStatus: 'Đang kiểm tra quyền truy cập cho {0}…',
    FullSiteAccessDetectedStatus: 'Đã phát hiện quyền truy cập đầy đủ vào trang web.',
    AccessibleLocationsFoundSingular: 'Đã tìm thấy {0} vị trí có thể truy cập.',
    AccessibleLocationsFoundPlural: 'Đã tìm thấy {0} vị trí có thể truy cập.',
    NoAccessibleLocationsFoundStatus: 'Không tìm thấy vị trí nào có thể truy cập.',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — Quét quyền truy cập của người dùng hoàn tất',
    UserAccessScanCompleteNotificationBody: '{0}: {1}',
    NewScanButton: 'Quét mới',
    NoUserAccessScansSavedYet: 'Chưa có quét quyền truy cập của người dùng nào được lưu.',
    UserColumnHeader: 'Người dùng',
    LocationsColumnHeader: 'Vị trí',
    FullControlBadge: 'Toàn quyền kiểm soát',
    DeleteThisRecordTitle: 'Xóa bản ghi này',
    SelectAUserFieldLabel: 'Chọn một người dùng',
    SearchUsersPlaceholder: 'Tìm kiếm người dùng…',
    SelectAUserToCheckAccessLabel: 'Chọn một người dùng để kiểm tra quyền truy cập',
    NotInThisSiteLabel: 'Không có trong trang web này',
    ScanInProgressLabel: 'Đang quét',
    ScanningUserAccessLabel: 'Đang quét quyền truy cập của người dùng',
    ScanningStatus: 'Đang quét…',
    FullControlAccessPre: 'Người dùng này có',
    FullControlWord: 'Toàn quyền kiểm soát',
    FullControlAccessPost: 'hoặc quyền truy cập cấp Chủ sở hữu đối với toàn bộ trang web — tất cả các thư viện và thư mục đều có thể truy cập.',
    SiteLevelPermissionCouldNotBeDeterminedPre: 'Không thể xác định quyền cấp trang web — trang web này có thể sử dụng quyền truy cập nhóm Microsoft 365. Để hiển thị, quản trị viên SharePoint phải phê duyệt quyền',
    SiteLevelPermissionCouldNotBeDeterminedMid: 'Graph trong',
    ShowingSiteLevelAccessOnlyPre: 'Chỉ hiển thị',
    SiteLevelAccessOnlyWord: 'quyền truy cập cấp trang web',
    ShowingSiteLevelAccessOnlyMid: ', dựa trên tư cách thành viên nhóm SharePoint mặc định. Các quyền duy nhất trên thư viện, thư mục và tệp không thể đọc được và không được hiển thị. Để có kết quả đầy đủ, hãy chạy quét này với tư cách là',
    UserAccessCouldNotBeDeterminedPre: 'Không thể xác định quyền truy cập của người dùng này. Việc đọc các quyền được gán yêu cầu quyền',
    UserAccessCouldNotBeDeterminedPost: '(Chủ sở hữu trang web trở lên), và người dùng này dường như không phải là thành viên của các nhóm Chủ sở hữu, Thành viên hoặc Khách truy cập mặc định của trang web.',
    SiteLevelAccessBannerPre: 'Người dùng này có quyền truy cập cấp trang web. Chỉ các vị trí có',
    UniquePermissionAssignmentsWord: 'quyền được gán duy nhất',
    SiteLevelAccessBannerPost: 'mới xuất hiện bên dưới — tất cả nội dung khác có thể truy cập được thông qua quyền cấp trang web được hiển thị ở đầu danh sách.',
    UserAccessResultsLabel: 'Kết quả quyền truy cập của người dùng',
  };
});
