define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions 配置',
    PropertyPane_GroupName: '常规',
    PropertyPane_DefaultViewLabel: '打开时的默认视图',
    PropertyPane_View_Home: '主页',
    PropertyPane_View_Report: '权限报告',
    PropertyPane_View_Explorer: '权限资源管理器',
    PropertyPane_View_UserAccess: '用户访问',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: '连接',
    CancelButton: '取消',
    ChangeUrlButton: '更改 URL',
    SettingsLabel: '设置',
    RenderErrorTitle: 'Smart Permissions — 呈现错误',
    RenderErrorMessageLabel: '消息：',
    RenderErrorStackLabel: '堆栈：',
    RenderErrorNoStack: '（堆栈不可用）',
    BackButton: '返回',
    BackToHomeLabel: '返回主页',
    ExplorerCardTitle: '权限资源管理器',
    ExplorerCardAlt: '带有文件夹树和权限面板的权限资源管理器',
    ExplorerCardDesc: '浏览任何文件夹或文件，通过实时权限查询立即查看谁有访问权限。',
    ExplorerCardButton: '打开权限资源管理器',
    ReportCardTitle: '权限报告',
    ReportCardAlt: '权限报告配置屏幕',
    ReportCardDesc: '为您站点中每个唯一权限分配生成带颜色编码的 Excel 报告。',
    ReportCardButton: '运行权限报告',
    UserAccessCardTitle: '用户访问',
    UserAccessCardAlt: '显示所选用户可访问位置的用户访问屏幕',
    UserAccessCardDesc: '查找任何用户以查看其在站点上可以访问的每个位置及其确切的权限级别。',
    UserAccessCardButton: '检查用户访问权限',
    SiteOwnerRequiredTitle: '需要站点所有者访问权限 —',
    SiteOwnerRequiredDesc: '这些工具需要站点所有者访问权限。如果您对权限有疑问，请联系站点所有者。',
    HomeSubtitle: '无需 PowerShell 即可审核并了解 SharePoint 权限。',
    RequiresSiteOwnerTooltip: '需要站点所有者访问权限',
    HomeNoteLabel: '注意：',
    HomeNoteText: '此 Web 部件以当前登录用户的身份运行。它只能查看该用户有权访问的站点和项目。要进行完整的租户扫描，请使用对所有站点具有适当读取权限的帐户。',
    SettingsTitle: '设置',
    LibrariesSectionTitle: '库',
    IncludeHiddenLabel: '包括系统库和隐藏库',
    IncludeHiddenTooltip: '如果选中，将包括样式库、表单模板、站点资产以及其他在默认视图中隐藏的库。适用于所有工具。',
    MoreInfoHiddenLibrariesLabel: '有关隐藏库的更多信息',
    ExcludeLimitedAccessLabel: '排除受限访问条目',
    ExcludeLimitedAccessTooltip: '隐藏唯一 SharePoint 权限为受限访问的用户和组 — 通过链接共享文件时会自动分配此权限。适用于权限报告、资源管理器和用户访问。',
    MoreInfoLimitedAccessLabel: '有关受限访问的更多信息',
    ExcludeSharingLinksLabel: '排除共享链接条目',
    ExcludeSharingLinksTooltip: '隐藏 SharePoint 为“任何拥有链接的人”和“特定人员”共享链接自动创建的内部 "SharingLinks.*" 组。适用于权限报告、资源管理器和用户访问。',
    MoreInfoSharingLinksLabel: '有关共享链接的更多信息',
    PerformanceSectionTitle: '性能',
    ConcurrentRequestsLabel: '并发 API 请求数：',
    ConcurrencyTooltip: '在权限报告扫描、用户访问扫描和资源管理器后台检查期间并行运行的 SharePoint API 请求数。较高的值速度更快，但更容易触发限流（HTTP 429）。建议使用 3–5。',
    MoreInfoConcurrencyLabel: '有关并发性的更多信息',
    ConcurrencyHint: '较高的值扫描速度更快，但可能触发 SharePoint 限流。建议值：3–5。',
    GroupMemberCapLabel: '组成员显示上限：',
    GroupMemberCapTooltip: '启用“展开组成员”时每个组显示的最大成员数。较大的组将受到限制，并显示通知。增加此值将使用更多内存。',
    MoreInfoGroupMemberCapLabel: '有关组成员上限的更多信息',
    GroupMemberCapHint: '超过此限制的组会显示截断通知。默认值：500。',
    DefaultViewSectionTitle: '加载时的默认视图',
    DefaultViewInstructionsIntro: '要更改 Web 部件首次加载时打开的屏幕，请编辑 Web 部件属性：',
    DefaultViewStep1Pre: '将 SharePoint 页面切换到',
    DefaultViewStep1Post: '模式。',
    DefaultViewStep2Pre: '单击 Smart Permissions Web 部件上的',
    DefaultViewStep2Post: '图标。',
    DefaultViewStep3Pre: '在属性面板中，从下拉列表',
    DefaultViewStep3Post: '中选择一个视图。',
    DefaultViewStep4Post: '页面以保存更改。',
    EditModeWord: '编辑',
    PencilEditWord: '铅笔（编辑）',
    DefaultViewOnOpenWord: '打开时的默认视图',
    RepublishWord: '重新发布',
    SiteOwnersLabel: '站点所有者：',
    EveryoneClaimLabel: '所有人',
    EveryoneExceptExternalClaimLabel: '除外部用户外的所有人',
    PermissionAssignmentsLabel: '权限分配',
    UserGroupColumnHeader: '用户/组',
    TypeColumnHeader: '类型',
    PermissionLevelColumnHeader: '权限级别',
    TenantWideAccessSuffix: '— 整个租户范围的访问权限',
    SecurityGroupType: '安全组',
    SpGroupType: 'SP 组',
    UserType: '用户',
    CheckAccessForLabel: '检查 {0} 的访问权限',
    ContainsUniqueAndExternalTooltip: '包含具有唯一权限和外部用户访问权限的项目',
    ContainsUniqueTooltip: '包含具有唯一权限的项目',
    ContainsExternalTooltip: '包含具有外部用户访问权限的项目',
    UniqueBadge: '唯一',
    ExternalAccessDetectedTooltip: '检测到外部用户访问',
    ConnectingStatus: '正在连接…',
    ConnectedLibrarySingular: '已连接 — 找到 {0} 个库',
    ConnectedLibraryPlural: '已连接 — 找到 {0} 个库',
    ConnectionFailedError: '连接失败：{0}',
    LibraryEmptyStatus: '此库为空。',
    ErrorLoadingLibrary: '加载库时出错：{0}',
    ErrorLoadingContents: '加载内容时出错',
    LibraryFieldLabel: '库',
    HiddenFromSearchSuffix: '{0}（已从搜索中隐藏）',
    UniquePermissionsOnlyToggle: '仅唯一权限',
    ExternalUsersOnlyToggle: '仅外部用户',
    LegendLabel: '图例：',
    LegendItemHasUnique: '项目具有唯一权限',
    LegendContainsUniqueBelow: '下方包含唯一权限',
    LegendContainsExternalBelow: '下方包含外部用户访问权限',
    LegendExternalOnItem: '此项目上有外部用户访问权限',
    ViewingWithMemberAccessTitle: '以成员权限查看',
    ViewingWithMemberAccessDesc1: '— 权限分配不可见。要查看谁有访问权限，需要',
    ManagePermissionsWord: '管理权限',
    ViewingWithMemberAccessDesc2: '权利（站点所有者或更高级别）。您仍然可以使用 ↓ 指示器查看哪些项目已中断继承。要查看您可以访问的位置，请使用',
    UserAccessWord: '用户访问',
    ViewingWithMemberAccessDesc3: '工具。',
    FoldersAndFilesLabel: '文件夹和文件',
    SelectFolderOrFilePrompt: '选择一个文件夹或文件以查看其权限。',
    UniquePermissionsBadge: '唯一权限',
    InheritedBadge: '已继承',
    ExpandGroupMembersLabel: '展开组成员',
    ShowParentPermissionsLabel: '显示父级权限',
    InheritsFromParentText: '此项目从其父项目继承权限。',
    YourAccessLabel: '您的访问权限：',
    PermissionsNotVisibleNodeText: '权限分配不可见 — 需要“管理权限”权利（站点所有者或更高级别）才能查看谁有权访问此项目。',
    NoExternalUsersDirectAccessText: '没有外部用户对此项目具有直接访问权限。',
    InheritedFromLabel: '继承自：',
    ParentPermissionsNotVisibleText: '父项目的权限分配不可见 — 需要“管理权限”权利（站点所有者或更高级别）。',
    NoPermissionsFoundOnParentText: '在父项目上未找到权限。',
    StartingScanStatus: '正在开始扫描…',
    ScanCancelledStatus: '扫描已取消 — 取消前已收集 {0} 个对象。',
    ScanCompleteStatus: '扫描完成 — 找到 {0} 个对象，其中 {1} 个具有唯一权限。',
    ScanCompleteNotificationTitle: 'Smart Permissions — 扫描完成',
    ScanCompleteNotificationBody: '{0} 个对象，其中 {1} 个具有唯一权限。',
    CancelledStatus: '已取消。',
    GenericErrorPrefix: '错误：{0}',
    ExportErrorPrefix: '导出错误：{0}',
    ScopeSiteOnly: '仅站点',
    ScopeLibraries: '库',
    ScopeFolders: '文件夹',
    ScopeFilesAndFolders: '文件和文件夹',
    ScanInProgressConfirm: '正在进行扫描。是否离开并取消？',
    HistoryButton: '历史记录',
    BackToHistoryButton: '返回历史记录',
    ComparingLabel: '正在比较',
    CompareMismatchWarning: '这些报告是使用不同的站点或扫描选项获取的 — 以下差异可能反映的是更改的扫描设置，而不是实际的权限更改。',
    NoPermissionDifferencesFound: '在这两个报告之间未发现权限差异。',
    PermissionChangesHeaderSingular: '权限更改（{0} 个对象）',
    PermissionChangesHeaderPlural: '权限更改（{0} 个对象）',
    ChangeColumnHeader: '更改',
    BeforeColumnHeader: '之前',
    AfterColumnHeader: '之后',
    AddedBadge: '已添加',
    RemovedBadge: '已移除',
    ChangedBadge: '已更改',
    InheritanceChangedHeader: '继承已更改（{0}）',
    NameColumnHeader: '名称',
    PathColumnHeader: '路径',
    NowColumnHeader: '当前',
    UniqueInheritanceBrokenBadge: '唯一（继承已中断）',
    InheritedRestoredBadge: '已继承（已恢复）',
    NewObjectsHeader: '新对象',
    RemovedObjectsHeader: '已移除的对象',
    BackToScanButton: '返回扫描',
    CompareSelectedButton: '比较所选项',
    NoReportsSavedYet: '尚未保存任何报告。',
    SelectForCompareLabel: '选择以进行比较',
    DateTimeColumnHeader: '日期/时间',
    SiteColumnHeader: '站点',
    ScopeColumnHeader: '范围',
    ObjectsColumnHeader: '对象',
    UniqueColumnHeader: '唯一',
    SelectReportForCompareLabel: '选择 {0} 的报告进行比较',
    AllSitesPrefix: '所有站点 · ',
    PlusSubsitesSuffix: ' + 子站点',
    ExportingStatus: '正在导出…',
    ExportButton: '导出',
    DeleteThisReportTitle: '删除此报告',
    ScanAllSiteCollectionsLabel: '扫描此租户中的所有网站集（仅在根站点可用）',
    AllSitesSearchCaveat: '站点列表来自搜索，可能不包括每个网站集 — 非常近期创建的站点，或从搜索索引中排除的站点可能会缺失。',
    IncludeSubsitesLabel: '包括子站点（扫描此站点下的每个子站点）',
    ScanDepthFieldLabel: '扫描深度',
    FolderDepthLimitLabel: '文件夹深度限制：',
    ExpandGroupMembersInReportLabel: '在报告中展开组成员（SharePoint 组、安全组和 M365 组）',
    LibrariesToScanLabel: '要扫描的库',
    OfSelectedCount: '已选择 {1} 个中的 {0} 个',
    AllButton: '全部',
    NoneButton: '无',
    LoadingLibrariesStatus: '正在加载库…',
    RunReportButton: '运行报告',
    ItemsFoundSoFar: '目前已找到 {0} 个项目',
    LibraryOfProgress: '库 {0}/{1}',
    ScanCancelledPartialResults: '扫描已取消 — 部分结果',
    ScanCompleteLabel: '扫描完成',
    ObjectsCountBadge: '{0} 个对象',
    UniqueCountBadge: '{0} 个唯一',
    InheritedCountBadge: '{0} 个已继承',
    GeneratingExcelStatus: '正在生成 Excel…',
    ExportFilteredRowsButton: '导出 {0} 行已过滤的行',
    ExportToExcelButton: '导出到 Excel',
    ExportToCsvButton: '导出到 CSV',
    ScanStoppedEarlyTitle: '扫描提前停止 — SharePoint 正在限制此租户。',
    SiteCollectionsScannedBeforeStopping: '停止前已扫描 {1} 个网站集中的 {0} 个。',
    ResultsBelowCoverOnlyPre: '以下结果仅涵盖已扫描的内容，并非',
    NotWord: '完整',
    ResultsBelowCoverOnlyPost: '审核。在这种情况下扫描会自动停止，因为继续发送请求会使限流持续生效。请等待几分钟，然后在设置中将',
    ConcurrentRequestsWord: '并发请求数',
    SetTo1Or2InSettings: '设置为 1 或 2 后重新运行。',
    ThrottledScanMessage: 'SharePoint 限制了此次扫描（{0} 个请求被限速并重试）。',
    OfEverythingScannedPre: '在所有已扫描的内容中，',
    ItemCountSingular: '{0} 个项目',
    ItemCountPlural: '{0} 个项目',
    CouldNotBeConfirmedText: '在重试后仍无法确认（有关具体是哪些项目，请参阅下方的“无法完全读取”通知）— 此失败与容量有关，并非其实际权限的反映。此报告中的所有其他项目均已成功读取，可以信赖。',
    DespiteThrottlingText: '尽管存在限流，但在重试后每个项目仍成功得到确认，因此此报告是完整的。',
    ForCleanRunPre: '为了获得干净的运行结果，请等待几分钟，并使用较低的',
    ValueInSettingsPost: '值在设置中重新扫描。',
    OneItemWord: '1 个项目',
    NItemsWord: '{0} 个项目',
    OutOfScannedCouldNotBeRead: '在已扫描的 {0} 个项目中，使用您当前的访问权限无法读取 —',
    PermissionAssignmentsForItAreNotShown: ' 权限分配未显示，',
    PermissionAssignmentsForThoseAreNotShown: ' 权限分配未显示，',
    RestOfReportReadSuccessfully: '但此报告的其余部分已成功读取。',
    RunScanAsSiteOwnerPre: '以',
    SiteOwnerWord: '站点所有者',
    RunScanAsSiteOwnerPost: '身份运行扫描，以查看下方被拒绝项目的完整详细信息。',
    AndNMoreText: '……以及另外 {0} 个',
    GroupExpansionSkippedPre: '已跳过组成员展开 — 尚未在此租户中批准 Graph 权限',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: '。SharePoint 管理员或全局管理员可以在',
    SharePointAdminCenterPath: 'SharePoint 管理中心 → 高级 → API 访问',
    ScanIncompleteItemsMessage: '{0} 个项目由于临时错误（非权限问题）而无法完全读取，作为权宜之计，将显示其父项目的权限 — 这可能无法反映其实际访问权限。请重新运行扫描以重试这些项目。',
    FilterByNamePathUserPlaceholder: '按名称、路径或用户/组筛选…',
    FilterResultsLabel: '筛选结果',
    ExternalUsersOnlyExtLabel: '仅外部用户 (#ext#)',
    ShowingOfCount: '显示 {1} 个中的 {0} 个',
    ScanResultsLabel: '扫描结果',
    PermissionsColumnHeader: '权限',
    CollapsePermissionsLabel: '折叠权限',
    ExpandPermissionsLabel: '展开权限',
    HiddenFromSearchBadge: '已从搜索中隐藏',
    AssignmentCountSingular: '{0} 个分配',
    AssignmentCountPlural: '{0} 个分配',
    LoadMoreRemainingButton: '加载更多（剩余 {0} 个）',
    LoadingUsersStatus: '正在加载用户…',
    ConnectedUserSingular: '已连接 — 找到 {0} 个用户',
    ConnectedUserPlural: '已连接 — 找到 {0} 个用户',
    CheckingAccessForStatus: '正在检查 {0} 的访问权限…',
    FullSiteAccessDetectedStatus: '检测到完全的站点访问权限。',
    AccessibleLocationsFoundSingular: '找到 {0} 个可访问位置。',
    AccessibleLocationsFoundPlural: '找到 {0} 个可访问位置。',
    NoAccessibleLocationsFoundStatus: '未找到可访问位置。',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — 用户访问扫描完成',
    UserAccessScanCompleteNotificationBody: '{0}：{1}',
    NewScanButton: '新扫描',
    NoUserAccessScansSavedYet: '尚未保存任何用户访问扫描。',
    UserColumnHeader: '用户',
    LocationsColumnHeader: '位置',
    FullControlBadge: '完全控制',
    DeleteThisRecordTitle: '删除此记录',
    SelectAUserFieldLabel: '选择用户',
    SearchUsersPlaceholder: '搜索用户…',
    SelectAUserToCheckAccessLabel: '选择要检查访问权限的用户',
    NotInThisSiteLabel: '不在此站点中',
    ScanInProgressLabel: '正在扫描',
    ScanningUserAccessLabel: '正在扫描用户访问权限',
    ScanningStatus: '正在扫描…',
    FullControlAccessPre: '此用户对整个站点拥有',
    FullControlWord: '完全控制',
    FullControlAccessPost: '或所有者级别的访问权限 — 所有库和文件夹均可访问。',
    SiteLevelPermissionCouldNotBeDeterminedPre: '无法确定站点级别的权限 — 此站点可能使用 Microsoft 365 组访问权限。要显示它，SharePoint 管理员必须在',
    SiteLevelPermissionCouldNotBeDeterminedMid: '中批准 Graph 权限。',
    ShowingSiteLevelAccessOnlyPre: '仅显示基于默认 SharePoint 组成员身份的',
    SiteLevelAccessOnlyWord: '站点级别访问权限',
    ShowingSiteLevelAccessOnlyMid: '。无法读取库、文件夹和文件上的唯一权限，因此不显示。要获得完整结果，请以',
    UserAccessCouldNotBeDeterminedPre: '无法确定此用户的访问权限。读取权限分配需要',
    UserAccessCouldNotBeDeterminedPost: '权利（站点所有者或更高级别），并且此用户似乎不是站点默认所有者、成员或访客组的成员。',
    SiteLevelAccessBannerPre: '此用户具有站点级别的访问权限。下方仅显示具有',
    UniquePermissionAssignmentsWord: '唯一权限分配',
    SiteLevelAccessBannerPost: '的位置 — 所有其他内容都可以通过列表顶部显示的站点级别权限访问。',
    UserAccessResultsLabel: '用户访问结果',
  };
});
