define([], function () {
  return {
    // Property pane
    PropertyPane_HeaderDescription: 'Smart Permissions 組態',
    PropertyPane_GroupName: '一般',
    PropertyPane_DefaultViewLabel: '開啟時的預設檢視',
    PropertyPane_View_Home: '首頁',
    PropertyPane_View_Report: '權限報表',
    PropertyPane_View_Explorer: '權限總管',
    PropertyPane_View_UserAccess: '使用者存取權',

    AppTitle: 'SharePoint Smart Permissions',
    SiteUrlPlaceholder: 'https://contoso.sharepoint.com/sites/mysite',
    ConnectButton: '連接',
    CancelButton: '取消',
    ChangeUrlButton: '變更 URL',
    SettingsLabel: '設定',
    RenderErrorTitle: 'Smart Permissions — 呈現錯誤',
    RenderErrorMessageLabel: '訊息：',
    RenderErrorStackLabel: '堆疊：',
    RenderErrorNoStack: '（堆疊無法使用）',
    BackButton: '返回',
    BackToHomeLabel: '返回首頁',
    ExplorerCardTitle: '權限總管',
    ExplorerCardAlt: '含有資料夾樹狀結構與權限面板的權限總管',
    ExplorerCardDesc: '瀏覽任何資料夾或檔案，透過即時權限查詢立即查看誰有存取權。',
    ExplorerCardButton: '開啟權限總管',
    ReportCardTitle: '權限報表',
    ReportCardAlt: '權限報表設定畫面',
    ReportCardDesc: '為您網站中每個唯一的權限指派產生具色彩標示的 Excel 報表。',
    ReportCardButton: '執行權限報表',
    UserAccessCardTitle: '使用者存取權',
    UserAccessCardAlt: '顯示所選使用者可存取位置的使用者存取權畫面',
    UserAccessCardDesc: '查詢任何使用者，以查看其在網站上可存取的每個位置及確切的權限層級。',
    UserAccessCardButton: '檢查使用者存取權',
    SiteOwnerRequiredTitle: '需要網站擁有者存取權 —',
    SiteOwnerRequiredDesc: '這些工具需要網站擁有者存取權。若您對權限有疑問，請聯絡網站擁有者。',
    HomeSubtitle: '不需使用 PowerShell 即可稽核並了解 SharePoint 權限。',
    RequiresSiteOwnerTooltip: '需要網站擁有者存取權',
    HomeNoteLabel: '注意：',
    HomeNoteText: '此 Web 組件以目前登入的使用者身分執行。它只能看到該使用者有權存取的網站和項目。若要進行完整的租用戶掃描，請使用對所有網站都具有適當讀取權限的帳戶。',
    SettingsTitle: '設定',
    LibrariesSectionTitle: '文件庫',
    IncludeHiddenLabel: '包含系統與隱藏文件庫',
    IncludeHiddenTooltip: '若勾選，則會包含樣式庫、表單範本、網站資產及其他在預設檢視中隱藏的文件庫。適用於所有工具。',
    MoreInfoHiddenLibrariesLabel: '深入了解隱藏文件庫',
    ExcludeLimitedAccessLabel: '排除受限存取項目',
    ExcludeLimitedAccessTooltip: '隱藏唯一 SharePoint 權限為受限存取的使用者與群組 — 透過連結分享檔案時會自動指派此權限。適用於權限報表、總管與使用者存取權。',
    MoreInfoLimitedAccessLabel: '深入了解受限存取',
    ExcludeSharingLinksLabel: '排除共用連結項目',
    ExcludeSharingLinksTooltip: '隱藏 SharePoint 為「擁有連結的任何人」及「特定人員」共用連結自動建立的內部 "SharingLinks.*" 群組。適用於權限報表、總管與使用者存取權。',
    MoreInfoSharingLinksLabel: '深入了解共用連結',
    PerformanceSectionTitle: '效能',
    ConcurrentRequestsLabel: '並行 API 要求數：',
    ConcurrencyTooltip: '在權限報表掃描、使用者存取權掃描及總管背景檢查期間並行執行的 SharePoint API 要求數。數值越高速度越快，但也越容易觸發節流（HTTP 429）。建議使用 3–5。',
    MoreInfoConcurrencyLabel: '深入了解並行性',
    ConcurrencyHint: '數值越高掃描速度越快，但可能觸發 SharePoint 節流。建議值：3–5。',
    GroupMemberCapLabel: '群組成員顯示上限：',
    GroupMemberCapTooltip: '啟用「展開群組成員」時，每個群組顯示的成員數上限。較大的群組會受到限制，並顯示通知。提高此值會使用更多記憶體。',
    MoreInfoGroupMemberCapLabel: '深入了解群組成員上限',
    GroupMemberCapHint: '超過此上限的群組會顯示截斷通知。預設值：500。',
    DefaultViewSectionTitle: '載入時的預設檢視',
    DefaultViewInstructionsIntro: '若要變更 Web 組件首次載入時開啟的畫面，請編輯 Web 組件屬性：',
    DefaultViewStep1Pre: '將 SharePoint 頁面切換至',
    DefaultViewStep1Post: '模式。',
    DefaultViewStep2Pre: '按一下 Smart Permissions Web 組件上的',
    DefaultViewStep2Post: '圖示。',
    DefaultViewStep3Pre: '在屬性面板中，從下拉式清單',
    DefaultViewStep3Post: '選擇檢視。',
    DefaultViewStep4Post: '頁面以儲存變更。',
    EditModeWord: '編輯',
    PencilEditWord: '鉛筆（編輯）',
    DefaultViewOnOpenWord: '開啟時的預設檢視',
    RepublishWord: '重新發佈',
    SiteOwnersLabel: '網站擁有者：',
    EveryoneClaimLabel: '所有人',
    EveryoneExceptExternalClaimLabel: '除外部使用者以外的所有人',
    PermissionAssignmentsLabel: '權限指派',
    UserGroupColumnHeader: '使用者/群組',
    TypeColumnHeader: '類型',
    PermissionLevelColumnHeader: '權限層級',
    TenantWideAccessSuffix: '— 整個租用戶範圍的存取權',
    SecurityGroupType: '安全性群組',
    SpGroupType: 'SP 群組',
    UserType: '使用者',
    CheckAccessForLabel: '檢查 {0} 的存取權',
    ContainsUniqueAndExternalTooltip: '包含具有唯一權限及外部使用者存取權的項目',
    ContainsUniqueTooltip: '包含具有唯一權限的項目',
    ContainsExternalTooltip: '包含具有外部使用者存取權的項目',
    UniqueBadge: '唯一',
    ExternalAccessDetectedTooltip: '偵測到外部使用者存取',
    ConnectingStatus: '正在連接…',
    ConnectedLibrarySingular: '已連接 — 找到 {0} 個文件庫',
    ConnectedLibraryPlural: '已連接 — 找到 {0} 個文件庫',
    ConnectionFailedError: '連接失敗：{0}',
    LibraryEmptyStatus: '此文件庫是空的。',
    ErrorLoadingLibrary: '載入文件庫時發生錯誤：{0}',
    ErrorLoadingContents: '載入內容時發生錯誤',
    LibraryFieldLabel: '文件庫',
    HiddenFromSearchSuffix: '{0}（已從搜尋中隱藏）',
    UniquePermissionsOnlyToggle: '僅唯一權限',
    ExternalUsersOnlyToggle: '僅外部使用者',
    LegendLabel: '圖例：',
    LegendItemHasUnique: '項目具有唯一權限',
    LegendContainsUniqueBelow: '下方包含唯一權限',
    LegendContainsExternalBelow: '下方包含外部使用者存取權',
    LegendExternalOnItem: '此項目上有外部使用者存取權',
    ViewingWithMemberAccessTitle: '以成員存取權檢視',
    ViewingWithMemberAccessDesc1: '— 權限指派無法顯示。若要查看誰有存取權，需要',
    ManagePermissionsWord: '管理權限',
    ViewingWithMemberAccessDesc2: '權限（網站擁有者或更高層級）。您仍可使用 ↓ 指標查看哪些項目已中斷繼承。若要查看您可存取的位置，請使用',
    UserAccessWord: '使用者存取權',
    ViewingWithMemberAccessDesc3: '工具。',
    FoldersAndFilesLabel: '資料夾與檔案',
    SelectFolderOrFilePrompt: '選取資料夾或檔案以檢視其權限。',
    UniquePermissionsBadge: '唯一權限',
    InheritedBadge: '已繼承',
    ExpandGroupMembersLabel: '展開群組成員',
    ShowParentPermissionsLabel: '顯示父項權限',
    InheritsFromParentText: '此項目會從其父項繼承權限。',
    YourAccessLabel: '您的存取權：',
    PermissionsNotVisibleNodeText: '權限指派無法顯示 — 需要「管理權限」權限（網站擁有者或更高層級）才能查看誰有權存取此項目。',
    NoExternalUsersDirectAccessText: '沒有外部使用者對此項目具有直接存取權。',
    InheritedFromLabel: '繼承自：',
    ParentPermissionsNotVisibleText: '父項的權限指派無法顯示 — 需要「管理權限」權限（網站擁有者或更高層級）。',
    NoPermissionsFoundOnParentText: '在父項上找不到權限。',
    StartingScanStatus: '正在開始掃描…',
    ScanCancelledStatus: '掃描已取消 — 取消前已收集 {0} 個物件。',
    ScanCompleteStatus: '掃描完成 — 找到 {0} 個物件，其中 {1} 個具有唯一權限。',
    ScanCompleteNotificationTitle: 'Smart Permissions — 掃描完成',
    ScanCompleteNotificationBody: '{0} 個物件，其中 {1} 個具有唯一權限。',
    CancelledStatus: '已取消。',
    GenericErrorPrefix: '錯誤：{0}',
    ExportErrorPrefix: '匯出錯誤：{0}',
    ScopeSiteOnly: '僅網站',
    ScopeLibraries: '文件庫',
    ScopeFolders: '資料夾',
    ScopeFilesAndFolders: '檔案與資料夾',
    ScanInProgressConfirm: '掃描正在進行中。是否要離開並取消？',
    HistoryButton: '記錄',
    BackToHistoryButton: '返回記錄',
    ComparingLabel: '正在比較',
    CompareMismatchWarning: '這些報表是使用不同的網站或掃描選項所產生 — 下方的差異可能反映的是變更後的掃描設定，而非實際的權限變更。',
    NoPermissionDifferencesFound: '這兩份報表之間未發現權限差異。',
    PermissionChangesHeaderSingular: '權限變更（{0} 個物件）',
    PermissionChangesHeaderPlural: '權限變更（{0} 個物件）',
    ChangeColumnHeader: '變更',
    BeforeColumnHeader: '之前',
    AfterColumnHeader: '之後',
    AddedBadge: '已新增',
    RemovedBadge: '已移除',
    ChangedBadge: '已變更',
    InheritanceChangedHeader: '繼承已變更（{0}）',
    NameColumnHeader: '名稱',
    PathColumnHeader: '路徑',
    NowColumnHeader: '目前',
    UniqueInheritanceBrokenBadge: '唯一（繼承已中斷）',
    InheritedRestoredBadge: '已繼承（已還原）',
    NewObjectsHeader: '新物件',
    RemovedObjectsHeader: '已移除的物件',
    BackToScanButton: '返回掃描',
    CompareSelectedButton: '比較所選項目',
    NoReportsSavedYet: '尚未儲存任何報表。',
    SelectForCompareLabel: '選取以進行比較',
    DateTimeColumnHeader: '日期/時間',
    SiteColumnHeader: '網站',
    ScopeColumnHeader: '範圍',
    ObjectsColumnHeader: '物件',
    UniqueColumnHeader: '唯一',
    SelectReportForCompareLabel: '選取 {0} 的報表以進行比較',
    AllSitesPrefix: '所有網站 · ',
    PlusSubsitesSuffix: ' + 子網站',
    ExportingStatus: '正在匯出…',
    ExportButton: '匯出',
    DeleteThisReportTitle: '刪除此報表',
    ScanAllSiteCollectionsLabel: '掃描此租用戶中的所有網站集合（僅在根網站可用）',
    AllSitesSearchCaveat: '網站清單來自搜尋，可能不包含每個網站集合 — 極新建立的網站，或已從搜尋索引中排除的網站可能會遺漏。',
    IncludeSubsitesLabel: '包含子網站（掃描此網站下的每個子網站）',
    ScanDepthFieldLabel: '掃描深度',
    FolderDepthLimitLabel: '資料夾深度限制：',
    ExpandGroupMembersInReportLabel: '在報表中展開群組成員（SharePoint 群組、安全性群組及 M365 群組）',
    LibrariesToScanLabel: '要掃描的文件庫',
    OfSelectedCount: '已選取 {1} 個中的 {0} 個',
    AllButton: '全部',
    NoneButton: '無',
    LoadingLibrariesStatus: '正在載入文件庫…',
    RunReportButton: '執行報表',
    ItemsFoundSoFar: '目前已找到 {0} 個項目',
    LibraryOfProgress: '文件庫 {0}/{1}',
    ScanCancelledPartialResults: '掃描已取消 — 部分結果',
    ScanCompleteLabel: '掃描完成',
    ObjectsCountBadge: '{0} 個物件',
    UniqueCountBadge: '{0} 個唯一',
    InheritedCountBadge: '{0} 個已繼承',
    GeneratingExcelStatus: '正在產生 Excel…',
    ExportFilteredRowsButton: '匯出 {0} 列已篩選的資料',
    ExportToExcelButton: '匯出至 Excel',
    ExportToCsvButton: '匯出至 CSV',
    ScanStoppedEarlyTitle: '掃描提前停止 — SharePoint 正在對此租用戶進行節流。',
    SiteCollectionsScannedBeforeStopping: '停止前已掃描 {1} 個網站集合中的 {0} 個。',
    ResultsBelowCoverOnlyPre: '以下結果僅涵蓋已掃描的內容，並非',
    NotWord: '完整',
    ResultsBelowCoverOnlyPost: '稽核。在此情況下，掃描會自動停止，因為持續傳送要求正是維持節流生效的原因。請等待數分鐘，然後在設定中將',
    ConcurrentRequestsWord: '並行要求數',
    SetTo1Or2InSettings: '設為 1 或 2 後重新執行。',
    ThrottledScanMessage: 'SharePoint 已對此掃描進行節流（{0} 個要求已受到速率限制並重試）。',
    OfEverythingScannedPre: '在所有已掃描的內容中，',
    ItemCountSingular: '{0} 個項目',
    ItemCountPlural: '{0} 個項目',
    CouldNotBeConfirmedText: '在重試後仍無法確認（如需確切為哪些項目，請參閱下方的「無法完全讀取」通知）— 此失敗與容量有關，並非其實際權限的反映。此報表中的所有其他項目均已成功讀取，可以信賴。',
    DespiteThrottlingText: '儘管有節流狀況，但每個項目在重試後仍成功獲得確認，因此此報表是完整的。',
    ForCleanRunPre: '為取得乾淨的執行結果，請等待數分鐘，並使用較低的',
    ValueInSettingsPost: '值在設定中重新掃描。',
    OneItemWord: '1 個項目',
    NItemsWord: '{0} 個項目',
    OutOfScannedCouldNotBeRead: '在已掃描的 {0} 個項目中，以您目前的存取權無法讀取 —',
    PermissionAssignmentsForItAreNotShown: ' 權限指派未顯示，',
    PermissionAssignmentsForThoseAreNotShown: ' 權限指派未顯示，',
    RestOfReportReadSuccessfully: '但此報表的其餘部分已成功讀取。',
    RunScanAsSiteOwnerPre: '以',
    SiteOwnerWord: '網站擁有者',
    RunScanAsSiteOwnerPost: '身分執行掃描，以查看下方遭拒項目的完整詳細資料。',
    AndNMoreText: '……以及其他 {0} 個',
    GroupExpansionSkippedPre: '已略過群組成員展開 — 尚未在此租用戶中核准 Graph 權限',
    GroupMemberReadAllWord: 'GroupMember.Read.All',
    GroupExpansionSkippedPost: '。SharePoint 管理員或全域管理員可以在',
    SharePointAdminCenterPath: 'SharePoint 系統管理中心 → 進階 → API 存取權',
    ScanIncompleteItemsMessage: '{0} 個項目因暫時性錯誤（非權限問題）而無法完全讀取，因此會顯示其父項的權限作為權宜之計 — 這可能無法反映其實際存取權。請重新執行掃描以重試這些項目。',
    FilterByNamePathUserPlaceholder: '依名稱、路徑或使用者/群組篩選…',
    FilterResultsLabel: '篩選結果',
    ExternalUsersOnlyExtLabel: '僅外部使用者 (#ext#)',
    ShowingOfCount: '顯示 {1} 個中的 {0} 個',
    ScanResultsLabel: '掃描結果',
    PermissionsColumnHeader: '權限',
    CollapsePermissionsLabel: '摺疊權限',
    ExpandPermissionsLabel: '展開權限',
    HiddenFromSearchBadge: '已從搜尋中隱藏',
    AssignmentCountSingular: '{0} 個指派',
    AssignmentCountPlural: '{0} 個指派',
    LoadMoreRemainingButton: '載入更多（剩餘 {0} 個）',
    LoadingUsersStatus: '正在載入使用者…',
    ConnectedUserSingular: '已連接 — 找到 {0} 位使用者',
    ConnectedUserPlural: '已連接 — 找到 {0} 位使用者',
    CheckingAccessForStatus: '正在檢查 {0} 的存取權…',
    FullSiteAccessDetectedStatus: '偵測到完整的網站存取權。',
    AccessibleLocationsFoundSingular: '找到 {0} 個可存取的位置。',
    AccessibleLocationsFoundPlural: '找到 {0} 個可存取的位置。',
    NoAccessibleLocationsFoundStatus: '找不到可存取的位置。',
    UserAccessScanCompleteNotificationTitle: 'Smart Permissions — 使用者存取權掃描完成',
    UserAccessScanCompleteNotificationBody: '{0}：{1}',
    NewScanButton: '新掃描',
    NoUserAccessScansSavedYet: '尚未儲存任何使用者存取權掃描。',
    UserColumnHeader: '使用者',
    LocationsColumnHeader: '位置',
    FullControlBadge: '完全控制',
    DeleteThisRecordTitle: '刪除此記錄',
    SelectAUserFieldLabel: '選取使用者',
    SearchUsersPlaceholder: '搜尋使用者…',
    SelectAUserToCheckAccessLabel: '選取要檢查存取權的使用者',
    NotInThisSiteLabel: '不在此網站中',
    ScanInProgressLabel: '正在掃描',
    ScanningUserAccessLabel: '正在掃描使用者存取權',
    ScanningStatus: '正在掃描…',
    FullControlAccessPre: '此使用者對整個網站擁有',
    FullControlWord: '完全控制',
    FullControlAccessPost: '或擁有者層級的存取權 — 所有文件庫與資料夾皆可存取。',
    SiteLevelPermissionCouldNotBeDeterminedPre: '無法判斷網站層級的權限 — 此網站可能使用 Microsoft 365 群組存取權。若要顯示，SharePoint 管理員必須在',
    SiteLevelPermissionCouldNotBeDeterminedMid: '中核准 Graph 權限。',
    ShowingSiteLevelAccessOnlyPre: '僅根據預設 SharePoint 群組成員資格顯示',
    SiteLevelAccessOnlyWord: '網站層級的存取權',
    ShowingSiteLevelAccessOnlyMid: '。無法讀取文件庫、資料夾與檔案上的唯一權限，因此不會顯示。若要取得完整結果，請以',
    UserAccessCouldNotBeDeterminedPre: '無法判斷此使用者的存取權。讀取權限指派需要',
    UserAccessCouldNotBeDeterminedPost: '權限（網站擁有者或更高層級），而此使用者似乎不是網站預設擁有者、成員或訪客群組的成員。',
    SiteLevelAccessBannerPre: '此使用者具有網站層級的存取權。下方僅顯示具有',
    UniquePermissionAssignmentsWord: '唯一權限指派',
    SiteLevelAccessBannerPost: '的位置 — 所有其他內容皆可透過清單頂端顯示的網站層級權限存取。',
    UserAccessResultsLabel: '使用者存取權結果',
  };
});
